Repository PolarisSS13/Polaris, pull requests merged in 2018-03, with the labels that each got.

#4957 GORILLA - The Revival
  code/game/mecha/combat/gorilla.dm
  code/game/mecha/equipment/tools/unused_tools.dm
  code/game/mecha/equipment/weapons/weapons.dm
  icons/mecha/mecha64x64.dmi
  icons/obj/projectiles.dmi
  polaris.dme
  sound/weapons/cannon.ogg
Labels: Feature

#4985 Updates changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Atermonera_umbrelloadout.yml
  html/changelogs/Nerezza - Shutter-tape.yml
  html/changelogs/Nerezza - Tilematic.yml
  html/changelogs/Woodrat - Wilderness.yml
  html/changelogs/battlefieldcommander - smoke weed every day.yml
Labels: Changelog Update

#4981 Adds 'Intercom Convo' verb
  code/game/objects/items/devices/radio/intercom.dm
  code/game/objects/items/devices/radio/radio.dm
  code/global.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
Labels: Feature

#4979 Discourages eating monkey cubes
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Feature Tweak

#4982 Fixes two minor PDA cart issues.
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/cart.dm
Labels: Bugfix

#4942 Removes translators from the loadout
  code/game/objects/items/devices/translator.dm
  code/modules/client/preference_setup/loadout/loadout_ears.dm
  code/modules/client/preference_setup/loadout/loadout_utility.dm
  code/modules/research/designs.dm
  html/changelogs/Anewbe - Translators.yml
Labels: Bikeshed, Feature Tweak, Forum Discussion in Progress, Staff Request, Unwanted Feature Removal

#4958 DNA injectors cause cloneloss.
  code/game/objects/items/weapons/dna_injector.dm
Labels: Feature Tweak

#4986 Hail is less omnicidal
  code/modules/planet/sif.dm
Labels: Feature Tweak

#4908 Manual revert of https://github.com/PolarisSS13/Polaris/pull/4839
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Higgs Bugson

#4995 Fixes rolling paper boxes disappearing
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/storage/fancy.dm
  icons/obj/cigarettes.dmi
Labels: Oversight

#4994 Fixed supply manifests having wrong amount of packages in shipment
  code/game/supplyshuttle.dm
Labels: Bugfix

#4989 Makes drills report faults over supply channel
  code/modules/mining/drilling/drill.dm
Labels: Feature

#4997 Fixes typo in alien pod loot pile
  code/game/objects/structures/loot_piles.dm
Labels: Oversight

#4998 Fixes Switch Shoe Layer to re-layer shoes in real time
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Bugfix

#5001 Fixes #4993
  code/game/objects/effects/overlays.dm
Labels: Bugfix, Oversight

#4996 Fixes drone borgs spawning with dropped IDs
  code/modules/mob/living/carbon/human/human.dm
Labels: Bugfix

#5000 Slime brains now actually have container settings!
  code/modules/organs/internal/brain.dm
Labels: Oversight

#5010 Update links to forum and wiki in README.md
  README.md
Labels: Oversight

#4906 Succumb changes
  code/modules/mob/living/living.dm
  html/changelogs/PrismaticGynoid-acceptyourfate.yml
Labels: Feature Tweak, Requires Staff Input

#4988 Removes some alt-titles with insufficiently clear roles
  code/game/jobs/job/captain.dm
  code/game/jobs/job/civilian.dm
  html/changelogs/Anewbe - Alt Titles 1.yml
Labels: Bikeshed, Staff Request, Unwanted Feature Removal

#5002 Map Bugfixes Miner Additions
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-3.dmm
  maps/southern_cross/southern_cross-4.dmm
  maps/southern_cross/southern_cross_areas.dm
Labels: Bugfix, Map Change / Issue

#5009 Fixes to runtime map loader
  code/modules/maps/tg/reader.dm
Labels: Bugfix

#5004 Port SSoverlays & Convert turfs to use it
  code/ATMOSPHERICS/pipes/universal.dm
  code/ZAS/Turf.dm
  code/__defines/items_clothing.dm
  code/__defines/math.dm
  code/__defines/stat_tracking.dm
  code/__defines/subsystems.dm
  code/_helpers/sorts/comparators.dm
  code/_helpers/unsorted.dm
  code/controllers/subsystems/floor_decals.dm
  code/controllers/subsystems/overlays.dm
  code/game/atoms.dm
  code/game/machinery/alarm.dm
  code/game/turfs/flooring/flooring_decals.dm
  code/game/turfs/flooring/flooring_premade.dm
  code/game/turfs/flooring/turf_overlay_holder.dm
  code/game/turfs/simulated.dm
  code/game/turfs/simulated/dungeon/wall.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor_icon.dm
  code/game/turfs/simulated/floor_types.dm
  code/game/turfs/simulated/outdoors/outdoors.dm
  code/game/turfs/simulated/outdoors/snow.dm
  code/game/turfs/simulated/wall_icon.dm
  code/game/turfs/simulated/wall_types.dm
  code/game/turfs/simulated/water.dm
  code/game/turfs/snow/snow.dm
  code/game/turfs/space/cracked_asteroid.dm
  code/game/turfs/unsimulated/beach.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/debug.dm
  code/modules/holodeck/HolodeckObjects.dm
  code/modules/multiz/turf.dm
  polaris.dme
Labels: Refactor

#5008 we now know who made gateways
  code/modules/awaymissions/gateway.dm
Labels: Lore

#5003 Changes states in borer holder sprites to "brainslug"
  icons/mob/head.dmi
  icons/mob/items/lefthand_holder.dmi
  icons/mob/items/righthand_holder.dmi
Labels: Bugfix, Sprite Change

#5005 Mob Spawners can now override certain vars.
  code/game/objects/random/random.dm
Labels: Feature Tweak

#4990 Adds a Frankenstein Surgical Procedure
  code/modules/mob/_modifiers/cloning.dm
  code/modules/surgery/neck.dm
  code/modules/surgery/surgery.dm
  html/changelogs/Mechoid - RecapitationSurgery.yml
  polaris.dme
Labels: Feature

#5014 Weather reports won't crash when planet controller dies
  code/game/objects/items/devices/communicator/UI.dm
Labels: Bugfix

#4968 Ater poi3
  code/game/objects/items/weapons/syndie.dm
  html/changelogs/Atermonera - package_bombs.yml
  maps/submaps/surface_submaps/mountains/BlastMine1.dmm
  maps/submaps/surface_submaps/mountains/SupplyDrop1.dmm
  maps/submaps/surface_submaps/mountains/mountains.dm
  maps/submaps/surface_submaps/mountains/mountains_areas.dm
  maps/submaps/surface_submaps/plains/RationCache.dmm
  maps/submaps/surface_submaps/plains/SupplyDrop2.dmm
  maps/submaps/surface_submaps/plains/plains.dm
  maps/submaps/surface_submaps/plains/plains_areas.dm
Labels: Feature, Point of Interest

#5017 First Aid Addition and Bug Fixes
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-6.dmm
Labels: Bugfix, Map Change / Issue, Priority: CRITICAL

#4943 Robolimbs require repair at 30 composite damage
  code/modules/organs/organ_external.dm
  html/changelogs/Anewbe - Robolimb Repair.yml
Labels: Controversial, Feature Tweak

#4987 VeyMed limbs (and organs) are now more vulnerable to EMP
  code/modules/organs/organ.dm
  code/modules/organs/organ_external.dm
  html/changelogs/Anewbe - VeyMed EMP tweaks.yml
Labels: Controversial, Feature Tweak

#5006 Adjusts probably-temporary attack values for simple mobs
  code/modules/mob/living/simple_animal/aliens/alien.dm
  code/modules/mob/living/simple_animal/aliens/creature.dm
  code/modules/mob/living/simple_animal/aliens/faithless.dm
  code/modules/mob/living/simple_animal/aliens/hivebot.dm
  code/modules/mob/living/simple_animal/aliens/shade.dm
  code/modules/mob/living/simple_animal/animals/bat.dm
  code/modules/mob/living/simple_animal/animals/bear.dm
  code/modules/mob/living/simple_animal/animals/crab.dm
  code/modules/mob/living/simple_animal/animals/giant_spider.dm
  code/modules/mob/living/simple_animal/animals/sif_wildlife/diyaab.dm
  code/modules/mob/living/simple_animal/animals/sif_wildlife/savik.dm
  code/modules/mob/living/simple_animal/animals/sif_wildlife/shantak.dm
  code/modules/mob/living/simple_animal/humanoids/pirate.dm
  code/modules/mob/living/simple_animal/humanoids/syndicate.dm
Labels: Feature Tweak, Prepare to Die

#5011 Ingested reagents act half as quickly, rather than half as well
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/reagents/Chemistry-Metabolism.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  html/changelogs/Anewbe - Pills.yml
Labels: Feature Tweak

#5012 Should be possible to replace cargo tug power cells
  code/modules/vehicles/vehicle.dm
Labels: Bugfix, Priority: High

#5019 Changelog Update
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Anewbe - Alt Titles 1.yml
  html/changelogs/Anewbe - Translators.yml
  html/changelogs/Atermonera - package_bombs.yml
  html/changelogs/Mechoid - RecapitationSurgery.yml
  html/changelogs/PrismaticGynoid-acceptyourfate.yml
Labels: Changelog Update

#5015 Makes slightly smaller objects capable of bashing open busted APCs
  code/modules/power/apc.dm
  html/changelogs/Nerezza - APC-Tweak.yml
Labels: Feature Tweak

#5030 Making Pilot Lockers Exist Again
  maps/southern_cross/southern_cross-1.dmm
Labels: Bugfix, Map Change / Issue, Southern Cross

#5041 Port's /vg/'s RCE prevention to shell().
  code/modules/ext_scripts/irc.dm
  code/modules/ext_scripts/python.dm
Labels: Priority: CRITICAL

#5035 Fix click disabling when unbuckling via resist
  code/modules/mob/living/carbon/resist.dm
Labels: Bugfix

#5043 Fixes #5042
  html/changelogs/Nerezza - sifwoodfix.yml
  icons/obj/stacks.dmi
Labels: Bugfix

#5039 Optimize scheduler process by sorting its task list
  code/controllers/Processes/scheduler.dm
Labels: Optimization, Refactor

#5021 Misc rig fixes/tweaks
  code/_onclick/hud/screen_objects.dm
  code/modules/clothing/spacesuits/rig/suits/station.dm
  code/modules/mob/living/carbon/human/life.dm
  html/changelogs/Nerezza - Hardsuit-fixes.yml
Labels: Feature Tweak

#4991 Reinforced snowball fix.
  code/game/objects/items/weapons/material/misc.dm
  html/changelogs/MisterLayne - SnowballTEMPFIX.yml
Labels: Bugfix, Needs Changelog

#4980 Adds the ED-CLN
  code/game/objects/items/robot/robot_parts.dm
  code/modules/mob/living/bot/edCLNbot.dm
  code/modules/reagents/reagent_containers/glass.dm
  html/changelogs/MisterLayne - ED-CLN.yml
  icons/obj/aibots.dmi
  polaris.dme
Labels: Feature

#5044 Reduce qdel log file by 150000%
  code/controllers/subsystems/garbage.dm
Labels: Optimization, Refactor

#5028 Ward-Takahashi names + Northern Star
  code/modules/busy_space/organizations.dm
Labels: Lore

#5029 Added different icons for improved capacitors and scanning modules
  code/defines/obj/weapon.dm
  icons/obj/stock_parts.dmi
Labels: Sprite Change

#5031 Drill grammar
  code/modules/mining/drilling/drill.dm
Labels: Bugfix

#5018 Syringe adjustments
  code/_helpers/mobs.dm
  code/modules/reagents/reagent_containers/syringes.dm
  html/changelogs/Anewbe - Syringes.yml
Labels: Bikeshed, Feature Tweak

#5024 Splits up random.dm
  code/game/objects/random/_random.dm
  code/game/objects/random/guns_and_ammo.dm
  code/game/objects/random/maintenance.dm
  code/game/objects/random/mapping.dm
  code/game/objects/random/misc.dm
  code/game/objects/random/mob.dm
  code/game/objects/random/random.dm
  code/game/objects/random/spacesuits.dm
  polaris.dme
Labels: Refactor

#5032 Adds Tajaran Akhani language.
  code/__defines/species_languages.dm
  code/game/antagonist/antagonist.dm
  code/game/antagonist/outsider/ninja.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/objects/effects/decals/posters/bs12.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/modkit.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
  code/modules/client/preference_setup/traits/trait_defines.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/spacesuits/rig/rig_pieces.dm
  code/modules/clothing/spacesuits/void/void.dm
  code/modules/games/cah_black_cards.dm
  code/modules/games/cah_white_cards.dm
  code/modules/lore_codex/lore_data/species.dm
  code/modules/mob/language/station.dm
  code/modules/mob/living/autohiss.dm
  code/modules/mob/living/carbon/human/human_species.dm
  code/modules/mob/living/carbon/human/species/station/prometheans.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/carbon/human/species/virtual_reality/opaque_form.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/pai/software_modules.dm
  code/modules/mob/living/silicon/robot/robot_modules/station.dm
  code/modules/mob/living/silicon/robot/robot_modules/syndicate.dm
  code/modules/mob/new_player/sprite_accessories.dm
  code/modules/mob/transform_procs.dm
  code/modules/virus2/disease2.dm
  code/stylesheet.dm
  html/changelogs/example - Copy.yml
Labels: Feature, Lore

#5046 Munitions/Security Supplypack touchy
  code/datums/supplypacks/contraband.dm
  code/datums/supplypacks/misc.dm
  code/datums/supplypacks/munitions.dm
  code/datums/supplypacks/security.dm
  html/changelogs/Woodrat - Supplypack Adjustments.yml
  maps/southern_cross/datums/supplypacks/munitions.dm
  maps/southern_cross/southern_cross.dm
Labels: Feature Tweak

#5054 Ater missed another <br>
  code/game/objects/items/devices/scanners.dm
Labels: Oversight

#5047 Sundry Runtime Fixes - March
  code/game/objects/buckling.dm
  code/game/objects/items/weapons/tools.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/robot/robot_items.dm
  code/modules/multiz/zshadow.dm
  code/modules/paperwork/paper_bundle.dm
Labels: Bugfix

#5057 Fixes Durasteel Alloying Producing Slag
  code/modules/mining/ore_datum.dm
Labels: Bugfix

#5023 Attaches Tajaran tails to 3 more station rigsuits
  html/changelogs/Nerezza - off-the-chopblock.yml
  icons/mob/species/tajaran/suit.dmi
Labels: Sprite Change

#5038 Adds wiggles to crawling
  code/game/turfs/turf.dm
Labels: Feature

#5056 I h*ckin' did an ambient music.
  code/game/area/Space Station 13 areas.dm
  maps/southern_cross/southern_cross_areas.dm
  sound/ambience/serspaceamb1.ogg
Labels: Feature

#5063 [PORT] Make cryopods check area first, then range
  code/game/machinery/cryopod.dm
Labels: Bugfix

#5070 Updates changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Anewbe - Pills.yml
  html/changelogs/Anewbe - Robolimb Repair.yml
  html/changelogs/Anewbe - Syringes.yml
  html/changelogs/Anewbe - VeyMed EMP tweaks.yml
  html/changelogs/MisterLayne - ED-CLN.yml
  html/changelogs/MisterLayne - SnowballTEMPFIX.yml
  html/changelogs/Nerezza - APC-Tweak.yml
  html/changelogs/Nerezza - Hardsuit-fixes.yml
  html/changelogs/Nerezza - off-the-chopblock.yml
  html/changelogs/Nerezza - sifwoodfix.yml
  html/changelogs/Woodrat - Supplypack Adjustments.yml
  html/changelogs/example - Copy.yml
Labels: Changelog Update

#5052 Ports ghost pAI alert
  code/modules/mob/dead/observer/observer.dm
  icons/obj/pda_old.dmi
Labels: Feature

#5027 Couple borg UI fixes.
  code/_onclick/hud/robot.dm
  icons/mob/screen1_robot.dmi
  icons/mob/screen1_robot_minimalist.dmi
Labels: Bugfix

#5053 Should speed up ZAS
  code/controllers/subsystems/air.dm
  code/controllers/subsystems/airflow.dm
Labels: Feature Tweak

#5048 More projectiles now ignite things
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/animate.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/change.dm
  code/modules/projectiles/projectile/energy.dm
  code/modules/projectiles/projectile/force.dm
  code/modules/projectiles/projectile/special.dm
Labels: Feature Tweak

#5049 Ports quickdraw storage items from VIRGO
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/quickdraw.dm
  icons/obj/storage.dmi
  polaris.dme
Labels: Feature

#5062 [PORT] Fix oversight in not-late-join jobs without spawnpoints on the map.
  code/game/jobs/job_controller.dm
Labels: Bugfix, Oversight

#5068 terminus is now not just serial-numbers-filed-off Spacer
  code/modules/mob/language/generic.dm
Labels: Feature Tweak

#5064 [PORT] Improved playsound and drop_location() from /tg
  code/__defines/atmos.dm
  code/__defines/sound.dm
  code/game/area/areas.dm
  code/game/atoms.dm
  code/game/machinery/kitchen/gibber.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/sound.dm
  code/game/turfs/turf.dm
  code/modules/admin/view_variables/view_variables.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob_helpers.dm
  code/modules/shuttles/shuttle.dm
  polaris.dme
Labels: Feature

#4931 Adds a cursed sword (and other haunted things)
  code/datums/ghost_query.dm
  code/game/objects/items/weapons/melee/misc.dm
  code/game/objects/objs.dm
  code/game/objects/structures/ghost_pods/ghost_pods.dm
  code/game/objects/structures/ghost_pods/silicon.dm
  code/modules/mob/living/carbon/brain/MMI.dm
  code/modules/mob/living/carbon/brain/say.dm
  icons/mob/back.dmi
  icons/mob/items/lefthand_melee.dmi
  icons/mob/items/righthand_melee.dmi
  icons/obj/structures.dmi
  icons/obj/weapons.dmi
  maps/submaps/surface_submaps/mountains/SwordCave.dmm
  maps/submaps/surface_submaps/mountains/mountains.dm
  maps/submaps/surface_submaps/mountains/mountains_areas.dm
Labels: Feature, Point of Interest

#5025 Fixes for gripper interaction with frame parts and mecha equipment
  code/game/machinery/wall_frames.dm
  code/modules/mob/living/silicon/robot/drone/drone_items.dm
  code/modules/mob/living/silicon/robot/robot.dm
  html/changelogs/Heroman3003 - Gripper Fixes.yml
Labels: Bugfix

#5060 AFK Kicker should affect ghosts and people in the lobby
  code/controllers/Processes/inactivity.dm
Labels: Feature Tweak

#5067 [PORT] Cleans up Humanoid Hiding
  code/__defines/mobs.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_powers.dm
  code/modules/mob/living/living_powers.dm
Labels: Refactor

#5075 Adds snow footsteps
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/simulated/outdoors/snow.dm
  sound/effects/footstep/snow1.ogg
  sound/effects/footstep/snow2.ogg
  sound/effects/footstep/snow3.ogg
  sound/effects/footstep/snow4.ogg
  sound/effects/footstep/snow5.ogg
Labels: Feature, Feature Tweak

#5051 Ports export reports
  code/game/machinery/computer/supply.dm
  code/game/supplyshuttle.dm
Labels: Feature

#5058 Xenoarch Multitool & Xenoarch Excavation Drill
  code/game/objects/items/weapons/storage/belt.dm
  code/modules/mining/mine_turfs.dm
  code/modules/research/designs.dm
  code/modules/xenoarcheaology/boulder.dm
  code/modules/xenoarcheaology/tools/tools.dm
  code/modules/xenoarcheaology/tools/tools_pickaxe.dm
  html/changelogs/Cameron - Xenoarch Upgrades.yml
  icons/obj/xenoarchaeology.dmi
Labels: Feature

#5050 Ports antibiotics overhaul
  code/__defines/chemistry.dm
  code/modules/organs/internal/organ_internal.dm
  code/modules/organs/organ.dm
  code/modules/organs/organ_external.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/virus2/disease2.dm
  code/modules/virus2/helpers.dm
Labels: Feature Tweak

#5082 Fixes preview color splotch blues
  code/modules/client/preference_setup/general/03_body.dm
Labels: Bugfix

#5081 Clean up diona-specific stuff in life.dm, move to its own section.
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
Labels: Refactor

#5080 Fixes the drone borg ID thing AGAIN.
  code/game/jobs/job_controller.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Oversight

#5089 Port Recharger Fixes
  code/game/machinery/rechargestation.dm
Labels: Bugfix

#5071 Makes coffee milkshakes STOP KILLING PEOPLE
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
Labels: Feature Tweak

#5088 VOREStation Ports Catchup
  code/__defines/mobs.dm
  code/_helpers/logging.dm
  code/game/gamemodes/changeling/powers/revive.dm
  code/game/objects/items/devices/communicator/UI.dm
  code/game/objects/items/devices/communicator/communicator.dm
  code/modules/admin/admin.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/client/preference_setup/general/03_body.dm
  code/modules/client/preference_setup/occupation/occupation.dm
  code/modules/clothing/clothing.dm
  code/modules/mob/animations.dm
  code/modules/mob/freelook/chunk.dm
  code/modules/mob/freelook/update_triggers.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/metroid/life.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/multiz/zshadow.dm
Labels: Bugfix, Refactor

#5092 Removes some problematic HIDEJUMPSUIT flags
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/jobs.dm
Labels: Bugfix

#5084 Tooltip framework + Mob tooltips
  code/_helpers/mobs.dm
  code/game/atoms.dm
  code/modules/client/client defines.dm
  code/modules/client/preference_setup/global/01_ui.dm
  code/modules/client/preference_setup/global/setting_datums.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_toggle_procs.dm
  code/modules/client/ui_style.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/simple_animal/animals/bat.dm
  code/modules/mob/living/simple_animal/animals/bear.dm
  code/modules/mob/living/simple_animal/animals/carp.dm
  code/modules/mob/living/simple_animal/animals/cat.dm
  code/modules/mob/living/simple_animal/animals/corgi.dm
  code/modules/mob/living/simple_animal/animals/crab.dm
  code/modules/mob/living/simple_animal/animals/farm_animals.dm
  code/modules/mob/living/simple_animal/animals/giant_spider.dm
  code/modules/mob/living/simple_animal/animals/goose.dm
  code/modules/mob/living/simple_animal/animals/lizard.dm
  code/modules/mob/living/simple_animal/animals/mouse.dm
  code/modules/mob/living/simple_animal/animals/parrot.dm
  code/modules/mob/living/simple_animal/animals/penguin.dm
  code/modules/mob/living/simple_animal/animals/slime.dm
  code/modules/mob/living/simple_animal/animals/spiderbot.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/login.dm
  code/modules/mob/mob.dm
  code/modules/tooltip/tooltip.dm
  code/modules/tooltip/tooltip.html
  interface/skin.dmf
  polaris.dme
Labels: Feature

#5085 Port Shuttle Pilot Helmet Animation
  code/game/machinery/doors/airlock.dm
  code/modules/clothing/head/pilot_helmet.dm
  code/modules/shuttles/shuttle.dm
  code/modules/shuttles/shuttles_web.dm
  icons/mob/pilot_helmet.dmi
  icons/mob/species/seromi/pilot_helmet.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/piloting_overlay.dmi
  maps/southern_cross/items/clothing/sc_head.dm
  maps/southern_cross/southern_cross.dm
  polaris.dme
Labels: Feature

#5091 Fixes cameras making completely black photos
  code/_helpers/icons.dm
Labels: Bugfix

#5095 Updates tracking implant description
  code/game/objects/items/weapons/implants/implant.dm
Labels: Lore

#5093 Cherrypicks missing typing indicator commit from Virgo
  code/modules/client/preference_setup/global/setting_datums.dm
  code/modules/client/preferences_toggle_procs.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/say.dm
  code/modules/mob/typing_indicator.dm
  code/modules/multiz/zshadow.dm
Labels: Bugfix

#5104 Revert "Fixes cameras making completely black photos"
  code/_helpers/icons.dm
Labels: Bugfix, Experimental: Needs End Date, Revert

#5110 Fixes Suit Storage Icons
  code/__defines/items_clothing.dm
Labels: Bug, Priority: High

#5079 Adds permanent markers
  code/datums/supplypacks/recreation.dm
  code/game/objects/items/crayons.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/modules/paperwork/pen.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
  code/modules/reagents/Chemistry-Recipes.dm
  html/changelogs/Billybangles - Markers.yml
  icons/obj/crayons.dmi
  maps/northern_star/polaris-1.dmm
  maps/southern_cross/southern_cross-1.dmm
Labels: Feature, Map Change / Issue

#5105 Nanoui now supports use of multiple templates
  code/modules/nano/nanoui.dm
  nano/js/nano_state.js
  nano/js/nano_template.js
Labels: Refactor

#5111 Lore-Compliant Oculum News Channel
  code/modules/economy/economy_misc.dm
  code/modules/economy/lorenews.dm
  code/modules/events/event_container.dm
  code/modules/events/event_dynamic.dm
  polaris.dme
Labels: Lore

#5112 prettified lorecodex, added a month's worth of news
  code/modules/lore_codex/news_data/main.dm
Labels: Lore

#5086 Pipe Construction Rewrite
  code/ATMOSPHERICS/_atmos_setup.dm
  code/ATMOSPHERICS/_atmospherics_helpers.dm
  code/ATMOSPHERICS/atmospherics.dm
  code/ATMOSPHERICS/components/binary_devices/binary_atmos_base.dm
  code/ATMOSPHERICS/components/binary_devices/circulator.dm
  code/ATMOSPHERICS/components/binary_devices/dp_vent_pump.dm
  code/ATMOSPHERICS/components/binary_devices/passive_gate.dm
  code/ATMOSPHERICS/components/binary_devices/pipeturbine.dm
  code/ATMOSPHERICS/components/binary_devices/pump.dm
  code/ATMOSPHERICS/components/binary_devices/volume_pump.dm
  code/ATMOSPHERICS/components/omni_devices/filter.dm
  code/ATMOSPHERICS/components/omni_devices/mixer.dm
  code/ATMOSPHERICS/components/omni_devices/omni_base.dm
  code/ATMOSPHERICS/components/portables_connector.dm
  code/ATMOSPHERICS/components/trinary_devices/filter.dm
  code/ATMOSPHERICS/components/trinary_devices/mixer.dm
  code/ATMOSPHERICS/components/trinary_devices/trinary_base.dm
  code/ATMOSPHERICS/components/tvalve.dm
  code/ATMOSPHERICS/components/unary/cold_sink.dm
  code/ATMOSPHERICS/components/unary/heat_exchanger.dm
  code/ATMOSPHERICS/components/unary/heat_source.dm
  code/ATMOSPHERICS/components/unary/outlet_injector.dm
  code/ATMOSPHERICS/components/unary/unary_base.dm
  code/ATMOSPHERICS/components/unary/vent_pump.dm
  code/ATMOSPHERICS/components/unary/vent_scrubber.dm
  code/ATMOSPHERICS/components/valve.dm
  code/ATMOSPHERICS/mainspipe.dm
  code/ATMOSPHERICS/pipes/cap.dm
  code/ATMOSPHERICS/pipes/he_pipes.dm
  code/ATMOSPHERICS/pipes/manifold.dm
  code/ATMOSPHERICS/pipes/manifold4w.dm
  code/ATMOSPHERICS/pipes/pipe_base.dm
  code/ATMOSPHERICS/pipes/simple.dm
  code/ATMOSPHERICS/pipes/tank.dm
  code/ATMOSPHERICS/pipes/universal.dm
  code/ATMOSPHERICS/pipes/vent.dm
  code/__defines/construction.dm
  code/__defines/math.dm
  code/game/machinery/pipe/construction.dm
  code/game/machinery/pipe/pipe_dispenser.dm
  code/game/machinery/pipe/pipe_recipes.dm
  code/game/machinery/pipe/pipelayer.dm
  code/modules/multiz/pipes.dm
  icons/atmos/heat.dmi
  icons/atmos/junction.dmi
  icons/obj/pipe-item.dmi
  polaris.dme
Labels: Refactor

#5115 Fix for MOB_CAN_SEE_PLANE
  code/__defines/_planes+layers.dm
Labels: Bugfix

#5076 MDs and EMTs spawn with the white medkit
  code/datums/outfits/jobs/medical.dm
  html/changelogs/Anewbe - Medkits.yml
Labels: Forum Discussion in Progress, Staff Request, Unwanted Feature Removal

#5126 Fixes fullbright mode hiding lighting overlays.
  code/modules/mob/mob_planes.dm
Labels: Bugfix

#5127 Table Layering and Runtime Fixes
  code/__defines/_planes+layers.dm
  code/modules/mob/language/language.dm
  code/modules/tables/tables.dm
Labels: Bugfix, Priority: High

#5128 Fixes #4951
  code/modules/mob/living/silicon/pai/software_modules.dm
  nano/templates/crew_manifest.tmpl
  nano/templates/pai_manifest.tmpl
Labels: Bugfix

#5113 44 revolvers
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/ammunition/rounds.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile/revolver.dm
  code/modules/projectiles/projectile/bullets.dm
  html/changelogs/Woodrat - 44 Revolver.yml
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
  icons/obj/ammo.dmi
  icons/obj/gun.dmi
Labels: Feature

#5101 Fixes custom accessories not showing up on things
  code/modules/clothing/under/accessories/accessory.dm
Labels: Bugfix

#5129 Adds a message on emag to the battle arcade machine.
  code/game/machinery/computer/arcade.dm
Labels: Bugfix

#5102 Fixes inconsistencies in organ system
  code/modules/organs/subtypes/diona.dm
  code/modules/organs/subtypes/standard.dm
Labels: Refactor
