Repository PolarisSS13/Polaris, pull requests merged in 2018-12, with the labels that each got.

#5715 Updates Rapid Service Fabricators.
  code/game/objects/items/weapons/RSF.dm
  html/changelogs/Mechoid-RSFs.yml
Labels: Bugfix, Feature Tweak

#5718 New hair + underwear
  code/datums/underwear/socks.dm
  code/datums/underwear/top.dm
  code/datums/underwear/undershirts.dm
  code/modules/mob/new_player/sprite_accessories.dm
  html/changelogs/kartagrafi-NewHairAndUnderwear.yml
  icons/mob/human.dmi
  icons/mob/human_face.dmi
  icons/mob/human_face_m.dmi
Labels: Feature, To Be Merged After Freeze

#5737 Adds logging to special world reboots, admins with debug access can now reboot while world is OOM'd
  code/world.dm
Labels: Feature Tweak, To Be Merged After Freeze

#5742 Changes Mech Diamond Drill Cooldown
  code/game/mecha/equipment/tools/tools.dm
Labels: To Be Merged After Freeze

#5649 ᵗᵉᵉⁿʸ ᶠˡᵃˢʰˡᶦᵍʰᵗ ᵗʷᵉᵃᵏ
  code/game/objects/items/devices/flashlight.dm
  sound/machines/button.ogg
Labels: Feature Tweak

#5643 Mech noises update.
  code/game/mecha/combat/durand.dm
  code/game/mecha/combat/gygax.dm
  code/game/mecha/combat/marauder.dm
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/mecha/mecha.dm
  sound/mecha/duranddefencemode.ogg
  sound/mecha/gasconnected.ogg
  sound/mecha/gasdisconnected.ogg
  sound/mecha/heavylightswitch.ogg
  sound/mecha/mech_reload_default.ogg
  sound/mecha/mechanical_toggle.ogg
Labels: Feature Tweak

#5713 Fixes personal ownership of cats
  code/modules/mob/living/simple_animal/animals/cat.dm
Labels: Bugfix

#5745 Updates changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Cerebulon - Namelists.yml
  html/changelogs/Kates - Hedgetrimmers.yml
  html/changelogs/Lbnesquik - Botany improvements #5662.yml
  html/changelogs/Mechoid-PromBlud.yml
  html/changelogs/Mechoid-RSFs.yml
  html/changelogs/Neerti-AI.yml
  html/changelogs/Neerti-RCDs.yml
  html/changelogs/Woodrat - XenoMove.yml
  html/changelogs/kartagrafi-NewHairAndUnderwear.yml
Labels: Changelog Update

#5723 Promethean Regen tweaks. (The one with the devil's deal.)
  code/modules/mob/living/carbon/human/human_powers.dm
  code/modules/mob/living/carbon/human/species/station/prometheans.dm
Labels: Feature Tweak

#5726 Refactors Sun and Inactivity processes to subsystems, and a few globa lvariables to be managed
  code/controllers/Processes/sun.dm
  code/controllers/subsystems/inactivity.dm
  code/controllers/subsystems/sun.dm
  code/controllers/verbs.dm
  code/datums/sun.dm
  code/global.dm
  code/modules/events/solar_storm.dm
  code/modules/power/solar.dm
  polaris.dme
Labels: Refactor

#5714 Borg, Gripper, and Integrated Circuit interaction update.
  code/__defines/objects.dm
  code/game/objects/items/devices/multitool.dm
  code/modules/integrated_electronics/core/assemblies.dm
  code/modules/integrated_electronics/core/assemblies/generic.dm
  code/modules/integrated_electronics/core/integrated_circuit.dm
  code/modules/integrated_electronics/core/pins.dm
  code/modules/integrated_electronics/core/printer.dm
  code/modules/integrated_electronics/core/special_pins/ref_pin.dm
  code/modules/integrated_electronics/core/tools.dm
  code/modules/mob/living/silicon/robot/drone/drone_items.dm
  code/modules/mob/living/silicon/robot/robot_modules/station.dm
  html/changelogs/Mechoid-Grippers.yml
  icons/obj/device.dmi
  polaris.dme
Labels: Feature, Feature Tweak, Quality of Life, To Be Merged After Freeze

#5747 Makes fulltile windows seperate from dir
  code/game/atoms_movable.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/structures/window.dm
  code/modules/materials/materials.dm
  code/modules/mob/living/living.dm
Labels: Refactor

#5748 Adds ability to selectively disable submap rotation.
  code/controllers/configuration.dm
  code/modules/maps/tg/map_template.dm
  config/example/config.txt
  maps/submaps/surface_submaps/plains/plains.dm
Labels: Feature Tweak

#5654 Makes math helpers defines for performance
  code/__defines/math.dm
  code/__defines/math_physics.dm
  code/_helpers/maths.dm
  code/_helpers/vector.dm
  code/controllers/subsystems/overlays.dm
  code/datums/beam.dm
  code/game/machinery/bioprinter.dm
  code/game/machinery/cloning.dm
  code/game/machinery/doors/blast_door.dm
  code/game/objects/effects/chem/chemsmoke.dm
  code/game/objects/items/devices/defib.dm
  code/game/objects/items/weapons/id cards/cards.dm
  code/game/objects/items/weapons/tools/weldingtool.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/window.dm
  code/modules/admin/admin.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/events/brand_intelligence.dm
  code/modules/food/kitchen/cooking_machines/_cooker.dm
  code/modules/gamemaster/actions/carp_migration.dm
  code/modules/games/cards.dm
  code/modules/integrated_electronics/subtypes/converters.dm
  code/modules/integrated_electronics/subtypes/trig.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/language/language.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/descriptors/_descriptors.dm
  code/modules/mob/living/carbon/metroid/powers.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/animals/giant_spider.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/carrier.dm
  code/modules/organs/organ_icon.dm
  code/modules/paperwork/papershredder.dm
  code/modules/planet/sif.dm
  code/modules/planet/time.dm
  code/modules/planet/weather.dm
  code/modules/power/cable.dm
  code/modules/power/fusion/core/core_field.dm
  code/modules/power/fusion/fuel_assembly/fuel_assembly.dm
  code/modules/power/singularity/emitter.dm
  code/modules/projectiles/gun.dm
  code/modules/random_map/noise/noise.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/shieldgen/directional_shield.dm
  code/modules/shuttles/shuttles_web.dm
  code/modules/turbolift/turbolift_map.dm
  polaris.dme
Labels: Refactor

#5744 Adds 12 new futuristic loadout clothing items + colour variants
  code/modules/client/preference_setup/loadout/loadout_accessories.dm
  code/modules/client/preference_setup/loadout/loadout_eyes.dm
  code/modules/client/preference_setup/loadout/loadout_head.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/accessories/clothing.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/clothing/under/pants.dm
  html/changelogs/Cerebulon - Clothes.yml
  icons/mob/eyes.dmi
  icons/mob/head.dmi
  icons/mob/species/seromi/eyes.dmi
  icons/mob/species/seromi/head.dmi
  icons/mob/species/seromi/suit.dmi
  icons/mob/species/seromi/uniform.dmi
  icons/mob/suit.dmi
  icons/mob/ties.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/glasses.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/ties.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature

#5758 Fixes several bugs with AI mobs
  code/modules/ai/aI_holder_subtypes/simple_mob_ai.dm
  code/modules/ai/aI_holder_subtypes/slime_xenobio_ai.dm
  code/modules/ai/ai_holder_targeting.dm
  code/modules/mob/living/simple_mob/combat.dm
  code/modules/mob/living/simple_mob/subtypes/slime/xenobio/xenobio.dm
Labels: Bugfix

#5760 Adds BIOACID damage type
  code/__defines/damage_organs.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/projectiles/projectile/energy.dm
Labels: Feature

#5756 Fixes a few AI bugs
  code/modules/ai/ai_holder_combat.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/nurse.dm
Labels: Bugfix

#5757 Adds several new map/event oriented objects
  code/datums/beam.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/effects/map_effects/beam_point.dm
  code/game/objects/effects/map_effects/effect_emitter.dm
  code/game/objects/effects/map_effects/map_effects.dm
  code/game/objects/effects/map_effects/perma_light.dm
  code/game/objects/effects/map_effects/radiation_emitter.dm
  code/game/objects/effects/map_effects/screen_shaker.dm
  code/game/objects/effects/map_effects/sound_emitter.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/living.dm
  code/modules/power/lighting.dm
  icons/effects/effects.dmi
  icons/effects/map_effects.dmi
  polaris.dme
Labels: Feature

#5746 Adds like 4 million articles.
  code/modules/lore_codex/news_data/main.dm
Labels: Feature

#5769 Fixes a compile error with the Initialize() proc
  code/datums/beam.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/effects/map_effects/beam_point.dm
  code/game/objects/effects/map_effects/effect_emitter.dm
  code/game/objects/effects/map_effects/map_effects.dm
  code/game/objects/effects/map_effects/radiation_emitter.dm
Labels: Bugfix, Priority: CRITICAL

#5768 Updates changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Cerebulon - Clothes.yml
  html/changelogs/Mechoid-Grippers.yml
Labels: Changelog Update

#5767 Fixed a typo in Space Heater's cell removal message
  code/game/machinery/spaceheater.dm
Labels: Bugfix

#5724 Added washing machine working sound
  code/game/machinery/washing_machine.dm
  sound/items/washingmachine.ogg
Labels: Feature Tweak

#5775 Startup runtimes
  code/_global_vars/misc.dm
  code/controllers/Processes/alarm.dm
  code/controllers/Processes/scheduler.dm
  code/datums/observation/_debug.dm
  code/datums/observation/destroyed.dm
  code/datums/observation/observation.dm
  code/datums/observation/~cleanup.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/modules/error_handler/error_handler.dm
  code/modules/holomap/station_holomap.dm
  code/modules/integrated_electronics/subtypes/manipulation.dm
Labels: Bugfix

#5778 Stops initialization from grinding to a halt when loading maps
  code/__defines/subsystems.dm
  code/controllers/subsystem.dm
  code/controllers/subsystems/mapping.dm
  code/modules/admin/verbs/map_template_loadverb.dm
  code/modules/maps/tg/map_template.dm
  code/world.dm
  polaris.dme
Labels: Bugfix, Priority: CRITICAL

#5773 Adds Identification System, New Autoinjectors
  code/__defines/_planes+layers.dm
  code/__defines/objects.dm
  code/game/gamemodes/technomancer/devices/hypos.dm
  code/game/machinery/door_control.dm
  code/game/machinery/doors/blast_door.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/random/unidentified/medicine.dm
  code/game/objects/structures/loot_piles.dm
  code/modules/identification/identification.dm
  code/modules/identification/item_procs.dm
  code/modules/reagents/Chemistry-Machinery.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/unidentified_hypospray.dm
  icons/obj/chemical.dmi
  icons/obj/loot_piles.dmi
  maps/southern_cross/southern_cross-1.dmm
  polaris.dme
  tools/mapmerge/1prepare_map.sh
  tools/mapmerge/2clean_map.sh
Labels: Feature

#5764 Event / Future PoI / Other weaponry & tools.
  code/modules/mob/_modifiers/modifiers_misc.dm
  code/modules/projectiles/effects.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/hooklauncher.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/magnetic/bore.dm
  code/modules/projectiles/projectile/hook.dm
  code/modules/projectiles/projectile/magnetic.dm
  code/modules/projectiles/projectile/special.dm
  icons/effects/projectiles.dmi
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
  icons/obj/gun.dmi
  icons/obj/projectiles.dmi
  icons/obj/railgun.dmi
  polaris.dme
Labels: Feature

#5765 Speeds up getFlatIcon
  code/_helpers/icons.dm
Labels: Optimization

#5792 Ports the lightpost and present tree from tg.
  code/game/objects/structures/flora/trees.dm
  code/game/objects/structures/lightpost.dm
  icons/obj/32x64.dmi
  icons/obj/flora/pinetrees.dmi
  polaris.dme
Labels: Feature

#5770 Standardizes rotation verbs
  code/ATMOSPHERICS/components/binary_devices/circulator.dm
  code/ATMOSPHERICS/components/binary_devices/pipeturbine.dm
  code/game/machinery/frame.dm
  code/game/machinery/pipe/construction.dm
  code/game/objects/structures/electricchair.dm
  code/game/objects/structures/gravemarker.dm
  code/game/objects/structures/musician.dm
  code/game/objects/structures/railing.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/windoor_assembly.dm
  code/game/objects/structures/window.dm
  code/modules/assembly/infrared.dm
  code/modules/mining/drilling/drill.dm
  code/modules/overmap/ships/ship.dm
  code/modules/power/fusion/fuel_assembly/fuel_injector.dm
  code/modules/power/generator.dm
  code/modules/power/singularity/emitter.dm
  code/modules/power/singularity/particle_accelerator/particle_accelerator.dm
  code/modules/recycling/disposal-construction.dm
  code/modules/shieldgen/shield_capacitor.dm
  code/modules/xenoarcheaology/tools/suspension_generator.dm
Labels: Quality of Life

#5795 Standardises SifGov to VirGov
  code/game/objects/banners.dm
  code/modules/busy_space/organizations.dm
  code/modules/lore_codex/legal_code_data/main.dm
  code/modules/lore_codex/legal_code_data/sif_law.dm
  code/modules/lore_codex/legal_code_data/sop/security.dm
  code/modules/lore_codex/lore_data/important_locations.dm
Labels: Lore

#5779 Emergency tanks start full
  code/game/objects/items/weapons/tanks/tank_types.dm
  html/changelogs/Novacat-PR-5779.yml
Labels: Feature Tweak
