Repository PolarisSS13/Polaris, pull requests merged in 2018-06, with the labels that each got.

#5313 Move character join log statement
  code/game/jobs/job_controller.dm
  code/modules/mob/new_player/new_player.dm
Labels: Bugfix

#5310 Fixed arcades dispensing their own board
  code/game/machinery/computer/arcade.dm
Labels: Bugfix

#5318 Fixed xenoarch multitool being unmakeable
  code/modules/research/designs.dm
Labels: Bugfix

#5314 Fix surgery breaking bones when performed correctly
  code/modules/surgery/encased.dm
Labels: Unwanted Feature Removal

#5305 Prevent autosay() from creating/deleting AIs
  code/_helpers/global_lists.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Optimization, Refactor

#5320 Radiation closet hood fix
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
Labels: Bugfix, Priority: CRITICAL

#5319 Adds two new sets of robolimbs
  code/modules/organs/robolimbs.dm
  icons/mob/human_races/cyberlimbs/unbranded/unbranded_alt1.dmi
  icons/mob/human_races/cyberlimbs/unbranded/unbranded_alt2.dmi
Labels: Feature

#5301 Adds armor to certain mobs, mercs have knives
  code/modules/mob/living/simple_animal/aliens/drone.dm
  code/modules/mob/living/simple_animal/humanoids/mechamobs.dm
  code/modules/mob/living/simple_animal/humanoids/syndicate.dm
  html/changelogs/Anewbe - More Merc PoIs.yml
Labels: Feature Tweak, Point of Interest, Prepare to Die

#5327 Changes "Setup Character" to "Character Setup"
  code/modules/mob/new_player/new_player.dm
Labels: Bugfix

#5326 Ion Rifle returned to original radius.
  code/modules/projectiles/projectile/special.dm
  html/changelogs/Mechoid - Ionrifle.yml
Labels: Bugfix, Oversight

#5325 Changes experimental welder fluff
  code/game/objects/items/weapons/tools.dm
Labels: Lore

#5331 Fix #5316 and #5220
  code/modules/xenoarcheaology/artifacts/replicator.dm
  code/modules/xenoarcheaology/tools/equipment.dm
Labels: Bugfix, Oversight

#5330 Fix #5321
  code/modules/hydroponics/seed_storage.dm
Labels: Bugfix

#5323 Wallet money spawns as a bundle.
  code/game/objects/items/weapons/storage/wallets.dm
Labels: Feature Tweak

#5334 Ater forgot to remove debug code
  code/game/machinery/computer3/component.dm
Labels: Oversight, Priority: High

#5336 Cult robes use the right sprite again
  code/game/gamemodes/cult/cult_items.dm
Labels: Bugfix, Oversight

#5333 Mining turf overlays should be properly placed now
  code/modules/mining/mine_turfs.dm
Labels: Bugfix

#5339 Change-Eye-Color verb should work again
  code/modules/organs/internal/eyes.dm
Labels: Bugfix

#5341 Wires are under catwalks, fueltanks are over floor decals
  code/game/objects/structures/catwalk.dm
  code/modules/reagents/reagent_dispenser.dm
Labels: Bugfix, Layering Issue

#5183 Robolimb brand damage tweaks, makes VeyMed more fragile
  code/modules/organs/organ_external.dm
  code/modules/organs/robolimbs.dm
  html/changelogs/Anewbe - Robolimb Fragility.yml
Labels: Controversial, Feature Tweak, Forum Discussion in Progress, Requires Staff Input

#5343 prevent slimes from spawning on top of people
  code/_helpers/events.dm
  code/modules/events/atmos_leak.dm
  code/modules/events/escaped_slimes.dm
Labels: Bugfix

#5344 Sky is not a 'skiy'
  code/modules/multiz/movement.dm
Labels: Bugfix

#5335 Ports some Bay hair code
  code/__defines/items_clothing.dm
  code/modules/mob/living/carbon/human/human_powers.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/new_player/sprite_accessories.dm
  code/modules/organs/organ_icon.dm
Labels: Feature, Ported from Baycode

#5352 Adds a "cancel" option to the Drop-Bomb admin verb.
  code/modules/admin/admin_verbs.dm
Labels: Feature Tweak

#5351 Fixes "glass of cup of coffee"
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
Labels: Bugfix

#5349 Clothing Bug Fixes
  code/modules/clothing/head/misc.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/suits/utility.dm
  icons/mob/ears.dmi
  icons/mob/mask.dmi
  icons/mob/spacesuit.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/masks.dmi
Labels: Bugfix

#5322 Move planets to SSplanets
  code/__defines/subsystems.dm
  code/controllers/Processes/planet.dm
  code/controllers/subsystems/planets.dm
  code/controllers/verbs.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/items/devices/communicator/UI.dm
  code/game/turfs/simulated/outdoors/outdoors.dm
  code/game/turfs/simulated/outdoors/sky.dm
  code/game/turfs/unsimulated/planetary.dm
  code/modules/admin/verbs/debug.dm
  code/modules/events/gravity.dm
  code/modules/planet/planet.dm
  code/modules/planet/sif.dm
  polaris.dme
Labels: Refactor

#5282 Allows AIs to produce and control maint/construction/mining drones.
  code/controllers/configuration.dm
  code/game/machinery/computer/ai_core.dm
  code/game/objects/items/devices/aicard.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/death.dm
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/mob/living/silicon/robot/drone/drone.dm
  code/modules/mob/living/silicon/robot/drone/drone_manufacturer.dm
  code/modules/mob/living/silicon/robot/drone/drone_remote_control.dm
  html/changelogs/Mechoid - AI_Drones.yml
  icons/mob/robots.dmi
  polaris.dme
Labels: Feature

#5337 Folders props, and adds the laser prism, receptor, and sealed doors.
  code/game/objects/structures/props/alien_props.dm
  code/game/objects/structures/props/beam_prism.dm
  code/game/objects/structures/props/projectile_lock.dm
  code/game/objects/structures/props/prop.dm
  code/game/objects/structures/props/puzzledoor.dm
  icons/obj/props/prism.dmi
  icons/obj/props/projectile_lock.dmi
  polaris.dme
Labels: Feature, Point of Interest

#5350 Weather is shorter, hail is less deadly.
  code/modules/planet/sif.dm
  code/modules/planet/weather.dm
Labels: Feature Tweak

#5355 Bioprinters and Cloners now use Biomass reagent, maps in a Bioprinter
  code/game/machinery/bioprinter.dm
  code/game/machinery/cloning.dm
  code/game/machinery/computer/cloning.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  html/changelogs/Anewbe - Biomass.yml
  maps/southern_cross/southern_cross-1.dmm
Labels: Feature Tweak, Map Change / Issue

#5357 Use SSoverlays please
  code/modules/organs/organ_icon.dm
Labels: Bugfix, Oversight

#5356 Recharger refactor
  code/game/machinery/computer3/laptop.dm
  code/game/machinery/recharger.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/devices/radio/jammer.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/items/weapons/tools.dm
  code/game/objects/objs.dm
  code/modules/integrated_electronics/core/device.dm
  code/modules/power/cell.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/magnetic/magnetic.dm
  code/modules/shieldgen/handheld_defuser.dm
Labels: Ported from Baycode, Refactor

#5276 More Phase Guns
  code/modules/projectiles/guns/energy/phase.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/projectile/energy.dm
  code/modules/research/designs.dm
  code/modules/research/designs/ai_modules.dm
  code/modules/research/designs/circuit_assembly.dm
  code/modules/research/designs/circuits.dm
  code/modules/research/designs/illegal.dm
  code/modules/research/designs/medical.dm
  code/modules/research/designs/mining_toys.dm
  code/modules/research/designs/misc.dm
  code/modules/research/designs/pdas.dm
  code/modules/research/designs/powercells.dm
  code/modules/research/designs/stock_parts.dm
  code/modules/research/designs/uncommented.dm
  code/modules/research/designs/weapons.dm
  icons/mob/back.dmi
  icons/mob/belt.dmi
  icons/mob/belt_mirror.dmi
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
  icons/obj/gun.dmi
  icons/obj/projectiles.dmi
  maps/southern_cross/datums/supplypacks/munitions.dm
  polaris.dme
Labels: Feature

#5358 Backports turret faction code
  code/game/machinery/portable_turret.dm
Labels: Feature

#5360 Adds aura style modifier code
  code/modules/mob/_modifiers/aura.dm
  polaris.dme
Labels: Feature

#5359 Adds arcing projectiles
  code/modules/projectiles/projectile/arc.dm
Labels: Feature

#5366 Fix AI-drone runtimes. Get angry at commits.
  code/modules/mob/living/silicon/robot/drone/drone.dm
  code/modules/mob/living/silicon/robot/drone/drone_remote_control.dm
Labels: Bugfix

#5363 Clones merc simple_animal mobs into the simple_mob format
  code/__defines/subsystems.dm
  code/controllers/Processes/planet.dm
  code/controllers/configuration.dm
  code/controllers/subsystems/planets.dm
  code/controllers/verbs.dm
  code/game/machinery/computer/ai_core.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/items/devices/aicard.dm
  code/game/objects/items/devices/communicator/UI.dm
  code/game/objects/items/weapons/grenades/explosive.dm
  code/game/objects/structures/props/alien_props.dm
  code/game/objects/structures/props/beam_prism.dm
  code/game/objects/structures/props/projectile_lock.dm
  code/game/objects/structures/props/prop.dm
  code/game/objects/structures/props/puzzledoor.dm
  code/game/turfs/simulated/outdoors/outdoors.dm
  code/game/turfs/simulated/outdoors/sky.dm
  code/game/turfs/unsimulated/planetary.dm
  code/modules/admin/verbs/debug.dm
  code/modules/ai/__readme.dm
  code/modules/ai/interfaces.dm
  code/modules/ai/say_list.dm
  code/modules/events/gravity.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/death.dm
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/mob/living/silicon/robot/drone/drone.dm
  code/modules/mob/living/silicon/robot/drone/drone_manufacturer.dm
  code/modules/mob/living/silicon/robot/drone/drone_remote_control.dm
  code/modules/mob/living/simple_mob/combat.dm
  code/modules/mob/living/simple_mob/simple_mob.dm
  code/modules/mob/living/simple_mob/subtypes/humanoid/humanoid.dm
  code/modules/mob/living/simple_mob/subtypes/humanoid/mercs/mercs.dm
  code/modules/planet/planet.dm
  code/modules/planet/sif.dm
  code/modules/planet/weather.dm
  html/changelogs/Mechoid - AI_Drones.yml
  icons/mob/animal.dmi
  icons/mob/robots.dmi
  icons/obj/props/prism.dmi
  icons/obj/props/projectile_lock.dmi
  polaris.dme
Labels: Project

#5354 Fulton balloons
  code/modules/mining/fulton.dm
  icons/obj/fulton.dmi
  icons/obj/fulton_balloon.dmi
  polaris.dme
  sound/items/fulext_deploy.wav
  sound/items/fultext_launch.wav
Labels: Feature

#5373 Fix invalid logic in clonepod beaker function
  code/game/machinery/cloning.dm
Labels: Bugfix, Oversight

#5374 Gloves cannot be put over Commwatches.
  code/modules/clothing/clothing.dm
Labels: Bugfix, Oversight

#5361 Ports Siik'Tajr from Baystation
  code/__defines/species_languages.dm
  code/modules/mob/language/station.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
Labels: Feature, Lore

#5369 Only slimes may squish.
  code/modules/mob/living/carbon/human/emote.dm
Labels: Bugfix

#5377 Renames Taj Sign Language
  code/__defines/species_languages.dm
  code/modules/mob/language/station.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
Labels: Feature Tweak, Lore, Priority: High

#5378 Apportation checks range again
  code/game/gamemodes/technomancer/spell_objs_helpers.dm
  code/game/gamemodes/technomancer/spells/apportation.dm
  html/changelogs/Anewbe - Apportation.yml
Labels: Bugfix
