Repository PolarisSS13/Polaris, pull requests merged in 2018-11, with the labels that each got.

#5700 Fixes Outdoor Electricity
  maps/southern_cross/southern_cross_areas.dm
Labels: Bugfix

#5728 Map Bugfixes
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-4.dmm
  maps/southern_cross/southern_cross_areas.dm
Labels: Bugfix, Map Change / Issue

#5729 Moves Travis to 512.1453 again
  .travis.yml
Labels: Feature Tweak

#5727 Fixes Bugs in AI Branch
  code/__defines/mobs.dm
  code/__defines/subsystems.dm
  code/controllers/subsystems/ai.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/portable_turret.dm
  code/game/objects/structures.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/window.dm
  code/game/turfs/simulated/outdoors/snow.dm
  code/game/turfs/simulated/wall_attacks.dm
  code/game/turfs/simulated/water.dm
  code/modules/admin/verbs/buildmode.dm
  code/modules/ai/__readme.dm
  code/modules/ai/_defines.dm
  code/modules/ai/aI_holder_subtypes/simple_mob_ai.dm
  code/modules/ai/aI_holder_subtypes/slime_xenobio_ai.dm
  code/modules/ai/ai_holder_combat.dm
  code/modules/ai/ai_holder_cooperation.dm
  code/modules/ai/ai_holder_follow.dm
  code/modules/ai/ai_holder_movement.dm
  code/modules/ai/interfaces.dm
  code/modules/events/carp_migration.dm
  code/modules/events/rogue_drones.dm
  code/modules/gamemaster/actions/carp_migration.dm
  code/modules/mob/living/simple_mob/simple_mob.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/hunter.dm
  code/modules/mob/living/simple_mob/subtypes/animal/passive/mouse.dm
  code/modules/mob/living/simple_mob/subtypes/animal/passive/passive.dm
  code/modules/mob/living/simple_mob/subtypes/animal/pets/bird.dm
  code/modules/mob/living/simple_mob/subtypes/animal/pets/parrot.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/hooligan_crab.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/shantak.dm
  code/modules/mob/living/simple_mob/subtypes/animal/space/carp.dm
  code/modules/mob/living/simple_mob/subtypes/blob/spore.dm
  code/modules/mob/living/simple_mob/subtypes/illusion/illusion.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/combat_drone.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/hivebot/hivebot.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/hivebot/ranged_damage.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/hivebot/support.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/mecha/adv_dark_gygax.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/ward/monitor_ward.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/ward/ward.dm
  code/modules/mob/living/simple_mob/subtypes/slime/feral/feral.dm
  code/modules/mob/living/simple_mob/subtypes/slime/slime.dm
  code/modules/mob/living/simple_mob/subtypes/slime/xenobio/subtypes.dm
  code/modules/power/tesla/tesla_act.dm
  code/modules/shieldgen/energy_field.dm
  icons/mob/birds.dmi
  icons/mob/hivebot.dmi
  maps/submaps/surface_submaps/plains/Shakden.dmm
  polaris.dme
Labels: Bugfix, Feature Tweak, Project

#5733 Fixes Area Initialization
  code/game/area/areas.dm
Labels: Bugfix

#5706 Hail tweaks
  code/modules/planet/sif.dm
Labels: Feature Tweak

#5689 Remplace pills made by the condimaster with bouillon cubes.
  code/modules/reagents/Chemistry-Machinery.dm
  icons/obj/chemical.dmi
  nano/templates/chem_master.tmpl
Labels: Feature Tweak

#5730 Adds Autolathe Cost to Knuckledusters
  code/modules/clothing/gloves/miscellaneous.dm
Labels: Bugfix
