Repository PolarisSS13/Polaris, pull requests merged in 2018-10, with the labels that each got.

#5621 Fixes some bloodloss bugs
  code/modules/organs/blood.dm
  html/changelogs/Anewbe - Bloodloss.yml
Labels: Bugfix, Priority: CRITICAL

#5619 Text for handheld plushies when poked
  code/game/objects/items/toys.dm
Labels: Feature Tweak

#5620 Shotgun cycling animation framework
  code/modules/projectiles/guns/projectile/boltaction.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  icons/obj/gun.dmi
Labels: Feature Tweak

#5628 Minor issues fix.
  code/__defines/misc.dm
  code/game/machinery/camera/camera.dm
  code/game/objects/items/weapons/tools/weldingtool.dm
Labels: Bugfix

#5639 Fixed smes terminal construction requiring more cable than used.
  code/modules/power/smes.dm
Labels: Bugfix

#5638 Fixes chem master dumping reagents.
  code/modules/reagents/Chemistry-Machinery.dm
Labels: Bugfix

#5633 Fix mislabelled posters.
  icons/obj/contraband.dmi
Labels: Bugfix, Sprite Change

#5634 Remove kobold.dm
  code/modules/mob/living/simple_animal/humanoids/kobold.dm
  polaris.dme
Labels: Unwanted Feature Removal

#5635 Fix yes emote not working correctly.
  code/modules/mob/living/carbon/human/emote.dm
Labels: Bugfix

#5632 Remplace sprite hammer with pickaxe
  code/modules/mining/mine_items.dm
  maps/northern_star/polaris-5.dmm
  maps/southern_cross/southern_cross-3.dmm
Labels: Map Change / Issue, Sprite Change

#5617 Admin ticket system (for real this time)
  code/__defines/admin.dm
  code/__defines/qdel.dm
  code/__defines/typeids.dm
  code/_global_vars/misc.dm
  code/_global_vars/mobs.dm
  code/_helpers/game.dm
  code/_helpers/lists.dm
  code/_helpers/time.dm
  code/_helpers/unsorted.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminjump.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/client/client defines.dm
  code/modules/client/client procs.dm
  code/modules/mob/mob.dm
  code/world.dm
  interface/interface.dm
  polaris.dme
Labels: Feature

#5641 Fixes several typos with oxygen_pump.dm.
  code/game/machinery/oxygen_pump.dm
Labels: Bugfix

#5650 Fix incorrect HUD/screen/hologram
  code/game/machinery/computer/atmos_control.dm
Labels: Bugfix

#5645 Fix the condimaster not working.
  nano/templates/chem_master.tmpl
Labels: Bugfix

#5646 Remove intensity from chemistry machines.
  code/modules/reagents/Chemistry-Machinery.dm
Labels: Feature Tweak

#5648 Prevents people from HREF exploiting around the R&D console lock.
  code/modules/research/rdconsole.dm
Labels: Bugfix

#5656 Fix plastic ashtrays only holding one butt. Now they hold 4 butts.
  code/game/objects/items/weapons/material/ashtray.dm
Labels: Feature Tweak

#5622 Graves
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/coffin.dm
  code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
  code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/recycling/sortingmachinery.dm
  html/changelogs/Anewbe - Graves.yml
  icons/obj/closet.dmi
Labels: Feature

#5668 Changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Anewbe - Bloodloss.yml
  html/changelogs/Anewbe - Emitters.yml
  html/changelogs/Anewbe - Graves.yml
  html/changelogs/Mechoid - Custom Rigs.yml
Labels: Changelog Update

#5653 Xenoflora and Xenobio House Move
  html/changelogs/Woodrat - XenoMove.yml
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross_areas.dm
Labels: Map Change / Issue

#5652 Fixes missing sprites when excavating rocks
  code/modules/mining/mine_turfs.dm
Labels: Bugfix

#5647 Add a noise for mining scanners.
  code/modules/mining/drilling/scanner.dm
Labels: Feature Tweak

#5674 Removes maintenance access from cleanbots
  code/modules/mob/living/bot/cleanbot.dm
Labels: Bugfix, Feature Tweak

#5670 Fix a couple of ticket bugs
  code/modules/admin/verbs/adminhelp.dm
Labels: Bugfix

#5669 Stop usage of multiple vision modifiers
  code/game/objects/items.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/death.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/mob/living/silicon/pai/life.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/mob_helpers.dm
Labels: Unwanted Feature Removal

#5671 Prevent people from removing papers from any distances.
  code/modules/paperwork/faxmachine.dm
Labels: Bugfix

#5678 Fixes two anchored-related bugs, taped papers and the medbay phone.
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/weapons/tape.dm
Labels: Bugfix

#5679 Makes RCDs Clean Again
  code/__defines/misc.dm
  code/datums/progressbar.dm
  code/game/atoms.dm
  code/game/machinery/doors/airlock.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/objects/items/weapons/RCD.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/window.dm
  code/game/turfs/flooring/flooring_premade.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/outdoors/outdoors.dm
  code/game/turfs/simulated/walls.dm
  code/game/turfs/space/space.dm
  code/game/turfs/space/transit.dm
  code/game/turfs/turf.dm
  code/game/turfs/unsimulated.dm
  code/modules/clothing/spacesuits/rig/modules/utility.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/living/silicon/robot/robot_modules/station.dm
  code/modules/mob/living/silicon/robot/robot_modules/syndicate.dm
  code/modules/multiz/turf.dm
  html/changelogs/Neerti-RCDs.yml
  icons/obj/ammo.dmi
  icons/obj/items.dmi
  icons/obj/tools.dmi
Labels: Bugfix, Feature, Refactor

#5663 More paths to Quick_Create
  code/modules/admin/create_object.dm
Labels: Feature

#5667 Bring back the traitor panel verb.
  code/modules/admin/admin_verbs.dm
Labels: Feature

#5687 Minor cyberlimb clipping fix
  icons/mob/human_races/cyberlimbs/cybersolutions/cybersolutions_alt1.dmi
  icons/mob/human_races/cyberlimbs/unbranded/unbranded_alt1.dmi
Labels: Sprite Change

#5690 Fix wax appearing to be steel.
  code/modules/hydroponics/beekeeping/beehive.dm
Labels: Bugfix

#5685 Fix for Viewing Newly Made Records
  code/datums/datacore.dm
  code/modules/client/client procs.dm
  html/images/no_image32.png
Labels: Bugfix

#5693 Fixes duplication of corpses by holding and then cooking
  code/modules/food/kitchen/cooking_machines/_cooker.dm
Labels: Bugfix

#5692 Correctly fix surgery caps selection this time.
  code/modules/client/preference_setup/loadout/loadout_head.dm
Labels: Oversight

#5686 Fixes all waistcoast being black when worn in the suit slot
  code/modules/clothing/under/accessories/clothing.dm
Labels: Bugfix

#5711 Makes Travis faster
  .travis.yml
Labels: Feature Tweak

#5719 Minor typo fix
  code/controllers/subsystems/vote.dm
Labels: Oversight

#5665 Port some noises from baystation.
  code/game/machinery/computer/computer.dm
  code/game/machinery/machinery.dm
  code/game/sound.dm
  code/modules/reagents/Chemistry-Machinery.dm
  sound/machines/button1.ogg
  sound/machines/button2.ogg
  sound/machines/button3.ogg
  sound/machines/button4.ogg
  sound/machines/switch1.ogg
  sound/machines/switch2.ogg
  sound/machines/switch3.ogg
  sound/machines/switch4.ogg
Labels: Feature

#5691 Remplace the plant clippers with a pair hedgetrimmers
  code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm
  code/modules/hydroponics/trays/tray_tools.dm
  html/changelogs/Kates - Hedgetrimmers.yml
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/tools.dmi
Labels: Sprite Change

#5705 Fix adminhelp sound toggle respect
  code/modules/admin/verbs/adminhelp.dm
Labels: Bugfix

#5662 Biogenerator improvements.
  code/game/machinery/biogenerator.dm
  code/game/objects/items/weapons/storage/bags.dm
  html/changelogs/Lbnesquik - Botany improvements #5662.yml
  sound/machines/biogenerator_end.ogg
Labels: Feature

#5698 Prometheans can process blood without exploding.
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Core.dm
  html/changelogs/Mechoid-PromBlud.yml
Labels: Feature Tweak, Oversight
