Repository PolarisSS13/Polaris, pull requests merged in 2018-07, with the labels that each got.

#5379 Fixes an infinite drowsyness bug
  code/modules/mob/living/carbon/human/life.dm
Labels: Bugfix, Oversight

#5380 Dungeon walls no longer take damage.
  code/game/turfs/simulated/dungeon/wall.dm
Labels: Oversight

#5375 Adds non-head of staff department cloaks
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/clothing/under/accessories/clothing.dm
  icons/mob/ties.dmi
Labels: Feature

#5385 Fix handheld Cameras
  code/modules/paperwork/photography.dm
Labels: Bugfix

#5376 Changelings Now Succ Traits
  code/game/gamemodes/changeling/absorbed_dna.dm
  code/game/gamemodes/changeling/powers/absorb.dm
  code/game/gamemodes/changeling/powers/transform.dm
Labels: Feature Tweak, Oversight

#5387 Chaplain PDA Bug Fix & Atmos Dedupe
  code/game/jobs/job/civilian_chaplain.dm
  code/game/objects/items/weapons/storage/belt.dm
Labels: Bugfix

#5389 Fix hypospray exploit
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: Oversight

#5390 Fixes some planets controller runtimes
  code/controllers/subsystems/planets.dm
Labels: Bugfix

#5383 Ports carp to new AI system, adds new mob class type for holocarp.
  code/__defines/mobs.dm
  code/modules/ai/aI_holder_subtypes/simple_mob_ai.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/giant_spider.dm
  code/modules/mob/living/simple_mob/subtypes/animal/space/carp.dm
  code/modules/mob/living/simple_mob/subtypes/animal/space/space.dm
  polaris.dme
Labels: Feature Tweak, Project

#5391 Tweak i_beam qdel logic
  code/modules/assembly/infrared.dm
Labels: Oversight

#5392 Prevents dummy AIs from spawning with communicators or PDAs.
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Oversight

#5393 Fixes a typo with cups of lime tea.
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
Labels: Bugfix

#5394 Adds an option to enable/disable markings on synth parts.
  code/modules/client/preference_setup/general/03_body.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/organs/organ_icon.dm
Labels: Feature

#5395 Adds four new tatoos
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_races/markings.dmi
Labels: Feature, Sprite Change

#5401 Taj Sign Language works
  code/__defines/species_languages.dm
  code/modules/mob/language/station.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
Labels: Bugfix

#5400 Fixes missing cloak item sprites
  icons/obj/clothing/ties.dmi
Labels: Oversight

#5399 Corrects the Taj Sec voidsuit helmet
  icons/mob/species/tajaran/helmet.dmi
Labels: Bugfix

#5398 Cutting cables will now transfer fingerprints.
  code/modules/power/cable.dm
Labels: Feature Tweak, Oversight, Staff Request

#5397 Global list boilerplates cause the target path to actually add to the list
  code/game/objects/effects/portals.dm
  code/game/objects/items/weapons/mop.dm
  code/game/objects/structures/janicart.dm
Labels: Oversight

#5403 Limbs can find the clothing that covers them
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/organs/organ_external.dm
Labels: Refactor

#5384 Saber fix.
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/research/designs/weapons.dm
  icons/obj/ammo.dmi
  icons/obj/gun.dmi
Labels: Refactor

#5406 Fixes invisible toy
  code/modules/clothing/suits/miscellaneous.dm
Labels: Bugfix

#5404 Water tiles clear underlays in update_icon
  code/game/turfs/simulated/water.dm
Labels: Oversight, Staff Request

#5407 Fixes a bug with integrated circuit printers.
  code/modules/integrated_electronics/core/printer.dm
Labels: Bugfix, Oversight

#5408 Updates changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Anewbe - Apportation.yml
Labels: Changelog Update

#5402 Language and Larynx Additions
  code/__defines/mobs.dm
  code/game/jobs/job_controller.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/implants/implantchair.dm
  code/game/objects/items/weapons/implants/implanter.dm
  code/game/objects/items/weapons/implants/implantfreedom.dm
  code/game/objects/items/weapons/implants/implantlanguage.dm
  code/game/objects/items/weapons/implants/implantuplink.dm
  code/modules/client/preference_setup/loadout/loadout_utility.dm
  code/modules/mob/language/generic.dm
  code/modules/mob/language/language.dm
  code/modules/mob/language/station.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species/outsider/event.dm
  code/modules/mob/living/carbon/human/species/outsider/shadow.dm
  code/modules/mob/living/carbon/human/species/outsider/vox.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/golem.dm
  code/modules/mob/living/carbon/human/species/station/human_subspecies.dm
  code/modules/mob/living/carbon/human/species/station/prometheans.dm
  code/modules/mob/living/carbon/human/species/station/seromi.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/carbon/human/species/virtual_reality/avatar.dm
  code/modules/mob/living/carbon/human/species/xenomorphs/alien_species.dm
  code/modules/organs/internal/voicebox.dm
  code/modules/organs/organ.dm
  code/modules/organs/subtypes/standard.dm
  html/changelogs/Anewbe - Languages.yml
  icons/obj/surgery.dmi
  polaris.dme
Labels: Refactor

#5317 Dead Ringer + PoI
  code/game/objects/items/poi_items.dm
  code/modules/artifice/deadringer.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  icons/effects/timestop.dmi
  icons/obj/deadringer.dmi
  maps/submaps/surface_submaps/mountains/deadspy.dmm
  maps/submaps/surface_submaps/mountains/mountains.dm
  maps/submaps/surface_submaps/mountains/mountains_areas.dm
  polaris.dme
  sound/effects/uncloak.ogg
Labels: Feature, Point of Interest

#5410 Fixes for R-UST Engine
  code/modules/power/fusion/core/core_control.dm
  code/modules/power/fusion/core/core_field.dm
  code/modules/power/fusion/fuel_assembly/fuel_control.dm
  code/modules/power/fusion/gyrotron/gyrotron_control.dm
Labels: Bugfix

#5386 Add a procedure for repairing limbs via surgery.
  code/game/objects/items/weapons/autopsy.dm
  code/game/objects/items/weapons/policetape.dm
  code/game/objects/items/weapons/tape.dm
  code/modules/mob/living/silicon/robot/robot_modules/station.dm
  code/modules/mob/living/silicon/robot/robot_modules/syndicate.dm
  code/modules/organs/organ_external.dm
  code/modules/surgery/external_repair.dm
  html/changelogs/Mechoid - Surgical.yml
  polaris.dme
Labels: Feature, Feature Tweak

#5413 Updates changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Anewbe - Languages.yml
  html/changelogs/Atermonera - Ceilings.yml
  html/changelogs/Mechoid - Surgical.yml
Labels: Changelog Update

#5396 Adds new AI core sprites
  code/modules/mob/living/silicon/ai/icons.dm
  html/changelogs/Mewchild - PR - 5396.yml
  icons/mob/AI.dmi
Labels: Bikeshed, Feature, Sprite Change

#5418 Fixes ghost pAI alert
  icons/obj/pda.dmi
Labels: Bugfix

#5417 Gender name adjustments
  code/modules/client/preference_setup/general/01_basic.dm
Labels: Feature Tweak

#5416 Hopefully fixes seeing and hearing AOOC bug
  code/game/antagonist/antagonist.dm
  code/game/antagonist/antagonist_add.dm
  code/game/antagonist/outsider/ert.dm
  code/game/antagonist/outsider/trader.dm
  code/game/antagonist/station/renegade.dm
  code/game/antagonist/station/thug.dm
  code/game/antagonist/station/traitor.dm
  code/modules/admin/verbs/antag-ooc.dm
Labels: Bugfix

#5420 Fixes Indoor Weather
  code/controllers/subsystems/planets.dm
  code/game/turfs/simulated/floor_attackby.dm
  code/game/turfs/simulated/wall_attacks.dm
Labels: Bugfix

#5424 Fixes indoor weather, hopefully for real this time.
  code/controllers/subsystems/planets.dm
  code/game/objects/items/weapons/RCD.dm
  code/game/turfs/simulated/floor_attackby.dm
  code/game/turfs/simulated/wall_attacks.dm
  code/game/turfs/turf_changing.dm
Labels: Bugfix

#5421 Mining turfs maybe probably possibly look nice all the time now I hope?
  code/modules/mining/mine_turfs.dm
Labels: Bugfix

#5423 Implements ways to make floors not get dirty
  code/game/turfs/simulated.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
Labels: Feature Tweak

#5425 Adds an indent formatting tag to paper
  code/modules/paperwork/paper.dm
Labels: Feature

#5427 Fixes the fireaxe cabinet
  code/game/objects/structures/crates_lockers/closets/fireaxe.dm
Labels: Bugfix

#5429 Adds Marking Order Changing at Character Creation
  code/modules/client/preference_setup/general/03_body.dm
  html/changelogs/KasparoVv - PR - 5429.yml
Labels: Feature Tweak

#5430 Fixes a few on-mob gun sprites
  code/modules/projectiles/guns/energy/phase.dm
  icons/mob/belt_mirror.dmi
Labels: Bugfix, Sprite Change

#5431 Fixes RCD runtime
  code/datums/observation/turf_changed.dm
  code/game/turfs/simulated/walls.dm
  code/game/turfs/space/space.dm
Labels: Bugfix

#5415 Fixes Stairs in BYOND 512.1436
  code/modules/multiz/structures.dm
Labels: Bugfix

#5433 Limits fire_stacks on mobs by temperature
  code/modules/mob/living/living_defense.dm
Labels: Feature Tweak

#5432 Refactors supply controller
  code/controllers/Processes/supply.dm
  code/game/area/Space Station 13 areas.dm
  code/game/objects/structures/plasticflaps.dm
  code/game/supplyshuttle.dm
  code/modules/paperwork/paper.dm
  polaris.dme
Labels: Refactor

#5441 Fixes the PDA Halogen Scanner's tendency to be number one.
  code/game/objects/items/devices/PDA/PDA.dm
Labels: Bugfix, Oversight

#5446 Fireaxe cabinets find their fireaxes in initialize(), rather than new()
  code/game/objects/structures/crates_lockers/closets/fireaxe.dm
Labels: Bugfix, Priority: High

#5445 Constant Chip has a sprite
  code/modules/integrated_electronics/subtypes/memory.dm
Labels: Bugfix, Oversight, Priority: High

#5443 Two pAI fixes
  code/modules/mob/holder.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/pai/software.dm
  html/changelogs/PrismaticGynoid-somemorepaifixes.yml
  icons/mob/head.dmi
  icons/mob/items/lefthand_holder.dmi
  icons/mob/items/righthand_holder.dmi
  icons/mob/pai.dmi
Labels: Feature Tweak, Sprite Change

#5442 Admin Supermatter Setup now closes the monitoring room shutters
  code/modules/power/supermatter/setup_supermatter.dm
  maps/southern_cross/southern_cross-1.dmm
Labels: Feature Tweak, Map Change / Issue

#5440 Converts Creature and Faithless to the new mob system
  code/modules/mob/living/simple_mob/subtypes/occult/creature.dm
  code/modules/mob/living/simple_mob/subtypes/occult/faithless.dm
  polaris.dme
Labels: Project

#5448 Fixes #5447 (Deadspy submap not overwriting mapgen)
  maps/submaps/surface_submaps/mountains/deadspy.dmm
Labels: Bugfix, Point of Interest

#5449 Speeds up alcohol ingested effects
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm
Labels: Feature Tweak

#5450 Fixed mining cloak not being in loadouts
  code/modules/client/preference_setup/loadout/loadout_suit.dm
Labels: Bugfix

#5453 Replaces Skrell namegen
  code/modules/mob/language/station.dm
  config/names/first_name_skrell.txt
  config/names/last_name_skrell.txt
Labels: Feature Tweak, Lore

#5455 Added Squid plushies of varying colours
  code/game/objects/items/toys.dm
  icons/mob/head.dmi
  icons/obj/toy.dmi
Labels: Feature
