Repository PolarisSS13/Polaris, pull requests merged in 2018-05, with the labels that each got.

#5230 Power cost decrease on Lights and Shield Diffusers
  code/modules/power/lighting.dm
  code/modules/shieldgen/shield_diffuser.dm
Labels: Feature Tweak, Staff Request

#5222 Increase zealousness of Portable Freezer item whitelist
  code/game/objects/items/weapons/storage/boxes.dm
Labels: Bugfix, Oversight

#5228 Skrell hardsuit helmet sprites
  html/changelogs/PrismaticGynoid-hardsuitsforsquishyskrell.yml
  icons/mob/species/skrell/helmet.dmi
Labels: Sprite Change

#5232 Center pocket newscaster sprite
  icons/obj/library.dmi
Labels: Sprite Change

#5216 Quick cleanup of mineral processing unit code
  code/modules/mining/machine_processing.dm
Labels: Refactor

#5231 Allow cancelling in chem master modals for pills
  code/modules/reagents/Chemistry-Machinery.dm
Labels: Feature Tweak

#5236 Fix decloner design in protolathe
  code/modules/research/designs.dm
Labels: Bugfix

#5237 Updates changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/PrismaticGynoid-hardsuitsforsquishyskrell.yml
  html/changelogs/mechoid-promtweaks.yml
Labels: Changelog Update

#5234 Fix signlang being totally broken
  code/modules/mob/hear_say.dm
  code/modules/mob/living/say.dm
Labels: Bugfix

#5182 Meteor events have fewer waves with less dangerous meteors
  code/modules/events/meteors.dm
  html/changelogs/Anewbe - Meteors.yml
Labels: Feature Tweak

#5207 Dufflebag of Holding
  code/game/objects/items/weapons/storage/backpack.dm
  code/modules/research/designs.dm
  icons/mob/back.dmi
  icons/mob/items/lefthand_storage.dmi
  icons/mob/items/righthand_storage.dmi
  icons/obj/clothing/backpack.dmi
Labels: Feature

#5209 Ports the medical item sounds from Bay
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/weapons/tape.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  sound/effects/hypospray.ogg
  sound/effects/ointment.ogg
  sound/effects/rip1.ogg
  sound/effects/rip2.ogg
  sound/effects/tape.ogg
Labels: Feature, Ported from Baycode

#5219 NanoUI multiple templates example.
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/communicator/UI.dm
  code/modules/nano/nanoui.dm
  nano/README.md
  nano/js/nano_state.js
  nano/js/nano_template.js
  nano/templates/atmospheric_scan.tmpl
  nano/templates/communicator.tmpl
  nano/templates/pda.tmpl
Labels: Refactor, Revert

#5243 Soporific and Chloral work when ingested again
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
Labels: Bugfix

#5244 Fix upload console runtimes.
  code/game/machinery/computer/law.dm
  code/game/machinery/computer3/computers/law.dm
Labels: Bugfix

#5250 Fixes a comment with spears that caused developers to scratch their heads.
  code/game/objects/items/weapons/material/twohanded.dm
Labels: Oversight

#5248 Colorblindness
  code/__defines/misc.dm
  code/__defines/mobs.dm
  code/modules/mob/_modifiers/traits.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob_planes.dm
Labels: Feature

#5246 improves and adds onto tt_descs
  code/modules/mob/living/simple_animal/animals/bat.dm
  code/modules/mob/living/simple_animal/animals/bear.dm
  code/modules/mob/living/simple_animal/animals/carp.dm
  code/modules/mob/living/simple_animal/animals/cat.dm
  code/modules/mob/living/simple_animal/animals/corgi.dm
  code/modules/mob/living/simple_animal/animals/crab.dm
  code/modules/mob/living/simple_animal/animals/farm_animals.dm
  code/modules/mob/living/simple_animal/animals/fish.dm
  code/modules/mob/living/simple_animal/animals/giant_spider.dm
  code/modules/mob/living/simple_animal/animals/goose.dm
  code/modules/mob/living/simple_animal/animals/lizard.dm
  code/modules/mob/living/simple_animal/animals/miscellaneous.dm
  code/modules/mob/living/simple_animal/animals/mouse.dm
  code/modules/mob/living/simple_animal/animals/parrot.dm
  code/modules/mob/living/simple_animal/animals/sif_wildlife/diyaab.dm
  code/modules/mob/living/simple_animal/animals/sif_wildlife/savik.dm
  code/modules/mob/living/simple_animal/animals/sif_wildlife/shantak.dm
  code/modules/mob/living/simple_animal/animals/tomato.dm
  code/modules/mob/living/simple_animal/animals/tree.dm
  code/modules/mob/living/simple_animal/humanoids/clown.dm
  code/modules/mob/living/simple_animal/humanoids/pirate.dm
  code/modules/mob/living/simple_animal/humanoids/russian.dm
  code/modules/mob/living/simple_animal/humanoids/syndicate.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
Labels: Lore

#5249 Fix alignment for grab insertion cryo placement
  code/game/machinery/cryo.dm
Labels: Bugfix

#5254 Fixes IC button label reference in chat messages
  code/modules/integrated_electronics/subtypes/input.dm
Labels: Oversight

#5259 May 8 news update
  code/modules/lore_codex/news_data/main.dm
Labels: Lore

#5258 Fix weak mobs being able to smash anything they want.
  code/game/objects/structures.dm
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Bugfix, Priority: CRITICAL

#5255 Adds a client FPS setting
  code/__defines/misc.dm
  code/modules/client/preference_setup/global/01_ui.dm
  code/modules/client/preferences.dm
  code/modules/mob/login.dm
  html/changelogs/arokha - client fps.yml
Labels: Feature

#5239 Corrects missing manifold and pipe in Distro loop
  maps/southern_cross/southern_cross-1.dmm
Labels: Map Change / Issue

#5263 Fix SSAO mode mouse opacity problem
  code/modules/mob/mob_planes.dm
Labels: Bugfix, Priority: CRITICAL

#5266 typo
  code/modules/mob/mob.dm
Labels: Oversight

#5264 SSAO object excludes
  code/__defines/_planes+layers.dm
  code/game/machinery/alarm.dm
  code/game/machinery/buttons.dm
  code/game/machinery/computer/camera.dm
  code/game/machinery/computer/guestpass.dm
  code/game/machinery/hologram.dm
  code/game/machinery/newscaster.dm
  code/game/machinery/recharger.dm
  code/game/machinery/requests_console.dm
  code/game/machinery/status_display.dm
  code/game/objects/items/devices/radio/intercom.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/game/objects/structures/extinguisher.dm
  code/game/objects/structures/signs.dm
  code/modules/power/apc.dm
  code/modules/reagents/reagent_dispenser.dm
Labels: Feature

#5265 Grammar tweak
  code/modules/mob/living/carbon/human/examine.dm
Labels: Bugfix

#5267 Added vending machine vending sound
  code/game/machinery/vending.dm
  sound/items/vending.ogg
Labels: Feature

#5270 Add's a few new POI's and minor fixes to old ones!
  maps/submaps/surface_submaps/plains/Diner.dmm
  maps/submaps/surface_submaps/plains/Oldhouse.dmm
  maps/submaps/surface_submaps/plains/plains.dm
  maps/submaps/surface_submaps/plains/plains_areas.dm
  maps/submaps/surface_submaps/wilderness/Drugden.dmm
  maps/submaps/surface_submaps/wilderness/Manor1.dmm
  maps/submaps/surface_submaps/wilderness/wilderness.dm
  maps/submaps/surface_submaps/wilderness/wilderness_areas.dm
Labels: Point of Interest

#5268 may 15 lore
  code/modules/lore_codex/news_data/main.dm
Labels: Lore

#5275 Buttons appear over tables
  code/game/machinery/buttons.dm
Labels: Bugfix

#5279 Laptops don't eat IDs
  code/game/machinery/computer3/NTOS.dm
  code/game/machinery/computer3/bios.dm
  code/game/machinery/computer3/buildandrepair.dm
  code/game/machinery/computer3/component.dm
  code/game/machinery/computer3/computer.dm
  code/game/machinery/computer3/computers/HolodeckControl.dm
  code/game/machinery/computer3/computers/arcade.dm
  code/game/machinery/computer3/computers/atmos_alert.dm
  code/game/machinery/computer3/computers/camera.dm
  code/game/machinery/computer3/computers/card.dm
  code/game/machinery/computer3/computers/communications.dm
  code/game/machinery/computer3/computers/crew.dm
  code/game/machinery/computer3/computers/medical.dm
  code/game/machinery/computer3/computers/power.dm
  code/game/machinery/computer3/computers/prisoner.dm
  code/game/machinery/computer3/computers/robot.dm
  code/game/machinery/computer3/computers/security.dm
  code/game/machinery/computer3/computers/welcome.dm
  code/game/machinery/computer3/file.dm
  code/game/machinery/computer3/laptop.dm
  code/game/machinery/computer3/lapvend.dm
  code/game/machinery/computer3/networking.dm
  code/game/machinery/computer3/program.dm
  code/game/machinery/computer3/server.dm
  code/game/machinery/computer3/storage.dm
  html/changelogs/atermonera - laptopID.yml
Labels: Bugfix, Refactor, Staff Request

#5274 Adjust Promethean limbs.
  code/modules/organs/organ_external.dm
  code/modules/organs/subtypes/slime.dm
  html/changelogs/Mechoid - Prometheans.yml
Labels: Feature Tweak, Oversight

#5278 Corrects some plane and layer issues
  code/game/machinery/atmoalter/canister.dm
  code/game/machinery/status_display.dm
  code/game/objects/structures/catwalk.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/signs.dm
  code/modules/reagents/reagent_dispenser.dm
Labels: Bugfix

#5283 Baystation Sprite Port
  icons/mob/head.dmi
  icons/mob/species/skrell/helmet.dmi
  icons/mob/species/skrell/suit.dmi
  icons/mob/species/tajaran/helmet.dmi
  icons/mob/species/tajaran/suit.dmi
  icons/mob/species/unathi/helmet.dmi
  icons/mob/species/unathi/suit.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/species/skrell/hats.dmi
  icons/obj/clothing/species/skrell/suits.dmi
  icons/obj/clothing/species/tajaran/hats.dmi
  icons/obj/clothing/species/tajaran/suits.dmi
  icons/obj/clothing/species/unathi/hats.dmi
  icons/obj/clothing/species/unathi/suits.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprite Change

#5286 Paranoid logging and byond account age
  code/controllers/configuration.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/panicbunker.dm
  code/modules/client/client defines.dm
  code/modules/client/client procs.dm
  config/example/config.txt
Labels: Feature Tweak

#5272 Adds SAR to allowed_roles of certain loadout items
  code/modules/client/preference_setup/loadout/loadout_accessories.dm
  code/modules/client/preference_setup/loadout/loadout_eyes.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  html/changelogs/lorwp - SARLoadout.yml
Labels: Feature

#5287 Adds 'Smite' verb and pray button
  code/__defines/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/pray.dm
  code/modules/admin/verbs/smite.dm
  code/modules/organs/organ_external.dm
  polaris.dme
Labels: Feature

#5285 Change accessories to use bitflags
  code/__defines/items_clothing.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/clothing_accessories.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/clothing/under/accessories/armband.dm
  code/modules/clothing/under/accessories/badges.dm
  code/modules/clothing/under/accessories/clothing.dm
  code/modules/clothing/under/accessories/holster.dm
  code/modules/clothing/under/accessories/lockets.dm
  code/modules/clothing/under/accessories/permits.dm
  code/modules/clothing/under/accessories/storage.dm
  code/modules/clothing/under/xenos/vox.dm
  maps/southern_cross/items/clothing/sc_suit.dm
Labels: Refactor

#5284 Swapping hands cancels zoom
  code/game/objects/items.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/living.dm
  html/changelogs/Anewbe - Item Zoom.yml
Labels: Bugfix

#5288 Blockers should no longer be visible
  code/modules/spells/aoe_turf/conjure/forcewall.dm
Labels: Bugfix

#5273 Ports the Stasis Only Sleeper
  code/game/machinery/Sleeper.dm
Labels: Feature

#5291 Updates changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Anewbe - Item Zoom.yml
  html/changelogs/Anewbe - Meteors.yml
  html/changelogs/Mechoid - Prometheans.yml
  html/changelogs/arokha - client fps.yml
  html/changelogs/arokha - ssao.yml
  html/changelogs/atermonera - laptopID.yml
  html/changelogs/lorwp - SARLoadout.yml
  html/changelogs/prismaticgynoid-laserpointers.yml
Labels: Changelog Update

#5290 Machete Sheath and Sprite Fixes
  icons/mob/species/tajaran/suit.dmi
  icons/mob/species/unathi/helmet.dmi
  icons/mob/species/unathi/suit.dmi
  icons/mob/suit.dmi
  icons/mob/suit_2.dmi
  icons/mob/ties.dmi
  icons/obj/clothing/species/unathi/hats.dmi
  icons/obj/clothing/species/unathi/suits.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/suits_2.dmi
  icons/obj/clothing/ties.dmi
Labels: Sprite Change

#5294 Fixes examine bugs
  code/modules/clothing/clothing_accessories.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: Bugfix, Priority: CRITICAL

#5296 Fixes a runtime with armor checks
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Bugfix, Priority: CRITICAL

#5280 Merc PoI Tweaks
  code/game/machinery/portable_turret.dm
  code/modules/mob/living/simple_animal/humanoids/syndicate.dm
  html/changelogs/Anewbe - Merc PoIs.yml
  icons/mob/animal.dmi
  maps/submaps/surface_submaps/wilderness/Blackshuttledown.dmm
  maps/submaps/surface_submaps/wilderness/DoomP.dmm
  maps/submaps/surface_submaps/wilderness/Rockybase.dmm
Labels: Controversial, Feature, Point of Interest, Prepare to Die

#5277 Seed storages are hackable.
  code/datums/wires/seedstorage.dm
  code/modules/hydroponics/seed_storage.dm
  html/changelogs/Mechoid - Seedvendorhack.yml
  polaris.dme
Labels: Feature

#5297 Fix Engi Material Synths
  code/modules/mob/living/silicon/robot/robot_modules/station.dm
Labels: Bugfix, Oversight

#5295 Spacesuits are now in their own dmi file
  code/__defines/mobs.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/spacesuits.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/mob/spacesuit.dmi
  icons/mob/suit.dmi
  icons/mob/suit_2.dmi
  icons/obj/clothing/spacesuits.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/suits_2.dmi
Labels: Bugfix, Feature Tweak

#5303 Active edge canary PR
  code/unit_tests/map_tests.dm
Labels: Bugfix

#5302 Ports Baystation12 newest item pickup animations. Fancy!
  code/game/objects/effects/item_pickup_ghost.dm
  code/game/objects/items.dm
  polaris.dme
Labels: Feature, Ported from Baycode

#5304 Reverse use of global lists where they hurt performance.
  code/game/atoms.dm
  code/game/machinery/computer3/computers/crew.dm
  code/game/objects/items.dm
  code/game/objects/objs.dm
  code/modules/admin/secrets/fun_secrets/remove_all_clothing.dm
  code/modules/admin/secrets/fun_secrets/remove_internal_clothing.dm
  code/modules/admin/verbs/SDQL.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/admin/verbs/massmodvar.dm
  code/modules/admin/view_variables/topic.dm
  code/modules/clothing/clothing.dm
  code/modules/recycling/disposal.dm
Labels: Optimization

#5306 Move space/New to space/initialize
  code/game/turfs/space/cracked_asteroid.dm
  code/game/turfs/space/space.dm
  code/game/turfs/space/transit.dm
Labels: Optimization

#5307 Split and clarify global lists of processing vs non-processing machinery.
  code/__defines/machinery.dm
  code/controllers/Processes/machinery.dm
  code/controllers/subsystems/machines.dm
  code/game/machinery/computer3/networking.dm
  code/game/machinery/machinery.dm
  code/global.dm
Labels: Refactor

#5311 Fixes #5083
  code/modules/assembly/proximity.dm
Labels: Bugfix

#5309 Fixed fruit salad not being make-able
  code/modules/hydroponics/seed_datums.dm
Labels: Oversight

#5289 Prometheans can now be revived as originally intended.
  code/modules/organs/internal/brain.dm
Labels: Feature Tweak
