Repository PolarisSS13/Polaris, pull requests merged in 2018-02, with the labels that each got.

#4707 Gives Virology teeth again
  code/game/atoms.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/effects/decals/Cleanable/misc.dm
  code/modules/mob/living/carbon/human/species/outsider/shadow.dm
  code/modules/mob/living/carbon/human/species/outsider/skeleton.dm
  code/modules/mob/living/carbon/human/species/station/golem.dm
  code/modules/mob/living/carbon/human/species/xenomorphs/alien_species.dm
  code/modules/mob/living/carbon/viruses.dm
  code/modules/virus2/admin.dm
  code/modules/virus2/disease2.dm
  code/modules/virus2/dishincubator.dm
  code/modules/virus2/effect.dm
  code/modules/virus2/helpers.dm
  html/changelogs/Cerebulon - VirologyTweaks.yml
  maps/submaps/surface_submaps/mountains/quarantineshuttle.dmm
Labels: Feature

#4762 Fixes vis_enabled becoming unobtainable if something happens to apply plane_holder to mob before client
  code/modules/mob/login.dm
Labels: Bugfix

#4761 Tweaks Shield Generators
  code/modules/shieldgen/shield_gen.dm
  code/modules/shieldgen/shield_gen_external.dm
Labels: Feature Tweak

#4758 "Planetary" Exploration Airlock Controller
  code/game/machinery/doors/airlock_control.dm
  code/game/machinery/embedded_controller/airlock_controllers.dm
  code/game/machinery/embedded_controller/airlock_program.dm
  html/changelogs/Hubblenaut - airlocks.yml
  html/changelogs/Leshana - vplk-airlocks-cycle-to-ext.yml
Labels: Feature Tweak

#4556 What's Yours Is Mined
  code/datums/wires/mines.dm
  code/game/objects/effects/mines.dm
  html/changelogs/MistyLuminescence-mines.yml
  polaris.dme
Labels: Feature

#4767 removes redundant override in human emp_act()
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Bugfix

#4766 POI Adjustments
  code/modules/mob/living/simple_animal/aliens/drone.dm
  code/modules/mob/living/simple_animal/humanoids/mechamobs.dm
  code/modules/power/apc.dm
  code/modules/power/smes_construction.dm
  maps/submaps/surface_submaps/mountains/CaveTrench.dmm
  maps/submaps/surface_submaps/mountains/Rockb1.dmm
  maps/submaps/surface_submaps/plains/bonfire.dmm
  maps/submaps/surface_submaps/wilderness/DoomP.dmm
  maps/submaps/surface_submaps/wilderness/Rockybase.dmm
Labels: Point of Interest

#4765 Mecha Equipment Resource Tweak
  code/modules/research/mechfab_designs.dm
Labels: Feature Tweak

#4763 Lowercases the Giant Crab name
  code/modules/mob/living/simple_animal/animals/crab.dm
Labels: Bugfix

#4679 Adds EMP mines
  code/game/objects/effects/mines.dm
  html/changelogs/Atermonera-EMP_Mine.yml
Labels: Feature, Refactor

#4760 Makes Projectiles Sometimes Pass Through Door Assemblies
  code/game/objects/structures/door_assembly.dm
Labels: Feature Tweak

#4769 Fixes flag resetting on dirtied/broken microwaves
  code/game/machinery/kitchen/microwave.dm
Labels: Bugfix

#4768 Adds borer holder sprites
  icons/mob/head.dmi
  icons/mob/items/lefthand_holder.dmi
  icons/mob/items/righthand_holder.dmi
Labels: Sprite Change

#4771 Clothing adjustments and fix
  code/modules/clothing/under/solgov.dm
  html/changelogs/Woodrat-Clothingtweaks.yml
  maps/southern_cross/loadout/loadout_accessories.dm
  maps/southern_cross/southern_cross.dm
Labels: Feature Tweak

#4772 GPS coordinates and POI names are obfuscated
  code/game/objects/items/devices/gps.dm
  html/changelogs/Atermonera - gps_tweaks.yml
  maps/southern_cross/southern_cross_defines.dm
  maps/submaps/surface_submaps/mountains/crashed_ufo.dmm
  maps/submaps/surface_submaps/wilderness/DJOutpost1.dmm
  maps/~map_system/maps.dm
Labels: Feature Tweak, Point of Interest, Staff Request

#4773 Fixes Typing Indicator
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/typing_indicator.dm
Labels: Bugfix

#4777 Typo, oversight in weather datums
  code/modules/planet/sif.dm
  code/modules/planet/weather.dm
Labels: Oversight

#4776 Mechs can now fall from non-shuttle heights without hurting the occupant
  code/modules/multiz/movement.dm
Labels: Feature Tweak

#4774 Falling onto space no longer hurts
  code/modules/multiz/movement.dm
Labels: Bugfix

#4778 Adjusts certain simple mobs, adds some things
  code/game/gamemodes/technomancer/spells/control.dm
  code/modules/mob/living/simple_animal/aliens/alien.dm
  code/modules/mob/living/simple_animal/animals/miscellaneous.dm
  code/modules/mob/living/simple_animal/animals/sif wildlife/diyaab.dm
  code/modules/mob/living/simple_animal/animals/sif wildlife/savik.dm
  code/modules/mob/living/simple_animal/animals/sif wildlife/shantak.dm
  code/modules/mob/living/simple_animal/humanoids/syndicate.dm
  icons/jungle.dmi
  polaris.dme
Labels: Feature Tweak

#4789 Make ghosts invisible again.
  code/modules/admin/admin_verbs.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Bugfix, Priority: High

#4790 Lets poi gps units display gps_tag instead of hardcoded string
  code/game/objects/items/devices/gps.dm
Labels: Oversight

#4797 Updates changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Atermonera - ethyl_fix.yml
  html/changelogs/Atermonera - gps_tweaks.yml
  html/changelogs/Atermonera-EMP_Mine.yml
  html/changelogs/Cerebulon - VirologyTweaks.yml
  html/changelogs/Hubblenaut - airlocks.yml
  html/changelogs/Leshana - vplk-airlocks-cycle-to-ext.yml
  html/changelogs/MistyLuminescence-mines.yml
  html/changelogs/Woodrat-Clothingtweaks.yml
  html/changelogs/Woodrat-ShuttleUpgradeMapFix.yml
Labels: Changelog Update

#4798 Removes a stray space, replaces it with glorious underscore
  code/modules/mob/living/simple_animal/animals/sif_wildlife/diyaab.dm
  code/modules/mob/living/simple_animal/animals/sif_wildlife/savik.dm
  code/modules/mob/living/simple_animal/animals/sif_wildlife/shantak.dm
  polaris.dme
Labels: Oversight, Priority: CRITICAL

#4788 Viro Symptoms and Automute now Play Nice
  code/modules/virus2/effect.dm
Labels: Bugfix, Feature Tweak, Optimization

#4792 Sleeper and Advanced Scanner consoles now find their machines
  code/game/machinery/Sleeper.dm
  code/game/machinery/adv_med.dm
Labels: Bugfix

#4787 Removes the Explorer hood lights
  code/modules/clothing/suits/miscellaneous.dm
Labels: Feature Tweak

#4786 Trees take damage from bullets/lasers
  code/game/objects/structures/flora/trees.dm
Labels: Bugfix

#4791 Makes Tape work on Nerds
  code/game/objects/items/weapons/tape.dm
Labels: Bugfix

#4795 Fixes ammo spawn at DJOutpost1.dmm (take two)
  maps/submaps/surface_submaps/wilderness/DJOutpost1.dmm
Labels: Bugfix, Point of Interest

#4801 Makes More Machines Movable
  code/game/machinery/biogenerator.dm
  code/game/machinery/bioprinter.dm
  code/game/machinery/computer3/lapvend.dm
  code/game/machinery/kitchen/cooking_machines/_cooker.dm
  code/game/machinery/kitchen/gibber.dm
  code/game/machinery/kitchen/microwave.dm
  code/game/machinery/kitchen/smartfridge.dm
  code/game/machinery/seed_extractor.dm
  code/game/machinery/washing_machine.dm
  code/modules/reagents/Chemistry-Machinery.dm
  code/modules/virus2/analyser.dm
  code/modules/virus2/centrifuge.dm
  code/modules/virus2/diseasesplicer.dm
  code/modules/virus2/dishincubator.dm
  code/modules/virus2/isolator.dm
  html/changelogs/PrismaticGynoid-movethosemachines.yml
Labels: Feature

#4802 Generalizes stack usage for machine frames.
  code/game/machinery/frame.dm
Labels: Refactor

#4799 Fixes pAI HUDs not working at all.
  code/modules/mob/living/silicon/pai/software_modules.dm
Labels: Bugfix

#4803 Feb 11 News
  code/modules/lore_codex/news_data/main.dm
Labels: Lore

#4806 Fixes Metaphysical Meatbread
  code/modules/reagents/reagent_containers/food/lunch.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Bugfix

#4793 SMES tweaks
  code/game/objects/items/weapons/circuitboards/machinery/power.dm
  code/modules/power/smes.dm
  code/modules/power/smes_construction.dm
Labels: Feature Tweak

#4800 Adds decorative bones and bone loot pile
  code/game/objects/items/weapons/bones.dm
  code/game/objects/structures/loot_piles.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/bones.dmi
  polaris.dme
Labels: Feature

#4796 Cyborg charger lessens FBP radiation.
  code/game/machinery/rechargestation.dm
  html/changelogs/Anewbe- Various.yml
Labels: Feature Tweak

#4185 Gun changes
  code/game/gamemodes/technomancer/spells/modifier/corona.dm
  code/game/gamemodes/technomancer/spells/modifier/repel_missiles.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/material/twohanded.dm
  code/modules/clothing/chameleon.dm
  code/modules/mob/_modifiers/cloning.dm
  code/modules/mob/_modifiers/modifiers.dm
  code/modules/mob/_modifiers/traits.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/mob_helpers.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/nuclear.dm
  code/modules/projectiles/guns/energy/pulse.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/guns/magnetic/magnetic.dm
  code/modules/projectiles/guns/magnetic/magnetic_railgun.dm
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/boltaction.dm
  code/modules/projectiles/guns/projectile/contender.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/guns/projectile/revolver.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  code/modules/projectiles/guns/projectile/sniper.dm
  code/modules/projectiles/guns/vox.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/energy.dm
  code/modules/projectiles/projectile/magnetic.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/xenobio/items/extracts.dm
  code/modules/xenobio/items/weapons.dm
  sound/weapons/gunshot/gunshot.ogg
  sound/weapons/gunshot/gunshot2.ogg
  sound/weapons/gunshot/gunshot3.ogg
  sound/weapons/gunshot/gunshot_pistol.ogg
  sound/weapons/gunshot/gunshot_smg.ogg
  sound/weapons/gunshot/gunshot_strong.ogg
  sound/weapons/gunshot/shotgun.ogg
  sound/weapons/gunshot/sniper.ogg
Labels: Feature Tweak, Needs Review, Requires Developer Input

#4804 THE MINI FIST-PUNCH UPDATE
  code/datums/autolathe/arms.dm
  code/game/objects/items/weapons/material/misc.dm
  code/game/objects/random/random.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/gloves/arm_guards.dm
  code/modules/clothing/gloves/gauntlets.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/unarmed_attack.dm
  html/changelogs/ANEWBE CASTS FIST.yml
  icons/mob/hands.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/weapons.dmi
Labels: Feature Tweak, Needs Review

#4807 Tweaks Lead & Radiation Resistance
  code/datums/repositories/radiation.dm
  code/game/turfs/simulated/wall_types.dm
  code/modules/materials/materials.dm
Labels: Feature Tweak

#4809 Suit Modkit Compatability
  code/game/objects/items/paintkit.dm
Labels: Bugfix, Oversight

#4810 Shapeshifters can properly wear the clothing of other species.
  code/modules/clothing/clothing.dm
Labels: Bugfix, Oversight

#4812 Explorers can get holsters in the loadout
  maps/southern_cross/loadout/loadout_accessories.dm
Labels: Feature Tweak, Southern Cross

#4817 Changes mine code, adds random mine spawners
  code/game/objects/effects/mines.dm
  code/game/objects/random/random.dm
  code/modules/mob/living/simple_animal/aliens/drone.dm
  code/modules/mob/living/simple_animal/animals/carp.dm
  code/modules/mob/living/simple_animal/constructs/constructs.dm
  code/modules/mob/living/simple_animal/humanoids/syndicate.dm
  html/changelogs/Anewbe - Mines.yml
  maps/submaps/surface_submaps/wilderness/CaveS.dmm
  maps/submaps/surface_submaps/wilderness/DoomP.dmm
  maps/submaps/surface_submaps/wilderness/MCamp1.dmm
Labels: Feature Tweak, Point of Interest

#4811 Build igloos and snowmen
  code/game/objects/structures/snowman.dm
  code/game/turfs/simulated/wall_types.dm
  code/modules/materials/material_recipes.dm
  code/modules/materials/material_sheets.dm
  code/modules/materials/materials.dm
  code/modules/mob/_modifiers/traits_phobias.dm
  html/changelogs/BattlefieldCommander-doyouwannabuildasnowman.yml
  icons/obj/snowman.dmi
  icons/obj/stacks.dmi
  polaris.dme
Labels: Feature

#4818 Ports Vorestation's emp effects and ion projectiles
  code/modules/organs/internal/eyes.dm
  code/modules/organs/subtypes/machine.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/projectile/special.dm
Labels: Feature Tweak

#4819 Small Fixes and Refactor
  code/game/machinery/machinery.dm
  code/modules/clothing/gloves/color.dm
Labels: Bugfix, Refactor

#4823 Fix the seedarkness variable
  code/modules/mob/living/life.dm
Labels: Bugfix

#4834 Fixes lack of borg fullbright with mesons etc
  code/game/objects/items/robot/robot_items.dm
  code/modules/mob/living/silicon/robot/life.dm
Labels: Bugfix

#4830 Prevent infinite deuterium
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Bugfix

#4835 Fix botanist hud icon
  icons/mob/hud.dmi
Labels: Bugfix

#4821 Allow simple_animal to have more than one attack verb
  code/modules/mob/living/simple_animal/aliens/alien.dm
  code/modules/mob/living/simple_animal/aliens/creature.dm
  code/modules/mob/living/simple_animal/aliens/faithless.dm
  code/modules/mob/living/simple_animal/aliens/hivebot.dm
  code/modules/mob/living/simple_animal/aliens/mimic.dm
  code/modules/mob/living/simple_animal/aliens/shade.dm
  code/modules/mob/living/simple_animal/animals/bat.dm
  code/modules/mob/living/simple_animal/animals/carp.dm
  code/modules/mob/living/simple_animal/animals/farm_animals.dm
  code/modules/mob/living/simple_animal/animals/goose.dm
  code/modules/mob/living/simple_animal/animals/lizard.dm
  code/modules/mob/living/simple_animal/animals/penguin.dm
  code/modules/mob/living/simple_animal/animals/spiderbot.dm
  code/modules/mob/living/simple_animal/animals/tomato.dm
  code/modules/mob/living/simple_animal/animals/tree.dm
  code/modules/mob/living/simple_animal/animals/worm.dm
  code/modules/mob/living/simple_animal/borer/borer.dm
  code/modules/mob/living/simple_animal/constructs/constructs.dm
  code/modules/mob/living/simple_animal/humanoids/clown.dm
  code/modules/mob/living/simple_animal/humanoids/mechamobs.dm
  code/modules/mob/living/simple_animal/humanoids/pirate.dm
  code/modules/mob/living/simple_animal/humanoids/russian.dm
  code/modules/mob/living/simple_animal/humanoids/syndicate.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Refactor

#4828 Allow Simple Animals to have armor in a normal sensible way
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Feature

#4832 Remove the admin ghostview verb
  code/modules/admin/admin_verbs.dm
Labels: Unwanted Feature Removal

#4826 Don't require hostile SAs for special purposes
  code/modules/mob/living/simple_animal/animals/cat.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Feature Tweak

#4827 Port Bay-style attack animations
  code/_helpers/game.dm
  code/controllers/subsystems/garbage.dm
  code/modules/client/preference_setup/global/setting_datums.dm
  code/modules/mob/animations.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob_defines.dm
  icons/effects/effects.dmi
Labels: Feature, Requires Staff Input

#4833 New sprite for the News Codex
  icons/obj/library.dmi
Labels: Sprite Change

#4841 Allows you to grille in space.
  code/game/objects/items/stacks/rods.dm
Labels: Bugfix

#4816 Adds hidden alarms, for air alarms, fire alarms, and APCs
  code/game/area/areas.dm
  code/game/machinery/alarm.dm
  code/modules/alarm/alarm.dm
  code/modules/alarm/alarm_handler.dm
  code/modules/alarm/atmosphere_alarm.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/nano/modules/alarm_monitor.dm
  code/modules/nano/modules/atmos_control.dm
  code/modules/power/apc.dm
Labels: Feature Tweak

#4845 Fixed typo in unfastening grille
  code/game/objects/structures/grille.dm
Labels: Bugfix

#4848 Walking with nonshoes on feet causes runtimes
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: Bugfix

#4825 Extend mob 'glow' capabilities
  code/modules/mob/living/life.dm
  code/modules/mob/living/living_defines.dm
Labels: Feature

#4822 Player-controlled SA QoL
  code/_onclick/hud/screen_objects.dm
  code/_onclick/other_mobs.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/living/simple_animal/simple_hud.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_grab.dm
  code/modules/mob/mob_helpers.dm
  code/modules/mob/mob_movement.dm
  code/modules/mob/update_icons.dm
  icons/mob/screen1_animal.dmi
  polaris.dme
Labels: Feature, Refactor

#4843 Department ponchos for all
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  html/changelogs/PrismaticGynoid-universalponchos.yml
Labels: Feature Tweak

#4837 Gift items + Cargo crate
  code/datums/supplypacks/hospitality.dm
  code/game/machinery/computer/arcade.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/modules/paperwork/paper.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  html/changelogs/schnayy-giftcrates.yml
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/bureaucracy.dmi
  icons/obj/food.dmi
  icons/obj/items.dmi
Labels: Feature

#4847 Adds new POI's along with minor fixes to older ones!
  maps/submaps/surface_submaps/plains/Boathouse.dmm
  maps/submaps/surface_submaps/plains/Diner.dmm
  maps/submaps/surface_submaps/plains/Mechpt.dmm
  maps/submaps/surface_submaps/plains/PooledR.dmm
  maps/submaps/surface_submaps/plains/Rocky2.dmm
  maps/submaps/surface_submaps/plains/Shakden.dmm
  maps/submaps/surface_submaps/plains/Smol3.dmm
  maps/submaps/surface_submaps/plains/Theifc.dmm
  maps/submaps/surface_submaps/plains/plains.dm
  maps/submaps/surface_submaps/plains/plains_areas.dm
  maps/submaps/surface_submaps/plains/smol2.dmm
  maps/submaps/surface_submaps/plains/snow1.dmm
  maps/submaps/surface_submaps/plains/snow2.dmm
  maps/submaps/surface_submaps/plains/snow3.dmm
  maps/submaps/surface_submaps/plains/snow4.dmm
  maps/submaps/surface_submaps/plains/snow5.dmm
  maps/submaps/surface_submaps/wilderness/Drugden.dmm
  maps/submaps/surface_submaps/wilderness/Rockybase.dmm
  maps/submaps/surface_submaps/wilderness/wilderness.dm
  maps/submaps/surface_submaps/wilderness/wilderness_areas.dm
Labels: Point of Interest

#4849 Allows the pocket newscaster to fit in pockets
  code/modules/lore_codex/codex.dm
Labels: Feature Tweak

#4855 Fix for borgs accidentally getting into useless grab/disarm intents
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob_helpers.dm
Labels: Bugfix, Priority: High

#4838 Port Bay's survival boxes
  code/datums/outfits/_defines.dm
  code/datums/outfits/outfit.dm
  code/game/antagonist/outsider/mercenary.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/items/weapons/tanks/tank_types.dm
  code/game/objects/random/random.dm
  code/game/objects/structures/loot_piles.dm
  code/modules/mob/living/carbon/human/species/outsider/vox.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  icons/obj/storage.dmi
  icons/obj/syringe.dmi
  icons/obj/tank.dmi
  maps/southern_cross/job/outfits.dm
  maps/southern_cross/southern_cross-6.dmm
Labels: Feature

#4829 Lets animals and ghosts look in boxes/backpacks/whatever
  code/game/objects/items/weapons/storage/storage.dm
Labels: Quality of Life

#4860 Changelog update
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/ANEWBE CASTS FIST.yml
  html/changelogs/Anewbe - Mines.yml
  html/changelogs/Anewbe- Various.yml
  html/changelogs/BattlefieldCommander-doyouwannabuildasnowman.yml
  html/changelogs/PrismaticGynoid-movethosemachines.yml
  html/changelogs/PrismaticGynoid-universalponchos.yml
  html/changelogs/schnayy-giftcrates.yml
Labels: Changelog Update

#4820 Suit coolers don't magically shut off in mild fires
  code/game/objects/items/devices/suit_cooling.dm
  code/modules/mob/living/carbon/human/life.dm
  html/changelogs/Anewbe - Suit Coolers.yml
Labels: Bugfix

#4840 Gives Miners shinybits.
  code/game/objects/items/stacks/marker_beacons.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/modules/mining/mine_items.dm
Labels: Feature

#4836 unions no longer make firearms
  code/modules/projectiles/guns/energy/nuclear.dm
Labels: Lore

#4856 EMPs no longer make meat eyes fuzzy
  code/modules/organs/internal/eyes.dm
Labels: Bugfix

#4857 Ghetto splints now spawn properly when used in hand
  code/game/objects/items/stacks/rods.dm
Labels: Bugfix

#4859 Makes devs able to see use of take admin command button
  code/modules/admin/topic.dm
Labels: Bugfix

#4871 Removes testing code.
  code/modules/nano/modules/power_monitor.dm
Labels: Oversight

#4858 Clean up some recent update_icons() changes
  code/__defines/_planes+layers.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/typing_indicator.dm
Labels: Refactor

#4864 Corrects a few accuracy/evasion errors
  code/modules/mob/_modifiers/modifiers.dm
  code/modules/mob/_modifiers/modifiers_misc.dm
  code/modules/projectiles/guns/energy/laser.dm
Labels: Bugfix

#4868 Should squash two runtimes
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/shieldgen/shield_capacitor.dm
Labels: Bugfix

#4839 Another attempt at leg icon generation fixes.
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Higgs Bugson

#4866 Cryobag oxygen supply increased
  code/game/objects/items/bodybag.dm
Labels: Feature Tweak

#4815 Change to first-aid post system (v2)
  maps/southern_cross/southern_cross-1.dmm
Labels: Feature Tweak, Requires Staff Input

#4831 Fix misnamed iconstate for engineering mrhandy
  icons/mob/robots.dmi
Labels: Sprite Change

#4863 Crashed Medical Shuttle PoI
  code/modules/mob/living/simple_animal/animals/giant_spider.dm
  code/modules/paperwork/paper.dm
  icons/mob/animal.dmi
  maps/submaps/surface_submaps/mountains/CrashedMedShuttle1.dmm
  maps/submaps/surface_submaps/mountains/mountains.dm
  maps/submaps/surface_submaps/mountains/mountains_areas.dm
Labels: Point of Interest

#4875 Moves most boxes to use starts_with
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/bible.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/game/objects/items/weapons/storage/lockbox.dm
  code/game/objects/items/weapons/storage/misc.dm
  code/game/objects/items/weapons/storage/secure.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/items/weapons/storage/toolbox.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/game/objects/items/weapons/storage/wallets.dm
  code/modules/power/cable.dm
  icons/mob/items/lefthand_storage.dmi
  icons/mob/items/righthand_storage.dmi
Labels: Refactor

#4878 Fixes uncleanable feet.
  code/modules/mob/living/carbon/human/human.dm
Labels: Bugfix, Higgs Bugson

#4846 Prometheans are bothered by water
  code/modules/mob/living/carbon/human/species/station/prometheans.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Core.dm
  html/changelogs/Anewbe - Prometheans.yml
Labels: Requires Staff Input, Tweak Request

#4874 Ports Bay's wall-mounted air pumps
  code/game/machinery/OpTable.dm
  code/game/machinery/oxygen_pump.dm
  code/modules/clothing/masks/breath.dm
  icons/obj/walllocker.dmi
  nano/templates/Oxygen_pump.tmpl
  polaris.dme
Labels: Feature

#4880 Actual fix for Engineer Handy's eyes
  icons/mob/robots.dmi
Labels: Bugfix, Sprite Change

#4884 rainbow
  code/modules/organs/robolimbs.dm
Labels: Bugfix

#4886 Fixes some tile overlays on z1
  maps/southern_cross/southern_cross-1.dmm
Labels: Map Change / Issue

#4877 Two organ bugfixes
  code/modules/organs/organ.dm
  code/modules/surgery/organs_internal.dm
Labels: Bugfix

#4867 Explorer gasmasks can be equipped through their hoods
  code/modules/clothing/masks/gasmask.dm
Labels: Feature Tweak

#4869 Headset sprites, planetside headset functionality
  code/datums/outfits/jobs/cargo.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  html/changelogs/Anewbe - Headsets.yml
  icons/mob/ears.dmi
  maps/southern_cross/items/headset_sc.dm
Labels: Feature

#4879 Adds planetside gun permits
  code/modules/clothing/under/accessories/permits.dm
  html/changelogs/Anewbe - Planetside Permits.yml
  maps/southern_cross/job/outfits.dm
  maps/southern_cross/structures/closets/misc.dm
Labels: Feature

#4882 Adds carbon pills to the NanoMed Plus
  code/game/machinery/vending.dm
Labels: Feature, Staff Request

#4904 Simple animals shouldn't be hit twice per click
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Bugfix, Priority: CRITICAL

#4890 Fix Destructive Analyzer and Circuit Imprinter deconstruction runtimes.
  code/modules/research/circuitprinter.dm
  code/modules/research/rdconsole.dm
Labels: Bugfix

#4895 Fixed typos in descriptions of some of the posters
  code/game/objects/effects/decals/posters/polarisposters.dm
Labels: Bugfix

#4894 New Cave PoIs
  code/game/objects/random/random.dm
  html/changelogs/Woodrat - VaultPOIs.yml
  maps/submaps/surface_submaps/mountains/digsite.dmm
  maps/submaps/surface_submaps/mountains/mountains.dm
  maps/submaps/surface_submaps/mountains/mountains_areas.dm
  maps/submaps/surface_submaps/mountains/vault1.dmm
  maps/submaps/surface_submaps/mountains/vault2.dmm
  maps/submaps/surface_submaps/mountains/vault3.dmm
  maps/submaps/surface_submaps/mountains/vault4.dmm
  maps/submaps/surface_submaps/mountains/vault5.dmm
Labels: Point of Interest

#4891 POI Bugfixes / Sprucing.
  maps/submaps/surface_submaps/plains/Diner.dmm
  maps/submaps/surface_submaps/plains/Mechpt.dmm
  maps/submaps/surface_submaps/plains/PooledR.dmm
  maps/submaps/surface_submaps/wilderness/Blackshuttledown.dmm
  maps/submaps/surface_submaps/wilderness/CaveS.dmm
  maps/submaps/surface_submaps/wilderness/MCamp1.dmm
  maps/submaps/surface_submaps/wilderness/Rockybase.dmm
Labels: Point of Interest

#4892 Preview background additions and a fix.
  code/modules/client/preference_setup/general/03_body.dm
  icons/effects/128x48.dmi
Labels: Bugfix

#4883 Makes electrochromatic glass buildable and programmable in game.
  code/game/objects/structures/window.dm
  html/changelogs/Leshana-polarized-windows.yml
Labels: Feature

#4876 Simple mobs respect armor pen, sharp, and edge
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Feature Tweak

#4885 Tones down package bombs
  code/game/objects/items/weapons/syndie.dm
Labels: Feature Tweak, Staff Request

#4893 Slimes should no longer /list you.
  code/game/gamemodes/technomancer/assistance/golem.dm
  code/modules/blob2/mobs/spore.dm
  code/modules/mob/living/simple_animal/animals/sif_wildlife/diyaab.dm
  code/modules/mob/living/simple_animal/animals/sif_wildlife/savik.dm
  code/modules/mob/living/simple_animal/animals/sif_wildlife/shantak.dm
  code/modules/mob/living/simple_animal/slime/combat.dm
  code/modules/xenobio2/mob/slime/slime.dm
  code/modules/xenobio2/mob/xeno.dm
Labels: Bugfix

#4896 Fix several Destoy()s
  code/controllers/subsystems/garbage.dm
  code/datums/EPv2.dm
  code/datums/mixed.dm
  code/datums/progressbar.dm
  code/game/objects/items/devices/communicator/communicator.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/modules/mob/mob_planes.dm
  code/modules/nano/modules/nano_module.dm
Labels: Bugfix

#4897 Fix health analyzer names
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/modules/research/designs.dm
  maps/submaps/surface_submaps/mountains/CrashedMedShuttle1.dmm
Labels: Bugfix

#4888 Adds various cabin-related things.
  code/datums/supplypacks/materials.dm
  code/game/objects/items/stacks/tiles/fifty_spawner_tiles.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/structures/bonfire.dm
  code/game/objects/structures/flora/trees.dm
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/flooring/flooring_premade.dm
  code/modules/materials/material_recipes.dm
  html/changelogs/battlefieldcommander - campfire song song.yml
  icons/obj/stacks.dmi
  icons/obj/structures.dmi
  icons/turf/flooring/carpet.dmi
  icons/turf/flooring/wood.dmi
Labels: Feature, Needs Review

#4898 Mining Bag / Box Speedification
  code/game/objects/items/weapons/storage/bags.dm
  code/modules/mining/satchel_ore_boxdm.dm
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Feature Tweak, Optimization

#4901 Adds holoplants, and to cargo
  code/datums/supplypacks/misc.dm
  code/game/objects/structures/holoplant.dm
  icons/obj/holoplants.dmi
  polaris.dme
Labels: Feature

#4907 Make spy bugs spawn spy cameras
  code/game/objects/items/devices/spy_bug.dm
Labels: Bugfix

#4865 Adds umbrellas
  code/game/objects/items/weapons/melee/misc.dm
  code/modules/planet/sif.dm
  html/changelogs/Atermonera - Umbrellas.yml
  icons/mob/items/lefthand_melee.dmi
  icons/mob/items/righthand_melee.dmi
  icons/obj/items.dmi
Labels: Feature

#4912 Small regenerate_icons tweak.
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Higgs Bugson

#4889 Allow mapped in pipes on openspace turfs with catwalks etc.
  code/ATMOSPHERICS/pipes.dm
  icons/atmos/pipes.dmi
Labels: Bugfix

#4913 Robot upgrade fixes
  code/game/objects/items/robot/robot_upgrades.dm
Labels: Bugfix, Feature Tweak

#4905 Zheng Hu Improvements
  code/modules/organs/organ_icon.dm
  code/modules/organs/robolimbs.dm
  icons/mob/human_races/cyberlimbs/zenghu/zenghu_main.dmi
Labels: Feature Tweak, Sprite Change

#4903 Adds halogen counter tool, adds gas scanner to analyzers
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/scanners.dm
  html/changelogs/Atermonera - tools.yml
Labels: Feature

#4916 Critters Can Crawl Carrying Client Constructs
  code/_onclick/hud/human.dm
  code/modules/mob/living/simple_animal/simple_hud.dm
  code/modules/ventcrawl/ventcrawl.dm
Labels: Bugfix

#4917 Corrects an oversight with surgery and defibs
  code/modules/organs/organ.dm
  code/modules/organs/subtypes/standard.dm
Labels: Oversight

#4918 Adds a few random mob spawners.
  code/game/objects/random/random.dm
Labels: Feature

#4919 Fixed pAI communicator buttons.
  code/modules/nano/interaction/default.dm
Labels: Bugfix

#4909 Ports more two-handed gun sprites from Bay
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  icons/mob/back.dmi
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
  icons/obj/gun.dmi
Labels: Feature Tweak, Sprite Change

#4862 Adds/steals more armor code, inventory changes
  code/__defines/items_clothing.dm
  code/datums/supplypacks/security.dm
  code/game/gamemodes/changeling/powers/bioelectrogenesis.dm
  code/game/gamemodes/changeling/powers/electric_lockpick.dm
  code/game/gamemodes/technomancer/spell_objs.dm
  code/game/objects/items.dm
  code/game/objects/objs.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/clothing_accessories.dm
  code/modules/clothing/gloves/arm_guards.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/spacesuits/spacesuits.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/accessories/armor.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  html/changelogs/Anewbe - Various1.yml
  icons/mob/modular_armor.dmi
  icons/mob/ties.dmi
  icons/obj/clothing/modular_armor.dmi
Labels: Feature, Ported from Baycode

#4910 Unobfuscates GPS locations
  code/_helpers/unsorted.dm
  code/game/objects/items/devices/gps.dm
  html/changelogs/Atermonera - GPS  fixes.yml
Labels: Feature Tweak, Staff Request

#4922 Should actually fix the flashbang thing, hopefully without a billion extra commits
  code/game/objects/items/weapons/grenades/flashbang.dm
Labels: Feature Tweak

#4930 Changelog update: 2/22/12018
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Anewbe - Various1.yml
  html/changelogs/Atermonera - GPS  fixes.yml
  html/changelogs/Atermonera - Umbrellas.yml
  html/changelogs/Atermonera - tools.yml
  html/changelogs/battlefieldcommander - campfire song song.yml
Labels: Changelog Update

#4923 Makes a dark ritual even darker
  code/datums/ghost_query.dm
  code/game/objects/structures/ghost_pods/ghost_pods.dm
  code/game/objects/structures/ghost_pods/silicon.dm
  icons/obj/structures.dmi
  maps/submaps/surface_submaps/mountains/ritual.dmm
Labels: Point of Interest

#4924 Eliminate duplicate code in trinary atmos components
  code/ATMOSPHERICS/atmospherics.dm
  code/ATMOSPHERICS/components/trinary_devices/filter.dm
  code/ATMOSPHERICS/components/trinary_devices/mixer.dm
  code/ATMOSPHERICS/components/trinary_devices/trinary_base.dm
  code/ATMOSPHERICS/components/tvalve.dm
  code/game/machinery/pipe/construction.dm
  maps/northern_star/polaris-1.dmm
Labels: Refactor

#4925 Tweak Tesla Grounding Rods
  code/modules/power/tesla/energy_ball.dm
  html/changelogs/Leshana - tesla-grounding.yml
Labels: Feature Tweak

#4926 Make gas turbine constructable and operational
  code/_helpers/unsorted.dm
  code/game/objects/items/weapons/circuitboards/computer/computer.dm
  code/modules/power/turbine.dm
  nano/templates/turbine_computer.tmpl
Labels: Feature Tweak

#4928 Create humans ON their spawn points
  code/game/jobs/job_controller.dm
  code/modules/mob/new_player/new_player.dm
Labels: Bugfix

#4927 Fix mode_name on guns always being null
  code/modules/projectiles/gun.dm
Labels: Bugfix

#4915 Slimebots drop the right baton.
  code/modules/mob/living/bot/ed209bot.dm
  code/modules/mob/living/bot/secbot.dm
Labels: Bugfix

#4936 Sundry Bugfixes - Feburary
  code/game/objects/items/weapons/RCD.dm
  code/game/objects/items/weapons/candle.dm
  code/game/objects/items/weapons/storage/fancy.dm
Labels: Bugfix

#4873 Fixes CS sprites (again)
  icons/mob/human_races/cyberlimbs/cybersolutions/cybersolutions_alt1.dmi
Labels: Sprite Change

#4887 AlliCo Hallmark Goods
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/reagent_containers/food/drinks/bottle.dm
  html/changelogs/Schnayy - AlliCo Hallmark Goods.yml
  icons/obj/drinks.dmi
  icons/obj/vending.dmi
  maps/southern_cross/southern_cross-1.dmm
Labels: Feature

#4932 Small tweak to survival boxes
  code/game/objects/items/weapons/storage/boxes.dm
  code/modules/mob/living/carbon/human/species/species.dm
Labels: Feature Tweak

#4933 Create client preference for if hotkey mode is enabled by default on login
  code/modules/client/preference_setup/global/setting_datums.dm
  code/modules/mob/living/silicon/robot/login.dm
  code/modules/mob/login.dm
  html/changelogs/Leshana - hotkeys-qol.yml
  interface/interface.dm
  interface/skin.dmf
Labels: Feature

#4934 adds new article, adds old article we forgot to add
  code/modules/lore_codex/news_data/main.dm
Labels: Lore

#4935 Ice Tiles and Ice Puzzles
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/simulated/outdoors/snow.dm
  code/modules/mob/mob.dm
  icons/turf/outdoors.dmi
Labels: Feature

#4939 Should fix an accessories oversight
  code/modules/clothing/clothing_accessories.dm
  code/modules/mob/living/carbon/human/inventory.dm
Labels: Bugfix, Priority: High

#4929 Splints no longer perfectly prevent negative effects from broken bones
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/mob.dm
  code/modules/organs/organ_external.dm
  html/changelogs/Anewbe - Splints.yml
Labels: Feature Tweak, Staff Request

#4940 Removes the VeyMed license from Cargo
  code/datums/supplypacks/robotics.dm
Labels: Feature Tweak

#4941 Turrets Target through Girders, Airlock assemblies, and other unanchored structures.
  code/modules/projectiles/projectile.dm
Labels: Feature Tweak

#4938 Further Package Bomb adjustments
  code/game/objects/items/weapons/syndie.dm
Labels: Feature Tweak

#4937 Prommie Cohesion Suits
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/items/lefthand_uniforms.dmi
  icons/mob/items/righthand_uniforms.dmi
  icons/mob/species/seromi/uniform.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature
