Repository PolarisSS13/Polaris, pull requests merged in 2018-09, with the labels that each got.

#5537 Fix Mech Grenade Launchers.
  code/game/mecha/equipment/weapons/weapons.dm
Labels: Bugfix, Oversight

#5540 Cult Girders are back to being proper.
  code/game/objects/structures/girders.dm
  code/game/turfs/simulated/wall_types.dm
  code/modules/materials/materials.dm
  icons/obj/cult.dmi
Labels: Bugfix, Oversight

#5539 Might fix the server startup error_handler runtime
  code/datums/observation/helpers.dm
  code/datums/observation/logged_in.dm
  code/datums/observation/moved.dm
  code/datums/observation/unequipped.dm
  code/modules/holomap/station_holomap.dm
  code/modules/mob/living/bot/secbot.dm
Labels: Bugfix

#5544 Should fix another runtime with tools
  code/game/objects/structures/grille.dm
Labels: Bugfix

#5541 Submaps can be rotated
  code/game/objects/items/poi_items.dm
  code/modules/admin/verbs/map_template_loadverb.dm
  code/modules/maps/tg/map_template.dm
  code/modules/maps/tg/reader.dm
Labels: Feature Tweak, Point of Interest

#5545 Buffs the Vox
  code/ZAS/Phoron.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/clothing/spacesuits/alien.dm
  code/modules/clothing/spacesuits/rig/suits/alien.dm
  code/modules/clothing/spacesuits/spacesuits.dm
  code/modules/clothing/suits/aliens/vox.dm
  code/modules/clothing/suits/bio.dm
  code/modules/clothing/under/xenos/vox.dm
  code/modules/integrated_electronics/subtypes/reagents.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/organs/organ_external.dm
  code/modules/projectiles/guns/vox.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  icons/obj/gun.dmi
Labels: Feature Tweak, Prepare to Die

#5512 Scrubbers no longer automatically scrub phoron
  code/ATMOSPHERICS/components/unary/vent_scrubber.dm
Labels: Controversial, Unwanted Feature Removal

#5514 Removes Shellguard Noble cyborg sprites.
  code/modules/mob/living/silicon/robot/robot_modules/station.dm
  icons/mob/robots.dmi
Labels: Requires Staff Input, Sprite Change, Unwanted Feature Removal

#5546 Adds new set of cyborg sprites
  code/modules/mob/living/silicon/robot/robot_modules/station.dm
  icons/mob/robots.dmi
Labels: Feature, Sprite Change

#5550 Helmets now show only certain hairstyles
  code/modules/clothing/head/helmet.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/new_player/sprite_accessories.dm
  code/modules/organs/organ_icon.dm
Labels: Bugfix, Feature Tweak

#5551 Adds tails to Unathi rig suit sprites
  icons/mob/species/unathi/suit.dmi
Labels: Sprite Change

#5555 communicator_header.tmpl now correctly includes Body
  nano/templates/communicator_header.tmpl
Labels: Bugfix, Priority: High

#5559 Emags have an effect on cargo consoles
  code/game/machinery/computer/supply.dm
Labels: Oversight

#5562 Fixes Lead Walls
  code/datums/repositories/radiation.dm
Labels: Bugfix, Oversight

#5564 Map Bugfixes
  code/game/objects/random/misc.dm
  code/game/objects/random/mob.dm
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-3.dmm
  maps/southern_cross/southern_cross-6.dmm
  maps/submaps/surface_submaps/mountains/crashedcontainmentshuttle.dmm
  maps/submaps/surface_submaps/wilderness/wilderness_areas.dm
Labels: Bugfix, Map Change / Issue

#5553 Vehicle Expansion 1: Zoom Harder
  code/datums/supplypacks/robotics.dm
  code/datums/supplypacks/supply.dm
  code/game/mecha/mech_sensor.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/game/objects/structures/crates_lockers/vehiclecage.dm
  code/modules/research/mechfab_designs.dm
  code/modules/vehicles/bike.dm
  code/modules/vehicles/cargo_train.dm
  code/modules/vehicles/construction.dm
  code/modules/vehicles/quad.dm
  code/modules/vehicles/train.dm
  code/modules/vehicles/vehicle.dm
  html/changelogs/Mechoid - Vehicles.yml
  icons/obj/bike.dmi
  icons/obj/custom_items_vehicle.dmi
  icons/obj/storage.dmi
  icons/obj/vehicles.dmi
  icons/obj/vehicles_64x64.dmi
  maps/northern_star/polaris-1.dmm
  maps/northern_star/polaris-2.dmm
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-4.dmm
  maps/southern_cross/southern_cross-6.dmm
  maps/submaps/surface_submaps/plains/Field1.dmm
  maps/submaps/surface_submaps/plains/Thiefc.dmm
  polaris.dme
Labels: Feature, Refactor

#5563 Cybersuit is now a space rig.
  code/modules/clothing/spacesuits/rig/suits/light.dm
Labels: Feature Tweak

#5511 Ports character physical descriptors from Bay
  code/modules/client/preference_setup/general/03_body.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/descriptors/_descriptors.dm
  code/modules/mob/living/carbon/human/descriptors/descriptors_generic.dm
  code/modules/mob/living/carbon/human/descriptors/descriptors_skrell.dm
  code/modules/mob/living/carbon/human/descriptors/descriptors_vox.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/species/outsider/vox.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  polaris.dme
Labels: Controversial, Feature Tweak, Ported from Baycode

#5573 More Blob modularity / Event-Manager compatability, Nests.
  code/game/objects/structures/props/nest.dm
  code/modules/blob2/blobs/base_blob.dm
  code/modules/blob2/blobs/core.dm
  code/modules/blob2/blobs/factory.dm
  code/modules/blob2/blobs/resource.dm
  code/modules/blob2/overmind/overmind.dm
  code/modules/blob2/overmind/powers.dm
  code/modules/blob2/overmind/types.dm
  code/modules/mob/living/death.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/projectiles/projectile/blob.dm
  polaris.dme
Labels: Feature, Feature Tweak

#5575 Rig and Spacesuit additions
  code/game/machinery/suit_storage_unit.dm
  code/modules/clothing/spacesuits/rig/suits/combat.dm
  code/modules/clothing/spacesuits/rig/suits/pmc.dm
  code/modules/clothing/spacesuits/void/station.dm
  html/changelogs/Woodrat - Spacesuit.yml
  icons/mob/feet.dmi
  icons/mob/hands.dmi
  icons/mob/head.dmi
  icons/mob/rig_back.dmi
  icons/mob/spacesuit.dmi
  icons/mob/species/seromi/head.dmi
  icons/mob/species/seromi/suit.dmi
  icons/mob/species/skrell/helmet.dmi
  icons/mob/species/skrell/suit.dmi
  icons/mob/species/tajaran/helmet.dmi
  icons/mob/species/tajaran/suit.dmi
  icons/mob/species/unathi/helmet.dmi
  icons/mob/species/unathi/suit.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/spacesuits.dmi
  icons/obj/clothing/species/seromi/hats.dmi
  icons/obj/clothing/species/seromi/suits.dmi
  icons/obj/clothing/species/skrell/hats.dmi
  icons/obj/clothing/species/skrell/suits.dmi
  icons/obj/clothing/species/tajaran/hats.dmi
  icons/obj/clothing/species/tajaran/suits.dmi
  icons/obj/clothing/species/unathi/hats.dmi
  icons/obj/clothing/species/unathi/suits.dmi
  icons/obj/rig_modules.dmi
  maps/southern_cross/southern_cross_defines.dm
  polaris.dme
Labels: Feature, Sprite Change

#5578 Fixes hand and leg cuffs
  code/game/objects/items/weapons/handcuffs.dm
Labels: Bugfix

#5576 Dermal implant doesn't cover hair
  code/modules/clothing/head/jobs.dm
Labels: Bugfix, Oversight

#5577 Fixes a couple of tool related oversight/runtimes
  code/game/machinery/doors/door.dm
  code/game/objects/structures/grille.dm
Labels: Bugfix, Oversight

#5583 Adds tails to Unathi rigsuits (again)
  icons/mob/species/unathi/suit.dmi
Labels: Oversight, Sprite Change

#5582 Boot knives fit in boots
  code/game/objects/items/weapons/material/kitchen.dm
  code/game/objects/items/weapons/material/knives.dm
  code/game/objects/items/weapons/material/misc.dm
  maps/submaps/surface_submaps/mountains/quarantineshuttle.dmm
Labels: Bugfix, Oversight

#5586 Descriptors now properly respect species differences
  code/modules/mob/living/carbon/human/descriptors/_descriptors.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/seromi.dm
Labels: Bugfix, Feature Tweak

#5584 Skrell names no longer contain spaces
  config/names/first_name_skrell.txt
  config/names/last_name_skrell.txt
Labels: Oversight

#5588 Psychiatric Medication Fix
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
Labels: Bugfix, Oversight

#5587 Wind in storms slightly nerfed
  code/modules/planet/sif.dm
Labels: Feature Tweak

#5581 Technically adds the Ore Redemption Machine
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/effects/temporary_visuals/temproary_visual.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/id cards/station_ids.dm
  code/modules/mining/machine_processing.dm
  code/modules/mining/ore_redemption_machine/construction.dm
  code/modules/mining/ore_redemption_machine/equipment_vendor.dm
  code/modules/mining/ore_redemption_machine/mine_point_items.dm
  code/modules/mining/resonator.dm
  icons/effects/96x96.dmi
  icons/obj/machines/mining_machines.dmi
  icons/obj/mining.dmi
  icons/obj/projectiles.dmi
  polaris.dme
  sound/weapons/resonator_blast.ogg
  sound/weapons/resonator_fire.ogg
Labels: Feature

#5589 Adds the Biopsy Scanner to the Surgery Kit
  code/game/objects/items/weapons/storage/firstaid.dm
Labels: Feature Tweak

#5574 Adds some Holy drinks, and Promethean-safe drinks / acclimators.
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_containers/drinkingglass/metaglass.dm
  icons/obj/drinks.dmi
Labels: Feature

#5599 Nests don't spawn things in null.
  code/game/objects/structures/props/nest.dm
Labels: Bugfix, Oversight

#5593 Tweaks emitters and Pacman
  code/modules/power/port_gen.dm
  code/modules/power/singularity/emitter.dm
  html/changelogs/Anewbe - Emitters.yml
Labels: Bugfix, Feature Tweak

#5600 Adds a generic proc to the mining vendor to add custom / blank entries.
  code/modules/mining/ore_redemption_machine/equipment_vendor.dm
Labels: Feature

#5590 Make the Statue 'better'.
  code/modules/mob/living/simple_animal/aliens/statue.dm
Labels: Bugfix, Feature Tweak

#5607 Pose now shows up under descriptors
  code/modules/mob/living/carbon/human/examine.dm
Labels: Bugfix, Feature Tweak

#5608 Fixes Circuitry Glasses.
  code/modules/clothing/glasses/glasses.dm
Labels: Bugfix, Oversight

#5605 Species item slowdown changes
  code/modules/mob/living/carbon/human/species/station/seromi.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
Labels: Feature Tweak

#5611 Phase rifle size correction
  code/modules/projectiles/guns/energy/phase.dm
Labels: Bugfix, Oversight

#5614 Hyposprays can now have different sounds
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: Feature Tweak

#5613 Custom RIG Framework
  code/game/objects/items/paintkit.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  html/changelogs/Mechoid - Custom Rigs.yml
  icons/mob/custom_items_rig_boots.dmi
  icons/mob/custom_items_rig_gloves.dmi
  icons/mob/custom_items_rig_helmet.dmi
  icons/mob/custom_items_rig_suit.dmi
Labels: Feature
