Repository PolarisSS13/Polaris, pull requests merged in 2018-04, with the labels that each got.

#5059 Fixes and tweaks for slime behavior.
  code/modules/mob/living/simple_animal/slime/ai.dm
  code/modules/mob/living/simple_animal/slime/life.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
  code/modules/mob/living/simple_animal/slime/subtypes.dm
Labels: Bugfix, Feature Tweak

#5073 Wallet Expansion!
  code/game/objects/items/weapons/storage/wallets.dm
  html/changelogs/MistyLuminescence - Wallets.yml
Labels: Feature Tweak, Requires Staff Input

#5125 Normal brute kits disinfect wounds
  code/game/objects/items/stacks/medical.dm
Labels: Feature Tweak, Requires Staff Input, Staff Request

#5137 Updates changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Anewbe - Medkits.yml
  html/changelogs/Billybangles - Markers.yml
  html/changelogs/Cameron - Xenoarch Upgrades.yml
  html/changelogs/Heroman3003 - Gripper Fixes.yml
  html/changelogs/MistyLuminescence - Wallets.yml
  html/changelogs/Woodrat - 44 Revolver.yml
  html/changelogs/Woodrat - Random Changes.yml
Labels: Changelog Update

#5131 Adds Map Template Groups
  code/game/turfs/flooring/flooring_premade.dm
  code/modules/maps/tg/map_template.dm
  maps/submaps/surface_submaps/wilderness/DJOutpost2.dmm
  maps/submaps/surface_submaps/wilderness/wilderness.dm
  maps/submaps/surface_submaps/wilderness/wilderness_areas.dm
Labels: Point of Interest

#5130 Fixes wallet-HUD interaction issues.
  code/game/machinery/newscaster.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Bugfix

#5133 Syndicate Dufflebag Tweak
  code/game/objects/items/weapons/storage/backpack.dm
Labels: Feature Tweak

#5134 Actually adds adhoc_fallback to pilot headsets
  html/changelogs/lorwp-pilotfallback.yml
  maps/southern_cross/items/headset_sc.dm
Labels: Oversight

#5135 Map fixes and tweaks
  code/game/area/Space Station 13 areas.dm
  code/game/machinery/vending.dm
  html/changelogs/Woodrat - Bugfixes.yml
  maps/southern_cross/southern_cross-1.dmm
Labels: Map Change / Issue

#5143 Reverted use of 'usr' back to 'user' from commit 05fd53e
  code/game/objects/items/crayons.dm
  code/game/objects/items/weapons/storage/fancy.dm
Labels: Refactor

#5147 Switch cables and pipes to use define constants instead of literals for layers.
  code/ATMOSPHERICS/atmospherics.dm
  code/ATMOSPHERICS/pipes/cap.dm
  code/ATMOSPHERICS/pipes/he_pipes.dm
  code/ATMOSPHERICS/pipes/manifold.dm
  code/ATMOSPHERICS/pipes/manifold4w.dm
  code/ATMOSPHERICS/pipes/pipe_base.dm
  code/ATMOSPHERICS/pipes/simple.dm
  code/ATMOSPHERICS/pipes/tank.dm
  code/__defines/_planes+layers.dm
  code/__defines/construction.dm
  code/game/machinery/atmoalter/portable_atmospherics.dm
  code/modules/multiz/pipes.dm
  code/modules/power/cable.dm
  code/modules/power/cable_ender.dm
  code/modules/power/cable_heavyduty.dm
  code/modules/recycling/disposal.dm
Labels: Bugfix

#5040 Constructs 2.0 - Living Stone
  code/_onclick/hud/other_mobs.dm
  code/_onclick/other_mobs.dm
  code/game/gamemodes/cult/construct_spells.dm
  code/game/gamemodes/cult/cult_items.dm
  code/game/gamemodes/technomancer/spell_objs.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/doors/blast_door.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/portable_turret.dm
  code/game/objects/items/devices/aicard.dm
  code/game/objects/items/weapons/AI_modules.dm
  code/game/objects/items/weapons/RCD.dm
  code/game/objects/structures/simple_doors.dm
  code/game/turfs/simulated/wall_attacks.dm
  code/modules/mob/_modifiers/unholy.dm
  code/modules/mob/animations.dm
  code/modules/mob/living/simple_animal/constructs/constructs.dm
  code/modules/mob/living/simple_animal/constructs/soulstone.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/multiz/movement.dm
  code/modules/projectiles/effects.dm
  code/modules/projectiles/gun.dm
  code/modules/spells/aoe_turf/conjure/construct.dm
  code/modules/spells/aoe_turf/knock.dm
  code/modules/spells/construct_spells.dm
  code/modules/spells/targeted/harvest.dm
  code/modules/spells/targeted/shift.dm
  code/modules/tables/tables.dm
  icons/effects/effects.dmi
  icons/effects/projectiles.dmi
  icons/mob/mob.dmi
  icons/mob/modifier_effects.dmi
  icons/mob/screen1_construct.dmi
  icons/mob/screen_spells.dmi
  polaris.dme
Labels: Feature Tweak, Prepare to Die

#5132 Kills the Vir Times and replaces the economic destination list with Polaris locations.
  code/modules/economy/Events.dm
  code/modules/economy/Events_Mundane.dm
  code/modules/economy/TradeDestinations.dm
  code/modules/economy/economy_misc.dm
  code/modules/economy/lorenews.dm
  code/modules/events/event_container.dm
  code/modules/events/event_dynamic.dm
Labels: Lore

#5153 Adds Tile-based Attacks
  code/game/objects/items/weapons/material/knives.dm
  code/game/objects/items/weapons/material/misc.dm
  code/game/objects/items/weapons/material/twohanded.dm
  code/game/objects/items/weapons/melee/energy.dm
  code/game/objects/weapons.dm
  code/game/turfs/simulated/floor_attackby.dm
  code/game/turfs/turf.dm
  code/modules/mob/animations.dm
Labels: Feature

#5158 Polar-izes shipping locations
  code/modules/busy_space/organizations.dm
Labels: Lore

#5157 yet another lore update
  code/modules/lore_codex/news_data/main.dm
Labels: Lore

#5160 Fix shuttle corner turfs disappearing when shuttle moves.
  code/game/turfs/simulated/floor_types.dm
Labels: Bugfix

#5151 Search and Rescue spawn with the right kit
  maps/southern_cross/job/outfits.dm
Labels: Bugfix, Oversight

#5155 Blast Doors can't be Emagged
  code/game/machinery/doors/blast_door.dm
Labels: Bugfix, Oversight

#5162 Optimizes Powercell Update Icons
  code/modules/power/cell.dm
Labels: Optimization

#5163 Fix bug in death ripley visuals
  code/game/mecha/working/ripley.dm
Labels: Bugfix

#5164 Fixed legcuffs not being placeable on handcuffed people
  code/game/objects/items/weapons/handcuffs.dm
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Bugfix

#4779 [WIP] Planetary Lighting Optimization Attempt
  code/controllers/Processes/planet.dm
  code/modules/lighting/lighting_atom.dm
  code/modules/lighting/lighting_source.dm
  code/modules/planet/planet.dm
  icons/effects/effects.dmi
Labels: Optimization

#5167 Fixed sheet snatcher spawning stacks with wrong looking icon
  code/game/objects/items/weapons/storage/bags.dm
Labels: Bugfix

#5165 Fix Wall Frames - Several Ways
  code/_helpers/unsorted.dm
  code/game/machinery/frame.dm
  code/game/machinery/wall_frames.dm
  code/game/objects/items/apc_frame.dm
  code/game/objects/structures/window.dm
  code/game/turfs/simulated/wall_attacks.dm
Labels: Bugfix

#5173 Mimics no longer have tooltips
  code/modules/mob/living/simple_animal/aliens/mimic.dm
Labels: Bugfix, Oversight

#5174 Fixes simplemob icons when killed while resting.
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Bugfix

#5169 Fixes missing icon on 2 teshari uniforms.
  icons/mob/species/seromi/teshari_uniform.dmi
  icons/obj/clothing/species/seromi/uniform.dmi
Labels: Sprite Change

#5166 Fixed closet painter making non-closet 'closets' invisible
  code/game/objects/items/devices/locker_painter.dm
Labels: Bugfix

#5177 Fixes various implant/admin verb typos
  code/game/area/Space Station 13 areas.dm
  code/game/objects/items/weapons/implants/implantcircuits.dm
  code/modules/admin/admin.dm
Labels: Bugfix

#5176 Better-quality replacements for some gunshot sounds
  sound/weapons/Gunshot_old.ogg
  sound/weapons/gunshot/gunshot.ogg
  sound/weapons/gunshot/shotgun.ogg
  sound/weapons/gunshot/sniper.ogg
  sound/weapons/shotgun.ogg
  sound/weapons/sniper.ogg
Labels: Feature Tweak

#5180 Fixes typo in mopgearrex movement icon.
  icons/mob/robots.dmi
Labels: Bugfix, Sprite Change

#5191 Updates changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Anewbe - AOOC.yml
  html/changelogs/Woodrat - Bugfixes.yml
  html/changelogs/lorwp-pilotfallback.yml
Labels: Changelog Update

#5185 Fixes borg synth sheet naming when depleted to 1
  code/modules/materials/material_synth.dm
Labels: Bugfix

#5188 Fixes mob wall-bashing.
  code/game/turfs/simulated/wall_attacks.dm
Labels: Bugfix, Oversight

#5161 Refactors human/examine.dm
  code/__defines/mobs.dm
  code/modules/mob/living/carbon/human/examine.dm
  html/changelogs/atermonera-refactorexamine.yml
Labels: Refactor

#5189 Optimize Planetary Sun Mk II
  code/controllers/Processes/planet.dm
  code/modules/lighting/lighting_atom.dm
  code/modules/lighting/lighting_source.dm
  code/modules/planet/planet.dm
  icons/effects/effects.dmi
Labels: Optimization

#5190 PunPun's clothes show up when he spawns
  code/modules/mob/living/carbon/human/npcs.dm
Labels: Bugfix

#5178 Adds new robot codex
  code/modules/client/preference_setup/loadout/loadout_utility.dm
  code/modules/lore_codex/codex.dm
  code/modules/lore_codex/robutt_data/bybrand.dm
  code/modules/lore_codex/robutt_data/main_robutts.dm
  code/modules/lore_codex/robutt_data/more.dm
  icons/obj/library.dmi
  polaris.dme
Labels: Lore

#5193 Fix access on security suit crates
  code/datums/supplypacks/voidsuits.dm
Labels: Bugfix

#5172 Add several new events
  code/_helpers/events.dm
  code/modules/events/atmos_leak.dm
  code/modules/events/electrified_door.dm
  code/modules/events/escaped_slimes.dm
  code/modules/events/wallrot.dm
  code/modules/events/window_break.dm
  code/modules/events/wormholes.dm
  polaris.dme
Labels: Feature

#5195 Sundry Fixes - Emitters, Bedsheets, Conveyors
  code/game/objects/structures/bedsheet_bin.dm
  code/modules/power/singularity/emitter.dm
  code/modules/recycling/conveyor2.dm
Labels: Bugfix

#5196 Carp Plushie Fix
  code/game/machinery/vending.dm
  code/game/objects/items/toys.dm
  html/changelogs/schnayy-plushietweak.yml
  icons/obj/toy.dmi
Labels: Bugfix, Feature Tweak

#5197 Rewrite brig timers to initialize properly
  code/game/machinery/doors/brigdoors.dm
Labels: Bugfix, Refactor

#5198 Makes clothing use the correct sprite sheet.
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Bugfix

#5199 Use define constants for subsystem init order and priority.
  code/__defines/subsystems.dm
  code/controllers/subsystem.dm
  code/controllers/subsystems/air.dm
  code/controllers/subsystems/airflow.dm
  code/controllers/subsystems/garbage.dm
  code/controllers/subsystems/machines.dm
  code/controllers/subsystems/orbits.dm
  code/controllers/subsystems/shuttles.dm
Labels: Refactor

#5186 Remove the 'tag' var from every map
  .travis.yml
  maps/RandomZLevels/Academy.dmm
  maps/RandomZLevels/arcticwaste.dmm
  maps/RandomZLevels/beach.dmm
  maps/RandomZLevels/blackmarketpackers.dmm
  maps/RandomZLevels/challenge.dmm
  maps/RandomZLevels/example.dmm
  maps/RandomZLevels/jungle.dmm
  maps/RandomZLevels/listeningpost.dmm
  maps/RandomZLevels/spacebattle.dmm
  maps/RandomZLevels/stationCollision.dmm
  maps/RandomZLevels/wildwest.dmm
  maps/RandomZLevels/zresearchlabs.dmm
  maps/example/example-1.dmm
  maps/example/example-2.dmm
  maps/northern_star/polaris-1.dmm
  maps/northern_star/polaris-2.dmm
  maps/northern_star/polaris-3.dmm
  maps/northern_star/polaris-4.dmm
  maps/northern_star/polaris-5.dmm
  maps/overmap/bearcat/bearcat.dmm
  maps/overmap/example_sector1.dmm
  maps/overmap/example_sector2.dmm
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-3.dmm
  maps/southern_cross/southern_cross-4.dmm
  maps/southern_cross/southern_cross-5.dmm
  maps/southern_cross/southern_cross-6.dmm
  maps/southern_cross/southern_cross-7.dmm
  maps/submaps/surface_submaps/mountains/CrashedMedShuttle1.dmm
  maps/submaps/surface_submaps/mountains/Mineshaft1.dmm
  maps/submaps/surface_submaps/mountains/crashed_ufo.dmm
  maps/submaps/surface_submaps/mountains/quarantineshuttle.dmm
  maps/submaps/surface_submaps/plains/Boathouse.dmm
  maps/submaps/surface_submaps/plains/Diner.dmm
  maps/submaps/surface_submaps/plains/Mechpt.dmm
  maps/submaps/surface_submaps/plains/farm1.dmm
  maps/submaps/surface_submaps/wilderness/Blackshuttledown.dmm
  maps/submaps/surface_submaps/wilderness/Boombase.dmm
  maps/submaps/surface_submaps/wilderness/DJOutpost1.dmm
  maps/submaps/surface_submaps/wilderness/DJOutpost2.dmm
  maps/submaps/surface_submaps/wilderness/DecoupledEngine.dmm
  maps/submaps/surface_submaps/wilderness/Drugden.dmm
  maps/submaps/surface_submaps/wilderness/Rockybase.dmm
  maps/submaps/surface_submaps/wilderness/Shack1.dmm
Labels: Refactor

#5187 Communicator visibility is now on a per-character basis, rather than global
  code/modules/client/preference_setup/general/04_equipment.dm
  code/modules/client/preference_setup/global/04_communicators.dm
  code/modules/client/preference_setup/global/04_ooc.dm
  html/changelogs/Anewbe - Communicators.yml
  polaris.dme
Labels: Feature Tweak, Quality of Life

#5205 Replaces Ice turf sprite for a prettier one
  icons/turf/outdoors.dmi
Labels: Sprite Change

#5194 Species economic modifier is now a species var
  code/game/jobs/job/job.dm
  code/modules/economy/economy_misc.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/prometheans.dm
  code/modules/mob/living/carbon/human/species/station/seromi.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
Labels: Refactor

#5203 Fixes pumpkins and watermelon sprites
  code/modules/hydroponics/seed_datums.dm
  html/changelogs/Cerebulon - pumpkins.yml
  icons/obj/hydroponics_growing.dmi
Labels: Sprite Change

#5204 Disposals pipe fix
  maps/southern_cross/southern_cross-1.dmm
Labels: Bugfix, Map Change / Issue

#5206 Removed ugly blood pools from sif mobs
  icons/jungle.dmi
Labels: Sprite Change

#5210 Fixes an exploit with circuit printers
  code/modules/integrated_electronics/core/printer.dm
Labels: Bugfix, Oversight, Priority: CRITICAL

#5224 Welding fuel has a sprite again
  icons/effects/effects.dmi
Labels: Bugfix, Priority: CRITICAL

#5221 Prevent negative weight events from happening
  code/modules/events/event_container.dm
Labels: Oversight

#5218 Fixes miners not being able to take supply snowsuit
  code/modules/client/preference_setup/loadout/loadout_suit.dm
Labels: Oversight

#5170 Upgrades Planetary Weather to vis_contents
  code/__defines/planets.dm
  code/controllers/Processes/planet.dm
  code/game/turfs/simulated/floor_icon.dm
  code/game/turfs/simulated/outdoors/outdoors.dm
  code/game/turfs/turf_changing.dm
  code/modules/planet/weather.dm
Labels: Refactor

#5208 Fixed sprites tilting when standing up during crawling
  code/game/turfs/turf.dm
Labels: Oversight

#5212 PoI Stage 0.5
  code/game/objects/random/guns_and_ammo.dm
  code/game/objects/random/mapping.dm
  code/game/objects/random/misc.dm
  code/game/objects/random/mob.dm
  code/game/objects/random/spacesuits.dm
  code/game/objects/structures/loot_piles.dm
  code/game/turfs/simulated/dungeon/wall.dm
  code/modules/mob/living/simple_animal/animals/giant_spider.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  code/modules/xenoarcheaology/finds/misc.dm
  icons/obj/ammo.dmi
Labels: Feature, Point of Interest

#5211 Hides jobs with the Never pref on late join
  code/modules/mob/new_player/new_player.dm
  html/changelogs/Anewbe - Late Join Hidden.yml
Labels: Feature Tweak, Quality of Life
