Repository PolarisSS13/Polaris, pull requests merged in 2019-11, with the labels that each got.

#6495 Fixes non-planet zlevel weather runtime cascade
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: Bugfix

#6508 Fixes simplemobs wandering when grabbed.
  code/modules/ai/ai_holder_movement.dm
Labels: Bugfix

#6509 Fixes adding verbs to mobs in varedit.
  code/modules/admin/view_variables/topic.dm
Labels: Bugfix

#6513 New FBP design.
  code/modules/organs/robolimbs.dm
  icons/mob/human_races/cyberlimbs/einstein/einstein_main.dmi
Labels: Feature

#6510 Fixes knocked out borgs never dying.
  code/modules/mob/living/silicon/robot/life.dm
Labels: Bugfix

#6514 Setup for New Library
  code/modules/library/hardcode_library/_library.dm
  code/modules/library/lib_items.dm
  code/modules/library/lib_machines.dm
  code/modules/lore_codex/codex.dm
  icons/obj/custom_books.dmi
  polaris.dme
Labels: Feature, Feature Tweak

#6491 Xenowork Prep For Future
  code/game/objects/effects/alien/aliens.dm
  code/game/objects/structures/girders.dm
  code/game/turfs/simulated/wall_attacks.dm
  code/game/turfs/simulated/wall_types.dm
  code/modules/materials/material_recipes.dm
  code/modules/materials/material_sheets.dm
  code/modules/materials/materials.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species/xenomorphs/alien_powers.dm
  code/modules/mob/living/carbon/human/species/xenomorphs/alien_species.dm
  code/modules/organs/organ.dm
  code/modules/organs/organ_external.dm
  code/modules/organs/subtypes/indestructible.dm
  code/modules/organs/subtypes/xenos.dm
  code/modules/reagents/reagent_containers/syringes.dm
  icons/mob/alien.dmi
  icons/obj/stacks.dmi
  icons/obj/structures.dmi
  icons/turf/wall_masks.dmi
Labels: Feature Tweak, Refactor

#6501 Sharpening kits.
  code/game/objects/items/weapons/material/material_weapons.dm
  code/game/objects/items/weapons/material/whetstone.dm
  icons/obj/kitchen.dmi
Labels: Feature

#6512 Sanity check for orphaned ai_holder runtimes
  code/modules/ai/ai_holder_disabled.dm
Labels: Bugfix

#6519 Fix Fruit Runtime
  code/modules/hydroponics/grown.dm
Labels: Bugfix, Priority: High

#6521 Stop protein's affect_ingest calling nutriment's affect_ingest twice
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
Labels: Bugfix

#6522 Botany Fix, again? [Why]
  code/modules/hydroponics/grown.dm
Labels: Bugfix, Priority: High

#6527 Air pump fixes: Reduce loop time, reduce noise level
  code/datums/looping_sounds/machinery_sounds.dm
Labels: Feature Tweak

#6528 Improve analyzers and gas mixers
  code/ATMOSPHERICS/components/trinary_devices/mixer.dm
  code/_helpers/atmospherics.dm
Labels: Feature

#6481 Reduces maintenance drone spawn time to 5 minutes
  code/modules/mob/living/silicon/robot/drone/drone_manufacturer.dm
  html/changelogs/atermonera - maintdronetime.yml
Labels: Bugfix

#6536 Captain and HoP Headsets Fully Enabled by Default
  code/game/objects/items/devices/radio/encryptionkey.dm
  html/changelogs/Nalarac - Enables Headset Channels.yml
  maps/southern_cross/items/encryptionkey_sc.dm
Labels: Feature Tweak

#6554 Protolathe Power Cells Tweak
  code/modules/power/cells/power_cells.dm
  code/modules/research/designs.dm
  code/modules/research/designs/power_cells.dm
  html/changelogs/Nalarac - Protolathe.yml
Labels: Feature Tweak

#6553 Fixes Naming ED-209 and ED-CLN
  code/modules/mob/living/bot/ed209bot.dm
  code/modules/mob/living/bot/edCLNbot.dm
  html/changelogs/Nalarac - ED209.yml
Labels: Bugfix

#6551 Fixes elevator doors opening in passing
  code/modules/turbolift/turbolift_console.dm
Labels: Bugfix

#6550 Fixes two typos (rengeration and Extranneous)
  code/game/gamemodes/changeling/powers/fleshmend.dm
  code/game/objects/items/weapons/teleportation.dm
Labels: Bugfix

#6548 Fix pAI preferences not loading
  code/modules/client/preference_setup/global/03_pai.dm
Labels: Bugfix

#6547 Lamps, Lights, Lackluster!
  code/game/objects/items/devices/flashlight.dm
  html/changelogs/TheFurryFeline - Lamps Light Lackluster.yml
Labels: Feature Tweak

#6539 Fix the bioprinter
  code/game/machinery/bioprinter.dm
  code/modules/organs/organ_icon.dm
Labels: Bugfix, Priority: Medium

#6537 Inaccuracy Rebalance (NPC)
  code/modules/mob/living/simple_mob/simple_mob.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/webslinger.dm
  code/modules/mob/living/simple_mob/subtypes/humanoid/mercs/mercs.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/hivebot/ranged_damage.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/mecha/durand.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/mecha/gygax.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/mecha/hoverpod.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/viscerator.dm
Labels: Feature Tweak, Results To Be Reviewed

#6535 Fix Strange Rock Size
  code/modules/xenoarcheaology/finds/finds.dm
  html/changelogs/TheFurryFeline - Strange Rock Fixy.yml
Labels: Bugfix
