Repository PolarisSS13/Polaris, pull requests merged in 2019-09, with the labels that each got.

#6435 Fixes oversight with instruments
  code/game/objects/structures/musician.dm
Labels: Oversight

#6443 Fixes runtime in library computers
  code/game/machinery/machinery.dm
Labels: Bugfix, Staff Request

#6436 Fixed an issue with multiple boot/shoe overlays.
  code/game/atoms.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/items.dm
  code/modules/clothing/clothing.dm
Labels: Bugfix

#6437 Fixes bordercorner2 not having a grey preset
  code/game/turfs/flooring/flooring_decals.dm
Labels: Oversight

#6438 Makes friendly viscerators not attack wards
  code/modules/mob/living/simple_mob/subtypes/mechanical/viscerator.dm
Labels: Oversight

#6439 Adding Vendors
  html/changelogs/Woodrat - Vendor Addition.yml
  maps/southern_cross/southern_cross-1.dmm
Labels: Map Change / Issue

#6440 fixes a stomach pump typo
  code/game/machinery/Sleeper.dm
Labels: Bugfix

#6442 Fixes missing hardsuit sprites
  icons/mob/species/skrell/helmet.dmi
  icons/mob/species/skrell/suit.dmi
  icons/mob/species/tajaran/helmet.dmi
  icons/mob/species/tajaran/suit.dmi
  icons/mob/species/unathi/helmet.dmi
  icons/mob/species/unathi/suit.dmi
Labels: Sprite Change

#6445 Fixes some lost drone laws not ever applying
  code/modules/mob/living/silicon/robot/subtypes/lost_drone.dm
Labels: Oversight

#6446 Fixes solar panel assembly dupe
  code/modules/power/solar.dm
Labels: Bugfix

#6448 Changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Heroman3003 - bellfixes.yml
  html/changelogs/MisterLayne - conductivity_fix.yml
  html/changelogs/MisterLayne - glass_shard_self_harm.yml
  html/changelogs/Novacat - MREs.yml
  html/changelogs/Woodrat - Vendor Addition.yml
  html/changelogs/chaoko99 - stomach_pump.yml
Labels: Changelog Update

#6450 Actually swaps the nitrous and phoron tanks
  maps/southern_cross/southern_cross-1.dmm
Labels: Map Change / Issue, Oversight

#6455 Properly fixes library computer runtime
  code/game/machinery/machinery.dm
  code/game/objects/objs.dm
Labels: Bugfix, Priority: CRITICAL

#6456 Emergency hotfix: Ater is a donk edition
  code/game/machinery/machinery.dm
Labels: Oversight, Priority: CRITICAL

#6457 Bar and Kitchen Merge
  html/changelogs/woodrat - Barkitchenmerge.yml
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-6.dmm
Labels: Map Change / Issue

#6404 Makes airtight plastic flaps unmakeable
  code/game/objects/structures/plasticflaps.dm
  code/modules/materials/material_recipes.dm
Labels: Unwanted Feature Removal

#6461 Fixes Soil not being makeable
  code/modules/materials/material_recipes.dm
Labels: Oversight

#6444 Ports Earrings from Baystation
  code/modules/client/preference_setup/loadout/loadout_ears.dm
  code/modules/clothing/ears/earrings.dm
  icons/mob/ears.dmi
  icons/obj/clothing/ears.dmi
  polaris.dme
Labels: Feature, Ported from Baycode, Sprite Change

#6447 Orange Is The New Orange Part 2
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/admin/secrets/admin_secrets/prison_warp.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/clothing/under/color.dm
  html/changelogs/TheFurryFeline - Orange_Is_The_New_Orange_Part_2.yml
  icons/mob/items/lefthand_uniforms.dmi
  icons/mob/items/righthand_uniforms.dmi
  icons/mob/uniform.dmi
  icons/mob/uniform_rolled_down.dmi
  icons/mob/uniform_sleeves_rolled.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Refactor, Sprite Change

#6466 Makes lightning strikes respect weather sound pref
  code/modules/admin/verbs/lightning_strike.dm
Labels: Feature Tweak

#6467 Makes every single shot not create ~40 timers but 1
  code/game/objects/effects/temporary_visuals/projectiles/tracer.dm
  code/modules/projectiles/projectile.dm
Labels: Refactor

#6460 Ports World Server Dialogue/Attack Log Viewer
  code/_global_vars/mobs.dm
  code/_helpers/logging.dm
  code/modules/admin/admin_attack_log.dm
  code/modules/admin/admin_tools.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/secrets/admin_secrets/admin_logs.dm
  polaris.dme
Labels: Feature

#6462 fix gun handle_suicide
  code/modules/projectiles/gun.dm
Labels: Bugfix

#6463 Fixes grab having big delay on deletion after throws
  code/modules/mob/living/living.dm
Labels: Bugfix
