Repository PolarisSS13/Polaris, pull requests merged in 2019-08, with the labels that each got.

#6364 Fixes Ripley Speedboost Being Uncreatable
  code/modules/research/mechfab_designs.dm
Labels: Bugfix

#6359 Updates Supermatter Guide Book
  code/game/objects/items/weapons/manuals.dm
  html/changelogs/Nalarac - Supermatter Guide.yml
Labels: Feature Tweak, Oversight

#6361 Changes Space Helmet Cameras to a Verb
  code/modules/clothing/spacesuits/spacesuits.dm
  html/changelogs/Nalarac - Helmet Cameras.yml
Labels: Feature Tweak

#6367 Fixes Medibots Targetting FBPs
  code/modules/mob/living/bot/medbot.dm
  html/changelogs/Nalarac - Medibot.yml
Labels: Feature Tweak

#6366 Tweaks Security Bots
  code/modules/mob/living/bot/secbot.dm
  html/changelogs/Nalarac - Sec Bot.yml
Labels: Bugfix, Feature Tweak

#6322 Allows synthetic names to start with a number
  code/_helpers/text.dm
Labels: Feature Tweak

#6357 Resprites Health Analyzers and Adds Scanning Animations
  code/game/objects/items/devices/scanners.dm
  icons/obj/device.dmi
Labels: Sprite Change

#6295 Adds an advanced TTS circuit, and sign-camera.
  code/game/objects/objs.dm
  code/modules/integrated_electronics/subtypes/input.dm
  code/modules/integrated_electronics/subtypes/output.dm
  code/modules/mob/living/say.dm
  html/changelogs/Mechoid - TTSandSign.yml
Labels: Feature

#6362 Event Tweaks / Fixes
  code/modules/gamemaster/actions/action.dm
  code/modules/gamemaster/actions/atmos_leak.dm
  code/modules/gamemaster/actions/blob.dm
  code/modules/gamemaster/actions/camera_damage.dm
  code/modules/gamemaster/actions/carp_migration.dm
  code/modules/gamemaster/actions/electrified_door.dm
  code/modules/gamemaster/actions/radiation_storm.dm
  code/modules/gamemaster/actions/rogue_drones.dm
  code/modules/gamemaster/actions/solar_storm.dm
  code/modules/gamemaster/actions/spider_infestation.dm
  code/modules/gamemaster/actions/surprise_carp_attack.dm
  code/modules/gamemaster/actions/viral_infection.dm
  code/modules/gamemaster/actions/viral_outbreak.dm
  code/modules/gamemaster/actions/wallrot.dm
  code/modules/gamemaster/actions/wormholes.dm
  code/modules/metric/count.dm
Labels: Bugfix, Feature Tweak

#6393 Adds NOCONDUCT to Some Items
  code/defines/obj/weapon.dm
  code/game/objects/items/weapons/mop.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/modules/food/food/drinks/bottle.dm
  code/modules/hydroponics/grown.dm
  code/modules/hydroponics/grown_inedible.dm
  code/modules/library/lib_items.dm
  code/modules/materials/materials.dm
  code/modules/reagents/reagent_containers/glass.dm
Labels: Oversight

#6387 Makes ahelping on existing ticket give proper feedback
  code/modules/admin/verbs/adminhelp.dm
Labels: Quality of Life

#6380 Allows Construction of Serenity in Robotics
  code/modules/research/designs/circuits.dm
  code/modules/research/mechfab_designs.dm
  html/changelogs/mistyLuminescence - Serenity Unlocked.yml
Labels: Results To Be Reviewed

#6399 jenga log
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Mechoid - TTSandSign.yml
  html/changelogs/Nalarac - Bot Ion Storm.yml
  html/changelogs/Nalarac - Helmet Cameras.yml
  html/changelogs/Nalarac - Medibot.yml
  html/changelogs/Nalarac - Rechargers.yml
  html/changelogs/Nalarac - Sec Bot.yml
  html/changelogs/Nalarac - Supermatter Guide.yml
  html/changelogs/mistyLuminescence - Serenity Unlocked.yml
Labels: Changelog Update

#6390 Makes bot patrolling into a map var
  code/modules/mob/living/bot/bot.dm
  code/modules/mob/living/bot/cleanbot.dm
  code/modules/mob/living/bot/edCLNbot.dm
  code/modules/mob/living/bot/secbot.dm
  maps/~map_system/maps.dm
Labels: Feature Tweak

#6381 Fixes Mech Cable Layer
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/mecha/equipment/tools/medical_tools.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/mecha/mecha.dm
  html/changelogs/Nalarac - Cable Layer.yml
Labels: Bugfix

#6363 Remaps atmospherics
  html/changelogs/Atermonera - atmos remap.yml
  maps/southern_cross/southern_cross-1.dmm
Labels: Map Change / Issue

#6403 Fixes language runtime upon ai creation
  code/modules/mob/transform_procs.dm
Labels: Bugfix

#6405 Changes Hooligan Crab Meat to Crab Meat
  code/modules/mob/living/simple_mob/subtypes/animal/sif/hooligan_crab.dm
Labels: Oversight

#6406 Makes magic creation of carpotoxin via cooking impossible
  code/modules/food/food/snacks.dm
Labels: Oversight

#6408 Fixes ghost jump-to-mob
  code/modules/mob/dead/observer/observer.dm
Labels: Bugfix

#6402 Uniform Adjustments Phase 1
  code/datums/outfits/military/fleet.dm
  code/datums/outfits/military/marines.dm
  code/datums/outfits/military/sifguard.dm
  code/modules/clothing/under/accessories/storage.dm
  code/modules/clothing/under/accessories/torch.dm
  code/modules/clothing/under/solgov.dm
  html/changelogs/Woodrat - Uniform Fix.yml
  icons/mob/uniform.dmi
  icons/mob/uniform_rolled_down.dmi
  icons/mob/uniform_sleeves_rolled.dmi
  icons/mob/uniform_solgov.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/clothing/uniforms_solgov.dmi
  maps/submaps/surface_submaps/wilderness/GovPatrol.dmm
Labels: Refactor, Sprite Change

#6411 Makes the Create Object menu not freeze the client for an eternity
  html/create_object.html
Labels: Refactor

#6397 Blind rage doesn't mean actually make them blind.
  code/modules/mob/_modifiers/modifiers_misc.dm
Labels: Quality of Life

#6410 Promethean Organ Tweakening
  code/__defines/mobs.dm
  code/modules/mob/living/carbon/human/human_powers.dm
  code/modules/mob/living/carbon/human/species/station/prometheans.dm
  code/modules/mob/living/living.dm
  code/modules/organs/organ.dm
  code/modules/organs/subtypes/slime.dm
  html/changelogs/Mechoid - Promethean Organs.yml
  icons/obj/surgery.dmi
Labels: Feature

#6396 Chemistry Expansion
  code/datums/supplypacks/medical.dm
  code/game/machinery/atmoalter/portable_atmospherics.dm
  code/game/machinery/frame.dm
  code/game/objects/items/weapons/circuitboards/frame.dm
  code/modules/mob/_modifiers/medical.dm
  code/modules/reagents/Chemistry-Machinery.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Modifiers.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/distilling/Distilling-Recipes.dm
  code/modules/reagents/distilling/distilling.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_containers/patch.dm
  code/modules/reagents/reagent_containers/pill.dm
  icons/mob/radial.dmi
  icons/obj/chemical.dmi
  icons/obj/machines/reagent.dmi
  nano/templates/chem_master.tmpl
  polaris.dme
Labels: Feature

#6413 Fixes Exploration Vendor Bugs
  code/modules/catalogue/cataloguer.dm
  code/modules/mining/ore_redemption_machine/construction.dm
  code/modules/mining/ore_redemption_machine/survey_vendor.dm
Labels: Oversight

#6414 Rigsuit Typo Fix
  code/modules/clothing/spacesuits/rig/rig_attackby.dm
Labels: Bugfix

#6416 Fixes some missing sprites
  icons/mob/modular_armor.dmi
  icons/obj/clothing/modular_armor.dmi
  icons/obj/pda_rugged.dmi
Labels: Sprite Change

#6415 Adjusts some desk bell mechanics
  code/game/objects/items/bells.dm
  code/modules/materials/material_recipes.dm
  html/changelogs/Heroman3003 - bellfixes.yml
Labels: Feature Tweak

#6429 Fixes editing colony director IDs editing global 'station access' list
  code/game/antagonist/station/highlander.dm
  code/game/jobs/job/captain.dm
  code/game/objects/items/weapons/id cards/station_ids.dm
  code/modules/admin/verbs/debug.dm
Labels: Bugfix

#6424 Ports MREs from Baystation
  code/datums/supplypacks/misc.dm
  code/game/objects/items/trash.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/game/objects/items/weapons/storage/mre.dm
  code/game/objects/random/misc.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/food/food/condiment.dm
  code/modules/food/food/snacks.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/Chemistry-Recipes.dm
  html/changelogs/Novacat - MREs.yml
  icons/obj/food.dmi
  icons/obj/trash.dmi
  polaris.dme
Labels: Feature

#6428 glove attack refactor
  code/modules/clothing/clothing.dm
  code/modules/holodeck/HolodeckObjects.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/unarmed_attack.dm
Labels: Refactor

#6430 Refactors strangerocks not to be ore
  code/modules/mining/mine_turfs.dm
  code/modules/mob/living/simple_mob/subtypes/animal/space/worm.dm
  code/modules/xenoarcheaology/finds/finds.dm
Labels: Feature Tweak

#6431 Fixed air injectors
  code/ATMOSPHERICS/components/unary/outlet_injector.dm
Labels: Feature Tweak

#6432 Makes hull materials behave more uniformly
  code/modules/materials/materials.dm
Labels: Feature Tweak

#6433 Fixes one of the Cancel buttons on Spawn Character not working
  code/modules/admin/verbs/randomverbs.dm
Labels: Bugfix

#6434 Adds hardhats to engineering lockers
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
Labels: Feature

#6426 Fixes rig gauntlets runtime
  code/modules/clothing/gloves/gauntlets.dm
Labels: Bugfix
