Repository PolarisSS13/Polaris, pull requests merged in 2019-02, with the labels that each got.

#5881 Changes (R&D made) Saber SMG to Advanced SMG
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/research/designs/weapons.dm
  icons/obj/gun.dmi
Labels: Feature Tweak

#5846 Adds multiple organ-related chemicals.
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Feature

#5918 [READY] Fixes pixel projectiles critical bugs
  code/__defines/_planes+layers.dm
  code/__defines/flags.dm
  code/modules/mob/living/living_movement.dm
  code/modules/mob/mob_movement.dm
  code/modules/projectiles/projectile.dm
  polaris.dme
Labels: Bugfix

#5913 Readds access restrictions to supply computer
  code/game/machinery/computer/supply.dm
Labels: Bikeshed, Feature Tweak, Staff Request

#5910 Pilot consoles require pilot access
  html/changelogs/Anewbe - Pilots.yml
  maps/southern_cross/shuttles/crew_shuttles.dm
Labels: Feature Tweak, Staff Request

#5924 Stairs go up
  code/modules/multiz/structures.dm
  html/changelogs/ater_stairs.yml
Labels: Bugfix, Priority: High

#5925 Updates changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Anewbe - Pilots.yml
  html/changelogs/Mechoid - LingJacket.yml
  html/changelogs/Mechoid - Virtual and Alien Reality.yml
  html/changelogs/ater - sinks.yml
Labels: Changelog Update

#5920 Map Fixes and Tweaks
  code/game/machinery/doppler_array.dm
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-4.dmm
Labels: Bugfix, Feature Tweak, Map Change / Issue

#5926 Tweaks to Sword Cave PoI
  maps/submaps/surface_submaps/mountains/SwordCave.dmm
Labels: Point of Interest

#5922 reduces delay in printing from librarian computer
  code/modules/library/lib_machines.dm
Labels: Feature Tweak

#5869 Adds the Zaddat Race + Modifies pressure damage calculations
  code/__defines/chemistry.dm
  code/__defines/mobs.dm
  code/__defines/species_languages.dm
  code/datums/outfits/misc.dm
  code/datums/supplypacks/misc.dm
  code/datums/supplypacks/voidsuits.dm
  code/game/machinery/vending.dm
  code/game/objects/items/devices/flash.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
  code/game/objects/structures/loot_piles.dm
  code/modules/client/preference_setup/loadout/loadout_accessories.dm
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/spacesuits/rig/rig_pieces.dm
  code/modules/clothing/spacesuits/spacesuits.dm
  code/modules/clothing/spacesuits/void/zaddat.dm
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/food/food/lunch.dm
  code/modules/mob/language/station.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/human_species.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/pai/software_modules.dm
  code/modules/mob/living/silicon/robot/robot_modules/station.dm
  code/modules/mob/living/silicon/robot/robot_modules/syndicate.dm
  code/modules/mob/transform_procs.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/stylesheet.dm
  html/changelogs/zaddat.yml
  icons/mob/head.dmi
  icons/mob/human_races/r_def_zaddat.dmi
  icons/mob/human_races/r_zaddat.dmi
  icons/mob/mask.dmi
  icons/mob/spacesuit.dmi
  icons/mob/ties.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/spacesuits.dmi
  icons/obj/clothing/ties.dmi
  polaris.dme
Labels: Feature, Feature Tweak, Needs Announcement, Priority: Dev Freeze

#5886 Introduces caseless ammo, and a caseless rifle
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/ammunition/rounds.dm
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/guns/projectile/caseless.dm
  icons/mob/back.dmi
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
  icons/obj/ammo.dmi
  icons/obj/gun.dmi
  polaris.dme
Labels: Feature

#5907 Flash rebalance.
  code/game/machinery/recharger.dm
  code/game/objects/items/devices/flash.dm
  code/modules/mob/living/silicon/robot/robot_modules/station.dm
  html/changelogs/Mechoid - Flashes.yml
  icons/obj/device.dmi
Labels: Controversial, Forum Discussion in Progress

#5937 Updates changeling
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Mechoid - Flashes.yml
  html/changelogs/ater_stairs.yml
  html/changelogs/zaddat.yml
Labels: Changelog Update

#5936 Rigsuits use the correct pressure protection mechanism
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/spacesuits/rig/rig_pieces.dm
  html/changelogs/ater - rig pressurecooker.yml
Labels: Bugfix, Oversight

#5940 Fix a div/0.
  code/modules/projectiles/guns/energy.dm
Labels: Bugfix, Oversight

#5944 I shouldn't do math at 2 AM
  code/modules/projectiles/guns/energy.dm
Labels: Bugfix

#5947 Rewrites Atmospherics
  code/ZAS/Atom.dm
  code/__defines/atmos.dm
  code/game/gamemodes/meteor/meteors.dm
  code/game/machinery/OpTable.dm
  code/game/machinery/deployable.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/blast_door.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/machinery/iv_drip.dm
  code/game/mecha/mech_sensor.dm
  code/game/objects/effects/alien/aliens.dm
  code/game/objects/effects/chem/foam.dm
  code/game/objects/effects/spiders.dm
  code/game/objects/effects/zone_divider.dm
  code/game/objects/items/weapons/policetape.dm
  code/game/objects/structures/cliff.dm
  code/game/objects/structures/coathanger.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/coffin.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/gravemarker.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/inflatable.dm
  code/game/objects/structures/plasticflaps.dm
  code/game/objects/structures/railing.dm
  code/game/objects/structures/simple_doors.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/windoor_assembly.dm
  code/game/objects/structures/window.dm
  code/game/objects/structures/window_spawner.dm
  code/game/shuttle_engines.dm
  code/modules/blob/blob.dm
  code/modules/blob2/blobs/base_blob.dm
  code/modules/blob2/blobs/shield.dm
  code/modules/holodeck/HolodeckObjects.dm
  code/modules/hydroponics/trays/tray.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/living_movement.dm
  code/modules/power/antimatter/shielding.dm
  code/modules/power/fusion/fusion_particle_catcher.dm
  code/modules/power/turbine.dm
  code/modules/recycling/disposal.dm
  code/modules/shieldgen/directional_shield.dm
  code/modules/shieldgen/emergency_shield.dm
  code/modules/shieldgen/energy_field.dm
  code/modules/shieldgen/sheldwallgen.dm
  code/modules/tables/interactions.dm
Labels: Bugfix, Priority: Dev Freeze, Refactor

#5935 Nerfs Sonic Speed Wheelchair
  code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
Labels: Feature Tweak

#5946 i don't know how vending machines work
  code/game/machinery/vending.dm
Labels: Bugfix

#5951 Bugspeak is whitelisted
  code/modules/mob/language/station.dm
  html/changelogs/Anewbe - Bugspeak.yml
Labels: Bugfix

#5950 Fixes turrets, AI shooting, and makes mob AI shooting a little smarter.
  code/game/machinery/portable_turret.dm
  code/modules/ai/ai_holder_combat.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/trace.dm
Labels: Bugfix

#5953 Fixes the 'cannot push thing being pulled' bug and other weirdness.
  code/game/atoms_movable.dm
  code/modules/mob/living/living.dm
Labels: Bugfix

#5954 Makes aiming more clear for the target.
  code/modules/projectiles/targeting/targeting_overlay.dm
Labels: Feature Tweak

#5933 AI sprite tweaks.
  code/modules/mob/living/silicon/ai/icons.dm
  icons/mob/AI.dmi
Labels: Forum Discussion in Progress, Sprite Change

#5961 Fixed typo on name of RCON's output setting popup window
  code/modules/nano/modules/rcon.dm
Labels: Bugfix

#5965 Fix Organs not removing their verbs properly.
  code/modules/organs/organ.dm
Labels: Bugfix

#5949 Tweaks Daxons
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
  html/changelogs/Mechoid-DAXONS.yml
Labels: Feature Tweak

#5969 Fixes Diona and Promethean prosthetics.
  code/modules/organs/robolimbs.dm
Labels: Bugfix, Feature Tweak

#5966 Fixes blast door issue, and slimesky being considered unjustified.
  code/game/machinery/doors/blast_door.dm
  code/modules/ai/aI_holder_subtypes/slime_xenobio_ai.dm
  code/modules/mob/living/bot/secbot.dm
Labels: Bugfix

#5942 Headgibbing is a config thing
  code/controllers/configuration.dm
  code/modules/organs/subtypes/standard.dm
  config/example/game_options.txt
  html/changelogs/Anewbe - Headgibs.yml
Labels: Feature Tweak, Needs Announcement, Prepare to Die, Staff Request

#5962 Prevents people from joining with the same character
  code/modules/mob/new_player/new_player.dm
Labels: Feature Tweak, Requires Staff Input

#5972 fixes zaddat mask problem
  code/modules/clothing/masks/gasmask.dm
Labels: Bugfix

#5977 BTW I USE (FIXED) ARC
  code/modules/mob/living/simple_mob/combat.dm
  code/modules/mob/living/simple_mob/simple_mob.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/arc.dm
Labels: Refactor

#5975 Promethean tuning
  code/modules/mob/living/carbon/human/species/station/prometheans.dm
  html/changelogs/Anewbe - Prometheans.yml
Labels: Controversial, Feature Tweak

#5970 Moves crashed medical shuttle PoI to deep caves
  maps/submaps/surface_submaps/mountains/mountains.dm
Labels: Point of Interest

#5974 Fixes departmental teshari cloaks and coats
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
  code/modules/clothing/suits/aliens/seromi.dm
  code/modules/clothing/under/xenos/seromi.dm
  icons/mob/species/seromi/deptjacket.dmi
Labels: Bugfix
