Repository PolarisSS13/Polaris, pull requests merged in 2019-12, with the labels that each got.

#6518 Bookbinder 2, Boogaloo.
  code/modules/library/lib_machines.dm
Labels: Bugfix, Oversight

#6534 Multi-Z connectivity no longer limited by bit field
  code/modules/multiz/basic.dm
Labels: Feature Tweak

#6552 AIs properly use radios in shells, clerical gets command.
  code/modules/mob/living/silicon/robot/robot_modules/station.dm
Labels: Quality of Life

#6561 Gives appropriate hairstyles the hair_tieable flag.
  code/modules/mob/new_player/sprite_accessories.dm
Labels: Feature Tweak

#6565 Fixes species without eyecolor being able to get one
  code/modules/organs/organ_icon.dm
Labels: Bugfix

#6566 Fix Multitool Modes
  code/game/objects/items/devices/multitool.dm
Labels: Bugfix

#6567 EPv2 x Communicator fix.
  code/game/objects/items/devices/communicator/UI.dm
  code/game/objects/items/devices/communicator/messaging.dm
  code/modules/integrated_electronics/subtypes/input.dm
Labels: Bugfix

#6520 Clean up dead code obsoleted by outfit system
  code/datums/outfits/jobs/cargo.dm
  code/datums/outfits/jobs/civilian.dm
  code/datums/outfits/jobs/command.dm
  code/datums/outfits/jobs/engineering.dm
  code/datums/outfits/jobs/job.dm
  code/datums/outfits/jobs/medical.dm
  code/datums/outfits/jobs/science.dm
  code/datums/outfits/jobs/security.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/civilian_chaplain.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/jobs/job/silicon.dm
  code/game/jobs/job_controller.dm
  code/game/objects/items/weapons/id cards/station_ids.dm
  maps/southern_cross/job/outfits.dm
  maps/southern_cross/southern_cross_jobs.dm
Labels: Refactor, Unwanted Feature Removal

#6558 Change various global species lists to GLOB versions, adds 2 more event subspecies.
  code/__defines/mobs.dm
  code/_global_vars/lists/species.dm
  code/_helpers/global_lists.dm
  code/_helpers/mobs.dm
  code/game/antagonist/station/changeling.dm
  code/game/gamemodes/technomancer/spells/aura/fire_aura.dm
  code/game/gamemodes/technomancer/spells/aura/frost_aura.dm
  code/game/jobs/job_controller.dm
  code/game/machinery/bioprinter.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/structures/mirror.dm
  code/modules/admin/admin.dm
  code/modules/admin/secrets/fun_secrets/paintball_mode.dm
  code/modules/admin/topic.dm
  code/modules/admin/view_variables/topic.dm
  code/modules/blob2/overmind/types.dm
  code/modules/client/preference_setup/general/01_basic.dm
  code/modules/client/preference_setup/general/02_language.dm
  code/modules/client/preference_setup/general/03_body.dm
  code/modules/client/preference_setup/loadout/loadout.dm
  code/modules/client/preference_setup/preference_setup.dm
  code/modules/integrated_electronics/subtypes/input.dm
  code/modules/mob/language/language.dm
  code/modules/mob/living/bot/bot.dm
  code/modules/mob/living/carbon/alien/diona/diona.dm
  code/modules/mob/living/carbon/alien/diona/progression.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/appearance.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species/outsider/event.dm
  code/modules/mob/living/carbon/human/species/outsider/vox.dm
  code/modules/mob/living/carbon/human/species/species_getters.dm
  code/modules/mob/living/carbon/human/species/species_shapeshift.dm
  code/modules/mob/living/default_language.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/silicon/robot/drone/drone_say.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_mob/simple_mob.dm
  code/modules/mob/living/voice/voice.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/mob/new_player/preferences_setup.dm
  code/modules/mob/say.dm
  code/modules/organs/internal/voicebox.dm
  code/modules/organs/organ.dm
  code/modules/projectiles/projectile/change.dm
  code/modules/research/prosfab_designs.dm
  code/modules/virus2/admin.dm
  code/modules/virus2/disease2.dm
  polaris.dme
Labels: Priority: High, Refactor

#6571 Fix Supply_conversion.dm runtime.
  code/modules/gamemaster/actions/supply_conversion.dm
Labels: Bugfix, Priority: High

#6575 Adds 10 new clothes + sprite fixes.
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/human_face.dmi
  icons/mob/human_face_m.dmi
  icons/mob/ties.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprite Change

#6577 Examining power cells state their name and size
  code/modules/power/cell.dm
Labels: Bugfix

#6572 Buffs radiation so it isn't defeated by a thin sheet of lead.
  code/__defines/misc.dm
  code/controllers/configuration.dm
  code/controllers/subsystems/radiation.dm
  code/modules/radiation/radiation.dm
  config/example/config.txt
  html/changelogs/atermonera - rad_buff.yml
Labels: Bugfix, Priority: High

#6576 Moves custom books to main repo.
  code/modules/library/hardcode_library/fiction/APsychonaut.dm
  code/modules/library/hardcode_library/fiction/PortedBooks.dm
  code/modules/library/hardcode_library/fiction/battlefieldcommander.dm
  code/modules/library/hardcode_library/fiction/schnayy.dm
  code/modules/library/hardcode_library/non-fiction/PortedBooks.dm
  code/modules/library/hardcode_library/reference/PortedBooks.dm
  code/modules/library/hardcode_library/reference/Schnayy.dm
  code/modules/library/hardcode_library/religious/PortedBooks.dm
Labels: Feature Tweak

#6578 Add sanity check to cyborg _onclick.
  code/_onclick/cyborg.dm
Labels: Bugfix

#6569 Light Replacer QOL
  code/game/objects/items/devices/lightreplacer.dm
  html/changelogs/TheFurryFeline - Bulbs_Recycling.yml
Labels: Feature Tweak

#6573 Changelog! For the first time in weeks because school!
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Mechoid - Medical Expansion.yml
  html/changelogs/Nalarac - ED209.yml
  html/changelogs/Nalarac - Enables Headset Channels.yml
  html/changelogs/Nalarac - Protolathe.yml
  html/changelogs/PrismaticGynoid - GraffitiSelection.yml
  html/changelogs/TheFurryFeline - Lamps Light Lackluster.yml
  html/changelogs/TheFurryFeline - Mouse_Plushie_Sprite_Change.yml
  html/changelogs/TheFurryFeline - Orange_Is_The_New_Orange_Part_2.yml
  html/changelogs/TheFurryFeline - Strange Rock Fixy.yml
  html/changelogs/atermonera - maintdronetime.yml
  html/changelogs/novacat - teshariplush.yml
  html/changelogs/woodrat - Barkitchenmerge.yml
  html/changelogs/woodrat - mapbugfixes.yml
  html/changelogs/woodrat - mapbugfixesnov.yml
  html/changelogs/woodrat - mobsizeport.yml
Labels: Changelog Update

#6580 APCs/Air Alarms can be (un)locked via altclick
  code/game/machinery/alarm.dm
  code/modules/power/apc.dm
Labels: Quality of Life

#6581 Adds emergency shutters to the kitchen/bar/cryo-escape pod
  maps/southern_cross/southern_cross-1.dmm
Labels: Map Change / Issue

#6582 QM can now get optical meson scanners
  code/modules/client/preference_setup/loadout/loadout_eyes.dm
Labels: Feature Tweak

#6559 Coffee Shop Revamp
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
  code/modules/food/food/snacks.dm
  code/modules/food/kitchen/microwave.dm
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/dispenser/cartridge_presets.dm
  code/modules/reagents/dispenser/dispenser2_energy.dm
  code/modules/reagents/dispenser/dispenser_presets.dm
  html/changelogs/Cerebulon - Coffee Shop.yml
  icons/obj/food.dmi
  icons/obj/storage.dmi
  maps/southern_cross/southern_cross-1.dmm
Labels: Cannot Merge, Feature

#6583 Tweaks the fixed AO
  code/__defines/lighting.dm
Labels: Bugfix

#6584 Printable Spray Bottles
  code/datums/autolathe/general.dm
  code/modules/reagents/reagent_containers/spray.dm
  html/changelogs/TheFurryFeline - Print_Da_Sprayers.yml
Labels: Feature

#6585 Fixes gentle hairstyle missing
  code/modules/mob/new_player/sprite_accessories.dm
Labels: Oversight
