Repository PolarisSS13/Polaris, pull requests merged in 2019-03, with the labels that each got.

#5981 Handtele no longer relies on teleporter being mapped in in very specific way
  code/game/objects/items/weapons/teleportation.dm
Labels: Feature Tweak

#5986 Rings no longer cover ones hands
  code/modules/clothing/clothing.dm
  code/modules/clothing/rings/rings.dm
Labels: Bugfix

#5985 Subspace Jammer now blocks signalers, suit sensors, lasts longer
  code/datums/repositories/crew.dm
  code/datums/uplink/tools.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/game/objects/items/devices/radio/jammer.dm
  code/modules/assembly/signaler.dm
  html/changelogs/Anewbe - Jamming.yml
Labels: Feature Tweak, Staff Request

#5989 golegnahC setadpU
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Anewbe - Bugspeak.yml
  html/changelogs/Anewbe - Headgibs.yml
  html/changelogs/Anewbe - Prometheans.yml
  html/changelogs/Mechoid-DAXONS.yml
  html/changelogs/ater - rig pressurecooker.yml
  html/changelogs/kartagrafi-nockrobes.yml
Labels: Changelog Update

#5992 Departmental Turtlenecks
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/under/jobs/engineering.dm
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/clothing/under/jobs/security.dm
  html/changelogs/mistyLuminescence - turtlenecks.yml
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature

#5988 Copy character slots
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  html/changelogs/PrismaticGynoid - charactercopy.yml
Labels: Feature Tweak

#5991 Fixes drinks and adds new one.
  code/game/machinery/vending.dm
  code/modules/food/food/drinks/bottle.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/Chemistry-Recipes.dm
  icons/obj/drinks.dmi
Labels: Feature, Feature Tweak

#5993 Fixes the greatest bug to affect our time.
  code/modules/organs/robolimbs.dm
Labels: Bugfix

#5996 Fixed construction of fulltile electrochromic windows
  code/game/objects/structures/window.dm
Labels: Bugfix

#5978 Unpicks some mining spaghetti
  code/modules/mining/mine_items.dm
  code/modules/mining/mine_turfs.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
Labels: Feature Tweak, Refactor

#5994 Revert "Promethean tuning"
  code/modules/mob/living/carbon/human/species/station/prometheans.dm
Labels: Do Not Merge, Revert

#5995 Tweak & Fix Promethean Stuff
  code/modules/mob/living/carbon/human/species/station/prometheans.dm
Labels: Feature Tweak

#6006 Adds 3 new crashed escape pod PoIs
  code/modules/ai/aI_holder_subtypes/simple_mob_ai.dm
  html/changelogs/PrismaticGynoid - crashedescapepods.yml
  maps/submaps/surface_submaps/plains/Epod2.dmm
  maps/submaps/surface_submaps/plains/plains.dm
  maps/submaps/surface_submaps/plains/plains_areas.dm
  maps/submaps/surface_submaps/wilderness/Epod3.dmm
  maps/submaps/surface_submaps/wilderness/Epod4.dmm
  maps/submaps/surface_submaps/wilderness/wilderness.dm
  maps/submaps/surface_submaps/wilderness/wilderness_areas.dm
Labels: Point of Interest

#6018 Fixes elevators deleting AI eyes
  code/modules/turbolift/turbolift.dm
Labels: Bugfix

#5997 Beakers for Botany
  code/game/machinery/vending.dm
  code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm
  html/changelogs/mistyLuminescence - hydrobeakers.yml
Labels: Feature

#6020 protolathes actually ACTUALLY update properly
  code/modules/research/rdconsole.dm
Labels: Oversight

#6002 Belt-Worn RIGs
  code/modules/clothing/spacesuits/rig/modules/modules.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/spacesuits/rig/rig_attackby.dm
  code/modules/clothing/spacesuits/rig/rig_pieces.dm
  code/modules/clothing/spacesuits/rig/rig_verbs.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/surgery/other.dm
  html/changelogs/mistyLuminescence - beltrigs.yml
Labels: Needs Review, Refactor

#5998 Loadout item role tweaks
  code/modules/client/preference_setup/loadout/loadout_accessories.dm
  code/modules/client/preference_setup/loadout/loadout_eyes.dm
  code/modules/client/preference_setup/loadout/loadout_head.dm
  code/modules/client/preference_setup/loadout/loadout_shoes.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  html/changelogs/mistyLuminescence - loadoutroles.yml
Labels: Feature Tweak

#5999 Winter coat suit storage expansion
  code/modules/clothing/suits/hooded.dm
  html/changelogs/mistyLuminescence - wintercoats.yml
  maps/southern_cross/items/clothing/sc_suit.dm
Labels: Feature Tweak

#6019 Adds New Alert Levels
  code/__defines/gamemode.dm
  code/controllers/configuration.dm
  code/game/gamemodes/malfunction/newmalf_ability_trees/tree_networking.dm
  code/game/machinery/alarm.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/computer3/computers/communications.dm
  code/game/machinery/status_display.dm
  code/game/response_team.dm
  code/modules/admin/admin_verbs.dm
  code/modules/security levels/security levels.dm
  html/changelogs/Novacat - alarms.yml
  icons/obj/monitors.dmi
  icons/obj/status_display.dmi
Labels: Feature

#6021 Lynx Fixes Runtimes
  code/game/objects/effects/spawners/bombspawner.dm
  code/game/objects/items/weapons/tanks/jetpack.dm
  code/modules/food/food/cans.dm
  code/modules/food/food/drinks.dm
  code/modules/food/food/drinks/bottle.dm
  code/modules/food/food/snacks.dm
  code/modules/mob/living/carbon/human/human_species.dm
Labels: Bugfix
