Repository PolarisSS13/Polaris, pull requests merged in 2019-06, with the labels that each got.

#6183 Fixes some Precursotech oversights.
  code/game/objects/random/misc.dm
  code/modules/materials/material_sheets.dm
  code/modules/research/designs/precursor.dm
Labels: Oversight

#6188 Fix Puzzledoors not being locked when no lock is found.
  code/game/objects/structures/props/puzzledoor.dm
Labels: Oversight

#6197 loanchegg
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Heroman3003 - alarmaccess.yml
  html/changelogs/Heroman3003 - cameraccess.yml
  html/changelogs/Mechoid - Borers.yml
  html/changelogs/Mechoid - SifAnimalExpansion1.yml
  html/changelogs/Nalarac-OldIssues.yml
  html/changelogs/Novacat - Fucktimers.yml
  html/changelogs/Novacat - Laptoptweak.yml
  html/changelogs/chaoko99 - medibots.yml
  html/changelogs/chaoko99 - reconnect.yml
  html/changelogs/mistyLuminescence - bugfix.yml
  html/changelogs/mistyLuminescence - makeover.yml
  html/changelogs/mistyLuminescence - randomevents.yml
Labels: Changelog Update

#6218 Fixes random item spawners not self-deleting.
  code/game/objects/random/_random.dm
Labels: Bugfix

#6214 Fixes ghost-edge runtime
  code/modules/mob/mob_movement.dm
Labels: Bugfix

#6079 Augment Work
  code/__defines/damage_organs.dm
  code/__defines/mobs.dm
  code/modules/organs/internal/bioaugment.dm
  code/modules/organs/organ.dm
  icons/obj/surgery.dmi
  polaris.dme
Labels: Feature, Feature Tweak

#6216 Fixes the Chargeblade's tech cost.
  code/modules/research/designs/illegal.dm
Labels: Bugfix

#6199 Grey scale pills and colored pillbottles
  code/game/objects/items/contraband.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/modules/reagents/Chemistry-Machinery.dm
  code/modules/reagents/reagent_containers/pill.dm
  html/changelogs/Novacat - Colorablepill.yml
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/chemical.dmi
  nano/css/icons.css
Labels: Feature Tweak

#6215 THIS PR IS 7+ DAYS OLD, SEE #6203 . Energy-Swords and Changeling Melee Weapons Can Deflect Projectiles
  code/game/gamemodes/changeling/powers/armblade.dm
  code/game/objects/items/weapons/material/swords.dm
  code/game/objects/items/weapons/melee/deflect.dm
  code/game/objects/items/weapons/melee/energy.dm
  code/game/objects/items/weapons/shields.dm
  html/changelogs/Mechoid - Melee2RevengeoftheDeflect.yml
  polaris.dme
Labels: Feature Tweak

#6196 An assortment of Lighting Stuff
  code/__defines/lighting.dm
  code/game/objects/items/devices/lightreplacer.dm
  code/modules/lighting/lighting_corner.dm
  code/modules/lighting/lighting_source.dm
  code/modules/power/lighting.dm
  html/changelogs/Novacat - Lighting.yml
  maps/submaps/surface_submaps/mountains/deadBeacon.dmm
Labels: Feature Tweak

#6201 Adds Cider Bottles
  code/game/machinery/vending.dm
  code/modules/food/drinkingglass/metaglass.dm
  code/modules/food/food/drinks/bottle.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/dispenser/cartridge_presets.dm
  code/modules/reagents/dispenser/dispenser2_energy.dm
  code/modules/reagents/dispenser/dispenser_presets.dm
  code/modules/reagents/reagent_containers/borghydro.dm
  icons/obj/drinks.dmi
Labels: Feature

#6223 June Map Tweaks v2
  code/modules/power/lighting.dm
  html/changelogs/Woodrat - Map Tweaksv2.yml
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-3.dmm
  maps/southern_cross/southern_cross-6.dmm
  maps/southern_cross/southern_cross_areas.dm
Labels: Feature Tweak, Map Change / Issue

#6219 Tweaks the NewTM event system further
  code/__defines/misc.dm
  code/modules/gamemaster/actions/atmos_leak.dm
  code/modules/gamemaster/actions/electrified_door.dm
  code/modules/gamemaster/actions/planet_weather_change.dm
  code/modules/gamemaster/actions/spontaneous_appendicitis.dm
  code/modules/metric/activity.dm
  code/modules/metric/count.dm
  code/modules/metric/department.dm
  polaris.dme
Labels: Feature

#6208 Serenity
  code/game/mecha/combat/gygax.dm
  code/game/mecha/mecha_construction_paths.dm
  code/game/mecha/mecha_parts.dm
  code/game/mecha/mecha_wreckage.dm
  code/game/objects/items/weapons/circuitboards/mecha.dm
  code/modules/research/designs/circuits.dm
  code/modules/research/mechfab_designs.dm
  html/changelogs/mistyLuminescence - Serenity.yml
  icons/mecha/mech_construction.dmi
Labels: Do Not Merge, Feature

#6221 Head/chest/groin splints
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/stacks/medical.dm
  html/changelogs/mistyLuminescence - Splinting.yml
Labels: Feature Tweak

#6206 tinytweaks
  code/datums/autolathe/autolathe.dm
  code/datums/autolathe/engineering.dm
  code/datums/autolathe/general.dm
  code/game/machinery/autolathe.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/flora.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/outdoors/grass.dm
  code/modules/blob2/blobs/core.dm
  code/modules/mob/living/simple_animal/animals/cat.dm
  code/modules/mob/living/simple_mob/subtypes/animal/pets/cat.dm
  code/modules/power/supermatter/supermatter.dm
  html/changelogs/mistyLuminescence - tinytweaks.yml
  icons/mob/animal.dmi
  icons/obj/engine.dmi
Labels: Bugfix, Feature, Feature Tweak

#6224 Fix for some electronics buttons having the wrong label on their pulses.
  code/modules/integrated_electronics/subtypes/input.dm
Labels: Bugfix

#6226 Makes some alt. roboheads actually use their monitors
  code/modules/organs/robolimbs.dm
  icons/mob/monitor_icons.dmi
Labels: Bugfix

#6231 Fixes ghost jump-to-mob
  code/modules/mob/dead/observer/observer.dm
Labels: Bugfix

#6233 Adds Industrial turrets, and an industrial teleporter defense turret.
  code/game/machinery/portable_turret.dm
  icons/obj/turrets.dmi
Labels: Feature

#6236 Adds Precursor Tech to Research Debugging Device
  code/defines/obj/weapon.dm
Labels: Bugfix

#6235 Adds Material Scanner to Protolathe
  code/modules/research/designs/misc.dm
Labels: Bugfix

#6230 Adds two new alternate sprites for the detective's revolver.
  code/modules/projectiles/guns/projectile/revolver.dm
  icons/obj/gun.dmi
Labels: Feature Tweak

#6228 golegchan
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Mechoid - Melee2RevengeoftheDeflect.yml
  html/changelogs/Novacat - Colorablepill.yml
  html/changelogs/Novacat - Lighting.yml
  html/changelogs/TheFurryFeline - Infinite Frame Fixy.yml
  html/changelogs/Woodrat - Map Tweaks.yml
  html/changelogs/Woodrat - Map Tweaksv2.yml
  html/changelogs/mistyLuminescence - Serenity.yml
  html/changelogs/mistyLuminescence - Splinting.yml
  html/changelogs/mistyLuminescence - tinytweaks.yml
Labels: Changelog Update

#6238 QoL improvements for broken components
  code/game/objects/structures/loot_piles.dm
  code/modules/mob/living/silicon/robot/component.dm
  html/changelogs/Heroman3003 - Broken Components.yml
Labels: Feature Tweak

#6244 Fixes glucose crate spawning
  code/datums/supplypacks/medical.dm
  code/datums/supplypacks/misc.dm
  code/datums/supplypacks/recreation.dm
  code/datums/supplypacks/supply.dm
  code/datums/supplypacks/voidsuits.dm
Labels: Bugfix

#6246 Fixes construction of lights
  code/modules/power/lighting.dm
Labels: Bugfix
