Repository PolarisSS13/Polaris, pull requests merged in 2019-07, with the labels that each got.

#6120 Multi-Tile Objects, Multi-Tile Hovershuttle
  code/datums/riding.dm
  code/game/atoms_movable.dm
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/mecha/equipment/weapons/weapons.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_wreckage.dm
  code/game/mecha/medical/medical.dm
  code/game/mecha/space/hoverpod.dm
  code/game/mecha/space/shuttle.dm
  code/game/objects/effects/effect_system.dm
  code/modules/multi-tile/multi-tile.dm
  code/modules/projectiles/projectile.dm
  code/modules/vehicles/vehicle.dm
  icons/mecha/mecha64x64.dmi
  icons/obj/vehicles_64x64.dmi
  polaris.dme
Labels: Feature

#6248 Adds more GPS variety
  code/game/objects/items/devices/gps.dm
  code/modules/research/designs/misc.dm
  icons/obj/gps.dmi
  maps/southern_cross/southern_cross-3.dmm
Labels: Feature Tweak

#6249 Makes lead icon display stack
  code/modules/materials/material_sheets.dm
Labels: Bugfix

#6250 Allows to interact with turf itself in Turf tab
  code/modules/mob/mob.dm
Labels: Feature Tweak

#6251 Fixes retaliate mobs ignoring melee attacks
  code/modules/mob/living/living_defense.dm
Labels: Bugfix

#6253 Fixes deconstructed wall frames blocking passage
  code/game/machinery/machinery.dm
Labels: Bugfix

#6261 Fixes atmosphere targeted mutation editing wrong plant traits
  code/modules/hydroponics/seed_gene_mut.dm
Labels: Bugfix

#6259 Fixes ppflowers having no icon sometiems
  code/game/objects/structures/flora.dm
Labels: Bugfix

#6254 Fixes farmbot infinite looping
  code/modules/mob/living/bot/farmbot.dm
Labels: Bugfix

#6256 Fixes '1' message from MCs
  code/modules/modular_computers/file_system/program_events.dm
Labels: Bugfix

#6260 Properly splits security and engineering alarms
  code/modules/modular_computers/file_system/programs/engineering/alarm_monitor.dm
  code/modules/modular_computers/file_system/programs/security/alarm_monitor.dm
  polaris.dme
Labels: Feature Tweak

#6263 Nerfs Simple Doors
  code/game/objects/structures/simple_doors.dm
Labels: Bugfix, Oversight

#6265 Fixes technical cameras being affected by random event
  code/modules/events/camera_damage.dm
  code/modules/gamemaster/actions/camera_damage.dm
Labels: Bugfix

#6266 Flashes actually work as said on the tin.
  code/game/objects/items/devices/flash.dm
Labels: Bugfix, Oversight

#6268 Fixes aiming at z-shadows breaking aiming
  code/modules/projectiles/targeting/targeting_gun.dm
Labels: Bugfix

#6267 Fixes carpeted tables refunding wrong carpet type if nonstandard one was used
  code/modules/tables/tables.dm
Labels: Bugfix

#6270 Fixes invisible ventcrawlers
  code/modules/ventcrawl/ventcrawl.dm
Labels: Bugfix

#6242 Adds Arcane Tech to Cult Items
  code/game/gamemodes/cult/cult_items.dm
  code/game/gamemodes/cult/soulstone.dm
Labels: Feature Tweak, Requires Staff Input

#6262 Civilian Expansion 1: The Plantening
  code/game/objects/effects/chem/coating.dm
  code/modules/clothing/head/flowercrowns.dm
  code/modules/food/food/snacks.dm
  code/modules/food/recipes_microwave.dm
  code/modules/hydroponics/seed.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/seed_mobs.dm
  code/modules/hydroponics/seed_packets.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/Chemistry-Recipes.dm
  icons/obj/food.dmi
  icons/obj/food_ingredients.dmi
  icons/obj/hydroponics_growing.dmi
  icons/obj/hydroponics_products.dmi
  icons/obj/seeds.dmi
  polaris.dme
Labels: Feature

#6271 Un-Nerfs Odysseus Tools
  code/game/mecha/equipment/tools/medical_tools.dm
Labels: Feature Tweak, Requires Staff Input

#6273 changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Heroman3003 - Broken Components.yml
  html/changelogs/mistyLuminescence - POInames.yml
  html/changelogs/mistyLuminescence - newcrates.yml
  html/changelogs/mistyLuminescence - zruntime.yml
Labels: Changelog Update

#6252 Fixes ghost riders
  code/modules/vehicles/bike.dm
Labels: Bugfix

#6277 Actually adds the new seeds to the vendors.
  code/modules/hydroponics/seed_packets.dm
  code/modules/hydroponics/seed_storage.dm
Labels: Oversight

#6269 MC camera and access fixes and adjustments
  code/__defines/machinery.dm
  code/game/machinery/camera/presets.dm
  code/modules/integrated_electronics/subtypes/output.dm
  code/modules/modular_computers/file_system/programs/command/card.dm
  code/modules/modular_computers/file_system/programs/generic/camera.dm
  maps/northern_star/northern_star_defines.dm
  maps/southern_cross/southern_cross_defines.dm
  maps/~map_system/maps.dm
Labels: Feature Tweak

#6280 Fixes Nurse Spider Feeding
  code/modules/ai/ai_holder_targeting.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/nurse.dm
Labels: Bugfix, Mob AI Issue

#6281 Mapfixesv3
  html/changelogs/maptweaksv3 - Woodrat.yml
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-3.dmm
  maps/southern_cross/southern_cross-6.dmm
Labels: Map Change / Issue

#6282 Try to fix slimes and Prometheans.
  code/modules/ai/aI_holder_subtypes/slime_xenobio_ai.dm
Labels: Bugfix

#6286 Patches Glitterflies
  code/modules/mob/living/simple_mob/subtypes/animal/sif/glitterfly.dm
Labels: Lore, Oversight

#6287 Allows Set Transfer Amounts of 250 and 500 for Reagent Cartridges
  code/modules/reagents/dispenser/cartridge.dm
Labels: Feature

#6272 Mining Expansion, the Diggening.
  code/_helpers/mobs.dm
  code/game/mecha/combat/combat.dm
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/objects/items/weapons/explosives.dm
  code/game/objects/items/weapons/grenades/spawnergrenade.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/spacesuits/rig/modules/combat.dm
  code/modules/clothing/spacesuits/rig/modules/ninja.dm
  code/modules/clothing/spacesuits/rig/modules/vision.dm
  code/modules/mining/drilling/scanner.dm
  code/modules/mining/ore_redemption_machine/equipment_vendor.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/viscerator.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/ward/monitor_ward.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/recycling/disposal.dm
  code/modules/research/mechfab_designs.dm
  icons/mecha/mecha_equipment.dmi
  icons/mob/critter.dmi
  icons/mob/eyes.dmi
  icons/obj/clothing/glasses.dmi
Labels: Feature, Feature Tweak, Prepare to Die

#6297 Nalarac's Farmbot Tweak
  code/modules/mob/living/bot/farmbot.dm
  html/changelogs/TheFurryFeline - Nalarac's Farmbot Tweak.yml
Labels: Feature Tweak

#6298 Fixes Plant Produced Stacks
  code/modules/hydroponics/seed.dm
Labels: Bugfix

#6245 The great rock update.
  code/game/objects/structures/ledges.dm
  code/modules/mining/mine_outcrops.dm
  code/modules/mining/mine_turfs.dm
  icons/obj/ledges.dmi
  icons/obj/outcrop.dmi
  icons/turf/flooring/asteroid.dmi
  icons/turf/walls.dmi
  polaris.dme
Labels: Feature

#6306 Fixes Razor Drones and Sentry Drones.
  code/modules/mob/living/simple_mob/subtypes/mechanical/viscerator.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/ward/monitor_ward.dm
Labels: Oversight

#6310 Emitters Hit Blob Again
  code/modules/blob2/overmind/overmind.dm
Labels: Bugfix

#6311 Melee Mobs Can Attack with Pointblank
  code/modules/ai/ai_holder_combat.dm
Labels: Bugfix

#6284 fixes communicator weather app's air reading
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/communicator/helper.dm
  nano/templates/atmospheric_scan.tmpl
  nano/templates/pda.tmpl
Labels: Bugfix

#6313 itty bitty changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/TheFurryFeline - Nalarac's Farmbot Tweak.yml
  html/changelogs/maptweaksv3 - Woodrat.yml
Labels: Changelog Update

#6308 Fixes some kitchen screwery
  code/modules/food/recipes_microwave.dm
  code/modules/hydroponics/seed_datums.dm
Labels: Bugfix

#6314 Corrects Mining Vendor Entries
  code/modules/mining/ore_redemption_machine/equipment_vendor.dm
Labels: Bugfix

#6315 Replaces Promethean Mouse with Food
  code/modules/mob/living/carbon/human/species/station/prometheans.dm
Labels: Feature Tweak

#6316 Makes rigpieces phoron immune
  code/modules/clothing/shoes/magboots.dm
  code/modules/clothing/spacesuits/rig/rig_pieces.dm
Labels: Bugfix, Oversight

#6320 Allows Multiple Light Printing in Autolathe
  code/datums/autolathe/autolathe.dm
  code/datums/autolathe/general.dm
  code/game/machinery/autolathe.dm
Labels: Feature

#6321 Allows Longer Visible Text on Beakers
  code/modules/reagents/reagent_containers/glass.dm
Labels: Feature Tweak

#6290 Adds Submunition projectiles, and a laser gun showcasing them.
  code/game/machinery/portable_turret.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/scatter.dm
  icons/obj/energygun.dmi
  polaris.dme
Labels: Feature

#6304 Adds Ripley Speedboost Equipment
  code/game/mecha/equipment/tools/tools.dm
  code/modules/research/mechfab_designs.dm
  html/changelogs/Nalarac - Ripley Speed Booster.yml
Labels: Feature

#6279 Pipe Clamps, Shutoff Valves, and Leaking Tubes, oh my.
  code/ATMOSPHERICS/components/shutoff.dm
  code/ATMOSPHERICS/datum_pipe_network.dm
  code/ATMOSPHERICS/datum_pipeline.dm
  code/ATMOSPHERICS/pipes/he_pipes.dm
  code/ATMOSPHERICS/pipes/manifold.dm
  code/ATMOSPHERICS/pipes/manifold4w.dm
  code/ATMOSPHERICS/pipes/pipe_base.dm
  code/ATMOSPHERICS/pipes/simple.dm
  code/ATMOSPHERICS/pipes/universal.dm
  code/game/machinery/atmoalter/clamp.dm
  code/game/machinery/pipe/pipe_recipes.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  html/changelogs/Mechoid - Leaky Pipes.yml
  icons/atmos/clamp.dmi
  polaris.dme
Labels: Bikeshed, Feature, Prepare to Die

#6303 Combat Mechs Can Punch More Things
  code/_onclick/other_mobs.dm
  code/game/gamemodes/cult/cult_structures.dm
  code/game/machinery/atmoalter/canister.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/deployable.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/portable_turret.dm
  code/game/mecha/combat/combat.dm
  code/game/mecha/mecha.dm
  code/game/objects/effects/alien/aliens.dm
  code/game/objects/structures/catwalk.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/inflatable.dm
  code/game/objects/structures/railing.dm
  code/game/objects/structures/simple_doors.dm
  code/game/objects/structures/window.dm
  code/game/turfs/simulated/walls.dm
  code/modules/modular_computers/computers/modular_computer/damage.dm
  code/modules/modular_computers/hardware/_hardware.dm
  code/modules/organs/organ.dm
  code/modules/power/lighting.dm
  code/modules/shieldgen/energy_field.dm
  code/modules/tables/tables.dm
  code/modules/vehicles/vehicle.dm
  html/changelogs/Nalarac - Combat Mech Punch.yml
Labels: Feature

#6339 Shutoff valves now behave like other valves.
  code/ATMOSPHERICS/components/shutoff.dm
  icons/obj/pipe-item.dmi
Labels: Bugfix, Oversight, Priority: CRITICAL

#6344 Manifolds now obey the laws of pipes.
  code/ATMOSPHERICS/pipes/manifold.dm
  code/ATMOSPHERICS/pipes/manifold4w.dm
Labels: Bugfix, Priority: CRITICAL

#6341 Adds automatic shutoff valves to distro
  maps/southern_cross/southern_cross-1.dmm
Labels: Map Change / Issue, Priority: CRITICAL

#6347 Cyborgs Can See and Repair Holes in Ceiling
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot_modules/station.dm
  html/changelogs/Nalarac - Cyborg Meson.yml
Labels: Feature Tweak

#6343 Fixes Integrated Circuit Printer Taking Fractions of a Sheet
  code/modules/integrated_electronics/core/printer.dm
  html/changelogs/Nalarac- Circuit Intake.yml
Labels: Bugfix

#6330 Fixes fishing vendor's name
  code/game/machinery/vending.dm
Labels: Bugfix, Oversight

#6325 Fixes Repairing Bots
  code/modules/mob/living/bot/bot.dm
  html/changelogs/Nalarac - Bot Repairing.yml
Labels: Feature

#6329 Adds Specialized SMES Coils to Suppy Console
  code/datums/supplypacks/engineering.dm
  html/changelogs/Nalarac - SMES Coil.yml
Labels: Feature

#6335 Bar Sign Changes
  html/changelogs/Schnayy - Bar Signs.yml
  icons/obj/barsigns.dmi
Labels: Sprite Change

#6331 Makes Husking Require More Burn
  code/modules/mob/living/carbon/human/human_damage.dm
  html/changelogs/Nalarac - Husking.yml
Labels: Feature Tweak

#6324 Adds Laser Tag Turrets Plus Changes
  code/datums/supplypacks/recreation.dm
  code/game/machinery/portable_turret.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/reagents/reagent_dispenser.dm
  code/modules/xenoarcheaology/tools/coolant_tank.dm
  html/changelogs/Nalarac - Turret Tweaks.yml
  icons/obj/turrets.dmi
Labels: Bugfix, Feature

#6352 Changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Mechoid - Leaky Pipes.yml
  html/changelogs/Mechoid - SLED.yml
  html/changelogs/Nalarac - Bot Repairing.yml
  html/changelogs/Nalarac - Combat Mech Punch.yml
  html/changelogs/Nalarac - Cyborg Meson.yml
  html/changelogs/Nalarac - Husking.yml
  html/changelogs/Nalarac - Ripley Speed Booster.yml
  html/changelogs/Nalarac - SMES Coil.yml
  html/changelogs/Nalarac - Turret Tweaks.yml
  html/changelogs/Nalarac- Circuit Intake.yml
  html/changelogs/Schnayy - Bar Signs.yml
  html/changelogs/Schnayy - Clothing Pack.yml
Labels: Changelog Update

#6351 Fixes 3 appearing to blind people when surgery table is used
  code/game/machinery/OpTable.dm
Labels: Bugfix, Higgs Bugson

#6349 Fixes the metamorphic glass sprite for the B-52
  code/modules/food/drinkingglass/metaglass.dm
Labels: Bugfix

#6353 Adds shutoff valve monitor
  code/ATMOSPHERICS/components/shutoff.dm
  code/game/machinery/computer/shutoff_monitor.dm
  code/game/objects/items/weapons/circuitboards/computer/computer.dm
  code/modules/research/designs/circuits.dm
  html/changelogs/Atermonera - Shutoff monitor.yml
  maps/southern_cross/southern_cross-1.dmm
  nano/css/shared.css
  nano/templates/shutoff_monitor.tmpl
  polaris.dme
Labels: Feature, Map Change / Issue, Priority: High

#6328 Makes Heavy-Duty Cell Chargers Constructable
  code/game/machinery/cell_charger.dm
  code/game/machinery/frame.dm
  code/game/machinery/recharger.dm
  code/game/objects/items/weapons/circuitboards/frame.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/modules/xenobio/items/weapons.dm
  html/changelogs/Nalarac - Rechargers.yml
  icons/obj/stock_parts.dmi
Labels: Feature

#6350 Fixes picking up ore after ripley digging
  code/game/mecha/equipment/tools/tools.dm
Labels: Bugfix

#6354 Adds proper miss chance for stabbing people in the eyes.
  code/game/objects/items.dm
  code/modules/mob/mob_helpers.dm
Labels: Bugfix

#6360 chagelong
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Atermonera - Shutoff monitor.yml
Labels: Changelog Update
