Repository PolarisSS13/Polaris, pull requests merged in 2019-05, with the labels that each got.

#6147 Fixes emergency pods not working
  code/controllers/emergency_shuttle_controller.dm
Labels: Bugfix

#6113 Fishing!
  code/game/turfs/simulated/water.dm
  code/modules/fishing/fishing.dm
  code/modules/fishing/fishing_net.dm
  code/modules/fishing/fishing_rod.dm
  code/modules/food/food/snacks.dm
  code/modules/materials/material_recipes.dm
  code/modules/mining/ore_redemption_machine/equipment_vendor.dm
  code/modules/mob/holder.dm
  code/modules/mob/living/simple_mob/subtypes/animal/passive/crab.dm
  code/modules/mob/living/simple_mob/subtypes/animal/passive/fish.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
  code/modules/reagents/Chemistry-Recipes.dm
  html/changelogs/Mechoid - Fishing.yml
  icons/mob/fish.dmi
  icons/mob/items/lefthand_holder.dmi
  icons/mob/items/lefthand_material.dmi
  icons/mob/items/righthand_holder.dmi
  icons/mob/items/righthand_material.dmi
  icons/obj/food.dmi
  icons/obj/items.dmi
  icons/obj/weapons.dmi
  polaris.dme
Labels: Feature, Feature Tweak

#6156 changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Mechoid - Fishing.yml
  html/changelogs/Novacat - accessories.yml
  html/changelogs/Novacat - medalsribbons.yml
  html/changelogs/Novacat - modularcomputers.yml
  html/changelogs/Novacat - nanochemistry.yml
  html/changelogs/Novacat - shortwave.yml
Labels: Changelog Update

#6161 Fixes access restriction for MC atmos control
  code/modules/modular_computers/file_system/programs/engineering/atmos_control.dm
Labels: Bugfix

#6164 Ports character setup subsystem from Bay.
  code/__defines/subsystems.dm
  code/controllers/subsystems/character_setup.dm
  code/game/verbs/ignore.dm
  code/modules/admin/admin_verbs.dm
  code/modules/client/preferences_toggle_procs.dm
  code/modules/client/ui_style.dm
  code/modules/mob/mob.dm
  code/modules/mob/new_player/new_player.dm
  polaris.dme
Labels: Priority: CRITICAL

#6167 Fixes some bugs with laptop
  code/modules/modular_computers/computers/subtypes/dev_laptop.dm
Labels: Bugfix

#6166 Lets sec people carry holoprojectors in their belts
  code/game/objects/items/weapons/storage/belt.dm
Labels: Feature Tweak

#6038 Sif Animal Expansion 1
  code/game/objects/items/glassjar.dm
  code/modules/ai/ai_holder_targeting.dm
  code/modules/mob/_modifiers/modifiers_misc.dm
  code/modules/mob/holder.dm
  code/modules/mob/living/simple_mob/simple_mob.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/duck.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/frostfly.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/glitterfly.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/kururak.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/leech.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/racoon.dm
  code/modules/projectiles/projectile/blob.dm
  html/changelogs/Mechoid - SifAnimalExpansion1.yml
  icons/mob/64x64.dmi
  icons/mob/animal.dmi
  icons/mob/modifier_effects.dmi
  polaris.dme
Labels: Feature, Point of Interest

#6170 Big Bugfix Bonanza
  code/game/machinery/computer/camera.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/recharger.dm
  code/game/mecha/equipment/tools/medical_tools.dm
  code/game/objects/items/weapons/circuitboards/computer/camera_monitor.dm
  code/game/objects/items/weapons/circuitboards/computer/computer.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/spacesuits/void/zaddat.dm
  code/modules/mob/living/bot/secbot.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/organs/organ_external.dm
  html/changelogs/mistyLuminescence - bugfix.yml
Labels: Bugfix

#6084 Borers TLC 1
  code/modules/mob/living/simple_mob/subtypes/animal/borer/borer.dm
  html/changelogs/Mechoid - Borers.yml
Labels: Feature Tweak

#6172 Makeover Kit
  code/datums/supplypacks/contraband.dm
  code/datums/uplink/stealth_items.dm
  code/game/objects/items/weapons/cosmetics.dm
  code/game/objects/items/weapons/storage/wallets.dm
  html/changelogs/mistyLuminescence - makeover.yml
Labels: Feature, Needs Review

#6154 Sif Trees and Icon Scaling
  code/game/atoms_movable.dm
  code/game/objects/structures/flora/trees.dm
  code/game/objects/structures/loot_piles.dm
  code/modules/mob/_modifiers/modifiers.dm
  code/modules/mob/_modifiers/modifiers_misc.dm
  code/modules/mob/_modifiers/traits.dm
  code/modules/mob/_modifiers/unholy.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/slime/subtypes.dm
  code/modules/mob/living/simple_mob/subtypes/animal/pets/bird.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/hooligan_crab.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/shantak.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/hivebot/ranged_damage.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/hivebot/tank.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/mecha/adv_dark_gygax.dm
  code/modules/mob/living/simple_mob/subtypes/occult/constructs/juggernaut.dm
  code/modules/mob/living/simple_mob/subtypes/slime/feral/feral.dm
  code/modules/projectiles/projectile/arc.dm
  icons/obj/flora/deadtrees.dmi
Labels: Refactor, Sprite Change

#6182 No More Pre-Roundstart Events
  code/modules/events/event_container.dm
  html/changelogs/mistyLuminescence - randomevents.yml
Labels: Bugfix

#6169 Ports Radial Menus
  code/__defines/_planes+layers.dm
  code/__defines/misc.dm
  code/_helpers/_lists.dm
  code/_onclick/hud/radial.dm
  code/_onclick/hud/radial_persistent.dm
  code/game/objects/items/bells.dm
  code/modules/materials/material_recipes.dm
  icons/mob/radial.dmi
  icons/obj/items.dmi
  polaris.dme
  sound/effects/deskbell.ogg
  sound/effects/deskbell_rude.ogg
Labels: Feature
