Repository PolarisSS13/Polaris, pull requests merged in 2019-01, with the labels that each got.

#5807 Fixes a typo that broke the saketini recipe
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
Labels: Oversight

#5809 Allows Prometheans to choose Sol Common as a language.
  code/modules/mob/living/carbon/human/species/station/prometheans.dm
Labels: Bugfix, Oversight

#5806 Fixes #5780
  code/modules/mob/living/simple_mob/subtypes/slime/slime.dm
  html/changelogs/Mechoid-Slimefix.yml
Labels: Bugfix

#5790 Drop the number of shots of normal and sec-xeno tasers back down to 5.
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/xenobio/items/weapons.dm
  html/changelogs/Mechoid-Tasers.yml
Labels: Feature Tweak

#5793 Upgrades SDQL2 and refactors it to a datum
  code/__defines/_tick.dm
  code/__defines/flags.dm
  code/_global_vars/mobs.dm
  code/_helpers/game.dm
  code/_helpers/global_lists.dm
  code/_helpers/time.dm
  code/_helpers/unsorted.dm
  code/controllers/subsystems/inactivity.dm
  code/controllers/subsystems/vote.dm
  code/datums/datumvars.dm
  code/game/gamemodes/game_mode.dm
  code/game/verbs/advanced_who.dm
  code/game/verbs/ignore.dm
  code/game/verbs/ooc.dm
  code/game/verbs/who.dm
  code/modules/admin/DB ban/functions.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_ranks.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/callproc/callproc.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/SDQL.dm
  code/modules/admin/verbs/SDQL2/SDQL_2.dm
  code/modules/admin/verbs/SDQL2/SDQL_2_parser.dm
  code/modules/admin/verbs/SDQL2/SDQL_2_wrappers.dm
  code/modules/admin/verbs/SDQL_2.dm
  code/modules/admin/verbs/SDQL_2_parser.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/verbs/getlogs.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/client/client procs.dm
  code/modules/mob/living/silicon/pai/admin.dm
  code/modules/mob/mob.dm
  code/modules/random_map/drop/droppod.dm
  code/world.dm
  polaris.dme
Labels: Refactor

#5816 Guns should once again let people know that they've been fired
  code/modules/projectiles/gun.dm
Labels: Bugfix, Priority: High

#5812 Fixes lift and shuttle moves not updating lighting
  code/_helpers/unsorted.dm
Labels: Bugfix

#5796 Adds New PoI Features + Bonus PoI
  code/game/atoms_movable.dm
  code/game/objects/effects/map_effects/effect_emitter.dm
  code/game/objects/effects/map_effects/map_effects.dm
  code/game/objects/effects/mines.dm
  code/game/objects/effects/step_triggers.dm
  code/game/objects/objs.dm
  code/game/objects/random/unidentified/medicine.dm
  code/game/objects/structures.dm
  code/game/objects/structures/cliff.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/signs.dm
  code/game/turfs/simulated/lava.dm
  code/game/turfs/simulated/outdoors/grass.dm
  code/game/turfs/simulated/outdoors/outdoors.dm
  code/game/turfs/simulated/water.dm
  code/game/turfs/turf.dm
  code/game/turfs/turf_changing.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/shoes/boots.dm
  code/modules/mob/_modifiers/modifiers_misc.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_mob/defense.dm
  code/modules/vehicles/vehicle.dm
  code/modules/xenoarcheaology/finds/misc.dm
  icons/effects/effects.dmi
  icons/mob/feet.dmi
  icons/mob/modifier_effects.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/decals.dmi
  icons/obj/fence.dmi
  icons/obj/flora/rocks.dmi
  icons/obj/mining.dmi
  icons/turf/areas.dmi
  icons/turf/outdoors.dmi
  maps/plane/plane-1.dmm
  maps/southern_cross/southern_cross_defines.dm
  maps/submaps/surface_submaps/mountains/lava_trench.dmm
  maps/submaps/surface_submaps/mountains/mountains.dm
  maps/submaps/surface_submaps/mountains/mountains_areas.dm
  polaris.dme
Labels: Feature, Point of Interest

#5835 Updates Religion Lists + Adds Religious Paraphernalia
  code/game/jobs/job/civilian_chaplain.dm
  code/game/objects/items/godfigures.dm
  code/game/objects/items/weapons/candle.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/client/preferences_factions.dm
  html/changelogs/Cerebulon - ReligionUpdate.yml
  icons/obj/candle.dmi
  icons/obj/chaplain.dmi
  polaris.dme
Labels: Feature

#5838 Fixes a couple of tiny glasses bugs
  code/modules/client/preference_setup/loadout/loadout_eyes.dm
  code/modules/clothing/glasses/glasses.dm
  icons/mob/eyes.dmi
Labels: Bugfix

#5851 Fix Technomancer Refunding
  code/game/gamemodes/technomancer/catalog.dm
Labels: Bugfix, Oversight

#5840 protolathe screen updates mat cost with better manips
  code/modules/research/rdconsole.dm
Labels: Bugfix

#5843 Adds Gibberish
  code/__defines/species_languages.dm
  code/modules/mob/language/generic.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/say.dm
  code/modules/mob/say.dm
  html/changelogs/Anewbe - Gibberish.yml
Labels: Feature

#5845 Adds three more crates
  code/datums/supplypacks/hydroponics.dm
  code/datums/supplypacks/misc.dm
Labels: Feature

#5841 Voice changer tweaks and fixes
  code/modules/clothing/masks/voice.dm
  code/modules/mob/living/carbon/human/say.dm
  html/changelogs/Anewbe - Voice Changers.yml
Labels: Bugfix, Feature, Feature Tweak, Staff Request

#5853 changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Anewbe - Gibberish.yml
  html/changelogs/Anewbe - Voice Changers.yml
  html/changelogs/Atermonera-pressure_protection.yml
  html/changelogs/Cerebulon - ReligionUpdate.yml
  html/changelogs/Eguns - Anewbe.yml
Labels: Changelog Update

#5858 Suit coolers don't overheat in vacuum
  code/game/objects/items/devices/suit_cooling.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  html/changelogs/atermonera_suit_cooling.yml
Labels: Bugfix

#5856 Fixes candle sprites
  code/game/objects/items/weapons/candle.dm
Labels: Bugfix

#5859 Audible emotes can be used again
  code/modules/mob/language/generic.dm
  code/modules/mob/language/language.dm
Labels: Bugfix, Priority: CRITICAL

#5849 Fixes a few mob AI bugs
  code/modules/ai/aI_holder_subtypes/simple_mob_ai.dm
  code/modules/ai/ai_holder_communication.dm
  code/modules/ai/ai_holder_targeting.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/hooligan_crab.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/savik.dm
Labels: Bugfix, Needs Review, Requires Developer Input

#5870 Borgs can use audible emotes again
  code/modules/mob/living/silicon/silicon.dm
Labels: Bugfix, Priority: CRITICAL

#5872 Stasis bags don't murder patients
  code/game/objects/items/bodybag.dm
  code/game/objects/items/weapons/tanks/tank_types.dm
  code/game/objects/items/weapons/tanks/tanks.dm
  code/game/objects/structures/crates_lockers/closets.dm
  html/changelogs/Ater - stasisbags.yml
Labels: Bugfix, Feature Tweak, Priority: CRITICAL

#5883 Fixes the disaster I caused with VV
  code/__defines/typeids.dm
  code/__defines/vv.dm
  code/datums/datumvars.dm
  code/modules/admin/callproc/callproc.dm
  code/modules/admin/view_variables/modify_variables.dm
  code/modules/admin/view_variables/view_variables.dm
Labels: Bugfix, Priority: CRITICAL

#5885 Bots don't speak gibberish
  code/modules/mob/language/language.dm
  code/modules/mob/living/bot/bot.dm
  code/modules/mob/living/say.dm
  html/changelogs/ater_botspeak.yml
Labels: Bugfix, Priority: CRITICAL

#5852 Adds a better debug controller verb that can target all controllers/processes/mc/failsafe/config/etc
  code/_helpers/type2type.dm
  code/controllers/verbs.dm
Labels: Feature, Staff Request

#5889 Allows borgs to move up and down with jetpacks
  code/modules/mob/living/silicon/robot/robot_movement.dm
  code/modules/multiz/movement.dm
Labels: Oversight

#5894 Fixes Some Mob Init Bugs
  code/modules/mob/living/carbon/human/human_species.dm
  code/modules/mob/mob.dm
Labels: Bugfix, Priority: CRITICAL

#5895 Fixes some AI bugs.
  code/modules/ai/aI_holder_subtypes/slime_xenobio_ai.dm
  code/modules/ai/ai_holder_combat.dm
  code/modules/ai/ai_holder_targeting.dm
  code/modules/mob/living/simple_mob/subtypes/slime/xenobio/defense.dm
Labels: Bugfix, Priority: CRITICAL

#5900 Rig helmets are now airtight when they should be, rather than when they shouldn't
  code/modules/clothing/spacesuits/rig/rig.dm
Labels: Bugfix, Oversight

#5898 Removes the hyphen from default language keys, should make people spew gibberish less
  code/controllers/configuration.dm
  config/example/config.txt
  html/changelogs/Anewbe - Yet More Gibberish.yml
Labels: Bugfix, Priority: High

#5903 changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Anewbe - Yet More Gibberish.yml
  html/changelogs/Ater - stasisbags.yml
  html/changelogs/Cerebulon -Teshrigs.yml
  html/changelogs/ater_botspeak.yml
  html/changelogs/atermonera_suit_cooling.yml
Labels: Changelog Update, Priority: High

#5893 Additional Hair
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
  icons/mob/human_face_m.dmi
Labels: Feature

#5896 Changeling & Straight Jacket modifications.
  code/game/gamemodes/changeling/powers/escape_restraints.dm
  code/game/gamemodes/changeling/powers/revive.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/mob/living/carbon/human/human_resist.dm
  code/modules/mob/living/carbon/resist.dm
  html/changelogs/Mechoid - LingJacket.yml
  polaris.dme
Labels: Feature Tweak, Oversight

#5901 Unclogs powersink drains
  code/controllers/subsystems/machines.dm
  code/game/objects/items/devices/powersink.dm
  html/changelogs/ater - sinks.yml
Labels: Bugfix, Staff Request

#5897 Fixes some circuit bugs.
  code/modules/integrated_electronics/core/assemblies.dm
  code/modules/integrated_electronics/passive/power.dm
  code/modules/integrated_electronics/subtypes/output.dm
  code/modules/integrated_electronics/subtypes/time.dm
  icons/obj/integrated_electronics/electronic_components.dmi
Labels: Bugfix

#5906 Gives the auto shotgun a new sprite
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  icons/obj/ammo.dmi
  icons/obj/gun.dmi
Labels: Sprite Change

#5877 Unfucks Vintage Rifle
  code/modules/projectiles/guns/projectile/boltaction.dm
Labels: Feature Tweak

#5905 Woops I misse dit, removes the forced announce from atom proccall
  code/modules/admin/callproc/callproc.dm
Labels: Oversight, Staff Request

#5912 Mechs can travel to the mines again
  code/game/objects/effects/step_triggers.dm
Labels: Bugfix, Priority: High

#5908 January News Update
  code/modules/lore_codex/news_data/main.dm
Labels: Lore

#5909 AFK Kicker stores AI cores
  code/controllers/subsystems/inactivity.dm
Labels: Feature Tweak
