Repository PolarisSS13/Polaris, pull requests merged in 2020-02, with the labels that each got.

#6656 Prettifies closet contents list with (newly added) countable variant of english_list
  code/_helpers/_lists.dm
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Feature Tweak, Refactor

#6658 Teshari Poncho Fix
  code/modules/clothing/under/accessories/clothing.dm
Labels: Bugfix

#6661 Fixes killer tomato mutation
  code/modules/hydroponics/seed_datums.dm
Labels: Bugfix

#6643 changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/TheFurryFeline - Changeling_Item_Name-Desc-Fixy.yml
  html/changelogs/TheFurryFeline - Light_Frame_Infinite_Steel_Fixy.yml
  html/changelogs/TheFurryFeline - Typo_Fixy_Again.yml
  html/changelogs/schnayy-glitterfly_borg.yml
Labels: Changelog Update

#6657 Unregulated passive regulators don't limit flow
  code/ATMOSPHERICS/components/binary_devices/passive_gate.dm
  html/changelogs/atermonera - unregulatorinator.yml
Labels: Feature Tweak

#6660 Shutoff valves actually find leaks before they decide to close
  code/ATMOSPHERICS/components/shutoff.dm
Labels: Bugfix, Feature Tweak

#6653 Changes DBCore connection procs to check for config value SQL_ENABLED instead of ENABLE_STAT_TRACKING
  code/defines/procs/dbcore.dm
Labels: Feature Tweak, Higgs Bugson

#6664 Adds some toys to the loadout
  code/game/objects/items/toys.dm
  code/modules/client/preference_setup/loadout/loadout_general.dm
  html/changelogs/PrismaticGynoid - loadouttoys.yml
Labels: Feature

#6669 Fix issues introduced by the world server icon system port.
  code/modules/clothing/clothing.dm
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Bugfix, Priority: High

#6665 2020 Civilian Wing Overhaul
  code/game/machinery/holosign.dm
  code/game/machinery/neonsign.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/modules/food/drinkingglass/glass_boxes.dm
  html/changelogs/woodrat-civilianmapfix.yml
  icons/obj/furniture.dmi
  icons/obj/library.dmi
  icons/obj/neonsigns.dmi
  icons/obj/sofas.dmi
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-6.dmm
  maps/southern_cross/southern_cross_areas.dm
  polaris.dme
Labels: Map Change / Issue

#6673 Fixes Jumpskirt Sprites
  code/modules/clothing/under/shorts.dm
Labels: Oversight, Priority: High

#6676 Fix frame deconstruction bugs
  code/game/machinery/frame.dm
Labels: Bugfix

#6677 ATMs can now be emagged
  code/modules/economy/ATM.dm
Labels: Bugfix

#6662 Stunbatons will now only harmbaton on grab/harm intents
  code/game/objects/items/weapons/stunbaton.dm
  html/changelogs/ShadowQuill-Baton_Intent_Change.yml
Labels: Feature Tweak

#6675 Logs graffiti and crayon drawings: Non-Cursed PR
  code/controllers/configuration.dm
  code/game/objects/items/crayons.dm
  config/example/config.txt
Labels: Feature

#6667 Prevents surgery from being done while wearing a voidsuit
  code/_onclick/item_attack.dm
  code/modules/surgery/bones.dm
  code/modules/surgery/encased.dm
  code/modules/surgery/external_repair.dm
  code/modules/surgery/face.dm
  code/modules/surgery/generic.dm
  code/modules/surgery/implant.dm
  code/modules/surgery/neck.dm
  code/modules/surgery/organs_internal.dm
  code/modules/surgery/other.dm
  code/modules/surgery/robotics.dm
  code/modules/surgery/surgery.dm
  html/changelogs/heroman3003 - voidsuti-surgery.yml
Labels: Needs Changelog

#6666 Applies same restrictions as first aid to external synth repair
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/stacks/nanopaste.dm
  code/game/objects/items/weapons/tools/weldingtool.dm
  code/modules/power/cable.dm
  html/changelogs/heroman3003 - synthpair-fix.yml
Labels: Feature Tweak

#6684 Very low levels of radiation are no longer harmful
  code/modules/mob/living/carbon/human/life.dm
  html/changelogs/atermonera - rad_tweaks.yml
Labels: Feature Tweak

#6687 Shutoff monitoring console remotely controls valves
  code/game/machinery/computer/shutoff_monitor.dm
  html/changelogs/Atermonera - Shutoff_monitor.yml
  nano/templates/shutoff_monitor.tmpl
Labels: Feature

#6685 Unmaps distro pressure regulators
  maps/southern_cross/southern_cross-1.dmm
Labels: Map Change / Issue

#6659 Metamorphic Pint Glass
  code/game/machinery/vending.dm
  code/modules/food/drinkingglass/metaglass.dm
  icons/obj/drinks.dmi
Labels: Feature

#6689 cash registers and retail scanners show transaction totals on examine
  code/modules/economy/cash_register.dm
  code/modules/economy/retail_scanner.dm
Labels: Quality of Life

#6682 Adds pineapple pizza box
  code/datums/supplypacks/hospitality.dm
  code/game/objects/random/misc.dm
  code/modules/food/food/snacks.dm
Labels: Feature

#6668 Changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/PrismaticGynoid - loadouttoys.yml
  html/changelogs/atermonera - preset_printers.yml
  html/changelogs/atermonera - unregulatorinator.yml
  html/changelogs/schnayy-bookcart.yml
Labels: Changelog Update

#6691 Fixes runtime in frame.dm, line 509: Cannot read null.len
  code/game/machinery/frame.dm
Labels: Bugfix, Priority: Medium

#6693 Fixes mining borg ore box movement astral sorcery
  code/modules/mining/mine_turfs.dm
  code/modules/mining/ore_box.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_movement.dm
  polaris.dme
Labels: Bugfix

#6707 Fixes broken tool usability logic
  code/_onclick/item_attack.dm
  code/modules/surgery/surgery.dm
Labels: Bugfix, Priority: CRITICAL

#6695 changelog!
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Atermonera - Shutoff_monitor.yml
  html/changelogs/ShadowQuill-Baton_Intent_Change.yml
  html/changelogs/atermonera - rad_tweaks.yml
  html/changelogs/heroman3003 - synthpair-fix.yml
  html/changelogs/heroman3003 - voidsuti-surgery.yml
  html/changelogs/woodrat-civilianmapfix.yml
Labels: Changelog Update

#6711 Revert "Fix runtime in helper.dm,92"
  code/game/objects/items/devices/communicator/helper.dm
Labels: Bugfix, Priority: CRITICAL

#6690 Fixes to Modular Computers and NTNet Relays
  code/game/objects/items/weapons/circuitboards/machinery/research.dm
  code/modules/modular_computers/NTNet/NTNet.dm
  code/modules/modular_computers/NTNet/NTNet_relay.dm
  code/modules/modular_computers/computers/modular_computer/core.dm
  code/modules/modular_computers/file_system/computer_file.dm
  code/modules/modular_computers/hardware/_hardware.dm
  code/modules/modular_computers/hardware/network_card.dm
  html/changelogs/leshana - vplk-ntnet-fixer.yml
Labels: Bugfix

#6703 Don't talk to strangers
  code/modules/admin/verbs/randomverbs.dm
Labels: Oversight

#6709 [Bugfix?] Bat Attack Spelling Fixy
  code/modules/mob/living/simple_mob/subtypes/animal/space/bats.dm
Labels: Oversight

#6712 Fix to_chat typo
  code/modules/admin/newbanjob.dm
Labels: Oversight

#6714 Renames Make All Areas (Un)Powered secret
  code/modules/admin/secrets/fun_secrets/make_all_areas_powered.dm
  code/modules/admin/secrets/fun_secrets/make_all_areas_unpowered.dm
  code/modules/admin/secrets/fun_secrets/power_failure_begin.dm
  code/modules/admin/secrets/fun_secrets/power_failure_end.dm
  polaris.dme
Labels: Refactor

#6702 Changed food sprites
  icons/obj/food.dmi
  icons/obj/food_ingredients.dmi
Labels: Sprite Change

#6697 Fixes missing sprites on forensic scanner
  code/modules/detectivework/tools/scanner.dm
  icons/obj/device.dmi
Labels: Bugfix, Sprite Change

#6710 Ports precision placement of items
  code/_onclick/click.dm
  code/_onclick/item_attack.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/id cards/cards.dm
  code/game/objects/items/weapons/material/ashtray.dm
  code/game/objects/items/weapons/material/shards.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/game/objects/items/weapons/storage/misc.dm
  code/game/objects/items/weapons/storage/toolbox.dm
  code/game/objects/items/weapons/tools/screwdriver.dm
  code/game/objects/items/weapons/tools/wirecutters.dm
  code/game/objects/items/weapons/traps.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/stool_bed_chair_nest/stools.dm
  code/game/turfs/simulated/floor_attackby.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/clothing/spacesuits/spacesuits.dm
  code/modules/clothing/suits/bio.dm
  code/modules/food/food.dm
  code/modules/food/food/cans.dm
  code/modules/food/food/condiment.dm
  code/modules/food/food/snacks.dm
  code/modules/games/cards.dm
  code/modules/materials/material_sheets.dm
  code/modules/mining/coins.dm
  code/modules/mining/ore.dm
  code/modules/mob/holder.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/living.dm
  code/modules/modular_computers/computers/modular_computer/variables.dm
  code/modules/projectiles/ammunition.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_containers/spray.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/research/research.dm
  code/modules/tables/interactions.dm
  code/modules/xenoarcheaology/sampling.dm
  html/changelogs/Cerebulon - precisionplacement.yml
Labels: Feature

#6728 Carbon mobs can be attacked again
  code/_onclick/click.dm
  code/_onclick/item_attack.dm
Labels: Oversight, Priority: CRITICAL

#6701 Hide items in plant pots and plushies
  code/game/machinery/vending.dm
  code/game/objects/items/tailoring.dm
  code/game/objects/items/toys.dm
  code/game/objects/structures/flora.dm
  icons/obj/items.dmi
  polaris.dme
Labels: Feature

#6717 Fixes Mint Apple Sparkle having a recipe, but no drink
  code/modules/food/drinkingglass/metaglass.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  icons/obj/drinks.dmi
Labels: Oversight

#6718 Added two chemical spill PoIs + More Immersive PoI Names
  code/game/objects/items/poi_items.dm
  code/game/turfs/simulated/water.dm
  html/changelogs/Cerebulon - ChemPoIs.yml
  maps/submaps/surface_submaps/plains/chemspill1.dmm
  maps/submaps/surface_submaps/plains/plains.dm
  maps/submaps/surface_submaps/plains/plains_areas.dm
  maps/submaps/surface_submaps/wilderness/chemspill2.dmm
  maps/submaps/surface_submaps/wilderness/wilderness.dm
  maps/submaps/surface_submaps/wilderness/wilderness_areas.dm
Labels: Point of Interest

#6720 Helmet Camera Moved Tabs
  code/modules/clothing/spacesuits/spacesuits.dm
  html/changelogs/Nalarac - Helmet Camera.yml
Labels: Quality of Life

#6721 Updated corgi icon
  icons/mob/animal.dmi
Labels: Sprite Change

#6723 Creates a preference for precise item placement
  code/modules/client/preference_setup/global/setting_datums.dm
  code/modules/client/preferences_toggle_procs.dm
  code/modules/tables/interactions.dm
Labels: Feature Tweak

#6726 Adds holster, lighter, and seatbelt sounds from World Server.
  code/game/objects/buckling.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/modules/clothing/under/accessories/holster.dm
  sound/effects/seatbelt.ogg
  sound/items/holsterin.ogg
  sound/items/holsterout.ogg
  sound/items/lighter_off.ogg
  sound/items/lighter_on.ogg
  sound/items/zippo_off.ogg
  sound/items/zippo_on.ogg
Labels: Feature Tweak

#6727 Adds a *dwoop emote
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/silicon/robot/emote.dm
  sound/machines/dwoop.ogg
Labels: Feature

#6729 Fix and tweak station Railguns.
  code/datums/supplypacks/munitions.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/projectiles/guns/magnetic/magnetic_railgun.dm
  code/modules/research/designs/weapons.dm
Labels: Feature Tweak

#6730 Fixes sprites for Ablative & Bulletproof modular armour
  code/modules/clothing/under/accessories/armor.dm
  icons/mob/modular_armor.dmi
Labels: Bugfix, Sprite Change

#6731 Adds individual modular armour crates, tweaks old prices
  code/datums/supplypacks/security.dm
Labels: Feature

#6734 Removes deadringer cloak exploit
  code/modules/mob/living/carbon/human/human_helpers.dm
Labels: Feature Tweak

#6736 Grass sprites are new and improved, from Paradise
  icons/turf/flooring/grass.dmi
  icons/turf/floors.dmi
Labels: Sprite Change

#6737 Makes pen click when you click on them
  code/game/objects/items/crayons.dm
  code/modules/paperwork/pen.dm
  sound/items/penclick.ogg
Labels: Feature Tweak

#6722 Fixes MCs not being rechargable
  code/game/machinery/recharger.dm
  code/modules/modular_computers/computers/modular_computer/power.dm
  code/modules/modular_computers/hardware/battery_module.dm
Labels: Bugfix

#6719 Adds an In-game Feedback System
  code/__defines/_protect.dm
  code/__defines/misc.dm
  code/__defines/sqlite_defines.dm
  code/__defines/subsystems.dm
  code/_helpers/unsorted.dm
  code/controllers/configuration.dm
  code/controllers/subsystems/sqlite.dm
  code/datums/managed_browsers/_managed_browser.dm
  code/datums/managed_browsers/feedback_form.dm
  code/datums/managed_browsers/feedback_viewer.dm
  code/modules/admin/admin_verbs.dm
  code/modules/mob/new_player/new_player.dm
  code/unit_tests/sqlite_tests.dm
  config/example/config.txt
  config/example/sqlite_feedback_pepper.txt
  html/changelogs/neerti-feedback_system.yml
  polaris.dme
Labels: Feature

#6735 Fixes custom table placement
  code/modules/tables/interactions.dm
Labels: Oversight

#6733 Readd some AI features and improve AI buildmode
  code/__defines/_planes+layers.dm
  code/__defines/mobs.dm
  code/global.dm
  code/modules/admin/verbs/buildmode.dm
  code/modules/ai/aI_holder_subtypes/simple_mob_ai.dm
  code/modules/ai/aI_holder_subtypes/slime_xenobio_ai.dm
  code/modules/ai/ai_holder.dm
  code/modules/ai/ai_holder_combat.dm
  code/modules/ai/ai_holder_combat_unseen.dm
  code/modules/ai/ai_holder_communication.dm
  code/modules/ai/ai_holder_cooperation.dm
  code/modules/ai/ai_holder_targeting.dm
  code/modules/client/client procs.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_mob/simple_mob.dm
  code/modules/mob/mob_planes.dm
  code/modules/xenobio/items/slimepotions.dm
  icons/misc/buildmode.dmi
  polaris.dme
Labels: Feature

#6740 Adds orange and yellow cloth materials
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/modules/materials/material_recipes.dm
  code/modules/materials/materials.dm
Labels: Feature

#6742 Better spriters for liquid dispensers
  code/game/machinery/ai_slipper.dm
  icons/obj/device.dmi
Labels: Sprite Change

#6747 Changes Pigs in a Blanket recipe
  code/modules/food/recipes_microwave.dm
Labels: Feature Tweak

#6749 Adds 1 pixel layer of alpha surrounding rods & rod-based weapons
  icons/obj/stacks.dmi
  icons/obj/weapons.dmi
Labels: Sprite Change

#6744 Adds holoPDA from Aurora
  code/_helpers/global_lists.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/client/preference_setup/general/04_equipment.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/new_player/preferences_setup.dm
  html/changelogs/lorilili - Holographic-PDA.yml
  icons/obj/pda_holo.dmi
Labels: Feature

#6743 Keekenox's vents + scrubbers 2.0
  icons/atmos/vent_pump.dmi
  icons/atmos/vent_scrubber.dmi
  icons/obj/atmospherics/vent_pump.dmi
  icons/obj/atmospherics/vent_scrubber.dmi
  icons/obj/pipe-item.dmi
Labels: Sprite Change

#6752 Defibrilators can be charged in rechargers
  code/game/machinery/recharger.dm
  code/game/objects/items/devices/defib.dm
  html/changelogs/lorilili - defib.yml
Labels: Feature Tweak

#6755 Devs can now View Feedback
  code/datums/managed_browsers/feedback_viewer.dm
  code/modules/admin/admin_verbs.dm
Labels: Oversight

#6756 Fixes various lightning strike bugs
  code/controllers/subsystems/planets.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/verbs/lightning_strike.dm
  code/modules/power/tesla/energy_ball.dm
  maps/southern_cross/southern_cross_defines.dm
  maps/~map_system/maps.dm
Labels: Bugfix

#6758 [Oversight] Orion Trail Grammar Fixy
  code/game/machinery/computer/arcade.dm
Labels: Oversight

#6754 Handholding
  code/modules/mob/living/carbon/human/human_attackhand.dm
Labels: Controversial, Feature

#6760 Adds 'warble' emote for Skrell
  code/modules/mob/living/carbon/human/emote.dm
  html/changelogs/lorilili - warble.yml
  sound/effects/warble.ogg
  sound/machines/dwoop.ogg
Labels: Feature

#6745 Removes Toy Story
  icons/obj/toy.dmi
Labels: Sprite Change

#6746 Pretty airlock_machines and meter sprites taken from CEV Eris
  icons/obj/airlock_machines.dmi
  icons/obj/meter.dmi
Labels: Sprite Change

#6765 Brainmechs can use guns again.
  code/game/mecha/equipment/weapons/weapons.dm
  code/game/mecha/mecha_helpers.dm
  polaris.dme
Labels: Bugfix

#6713 Fixes communicator newsfeed app.
  code/game/machinery/newscaster.dm
  code/game/objects/items/devices/communicator/UI.dm
  code/game/objects/items/devices/communicator/communicator.dm
  code/game/objects/items/devices/communicator/helper.dm
  nano/templates/communicator.tmpl
Labels: Bugfix, Priority: Medium
