Repository PolarisSS13/Polaris, pull requests merged in 2020-03, with the labels that each got.

#6766 changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Cerebulon - ChemPoIs.yml
  html/changelogs/Cerebulon - precisionplacement.yml
  html/changelogs/Nalarac - Helmet Camera.yml
  html/changelogs/leshana - vplk-ntnet-fixer.yml
  html/changelogs/lorilili - Holographic-PDA.yml
  html/changelogs/lorilili - defib.yml
  html/changelogs/lorilili - warble.yml
  html/changelogs/neerti-feedback_system.yml
Labels: Changelog Update

#6770 High-priority Job Display
  code/modules/mob/new_player/new_player.dm
  code/modules/mob/new_player/preferences_setup.dm
Labels: Feature

#6772 Fixes a teshari mining undercoat
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
Labels: Bugfix

#6774 Sprite fixes
  code/modules/food/food/snacks.dm
  icons/mob/ears.dmi
  icons/mob/hud.dmi
  icons/mob/species/seromi/ears.dmi
  icons/obj/drinks.dmi
Labels: Sprite Change

#6778 Let them finally eat cake
  code/modules/food/food/snacks.dm
  code/modules/food/food/thecake.dm
  code/modules/food/recipes_microwave.dm
  code/modules/hydroponics/seed_datums.dm
Labels: Bugfix

#6751 Ports tgstation bloodpack sprites
  icons/obj/bloodpack.dmi
Labels: Sprite Change

#6768 Salvageable machines
  code/game/objects/items/trash_material.dm
  code/game/objects/structures/salvageable.dm
  icons/obj/material_trash.dmi
  icons/obj/salvageable.dmi
  polaris.dme
  sound/machines/shutdown.ogg
Labels: Feature

#6787 Trains try to talk to nobody on init
  code/modules/vehicles/train.dm
Labels: Oversight

#6789 Moving AI busy check so it's performed less and more centrally
  code/controllers/subsystems/ai.dm
  code/modules/ai/ai_holder.dm
Labels: Optimization

#6767 Exosuit Expansion: Return of the Ripley
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/mecha/equipment/mecha_equipment_dynamicprocs.dm
  code/game/mecha/equipment/tools/armor_melee.dm
  code/game/mecha/equipment/tools/armor_ranged.dm
  code/game/mecha/equipment/tools/hardpoint_actuator.dm
  code/game/mecha/equipment/tools/inflatables.dm
  code/game/mecha/equipment/tools/passenger.dm
  code/game/mecha/equipment/tools/powertool.dm
  code/game/mecha/equipment/tools/weldinglaser.dm
  code/game/mecha/equipment/weapons/defense/shocker.dm
  code/game/mecha/mecha.dm
  code/game/objects/items/weapons/tools/weldingtool.dm
  code/modules/mob/_modifiers/fire.dm
  code/modules/mob/_modifiers/modifiers_misc.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/research/mechfab_designs.dm
  html/changelogs/mechoid - exoexpansion.yml
  icons/mecha/mecha_equipment.dmi
  polaris.dme
Labels: Feature

#6792 Boring minor things
  code/game/objects/effects/map_effects/perma_light.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/stool_bed_chair_nest/stools.dm
  code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
  code/modules/power/powernet.dm
  code/modules/power/smes.dm
Labels: Feature Tweak, Refactor

#6793 Fixes shuttle emergency locker sprites
  code/game/objects/structures/crates_lockers/closets/walllocker.dm
  icons/obj/walllocker.dmi
Labels: Bugfix, Sprite Change

#6795 Makes pregame time a config setting
  code/controllers/configuration.dm
  code/game/gamemodes/gameticker.dm
  config/example/config.txt
Labels: Feature Tweak

#6798 Ports Rollerbed Sprites from Vore
  icons/obj/rollerbed.dmi
Labels: Sprite Change

#6796 Oct-Feb News Update
  code/modules/lore_codex/news_data/main.dm
Labels: Lore

#6797 Fixed menthol cigarette runtime
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
Labels: Bugfix

#6800 Allows Spiderlings to be Stomped
  code/game/objects/effects/spiders.dm
Labels: Feature

#6803 Cooking adjustments
  code/datums/supplypacks/supply.dm
  code/game/machinery/vending.dm
  code/modules/food/food/condiment.dm
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  html/changelogs/schnayy - cooking adjustments.yml
  icons/obj/food.dmi
Labels: Feature Tweak, Sprite Change

#6812 Gives +MOD the traitor panel and colorable OOC.
  code/modules/admin/admin_verbs.dm
Labels: Oversight, Priority: CRITICAL

#6805 Ports Inactivity SS from Bay
  code/controllers/subsystems/inactivity.dm
Labels: Bugfix, Higgs Bugson

#6807 QoL: Comms Consoles
  code/game/machinery/computer/communications.dm
  code/game/machinery/status_display.dm
  code/modules/modular_computers/file_system/programs/command/comm.dm
  code/modules/security levels/security levels.dm
Labels: Quality of Life

#6786 Stabilizer stabilizes stably
  code/game/machinery/oxygen_pump.dm
Labels: Feature Tweak

#6725 Job description alt
  code/_macros.dm
  code/datums/outfits/jobs/civilian.dm
  code/game/jobs/job/_alt_title.dm
  code/game/jobs/job/assistant.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/civilian_chaplain.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/jobs/job/silicon.dm
  code/game/jobs/job_controller.dm
  code/modules/client/preference_setup/occupation/occupation.dm
  maps/southern_cross/southern_cross_jobs.dm
  polaris.dme
Labels: Feature, Needs Changelog

#6775 Robotics Expansion: RIG-ged and Ready
  code/__defines/misc.dm
  code/game/mecha/mech_fabricator.dm
  code/game/mecha/mech_prosthetics.dm
  code/modules/clothing/spacesuits/rig/modules/specific/ai_container.dm
  code/modules/clothing/spacesuits/rig/modules/specific/chem_dispenser.dm
  code/modules/clothing/spacesuits/rig/modules/specific/cleaner_launcher.dm
  code/modules/clothing/spacesuits/rig/modules/specific/cloak.dm
  code/modules/clothing/spacesuits/rig/modules/specific/datajack.dm
  code/modules/clothing/spacesuits/rig/modules/specific/device.dm
  code/modules/clothing/spacesuits/rig/modules/specific/electrowarfare.dm
  code/modules/clothing/spacesuits/rig/modules/specific/grenade_launcher.dm
  code/modules/clothing/spacesuits/rig/modules/specific/inhand_fabricator.dm
  code/modules/clothing/spacesuits/rig/modules/specific/jetpack.dm
  code/modules/clothing/spacesuits/rig/modules/specific/metalfoam_launcher.dm
  code/modules/clothing/spacesuits/rig/modules/specific/mounted_gun.dm
  code/modules/clothing/spacesuits/rig/modules/specific/powersink.dm
  code/modules/clothing/spacesuits/rig/modules/specific/self_destruct.dm
  code/modules/clothing/spacesuits/rig/modules/specific/sprinter.dm
  code/modules/clothing/spacesuits/rig/modules/specific/teleporter.dm
  code/modules/clothing/spacesuits/rig/modules/specific/vision.dm
  code/modules/clothing/spacesuits/rig/modules/specific/voice.dm
  code/modules/clothing/spacesuits/rig/modules/utility.dm
  code/modules/clothing/spacesuits/rig/suits/robotics.dm
  code/modules/materials/fifty_spawner_mats.dm
  code/modules/materials/material_sheets.dm
  code/modules/materials/materials.dm
  code/modules/mining/ore_datum.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/projectiles/guns/energy/temperature.dm
  code/modules/research/circuitprinter.dm
  code/modules/research/mechfab_designs.dm
  code/modules/research/protolathe.dm
  html/changelogs/mechoid - RoboticsRigs.yml
  icons/mob/head.dmi
  icons/mob/rig_back.dmi
  icons/mob/spacesuit.dmi
  icons/mob/species/seromi/back.dmi
  icons/mob/species/seromi/head.dmi
  icons/mob/species/seromi/suit.dmi
  icons/mob/species/skrell/helmet.dmi
  icons/mob/species/skrell/suit.dmi
  icons/mob/species/tajaran/helmet.dmi
  icons/mob/species/tajaran/suit.dmi
  icons/mob/species/unathi/helmet.dmi
  icons/mob/species/unathi/suit.dmi
  icons/obj/rig_modules.dmi
  polaris.dme
Labels: Feature

#6801 PDA Boops when you button
  code/game/objects/items/devices/PDA/PDA.dm
  sound/machines/pda_click.ogg
Labels: Feature

#6802 Adds more machine button sounds
  code/game/machinery/Sleeper.dm
  code/game/machinery/alarm.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/cryo.dm
  code/game/machinery/jukebox.dm
  code/game/machinery/spaceheater.dm
  code/game/machinery/vending.dm
  code/game/machinery/washing_machine.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/food/kitchen/microwave.dm
  code/modules/power/apc.dm
  code/modules/power/smes.dm
  code/modules/reagents/dispenser/dispenser2.dm
  html/changelogs/Cerebulon - machinesounds.yml
  sound/machines/buttonbeep.ogg
  sound/machines/id_swipe.ogg
Labels: Feature

#6790 Water -> Wet
  code/game/turfs/simulated/water.dm
  html/changelogs/Aronai - wateriswet.yml
Labels: Feature

#6811 Deluxe microwave sprites work
  code/modules/food/kitchen/microwave.dm
  icons/obj/deluxemicrowave.dmi
  icons/obj/kitchen.dmi
Labels: Bugfix, Sprite Change

#6818 Fully Implements R_EVENT for Event Managers
  code/controllers/subsystems/vote.dm
  code/datums/managed_browsers/feedback_viewer.dm
  code/datums/mind.dm
  code/game/jobs/whitelist.dm
  code/game/verbs/ooc.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminjump.dm
  code/modules/admin/verbs/antag-ooc.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/verbs/grief_fixers.dm
  code/modules/admin/verbs/pray.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/admin/view_variables/topic.dm
  code/modules/client/preference_setup/general/03_body.dm
  code/modules/client/preference_setup/global/01_ui.dm
  code/modules/client/preference_setup/global/setting_datums.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/appearance.dm
  code/modules/mob/living/silicon/pai/admin.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_helpers.dm
  code/modules/modular_computers/computers/modular_computer/interaction.dm
  code/modules/modular_computers/file_system/program.dm
  code/modules/nano/interaction/admin.dm
  code/modules/paperwork/faxmachine.dm
  code/modules/virus2/admin.dm
  config/example/admin_ranks.txt
Labels: Bugfix, Priority: High

#6781 Tweak Station-Railguns
  code/modules/projectiles/guns/magnetic/magnetic_railgun.dm
  code/modules/projectiles/projectile/magnetic.dm
Labels: Feature Tweak, Staff Request

#6785 Prosthetic Expansion: Advent of Species
  code/game/mecha/mech_prosthetics.dm
  code/modules/mob/living/carbon/human/human_powers.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/organs/organ_icon.dm
  code/modules/organs/robolimbs.dm
  code/modules/organs/subtypes/diona.dm
  code/modules/research/designs/circuits/disks.dm
  code/modules/research/prosfab_designs.dm
  code/modules/surgery/robotics.dm
  icons/mob/human_races/cyberlimbs/nanotrasen/nanotrasen_tajaran.dmi
  icons/mob/human_races/cyberlimbs/nanotrasen/nanotrasen_unathi.dmi
  icons/mob/human_races/cyberlimbs/unbranded/unbranded_tajaran.dmi
  icons/mob/human_races/cyberlimbs/unbranded/unbranded_unathi.dmi
  icons/mob/human_races/cyberlimbs/veymed/dionaea/skrellian.dmi
  icons/mob/human_races/cyberlimbs/veymed/veymed_skrell.dmi
  nano/templates/mechfab.tmpl
  polaris.dme
Labels: Feature, Lore

#6817 changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Cerebulon - machinesounds.yml
  html/changelogs/mechoid - RoboticsRigs.yml
  html/changelogs/mechoid - exoexpansion.yml
  html/changelogs/neerti-hacking_QoL.yml
  html/changelogs/schnayy - cooking adjustments.yml
Labels: Changelog Update

#6813 Fixes the occupation screen.
  code/controllers/subsystems/job.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/department.dm
  code/modules/client/preference_setup/occupation/occupation.dm
  maps/southern_cross/southern_cross_jobs.dm
Labels: Refactor

#6816 [Bugfix/Oversight] Response Team Channel Shortcut
  code/modules/mob/living/say.dm
  html/changelogs/TheFurryFeline - Response Team Channel Shortcut.yml
Labels: Oversight

#6823 Makes PDA beeps a toggable option.
  code/game/objects/items/devices/PDA/PDA.dm
  nano/templates/pda.tmpl
Labels: Feature Tweak

#6828 Hair adjustments and additions
  code/modules/mob/new_player/sprite_accessories.dm
  html/changelogs/schnayy - hair adjustments.yml
  icons/mob/human_face.dmi
  icons/mob/human_face_m.dmi
Labels: Sprite Change

#6819 Makes language keys case sensitive, adds unit tests for language conflicts, fixes some language conflicts
  code/_global_vars/lists/species.dm
  code/_helpers/global_lists.dm
  code/game/world.dm
  code/global_init.dm
  code/modules/mob/language/monkey.dm
  code/modules/mob/say.dm
  code/unit_tests/language_tests.dm
  html/changelogs/Meghan Rossi - Language key tweaks.yml
  polaris.dme
Labels: Refactor

#6788 Antag Uplink Expansion
  code/datums/uplink/announcements.dm
  code/datums/uplink/armor.dm
  code/datums/uplink/implants.dm
  code/datums/uplink/medical.dm
  code/datums/uplink/resources.dm
  code/datums/uplink/stealth_items.dm
  code/datums/uplink/stealthy_weapons.dm
  code/datums/uplink/tools.dm
  code/datums/uplink/uplink_categories.dm
  code/datums/uplink/uplink_items.dm
  code/datums/uplink/visible_weapons.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/implants/implantaugment.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/items/weapons/storage/quickdraw.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/game/objects/items/weapons/tanks/tank_types.dm
  code/game/objects/items/weapons/traps.dm
  code/modules/clothing/gloves/antagonist.dm
  code/modules/mob/_modifiers/fire.dm
  code/modules/organs/internal/augment.dm
  code/modules/paperwork/pen.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/magnetic/gasthrower.dm
  code/modules/projectiles/guns/projectile/sniper.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/scatter.dm
  html/changelogs/mechoid - antaguplink.yml
  icons/mob/items/lefthand_melee.dmi
  icons/obj/bureaucracy.dmi
  icons/obj/railgun.dmi
  polaris.dme
Labels: Feature

#6825 Shock modification
  code/modules/mob/living/carbon/carbon.dm
Labels: Feature Tweak

#6829 QoL: Projectiles
  code/game/gamemodes/technomancer/spells/projectile/force_missile.dm
  code/game/gamemodes/technomancer/spells/projectile/overload.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/sound.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/hivebot/ranged_damage.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/energy.dm
  code/modules/projectiles/projectile/force.dm
  code/modules/projectiles/projectile/special.dm
  html/changelogs/neerti_projectile_qol.yml
  icons/effects/effects.dmi
  sound/weapons/attributions.txt
  sound/weapons/bulletflyby.ogg
  sound/weapons/bulletflyby2.ogg
  sound/weapons/bulletflyby3.ogg
  sound/weapons/effects/batreflect1.ogg
  sound/weapons/effects/batreflect2.ogg
  sound/weapons/effects/ric1.ogg
  sound/weapons/effects/ric2.ogg
  sound/weapons/effects/ric3.ogg
  sound/weapons/effects/ric4.ogg
  sound/weapons/effects/ric5.ogg
  sound/weapons/effects/searwall.ogg
  sound/weapons/ionrifle.ogg
  sound/weapons/sear.ogg
  sound/weapons/zapbang.ogg
Labels: Bugfix, Feature Tweak, Quality of Life

#6834 Fix various RIG issues
  code/_onclick/hud/screen_objects.dm
  code/game/objects/items/devices/flash.dm
  code/game/objects/items/weapons/mop_deploy.dm
  code/modules/clothing/spacesuits/rig/modules/specific/device.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/projectiles/guns/energy.dm
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/spacesuits.dmi
Labels: Bugfix

#6839 Streamline Job Alt Titles
  code/game/jobs/job/assistant.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/civilian_chaplain.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/jobs/job/silicon.dm
Labels: Refactor

#6853 Makes holsters and webbing get along.
  code/modules/clothing/clothing_accessories.dm
  code/modules/clothing/under/accessories/holster.dm
  html/changelogs/neerti-holsters.yml
Labels: Feature Tweak, Staff Request

#6855 POI wall nonsense
  code/game/turfs/simulated/dungeon/wall.dm
  code/modules/mining/mine_turfs.dm
  icons/turf/wall_masks.dmi
Labels: Bugfix, Sprite Change

#6773 Cutting rigs now retracts all components, to stop the dreaded pseudoprison.
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/surgery/other.dm
Labels: Bugfix

#6873 Fixes mistake in #6855
  code/game/turfs/simulated/dungeon/wall.dm
Labels: Bugfix, Priority: CRITICAL

#6863 Some Sprite Fixes
  code/game/objects/items/weapons/melee/energy.dm
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/lefthand_melee.dmi
  icons/mob/items/righthand_guns.dmi
  icons/mob/items/righthand_melee.dmi
  icons/obj/clothing/backpack.dmi
  icons/obj/storage.dmi
Labels: Sprite Change

#6840 QoL: Various Notifications
  code/datums/ghost_query.dm
  code/game/antagonist/antagonist.dm
  code/game/antagonist/antagonist_create.dm
  code/game/antagonist/outsider/commando.dm
  code/game/antagonist/outsider/deathsquad.dm
  code/game/antagonist/outsider/ert.dm
  code/game/antagonist/outsider/technomancer.dm
  code/game/antagonist/outsider/trader.dm
  code/game/antagonist/station/changeling.dm
  code/game/antagonist/station/cultist.dm
  code/game/antagonist/station/loyalist.dm
  code/game/antagonist/station/renegade.dm
  code/game/antagonist/station/rogue_ai.dm
  code/game/antagonist/station/traitor.dm
  code/game/gamemodes/technomancer/spells/resurrect.dm
  code/game/machinery/computer/cloning.dm
  code/game/objects/items/devices/defib.dm
  code/game/objects/items/weapons/AI_modules.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/silicon/laws.dm
  code/stylesheet.dm
  html/changelogs/neerti-qol_notifications.yml
  sound/effects/antag_notice/cult_alert.ogg
  sound/effects/antag_notice/deathsquid_alert.ogg
  sound/effects/antag_notice/general_baddie_alert.ogg
  sound/effects/antag_notice/general_goodie_alert.ogg
  sound/effects/antag_notice/ling_alert.ogg
  sound/effects/antag_notice/malf_alert.ogg
  sound/effects/antag_notice/technomancer_alert.ogg
  sound/effects/antag_notice/traitor_alert.ogg
  sound/effects/genetics.ogg
Labels: Feature, Quality of Life

#6820 Emergency lighting
  code/modules/power/apc.dm
  code/modules/power/cells/power_cells.dm
  code/modules/power/lighting.dm
  html/changelogs/ShadowQuill - Emergency-Lighting.yml
  nano/templates/apc.tmpl
Labels: Feature

#6852 Ports chemistry sprites from CEV-Eris
  icons/obj/chemical.dmi
  icons/obj/reagentfillings.dmi
Labels: Sprite Change

#6870 Makes AI give up bashing if nothing to bash
  code/modules/ai/_defines.dm
  code/modules/ai/ai_holder_combat.dm
  code/modules/ai/ai_holder_movement.dm
  code/modules/ai/interfaces.dm
  code/modules/mob/living/simple_mob/combat.dm
Labels: Feature Tweak

#6871 Remove stray 'return'
  code/modules/mob/living/carbon/human/life.dm
Labels: Oversight

#6872 Fixes taking items out of sewn plushies
  code/game/objects/items/toys.dm
Labels: Oversight

#6874 Fixes Manifest Bug
  code/defines/obj.dm
Labels: Oversight

#6876 Adds PDA-lawyer-old to pda_holo.dmi
  icons/obj/pda_holo.dmi
Labels: Sprite Change

#6879 Small mech tweaks
  code/game/mecha/equipment/tools/repair_droid.dm
  code/game/mecha/mecha.dm
  code/game/mecha/space/hoverpod.dm
  code/game/mecha/space/shuttle.dm
  code/modules/multiz/movement.dm
Labels: Feature Tweak

#6883 Safely change world.fps for SStimer
  code/controllers/master.dm
  code/game/world.dm
  code/modules/admin/verbs/fps.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/admin/verbs/ticklag.dm
  polaris.dme
Labels: Bugfix

#6875 [Oversight] Yay, another typo fixy
  code/game/machinery/doors/door.dm
  code/modules/mob/living/silicon/robot/robot_items.dm
  code/modules/mob/living/simple_mob/subtypes/animal/farm animals/chicken.dm
  code/modules/mob/living/simple_mob/subtypes/animal/pets/bird.dm
  code/modules/mob/living/simple_mob/subtypes/blob/spore.dm
Labels: Oversight

#6880 Teshari prosthetics
  code/datums/supplypacks/robotics.dm
  code/modules/mob/new_player/sprite_accessories.dm
  code/modules/organs/robolimbs.dm
  icons/mob/human_races/cyberlimbs/cenilimicybernetics/cenilimicybernetics_teshari.dmi
  icons/mob/human_races/cyberlimbs/unbranded/unbranded_teshari.dmi
  icons/mob/human_races/r_seromi.dmi
  icons/mob/species/seromi/eyes.dmi
  icons/mob/species/seromi/head.dmi
Labels: Lore, Sprite Change

#6881 Add mob/living stat setter and observer
  code/datums/observation/stat_set.dm
  code/game/dna/genes/monkey.dm
  code/game/gamemodes/changeling/powers/epinephrine_overdose.dm
  code/game/gamemodes/changeling/powers/lesser_form.dm
  code/game/gamemodes/changeling/powers/revive.dm
  code/game/gamemodes/gameticker.dm
  code/game/gamemodes/technomancer/spells/resurrect.dm
  code/game/machinery/computer/aifixer.dm
  code/game/machinery/cryo.dm
  code/game/mecha/mecha.dm
  code/game/objects/items/devices/defib.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/clothing/gloves/antagonist.dm
  code/modules/hydroponics/seed_mobs.dm
  code/modules/mob/dead/corpse.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/death.dm
  code/modules/mob/living/bot/bot.dm
  code/modules/mob/living/carbon/alien/life.dm
  code/modules/mob/living/carbon/brain/MMI.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/metroid/life.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/mob/living/silicon/decoy/life.dm
  code/modules/mob/living/silicon/pai/life.dm
  code/modules/mob/living/silicon/robot/drone/drone.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot_damage.dm
  code/modules/mob/living/simple_mob/subtypes/animal/passive/mouse.dm
  code/modules/mob/mob.dm
  code/modules/organs/subtypes/machine.dm
  code/modules/research/prosfab_designs.dm
  code/modules/xenobio2/mob/xeno.dm
  maps/RandomZLevels/wildwest.dm
  polaris.dme
Labels: Refactor

#6877 changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Aronai - wateriswet.yml
  html/changelogs/Cerebulon - bigsounds.yml
  html/changelogs/Meghan Rossi - Language key tweaks.yml
  html/changelogs/TheFurryFeline - Response Team Channel Shortcut.yml
  html/changelogs/mechoid - antaguplink.yml
  html/changelogs/neerti-holsters.yml
  html/changelogs/neerti-qol_notifications.yml
  html/changelogs/neerti_projectile_qol.yml
  html/changelogs/prismaticgynoid - xenoarch_fix.yml
  html/changelogs/schnayy - hair adjustments.yml
Labels: Changelog Update

#6899 Update Travis configuration
  .travis.yml
  tools/travis/compile_and_run.sh
  tools/travis/install_byond.sh
  tools/travis/validate_files.sh
Labels: Optimization, Priority: High, Refactor

#6854 Xenoarch Expansion
  code/__defines/xenoarcheaology.dm
  code/game/gamemodes/technomancer/spells/aura/shock_aura.dm
  code/modules/mob/_modifiers/feysight.dm
  code/modules/mob/living/simple_mob/subtypes/animal/space/bats.dm
  code/modules/shieldgen/energy_field.dm
  code/modules/xenoarcheaology/artifacts/artifact.dm
  code/modules/xenoarcheaology/effects/animate_anomaly.dm
  code/modules/xenoarcheaology/effects/cannibal.dm
  code/modules/xenoarcheaology/effects/electric_field.dm
  code/modules/xenoarcheaology/effects/feysight.dm
  code/modules/xenoarcheaology/effects/gaia.dm
  code/modules/xenoarcheaology/effects/gravitational_waves.dm
  code/modules/xenoarcheaology/effects/poltergeist.dm
  code/modules/xenoarcheaology/effects/resurrect.dm
  code/modules/xenoarcheaology/effects/vampire.dm
  code/modules/xenoarcheaology/finds/find_spawning.dm
  code/modules/xenoarcheaology/tools/ano_device_battery.dm
  code/modules/xenoarcheaology/tools/artifact_harvester.dm
  html/changelogs/Mechoid - Xenoarch.yml
  icons/obj/xenoarchaeology.dmi
  polaris.dme
Labels: Feature

#6892 Distillery tweaks
  code/datums/supplypacks/medical.dm
  code/modules/reagents/distilling/distilling.dm
  html/changelogs/atermonera_distillery.yml
Labels: Bugfix, Feature Tweak

#6893 Berserkjuice doesn't spam chat
  code/modules/mob/_modifiers/modifiers.dm
  code/modules/mob/_modifiers/modifiers_misc.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Modifiers.dm
Labels: Bugfix

#6895 Fix runtime in sound.dm: playsound(): source is an area
  code/game/turfs/simulated/wall_attacks.dm
Labels: Bugfix

#6896 Repaths collapsible white canes to not anger beepsky
  code/defines/obj/weapon.dm
  code/game/objects/items/weapons/canes.dm
  code/modules/client/preference_setup/loadout/loadout_general.dm
  polaris.dme
Labels: Bugfix, Refactor

#6897 Silly admins can't blindly break movement irreparably
  code/game/atoms_movable.dm
  code/modules/admin/view_variables/modify_variables.dm
Labels: Bugfix, Priority: High

#6885 [Feature Tweak] Message Fixy For Snowballs/Kickstands
  code/game/objects/items/weapons/material/misc.dm
  code/modules/vehicles/bike.dm
  html/changelogs/TheFurryFeline - Message_Fixy_For_Snowballs_and_Kickstands.yml
Labels: Feature Tweak

#6898 Prometheans can be slipped again
  code/modules/mob/living/carbon/human/human_attackhand.dm
  html/changelogs/atermonera_prommie_slippers.yml
Labels: Bugfix

#6865 Tweak Fire, Flamethrowers, and Water.
  code/modules/mob/_modifiers/fire.dm
  code/modules/mob/living/carbon/human/human_resist.dm
  code/modules/mob/living/living_defense.dm
  code/modules/projectiles/guns/magnetic/gasthrower.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Core.dm
Labels: Bugfix, Oversight

#6901 Remove turbolift_controller proccess, just use SSprocessing instead.
  code/modules/turbolift/turbolift.dm
  code/modules/turbolift/turbolift_process.dm
  polaris.dme
Labels: Refactor

#6906 Fix runtimes in lungs.dm
  code/modules/organs/internal/lungs.dm
Labels: Bugfix

#6830 Make diagonal shuttle walls look less bad
  code/game/turfs/simulated/floor_types.dm
  icons/effects/lighting_overlay.dmi
Labels: Sprite Change

#6908 Fix biogenerator exploit
  code/game/machinery/biogenerator.dm
Labels: Oversight

#6886 Inactivity subsystem kicks ghosts and admins again
  code/controllers/subsystems/inactivity.dm
Labels: Bugfix, Staff Request

#6889 2 new mech equipments
  code/__defines/_planes+layers.dm
  code/__defines/mobs.dm
  code/game/atoms_movable.dm
  code/game/mecha/combat/fighter.dm
  code/game/mecha/equipment/tools/cloak.dm
  code/game/mecha/equipment/tools/shield_omni.dm
  code/game/mecha/mecha.dm
  code/modules/artifice/deadringer.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/mob/dead/observer/login.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/lurker.dm
  code/modules/mob/login.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_planes.dm
  code/modules/research/mechfab_designs.dm
  code/modules/shieldgen/directional_shield.dm
  icons/mecha/fighters64x64.dmi
  polaris.dme
  sound/mecha/fighter_entered.ogg
  sound/mecha/fighter_entered_bad.ogg
Labels: Feature

#6890 Fixes slime enrage message
  code/modules/ai/aI_holder_subtypes/slime_xenobio_ai.dm
Labels: Mob AI Issue, Oversight

#6891 Fixes headphone offear
  code/modules/clothing/clothing.dm
  html/changelogs/atermonera_headphone_fix.yml
Labels: Bugfix

#6915 changelog update
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Leshana - vplk-overmap-skybox.yml
  html/changelogs/Mechoid - Xenoarch.yml
  html/changelogs/ShadowQuill - Emergency-Lighting.yml
  html/changelogs/TheFurryFeline - Message_Fixy_For_Snowballs_and_Kickstands.yml
  html/changelogs/atermonera_distillery.yml
  html/changelogs/atermonera_prommie_slippers.yml
Labels: Changelog Update

#6914 Fixes examine panel icons
  code/modules/examine/examine.dm
  interface/skin.dmf
Labels: Oversight

#6902 Convert alarm_manager into SSalarm subsystem.
  code/__defines/subsystems.dm
  code/controllers/Processes/alarm.dm
  code/controllers/subsystems/alarm.dm
  code/controllers/verbs.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/silicon/subystems.dm
  code/modules/modular_computers/file_system/programs/engineering/alarm_monitor.dm
  polaris.dme
Labels: Refactor

#6858 Port Bay's vendor/smartfridge sprites
  code/game/machinery/vending.dm
  code/modules/food/kitchen/smartfridge.dm
  icons/obj/vending.dmi
Labels: Sprite Change

#6911 Added three utilities for admins & developers
  code/controllers/configuration.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/mob/login.dm
  config/example/config.txt
Labels: Feature
