Repository PolarisSS13/Polaris, pull requests merged in 2020-08, with the labels that each got.

#7365 Fish tank
  code/datums/autolathe/general.dm
  code/game/machinery/vending_machines.dm
  code/game/objects/items/glassjar.dm
  code/modules/materials/material_recipes.dm
  code/modules/mob/living/simple_mob/subtypes/animal/passive/fish.dm
  html/changelogs/mechoid - fishtank.yml
  icons/obj/items.dmi
Labels: Feature

#7366 Ambiance and Sound Updates
  code/__defines/sound.dm
  code/game/area/areas.dm
  code/game/machinery/computer/arcade.dm
  code/game/machinery/computer/computer.dm
  code/game/machinery/doors/blast_door.dm
  code/game/machinery/portable_turret.dm
  code/modules/mob/living/life.dm
  code/modules/mob/mob_defines.dm
  sound/ambience/foreboding/foreboding1.ogg
  sound/ambience/foreboding/foreboding2.ogg
  sound/ambience/foreboding/foreboding3.ogg
  sound/ambience/foreboding/foreboding4.ogg
  sound/ambience/foreboding/foreboding5.ogg
  sound/ambience/foreboding/foreboding6.ogg
  sound/ambience/maintenance/maintenance1.ogg
  sound/ambience/maintenance/maintenance2.ogg
  sound/ambience/maintenance/maintenance3.ogg
  sound/ambience/maintenance/maintenance4.ogg
  sound/ambience/maintenance/maintenance5.ogg
  sound/ambience/old_foreboding/foreboding1.ogg
  sound/ambience/old_foreboding/foreboding2.ogg
  sound/arcade/Ori_begin.ogg
  sound/arcade/Ori_fail.ogg
  sound/arcade/Ori_win.ogg
  sound/arcade/boom.ogg
  sound/arcade/explo.ogg
  sound/arcade/get_fuel.ogg
  sound/arcade/heal.ogg
  sound/arcade/hit.ogg
  sound/arcade/kill_crew.ogg
  sound/arcade/lose.ogg
  sound/arcade/lose_fuel.ogg
  sound/arcade/mana.ogg
  sound/arcade/raid.ogg
  sound/arcade/steal.ogg
  sound/arcade/win.ogg
  sound/machines/blastdoorclose.ogg
  sound/machines/blastdooropen.ogg
  sound/machines/terminal_alert.ogg
  sound/machines/terminal_button01.ogg
  sound/machines/terminal_button02.ogg
  sound/machines/terminal_button03.ogg
  sound/machines/terminal_button04.ogg
  sound/machines/terminal_button05.ogg
  sound/machines/terminal_button06.ogg
  sound/machines/terminal_button07.ogg
  sound/machines/terminal_button08.ogg
  sound/machines/terminal_insert_disc.ogg
  sound/machines/terminal_off.ogg
  sound/machines/terminal_on.ogg
  sound/machines/terminal_prompt.ogg
  sound/machines/terminal_prompt_confirm.ogg
  sound/machines/terminal_prompt_deny.ogg
  sound/machines/turrets/turret_deploy.ogg
  sound/machines/turrets/turret_retract.ogg
  sound/machines/turrets/turret_rotate.ogg
Labels: Feature Tweak

#7381 Adds a preference dropdown for window scaling
  interface/skin.dmf
Labels: Feature

#7383 Adds Area-Based Meson Obfuscation
  code/game/area/areas.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Feature

#7387 Teshari sneeze fix
  sound/effects/mob_effects/tesharisneeze.ogg
Labels: Feature Tweak

#7388 Ports library machine sprites from Aurora
  icons/obj/library.dmi
Labels: Sprite Change

#7389 Ports Baystation virology machinery sprites
  icons/obj/virology.dmi
Labels: Sprite Change

#7392 Add a 'Restarting world!' notice.
  code/controllers/subsystems/ticker.dm
Labels: Quality of Life

#7396 Swaps codersprites of status icons, meant to be done before merge.
  icons/mob/status_indicators.dmi
Labels: Sprite Change

#7400 Icon Updates!
  code/modules/food/kitchen/cooking_machines/fryer.dm
  code/modules/food/kitchen/cooking_machines/oven.dm
  icons/obj/cooking_machines.dmi
  icons/obj/food.dmi
  icons/obj/food_custom.dmi
  icons/obj/food_syn.dmi
Labels: Sprite Change

#7401 Fixes null grab runtime breaking mob movement
  code/modules/mob/mob_movement.dm
Labels: Bugfix

#7404 Fuel spills no longer persistent
  code/game/objects/effects/decals/Cleanable/fuel.dm
Labels: Bugfix

#7418 Critical Bugfix to Aurora Cooking not working with Reagents
  code/modules/food/recipe.dm
Labels: Oversight, Priority: High

#7329 Exosuit Modular Internals, The Squeakening
  code/__defines/objects.dm
  code/datums/autolathe/arms.dm
  code/datums/autolathe/autolathe.dm
  code/datums/autolathe/general.dm
  code/game/machinery/autolathe.dm
  code/game/mecha/combat/combat.dm
  code/game/mecha/combat/durand.dm
  code/game/mecha/combat/gygax.dm
  code/game/mecha/combat/marauder.dm
  code/game/mecha/combat/phazon.dm
  code/game/mecha/components/_component.dm
  code/game/mecha/components/actuators.dm
  code/game/mecha/components/armor.dm
  code/game/mecha/components/electrical.dm
  code/game/mecha/components/hull.dm
  code/game/mecha/components/lifesupport.dm
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/mecha/equipment/tools/armor_melee.dm
  code/game/mecha/equipment/tools/armor_ranged.dm
  code/game/mecha/equipment/tools/repair_droid.dm
  code/game/mecha/equipment/tools/shield.dm
  code/game/mecha/equipment/tools/shield_omni.dm
  code/game/mecha/equipment/tools/speedboost.dm
  code/game/mecha/equipment/weapons/ballistic/mortar.dm
  code/game/mecha/equipment/weapons/ballistic/shotgun.dm
  code/game/mecha/equipment/weapons/energy/laser.dm
  code/game/mecha/equipment/weapons/explosive/missile.dm
  code/game/mecha/equipment/weapons/fire/flamethrower.dm
  code/game/mecha/equipment/weapons/fire/incendiary.dm
  code/game/mecha/equipment/weapons/weapons.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_actions.dm
  code/game/mecha/medical/medical.dm
  code/game/mecha/medical/odysseus.dm
  code/game/mecha/working/ripley.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/modules/mob/living/silicon/robot/analyzer.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/ammunition/rounds.dm
  code/modules/projectiles/projectile/scatter.dm
  code/modules/research/circuitprinter.dm
  code/modules/research/designs/circuits/circuits.dm
  code/modules/research/designs/weapons.dm
  code/modules/research/mechfab_designs.dm
  html/changelogs/mechoid - exointernals.yml
  icons/effects/actions_mecha.dmi
  icons/mecha/mech_component.dmi
  polaris.dme
Labels: Feature, Results To Be Reviewed

#7361 Overdose changes + General chem mods
  code/game/machinery/adv_med.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Core.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
  nano/templates/adv_med.tmpl
Labels: Feature Tweak, Results To Be Reviewed

#7378 Think with Portals
  code/game/objects/effects/map_effects/perma_light.dm
  code/game/objects/effects/map_effects/portal.dm
  icons/effects/map_effects.dmi
  maps/southern_cross/southern_cross-3.dmm
  maps/southern_cross/southern_cross-4.dmm
  maps/southern_cross/southern_cross-8.dmm
  maps/southern_cross/southern_cross_defines.dm
  maps/submaps/surface_submaps/mountains/mountains.dm
  maps/submaps/surface_submaps/mountains/mountains_areas.dm
  maps/submaps/surface_submaps/mountains/spatial_anomaly.dmm
  polaris.dme
Labels: Feature, Map Change / Issue, Point of Interest

#7380 Port Blast Door Crushing!
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/blast_door.dm
  html/changelogs/rykka-stormheart-pr-7380.yml
Labels: Feature

#7391 Adds tg-style fast(ish) magazine restocking.
  code/modules/projectiles/ammunition.dm
  html/changelogs/forfoxsake - fastmagazines.yml
Labels: Feature, Ported from /TG/code

#7403 Mechtoy and arcade
  code/game/machinery/computer/arcade.dm
  code/game/objects/items/toys.dm
Labels: Feature Tweak

#7409 Adjusts Skrellian hair names to fit descriptions on wiki
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
  icons/mob/human_face_m.dmi
Labels: Feature Tweak

#7421 changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/billybangles-chessboard.yml
  html/changelogs/cerebulon - booksprites.yml
  html/changelogs/cerebulon - persistence.yml
  html/changelogs/kasparovy-pr-7314.yml
  html/changelogs/mechoid - fishtank.yml
  html/changelogs/rykka-stormheart-pr-7344.yml
Labels: Changelog Update

#7408 adds cold discomfort messages for tesh + one new for heat
  code/modules/mob/living/carbon/human/species/station/seromi.dm
Labels: Feature Tweak

#7410 Fixes Arachnophobia Exploit
  code/__defines/mobs.dm
  code/modules/ai/ai_holder_targeting.dm
  code/modules/mob/_modifiers/traits_phobias.dm
Labels: Feature Tweak

#7413 Makes status indicators layer below lighting/weather effects.
  code/__defines/_planes+layers.dm
Labels: Feature Tweak, Staff Request

#7438 Changelog update
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/cerebulon - schnemobs.yml
  html/changelogs/forfoxsake - fastmagazines.yml
  html/changelogs/mechoid - exointernals.yml
  html/changelogs/rykka-stormheart-pr-7380.yml
Labels: Changelog Update

#7437 Radiation storms no longer wrack the surface
  maps/southern_cross/southern_cross_defines.dm
Labels: Bugfix, Staff Request

#7398 Stickynote tweaks
  code/datums/supplypacks/supply.dm
  code/modules/paperwork/paper_sticky.dm
  code/modules/paperwork/paperbin.dm
Labels: Feature Tweak

#7439 Ports CEV-Eris status display frame
  icons/obj/status_display.dmi
Labels: Sprite Change

#7424 Skip calling handle_ambience() if there is no client assigned
  code/modules/mob/living/life.dm
Labels: Optimization

#7425 Tweak to kitchen machinery:
  code/modules/food/kitchen/cooking_machines/_appliance.dm
  code/modules/food/kitchen/cooking_machines/container.dm
  code/modules/food/kitchen/cooking_machines/oven.dm
  code/modules/reagents/Chemistry-Machinery.dm
Labels: Quality of Life

#7427 Ports Baystation12 chemistry cartridge sprite
  icons/obj/chemical.dmi
Labels: Sprite Change

#7433 Gives mice non-default melee stats
  code/modules/mob/living/simple_mob/subtypes/animal/passive/mouse.dm
Labels: Oversight

#7420 Ports Aurora janitorial sprites
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/aibots.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/janitor.dmi
Labels: Sprite Change

#7429 Replaces floodlight sprites with Baystation 12 floodlights
  icons/obj/machines/floodlight.dmi
Labels: Sprite Change

#7405 Mortiferin
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
  code/modules/reagents/Chemistry-Recipes.dm
  html/changelogs/mechoid - mortiferin.yml
Labels: Feature Tweak

#7431 ports a whole lot of Teshari stuff from Arkstation
  code/game/objects/effects/map_effects/portal.dm
  code/game/objects/items/weapons/towels.dm
  code/modules/client/preference_setup/loadout/loadout_accessories.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/clothing/under/xenos/seromi.dm
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
  icons/mob/human_face_m.dmi
  icons/mob/species/seromi/belt.dmi
  icons/mob/species/seromi/ears.dmi
  icons/mob/species/seromi/head.dmi
  icons/mob/species/seromi/suit.dmi
  icons/mob/species/seromi/teshari_uniform.dmi
  icons/mob/species/seromi/ties.dmi
  icons/mob/species/seromi/uniform.dmi
  icons/obj/clothing/species/seromi/uniform.dmi
  icons/obj/clothing/ties.dmi
  maps/southern_cross/southern_cross-8.dmm
  maps/submaps/surface_submaps/mountains/spatial_anomaly.dmm
Labels: Feature, Needs Changelog

#7440 Allows non-base welders to remove graffiti
  code/modules/persistence/graffiti.dm
Labels: Oversight

#7441 Rename the shield drone to linear combat shield in mech fab.
  code/modules/research/mechfab_designs.dm
Labels: Quality of Life

#7444 Removes the ability to forge plasteel from steel.
  code/datums/autolathe/general.dm
Labels: Bugfix, Priority: High

#7447 Gives NOREACT flag back to fixed microwaves
  code/modules/food/kitchen/microwave.dm
Labels: Bugfix

#7448 Shower Audio Reduction - Replaces audio files with quieter versions of them!
  sound/machines/shower/shower_end.ogg
  sound/machines/shower/shower_mid1.ogg
  sound/machines/shower/shower_mid2.ogg
  sound/machines/shower/shower_mid3.ogg
  sound/machines/shower/shower_start.ogg
Labels: Results To Be Reviewed, Sound Change

#7450 Manipulators now also drop items with alt click.
  code/modules/mob/living/silicon/robot/drone/drone_items.dm
Labels: Feature Tweak, Quality of Life

#7453 Fix: Prevent planet weather sounds in Transit
  maps/southern_cross/southern_cross_defines.dm
Labels: Oversight

#7455 Fix play_ambience in Life() causing premature loops
  code/game/area/areas.dm
  code/modules/holodeck/HolodeckControl.dm
  code/modules/mob/living/life.dm
Labels: Oversight

#7457 Adds second confirmation to character slot reset
  code/modules/client/preferences.dm
Labels: Feature Tweak

#7458 Replaces curtain sprites with World Server sprites
  icons/obj/curtain.dmi
Labels: Sprite Change

#7460 Fixes infinite loop on synth brain transplant
  code/modules/surgery/robotics.dm
Labels: Oversight

#7461 Ports Bastion of Hestia rig sounds
  code/modules/clothing/spacesuits/rig/rig.dm
  sound/machines/rig/rigdown.ogg
  sound/machines/rig/rigerror.ogg
  sound/machines/rig/rigonline.ogg
  sound/machines/rig/rigstarted.ogg
  sound/machines/rig/rigstep.ogg
Labels: Sound Change

#7462 Adds audio and visual feedback to pulling.
  code/modules/mob/mob.dm
Labels: Feature Tweak, Sound Change

#7435 Accessory colors aren't modified by clothing colors
  code/modules/clothing/under/accessories/accessory.dm
Labels: Bugfix, Quality of Life

#7436 Adds overmap sensors to the Southern Cross
  code/controllers/subsystems/skybox.dm
  code/modules/multiz/basic.dm
  code/modules/overmap/sectors.dm
  code/modules/overmap/ships/computers/sensors.dm
  code/modules/overmap/ships/computers/ship.dm
  html/changelogs/atermonera - sensor_suite.yml
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross_defines.dm
Labels: Feature, Map Change / Issue, Project

#7443 Makes Skrell eyes black
  icons/mob/human_face.dmi
  icons/mob/human_face_m.dmi
Labels: Sprite Change

#7483 News update... April-May 2020
  code/modules/lore_codex/news_data/main.dm
Labels: Lore

#7490 Improves mecha strafing
  code/game/mecha/mecha.dm
  html/changelogs/BlinsKot - strafing.yml
Labels: Feature Tweak

#7451 Tweak to the washing machine.
  code/game/machinery/washing_machine.dm
  html/changelogs/Kot-Washing.yml
Labels: Refactor

#7426 Disable breaking fragile floor tiles with the crowbar
  code/game/turfs/simulated/floor_attackby.dm
Labels: Controversial, Feature Tweak

#7514 Revert "Disable breaking fragile floor tiles with the crowbar"
  code/game/turfs/simulated/floor_attackby.dm
Labels: Oversight, Priority: High

#7515 Removes TURF_IS_FRAGILE from wooden flooring
  code/game/turfs/flooring/flooring.dm
Labels: Feature Tweak, Priority: High

#7466 Adds wearing cones and caution signs
  code/datums/supplypacks/supply.dm
  code/defines/obj/weapon.dm
  code/game/objects/random/maintenance.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/janicart.dm
  code/game/objects/structures/loot_piles.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/xenoarcheaology/artifacts/replicator.dm
  html/changelogs/Lorilili - janiwear.yml
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/janitor.dmi
  maps/southern_cross/southern_cross-1.dmm
  maps/submaps/surface_submaps/mountains/quarantineshuttle.dmm
Labels: Feature, Map Change / Issue

#7467 Adds New Prosthetics Set
  code/modules/organs/robolimbs.dm
  html/changelogs/SubberTheFabulous-PR-7467.yml
  icons/mob/human_races/cyberlimbs/cybersolutions/cybersolutions_alt2.dmi
  icons/mob/human_races/cyberlimbs/cybersolutions/cybersolutions_alt3.dmi
Labels: Feature Tweak, Lore, Sprite Change

#7470 Admin ghosts can now examine other ghosts to pull up admin tools!
  code/modules/mob/dead/observer/observer.dm
Labels: Feature

#7473 Exosuit Upkeep
  code/game/mecha/components/armor.dm
  code/game/mecha/equipment/tools/armor_melee.dm
  code/game/mecha/equipment/tools/armor_ranged.dm
  code/game/mecha/equipment/tools/shield.dm
  code/game/mecha/equipment/tools/shield_omni.dm
  code/game/mecha/equipment/weapons/ballistic/shotgun.dm
  code/game/mecha/equipment/weapons/energy/laser.dm
  code/game/mecha/equipment/weapons/explosive/missile.dm
  code/game/mecha/equipment/weapons/fire/flamethrower.dm
  code/game/mecha/equipment/weapons/weapons.dm
  code/game/mecha/mecha.dm
  code/modules/research/designs/circuits/circuits.dm
  code/modules/research/mechfab_designs.dm
Labels: Feature Tweak, Results To Be Reviewed

#7477 Replaces bolt sounds for rigs with servo sounds
  code/modules/clothing/spacesuits/rig/rig.dm
  sound/machines/rig/rigservo.ogg
Labels: Sound Change

#7386 Reagent Hoses
  code/__defines/hoses.dm
  code/datums/autolathe/tools.dm
  code/datums/beam.dm
  code/datums/supplypacks/misc.dm
  code/game/machinery/reagents/pump.dm
  code/game/objects/items/weapons/circuitboards/machinery/fluidpump.dm
  code/modules/materials/material_recipes.dm
  code/modules/mining/mineral_effect.dm
  code/modules/mining/ore_datum.dm
  code/modules/mob/_modifiers/medical.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Modifiers.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
  code/modules/reagents/hoses/connector.dm
  code/modules/reagents/hoses/hose.dm
  code/modules/reagents/hoses/hose_connector.dm
  code/modules/reagents/reagent_containers/spray.dm
  code/modules/reagents/reagent_dispenser.dm
  html/changelogs/mechoid - reagenthoses.yml
  icons/effects/beam.dmi
  icons/obj/janitor.dmi
  icons/obj/machines/reagent.dmi
  polaris.dme
Labels: Cannot Merge, Feature, Needs Documentation

#7428 Small tweaks to cyborg verbs and icon
  code/modules/mob/living/silicon/robot/robot.dm
  icons/mob/screen1_robot.dmi
Labels: Feature Tweak

#7449 Flavour Enhancement: Vending
  code/datums/supplypacks/medical.dm
  code/datums/supplypacks/voidsuits.dm
  code/game/machinery/vending_machines.dm
  code/game/objects/items/trash.dm
  code/game/objects/items/weapons/chewables.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/ecigs.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/loot_piles.dm
  code/modules/food/food/cans.dm
  code/modules/food/food/drinks.dm
  code/modules/food/food/drinks/bottle.dm
  code/modules/food/food/snacks.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/dispenser/cartridge_presets.dm
  code/modules/reagents/dispenser/dispenser_presets.dm
  html/changelogs/Cerebulon - Vending.yml
  icons/obj/cigarettes.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/drinks.dmi
  icons/obj/food.dmi
  icons/obj/food_snacks.dmi
  icons/obj/trash.dmi
  polaris.dme
  sound/items/drop/papercup.ogg
Labels: Feature, Refactor, Sprite Change

#7452 Gives FBP's a proc to change their monitor display without using a mask item.
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/human_powers.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/organs/robolimbs.dm
  html/changelogs/splintergp-PR-7452.yml
  icons/mob/monitor_icons.dmi
  polaris.dme
Labels: Feature, Sprite Change

#7445 FBP Internal Components
  code/__defines/mobs.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/modules/mob/living/carbon/human/human_powers.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/species_getters.dm
  code/modules/mob/living/carbon/human/species/station/prometheans.dm
  code/modules/organs/blood.dm
  code/modules/organs/internal/heart.dm
  code/modules/organs/internal/robotic/diagnostic.dm
  code/modules/organs/internal/robotic/heatsink.dm
  code/modules/organs/internal/robotic/robotic.dm
  code/modules/organs/internal/stomach.dm
  code/modules/organs/robolimbs.dm
  code/modules/organs/subtypes/machine.dm
  code/modules/organs/subtypes/standard.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Core.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
  code/modules/research/prosfab_designs.dm
  icons/obj/surgery.dmi
  polaris.dme
Labels: Feature, Feature Tweak, Prepare to Die

#7482 Replaces water + welding tank sprites with sprites from Aurora
  icons/obj/aibots.dmi
  icons/obj/objects.dmi
Labels: Sprite Change

#7485 Fix Asset Cache Verification - BYOND Bugfix
  interface/skin.dmf
Labels: BYOND Issue, Bugfix

#7487 Adds shift-middle click pointing
  code/_onclick/click.dm
  code/_onclick/cyborg.dm
  code/modules/mob/living/living.dm
  html/changelogs/Lorilili - pointing.yml
Labels: Feature

#7488 Ports more Teshari clothes from Urist & Citadel
  code/modules/clothing/under/xenos/seromi.dm
  icons/mob/species/seromi/back.dmi
  icons/mob/species/seromi/belt_mirror.dmi
  icons/mob/species/seromi/ears.dmi
  icons/mob/species/seromi/gloves.dmi
  icons/mob/species/seromi/head.dmi
  icons/mob/species/seromi/masks.dmi
  icons/mob/species/seromi/shoes.dmi
  icons/mob/species/seromi/suit.dmi
  icons/mob/species/seromi/ties.dmi
  icons/mob/species/seromi/uniform.dmi
  icons/obj/clothing/species/seromi/suits.dmi
  icons/obj/clothing/species/seromi/uniform.dmi
Labels: Feature, Sprite Change

#7489 Make it quicker to unfasten pipes.
  code/ATMOSPHERICS/pipes/pipe_base.dm
Labels: Quality of Life

#7492 Skrell blood is now hemocyanin-based
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm
  html/changelogs/Lorilili - hemocyanin.yml
Labels: Feature, Lore

#7494 Delete some duplication in the mech drill
  code/game/mecha/equipment/tools/drill.dm
Labels: Refactor

#7495 Replaces ATM sprite with CEV-Eris ATM
  icons/obj/terminals.dmi
Labels: Sprite Change

#7496 Add a plastic knife to the pizzzaaaaa crate.
  code/datums/supplypacks/hospitality.dm
Labels: Feature Tweak

#7497 Cancelling choosing someone to admin PM won't say "no mob"
  code/modules/admin/verbs/adminpm.dm
Labels: Oversight

#7498 5 POI's
  maps/submaps/surface_submaps/plains/hotspring.dmm
  maps/submaps/surface_submaps/plains/lonehome.dmm
  maps/submaps/surface_submaps/plains/methlab.dmm
  maps/submaps/surface_submaps/plains/oldhotel.dmm
  maps/submaps/surface_submaps/plains/plains.dm
  maps/submaps/surface_submaps/plains/plains_areas.dm
  maps/submaps/surface_submaps/plains/priderock.dmm
Labels: Point of Interest

#7502 Fix duct tape on self
  code/game/objects/items/weapons/tape.dm
  html/changelogs/meghan rossi - duct tape.yml
Labels: Bugfix, Refactor

#7503 Replaces cable attack_ghost with normal examine
  code/modules/power/cable.dm
Labels: Refactor

#7507 De-capitalizes shield generators
  code/modules/shieldgen/emergency_shield.dm
  code/modules/shieldgen/sheldwallgen.dm
Labels: Oversight

#7508 Persistence Patch
  code/controllers/configuration.dm
  code/controllers/subsystems/persistence.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/items/trash.dm
  code/game/world.dm
  code/modules/admin/admin.dm
  code/modules/paperwork/paper.dm
  code/modules/persistence/datum/datum_paper.dm
  code/modules/persistence/datum/persistence_datum.dm
  code/modules/persistence/graffiti.dm
  config/example/config.txt
Labels: Feature Tweak

#7509 Stop bots standing around blocking doors
  code/modules/mob/living/bot/bot.dm
  html/changelogs/meghan rossi - bots clear doorways.yml
Labels: Feature Tweak

#7513 Allows you to YEET mob holders (diona, etc)
  code/modules/mob/holder.dm
Labels: Feature

#7504 Beginnings of a global volume control system
  code/__defines/misc.dm
  code/game/area/areas.dm
  code/game/machinery/fire_alarm.dm
  code/game/sound.dm
  code/modules/client/client defines.dm
  code/modules/client/preference_setup/volume_sliders/01_volume.dm
  code/modules/client/preferences.dm
  polaris.dme
  tgui/packages/tgui/interfaces/VolumePanel.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Feature, Needs Changelog

#7534 Emergency Travis Appeasement: Sacrifice of one Giant Spider, one HMS Jolly Pip, and one Capital City sacked and looted by Cultists
  _build_dependencies.sh
  code/modules/reagents/hoses/hose_connector.dm
  maps/submaps/surface_submaps/plains/lonehome.dmm
  polaris.dme
Labels: Bugfix, Priority: CRITICAL

#7518 Fix cyborgs not being able to cook
  code/game/objects/items.dm
  code/modules/food/kitchen/cooking_machines/_appliance.dm
  code/modules/mob/inventory.dm
  html/changelogs/meghan rossi - borg cooking fix.yml
Labels: Bugfix

#7519 Allows building plating on grass
  code/game/turfs/simulated/outdoors/outdoors_attackby.dm
  code/modules/examine/descriptions/turfs.dm
  html/changelogs/meghan rossi - grass plating.yml
Labels: Bugfix

#7521 Adds metamorphic pint glasses to RSF, autolathe, supply packs
  code/datums/autolathe/general.dm
  code/datums/supplypacks/hospitality.dm
  code/game/objects/items/weapons/RSF.dm
  code/modules/food/drinkingglass/glass_boxes.dm
  html/changelogs/meghan rossi - metapint.yml
Labels: Feature Tweak

#7522 Improve cleanbot ai slightly
  code/_helpers/global_lists.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/bot/cleanbot.dm
  html/changelogs/meghan rossi - cleanbot tweaks.yml
Labels: Feature Tweak, Mob AI Issue

#7523 Ghost sechud verb, shift-click examine, alt-click turf tab
  code/_onclick/click.dm
  code/_onclick/observer.dm
  code/modules/mob/dead/observer/observer.dm
  html/changelogs/Meghan Rossi - ghostqol.yml
Labels: Feature

#7555 Actually adds (and TESTS) exclude_mobs parameter to visible_message
  code/game/atoms.dm
  code/modules/mob/mob.dm
  code/modules/multiz/zshadow.dm
Labels: Bugfix, Oversight

#7557 Fixes Runtime in vchat_client.dm,85: Cannot execute null.is preference enabled
  code/modules/vchat/vchat_client.dm
Labels: Bugfix, Higgs Bugson, Results To Be Reviewed

#7456 The great Aurora shoe heist
  code/datums/supplypacks/costumes.dm
  code/game/machinery/biogenerator.dm
  code/game/objects/random/maintenance.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/game/objects/structures/loot_piles.dm
  code/modules/client/preference_setup/loadout/loadout_shoes.dm
  code/modules/clothing/shoes/boots.dm
  code/modules/clothing/shoes/colour.dm
  code/modules/clothing/shoes/miscellaneous.dm
  html/changelogs/Lorilili - footwear.yml
  icons/mob/feet.dmi
  icons/mob/items/lefthand_shoes.dmi
  icons/mob/items/righthand_shoes.dmi
  icons/obj/clothing/shoes.dmi
  maps/southern_cross/structures/closets/research.dm
Labels: Needs Changelog, Sprite Change

#7474 Improvements to mech missiles.
  code/game/mecha/equipment/weapons/explosive/missile.dm
  code/modules/projectiles/ammunition/rounds.dm
  code/modules/projectiles/guns/launcher/rocket.dm
  code/modules/projectiles/projectile/explosive.dm
  icons/obj/projectiles.dmi
  polaris.dme
Labels: Ported from /TG/code, Refactor

#7480 Ports Aurora Diona markings
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_races/markings.dmi
Labels: Feature, Sprite Change

#7548 Xenoarchaeology Upkeep
  code/__defines/xenoarcheaology.dm
  code/modules/xenoarcheaology/artifacts/artifact.dm
  code/modules/xenoarcheaology/artifacts/artifact_find.dm
  code/modules/xenoarcheaology/boulder.dm
  code/modules/xenoarcheaology/finds/find_spawning.dm
  code/modules/xenoarcheaology/finds/finds_defines.dm
  icons/obj/xenoarchaeology.dmi
Labels: Feature Tweak, Oversight

#7550 Fix combinination_cook() creating items with no reagents
  code/modules/food/kitchen/cooking_machines/_appliance.dm
Labels: Oversight

#7551 Improves Portal Documentation for New Mappers unfamiliar with DIR
  code/game/objects/effects/map_effects/portal.dm
Labels: Refactor

#7553 [Untested] Emotes won't be foiled by pesky capitals
  code/modules/mob/living/carbon/alien/emote.dm
Labels: Feature Tweak

#7554 Fixes turf slowdown not applying on non-water/snow turfs
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: Oversight

#7556 Fixes Mercs threaten timers, and threaten sounds
  code/modules/ai/say_list.dm
  code/modules/mob/living/simple_mob/subtypes/humanoid/mercs/mercs.dm
Labels: Feature Tweak, Mob AI Issue

#7558 Returns the jackolantern overlay
  code/modules/clothing/head/misc_special.dm
  icons/mob/light_overlays.dmi
  icons/obj/light_overlays.dmi
Labels: Sprite Change

#7560 Some borg bugfixes
  code/_onclick/cyborg.dm
  code/modules/reagents/reagent_containers/syringes.dm
Labels: Oversight

#7565 Fix ventcrawling while in 0 gravity
  code/modules/mob/mob_movement.dm
Labels: Quality of Life

#7567 Fix a pizza issue.
  code/datums/supplypacks/hospitality.dm
Labels: Bugfix

#7568 Add a warning line to the supply computer about access.
  code/game/machinery/computer/supply.dm
Labels: Quality of Life

#7569 Removes Unused Map Files to reduce filebloat and map confusion
  maps/RandomZLevels/Academy.dm
  maps/RandomZLevels/Academy.dmm
  maps/RandomZLevels/arcticwaste.dmm
  maps/RandomZLevels/assistantChamber.dmm
  maps/RandomZLevels/beach.dmm
  maps/RandomZLevels/blackmarketpackers.dmm
  maps/RandomZLevels/challenge.dm
  maps/RandomZLevels/challenge.dmm
  maps/RandomZLevels/example.dmm
  maps/RandomZLevels/fileList.txt
  maps/RandomZLevels/jungle.dmm
  maps/RandomZLevels/listeningpost.dmm
  maps/RandomZLevels/spacebattle.dmm
  maps/RandomZLevels/stationCollision.dm
  maps/RandomZLevels/stationCollision.dmm
  maps/RandomZLevels/wildwest.dm
  maps/RandomZLevels/wildwest.dmm
  maps/RandomZLevels/zresearchlabs.dmm
  maps/plane/plane-1.dmm
  maps/plane/plane-2.dmm
  maps/plane/plane.dm
  maps/plane/plane_areas.dm
  maps/plane/plane_defines.dm
Labels: Map Change / Issue, Unwanted Feature Removal

#7570 Fading titlescreen from /tg/
  code/_onclick/hud/screen_objects.dm
  code/controllers/subsystems/ticker.dm
  code/modules/mob/new_player/new_player.dm
Labels: Feature, Ported from /TG/code

#7572 8 SPICY POIS!
  icons/obj/alien_smes.dmi
  maps/submaps/surface_submaps/wilderness/borglab.dmm
  maps/submaps/surface_submaps/wilderness/chasm.dmm
  maps/submaps/surface_submaps/wilderness/deathden.dmm
  maps/submaps/surface_submaps/wilderness/demonpool.dmm
  maps/submaps/surface_submaps/wilderness/derelictengine.dmm
  maps/submaps/surface_submaps/wilderness/frostoasis.dmm
  maps/submaps/surface_submaps/wilderness/wilderness.dm
  maps/submaps/surface_submaps/wilderness/wilderness_areas.dm
  maps/submaps/surface_submaps/wilderness/wolfden.dmm
  maps/submaps/surface_submaps/wilderness/xenohive.dmm
Labels: Point of Interest

#7574 Adds Engine Randomization on Mapload! (From VOREStation!)
  code/controllers/configuration.dm
  code/controllers/subsystems/mapping.dm
  maps/southern_cross/southern_cross-1.dmm
  maps/submaps/engine_submaps/engine.dm
  maps/submaps/engine_submaps/engine_areas.dm
  maps/submaps/engine_submaps/southern_cross/_engine_submaps.dm
  maps/submaps/engine_submaps/southern_cross/engine_rust.dmm
  maps/submaps/engine_submaps/southern_cross/engine_singulo.dmm
  maps/submaps/engine_submaps/southern_cross/engine_sme.dmm
  maps/submaps/engine_submaps/southern_cross/engine_tesla.dmm
  polaris.dme
Labels: Feature, Map Change / Issue, Prepare to Die

#7575 Make it so beer bottles are filled. No longer get scammed!
  code/modules/food/food/drinks/bottle.dm
Labels: Oversight

#7547 Station overmap sensors should connect automatically now
  code/modules/overmap/sectors.dm
  code/modules/overmap/ships/computers/sensors.dm
  code/modules/overmap/ships/computers/ship.dm
  code/modules/overmap/ships/ship.dm
Labels: Bugfix

#7559 Ladders respect Move Up/Down paradigm
  code/modules/multiz/movement.dm
  code/modules/multiz/structures.dm
  html/changelogs/atermonera - move updown.yml
Labels: Feature Tweak, Project

#7584 Reverts #7560, Adds Proper check to syringes.dm and flora.dm for borgs
  code/_onclick/cyborg.dm
  code/game/objects/structures/flora/flora.dm
  code/modules/reagents/reagent_containers/syringes.dm
Labels: Oversight, Priority: High

#7586 Travis only loads legal engines
  code/controllers/configuration.dm
Labels: Bugfix, Priority: CRITICAL, Travis Issue

#7576 Replace "Sleeping Agent" with Nitrous Oxide, Add New Sprites for Gases
  code/ATMOSPHERICS/components/omni_devices/_omni_extras.dm
  code/ATMOSPHERICS/components/trinary_devices/filter.dm
  code/ATMOSPHERICS/components/unary/vent_scrubber.dm
  code/ATMOSPHERICS/pipes/tank.dm
  code/datums/supplypacks/atmospherics.dm
  code/defines/gases.dm
  code/game/machinery/air_alarm.dm
  code/game/machinery/atmoalter/canister.dm
  code/game/machinery/atmoalter/scrubber.dm
  code/game/objects/effects/mines.dm
  code/game/objects/items/weapons/tanks/tank_types.dm
  code/game/turfs/flooring/flooring_premade.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/events/atmos_leak.dm
  code/modules/gamemaster/event2/events/engineering/gas_leak.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/modular_computers/file_system/programs/engineering/supermatter_monitor.dm
  code/modules/projectiles/guns/magnetic/gasthrower.dm
  code/modules/xenoarcheaology/effects/gassleeping.dm
  icons/effects/tile_effects.dmi
  maps/northern_star/polaris-1.dmm
  maps/northern_star/polaris-2.dmm
  maps/northern_star/polaris-5.dmm
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-4.dmm
  maps/southern_cross/southern_cross-6.dmm
Labels: Cannot Merge, Map Change / Issue, Refactor, Sprite Change

#7582 Hotfix for Ambience Freq Overwriting Ambience Chance on Save
  code/modules/client/preference_setup/global/01_ui.dm
Labels: Oversight

#7552 Adds hailer gas (face) masks.
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/masks/hailer.dm
  html/changelogs/splintergp - hailermasks.yml
  icons/mob/mask.dmi
  icons/mob/species/seromi/masks.dmi
  icons/mob/species/tajaran/mask.dmi
  icons/mob/species/vox/masks.dmi
  icons/obj/clothing/masks.dmi
  polaris.dme
  sound/voice/complionator/asshole.ogg
  sound/voice/complionator/bash.ogg
  sound/voice/complionator/bobby.ogg
  sound/voice/complionator/compliance.ogg
  sound/voice/complionator/dontmove.ogg
  sound/voice/complionator/dredd.ogg
  sound/voice/complionator/floor.ogg
  sound/voice/complionator/freeze.ogg
  sound/voice/complionator/god.ogg
  sound/voice/complionator/halt.ogg
  sound/voice/complionator/harry.ogg
  sound/voice/complionator/imperial.ogg
  sound/voice/complionator/justice.ogg
  sound/voice/complionator/robocop.ogg
  sound/voice/complionator/running.ogg
  sound/voice/complionator/shutup.ogg
  sound/voice/complionator/stfu.ogg
  sound/voice/complionator/super.ogg
Labels: Feature

#7561 Projectile Upkeep
  code/modules/projectiles/guns/energy/hooklauncher.dm
  code/modules/projectiles/guns/magic.dm
  code/modules/projectiles/guns/magic/fireball.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/hook.dm
  code/modules/projectiles/projectile/magic.dm
  icons/mob/back.dmi
  icons/mob/items/lefthand_magic.dmi
  icons/mob/items/lefthand_melee.dmi
  icons/mob/items/righthand_magic.dmi
  icons/mob/items/righthand_melee.dmi
  icons/obj/gun2.dmi
  icons/obj/projectiles.dmi
  icons/obj/wizard.dmi
  polaris.dme
Labels: Bugfix, Feature, Oversight
