Repository PolarisSS13/Polaris, pull requests merged in 2020-09, with the labels that each got.

#7609 Stop in the name of the law, open tag.
  code/modules/clothing/masks/hailer.dm
Labels: Bugfix, Priority: CRITICAL

#7573 Distillery Upkeep, Chemistry Tweakening
  code/datums/supplypacks/medical.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Core.dm
  code/modules/reagents/distilling/Distilling-Recipes.dm
  code/modules/reagents/distilling/distilling.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
  html/changelogs/Mechoid - distil4chem.yml
  maps/southern_cross/southern_cross-1.dmm
Labels: Feature, Map Change / Issue, Southern Cross

#7587 Fixes Teshari dresses
  code/modules/clothing/under/xenos/seromi.dm
Labels: Oversight

#7588 Adds ENGINE_MAP to example config
  config/example/config.txt
Labels: Refactor

#7589 Adds toe-less jackboots to xenowear
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
Labels: Feature

#7590 Some missed instances of Colony Director
  code/controllers/subsystems/ticker.dm
  code/game/gamemodes/events.dm
  code/modules/events/ion_storm.dm
  code/modules/mob/new_player/skill.dm
Labels: Oversight

#7591 Stops meson/etc use with overmap consoles
  code/modules/overmap/ships/computers/ship.dm
Labels: Oversight

#7593 Increases number of things that survive overmap ztransit
  code/modules/overmap/spacetravel.dm
Labels: Bugfix

#7596 Perspective-y drone fabricator from CEV-Eris
  icons/obj/machines/drone_fab.dmi
Labels: Sprite Change

#7600 Reduce the ore scanner time from 10 to 2 seconds. Same as the mech one.
  code/modules/mining/drilling/scanner.dm
Labels: Feature Tweak

#7602 Fix jetpack ion trail
  code/game/objects/effects/effect_system.dm
Labels: Bugfix

#7585 Adds two effect types for PoIs and theoretical future bossmobs.
  code/game/objects/effects/prop/columnblast.dm
  code/game/objects/effects/prop/snake.dm
  icons/effects/64x64.dmi
  icons/effects/effects.dmi
  polaris.dme
Labels: Feature

#7603 adds the ability to give loadout items a custom name/description
  code/modules/admin/topic.dm
  code/modules/client/preference_setup/loadout/gear_tweaks.dm
  code/modules/client/preference_setup/loadout/loadout.dm
  code/modules/client/preference_setup/loadout/loadout_accessories.dm
  code/modules/client/preference_setup/loadout/loadout_general.dm
  code/modules/client/preference_setup/loadout/loadout_gloves.dm
  code/modules/client/preference_setup/loadout/loadout_head.dm
  code/modules/client/preference_setup/loadout/loadout_shoes.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/client/preference_setup/loadout/loadout_utility.dm
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
Labels: Feature

#7618 Revert strafing speed nerf.
  code/game/mecha/components/actuators.dm
Labels: Feature Tweak, Results To Be Reviewed

#7622 Changes default skin tone from 35 to 110
  code/modules/client/preference_setup/general/03_body.dm
  code/modules/client/preferences.dm
Labels: Bikeshed

#7493 Allow mechs to butcher things with their drill.
  code/game/mecha/equipment/tools/drill.dm
  code/modules/mob/living/simple_mob/simple_mob.dm
  html/changelogs/Kot - Mechdrill.yml
Labels: Feature, Ported from /TG/code

#7632 changelog update
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Killian - randomstuff.yml
  html/changelogs/Killian - synth injections.yml
  html/changelogs/Kot - Mechdrill.yml
  html/changelogs/Lorilili - borgpet.yml
  html/changelogs/Lorilili - footwear.yml
  html/changelogs/Mechoid - distil4chem.yml
  html/changelogs/atermonera - move updown.yml
  html/changelogs/rykka-stormheart - ambience prefs.yml
  html/changelogs/rykka-stormheart - toy mechs.yml
  html/changelogs/shadowlarkens - job preferences.yml
  html/changelogs/splintergp - hailermasks.yml
Labels: Changelog Update

#7597 Adds Toggles to Revert to Legacy Door Sounds and Enable Department Doors
  code/game/gamemodes/technomancer/spells/audible_deception.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/blast_door.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/mecha/equipment/tools/clamp.dm
  code/game/mecha/mecha.dm
  code/global.dm
  code/modules/client/preference_setup/global/setting_datums.dm
  code/modules/client/preferences_toggle_procs.dm
  code/modules/flufftext/Hallucination.dm
  sound/machines/door/airlock_creaking.ogg
  sound/machines/door/airlockcycle.ogg
  sound/machines/door/airlockforced.ogg
  sound/machines/door/blastdoorclose.ogg
  sound/machines/door/blastdooropen.ogg
  sound/machines/door/boltsdown.ogg
  sound/machines/door/boltsup.ogg
  sound/machines/door/old_airlock.ogg
  sound/machines/door/old_airlockclose.ogg
  sound/machines/door/windowdoor.ogg
Labels: Feature, Results To Be Reviewed, Staff Request

#7607 Fixes the hacktool.
  code/game/objects/items/devices/hacktool.dm
Labels: Bugfix

#7654 Fixes runtime in Chemistry-Reagents-Food-Drinks.dm,25: bad index
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
Labels: Oversight

#7662 Allows non-shell borgs to use static camera consoles.
  code/game/machinery/computer/camera.dm
Labels: Bugfix

#7663 Makes demonpool loot piles actual loot piles.
  maps/submaps/surface_submaps/wilderness/demonpool.dmm
Labels: Oversight, Point of Interest

#7664 Enforces adjacency on wall rechargers
  code/game/machinery/recharger.dm
Labels: Bugfix

#7665 /atom/visible_message respects exclude_mobs
  code/modules/mob/mob.dm
Labels: Bugfix

#7666 AI eye no longer appears on turf tab
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/mob_defines.dm
Labels: Bugfix

#7655 Fixes janitor cart examine
  code/game/objects/structures/janicart.dm
Labels: Bugfix

#7628 [MAPPING] Fuel Port Subtypes
  code/modules/overmap/overmap_shuttle.dm
Labels: Refactor

#7657 Should fix unset PDA name glitches
  code/modules/mob/living/carbon/human/human.dm
Labels: Bugfix, Priority: High

#7658 Fix stripping.dm cloning
  code/modules/mob/living/carbon/human/stripping.dm
Labels: Bugfix

#7659 Fix trying to put people on themselves with the stripping menu
  code/modules/mob/living/carbon/human/stripping.dm
  html/changelogs/Meghan Rossi - stripping.yml
Labels: Bugfix

#7660 Fix duplicate results from analyzing some objects
  code/ATMOSPHERICS/pipes/tank.dm
  code/game/machinery/atmoalter/portable_atmospherics.dm
  code/game/objects/items/weapons/flamethrower.dm
  code/game/objects/items/weapons/tanks/tanks.dm
  code/modules/power/singularity/particle_accelerator/particle_smasher.dm
  html/changelogs/Meghan Rossi - atmosanalyzer.yml
Labels: Bugfix

#7675 Fixes compile errors in code\modules\projectiles\broken.dm:42,44
  code/modules/projectiles/broken.dm
Labels: Oversight, Priority: CRITICAL

#7638 Remove broken, unused commcard system from communicators
  code/game/objects/items/devices/communicator/UI.dm
  code/game/objects/items/devices/communicator/cartridge.dm
  code/game/objects/items/devices/communicator/communicator.dm
  code/game/objects/items/devices/communicator/helper.dm
  nano/templates/comm_power_monitor.tmpl
  nano/templates/emp_records.tmpl
  nano/templates/gps_access.tmpl
  nano/templates/janitorialLocator.tmpl
  nano/templates/med_records.tmpl
  nano/templates/merc_blast_door_control.tmpl
  nano/templates/sec_bot_access.tmpl
  nano/templates/sec_records.tmpl
  nano/templates/signaler_access.tmpl
  nano/templates/stat_display_access.tmpl
  polaris.dme
Labels: Requires Developer Input, Unwanted Feature Removal

#7668 Actually commit the reagent cycler's entire gimmick.
  code/modules/organs/internal/stomach.dm
Labels: Bugfix, Oversight

#7669 Fix Beaker Dipping
  code/modules/reagents/reagent_containers/glass.dm
Labels: Bugfix

#7672 Fix fat tasting bitter
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  html/changelogs/Meghan Rossi - triglyceride taste.yml
Labels: Feature Tweak

#7673 Gives mob xenos full darksight
  code/modules/mob/living/simple_mob/subtypes/animal/space/alien.dm
Labels: Feature Tweak

#7641 Fix communicator video
  code/modules/mob/living/life.dm
Labels: Bugfix

#7667 Adds lrifle_open sprite for lrifle set
  icons/obj/gun.dmi
Labels: Bugfix, Sprite Change

#7676 Fixes runtime in add_reagent()
  code/modules/reagents/Chemistry-Holder.dm
Labels: Bugfix

#7677 Fixes runtime in prison_break.dm
  code/modules/gamemaster/event2/events/security/prison_break.dm
Labels: Bugfix, Higgs Bugson

#7630 Exo Encumberence
  code/game/mecha/combat/combat.dm
  code/game/mecha/combat/phazon.dm
  code/game/mecha/mecha.dm
  code/game/mecha/working/ripley.dm
  html/changelogs/Mechoid - Encumbrance.yml
Labels: Feature Tweak

#7679 Cycler sprite check fixes
  code/game/machinery/suit_storage_unit.dm
Labels: Oversight

#7691 Sets the cosmetic tab's name to Genetics.
  code/modules/client/preference_setup/virgo/01_spriteaccessories.dm
Labels: Lore, Priority: CRITICAL

#7686 Allow separate overlays file for modular computers
  code/modules/modular_computers/computers/modular_computer/core.dm
  code/modules/modular_computers/computers/modular_computer/variables.dm
Labels: Refactor

#7684 Diagonal barricade cleave exploit fix
  code/game/objects/weapons.dm
Labels: Bugfix

#7685 Teshari sprites and white eyepatch
  code/modules/client/preference_setup/loadout/loadout_eyes.dm
  code/modules/clothing/glasses/glasses.dm
  icons/mob/eyes.dmi
  icons/mob/human_races/cyberlimbs/unbranded/unbranded_teshari.dmi
  icons/mob/species/seromi/ears.dmi
  icons/mob/species/seromi/eyes.dmi
  icons/mob/species/seromi/head.dmi
  icons/mob/species/seromi/ties.dmi
  icons/obj/clothing/glasses.dmi
Labels: Feature

#7688 Add U as hotkey to rest
  interface/skin.dmf
Labels: Feature

#7689 Job controller now uses using_map email TLD
  code/game/jobs/job_controller.dm
Labels: Lore

#7690 Berry
  code/modules/food/recipes_oven.dm
Labels: Bugfix
