Repository PolarisSS13/Polaris, pull requests merged in 2020-05, with the labels that each got.

#7047 Actually Adds Teshari White Apron Sprite & Fixes Name of Labcoat
  icons/mob/species/seromi/suit.dmi
Labels: Oversight, Sprite Change

#7051 Tweak to mining scanner
  code/modules/mining/drilling/scanner.dm
Labels: Quality of Life

#7062 changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Leshana-vplk-shuttle-construction.yml
  html/changelogs/Lshana-vplk-gameticker.yml
  html/changelogs/Shadow_Airlocks.yml
  html/changelogs/Shadow_flashingcells.yml
  html/changelogs/atlantiscze-valveprogram.yml
  html/changelogs/atlantiscze-xenoarch.yml
  html/changelogs/neerti_all_the_food.yml
  html/changelogs/novacat-dualwielding.yml
Labels: Changelog Update

#7066 Make failing unit tests actually fail travis checks.
  tools/travis/compile_and_run.sh
Labels: Oversight, Priority: CRITICAL

#7056 Adds some hyperlink functionality
  code/modules/vchat/js/vchat.js
Labels: Quality of Life

#7068 Fix Mob Examine
  code/modules/mob/living/simple_mob/harvesting.dm
Labels: Bugfix, Priority: High

#7069 Fix Temp check.
  code/modules/mob/living/carbon/human/life.dm
Labels: Bugfix, Priority: High

#7070 I love BYOND RNG, it is perfect and 100% reliable for testing.
  code/game/objects/random/mob.dm
  code/game/turfs/simulated/outdoors/grass.dm
Labels: Bugfix, Priority: High

#7043 Promethean Language
  code/__defines/species_languages.dm
  code/modules/mob/language/station.dm
  code/modules/mob/living/carbon/human/species/station/prometheans.dm
  code/modules/mob/living/say.dm
  code/modules/vchat/css/ss13styles.css
  code/stylesheet.dm
  html/changelogs/Layne - Promethean Language.yml
Labels: Feature

#7049 Overmap Consoles now check access
  code/__defines/__513_compatibility.dm
  code/modules/overmap/ships/computers/computer_shims.dm
Labels: Feature Tweak

#7058 Allows backpacks to be carried on most hardsuits
  code/modules/clothing/spacesuits/rig/suits/alien.dm
  code/modules/clothing/spacesuits/rig/suits/combat.dm
  code/modules/clothing/spacesuits/rig/suits/ert.dm
  code/modules/clothing/spacesuits/rig/suits/light.dm
  code/modules/clothing/spacesuits/rig/suits/merc.dm
  code/modules/clothing/spacesuits/rig/suits/pmc.dm
  code/modules/clothing/spacesuits/rig/suits/station.dm
  html/changelogs/atlantiscze-hardsuit.yml
Labels: Feature, Results To Be Reviewed

#7010 Ports over power-related enhancements and tweaks i coded for Bay a while back
  code/__defines/machinery.dm
  code/datums/wires/smes.dm
  code/defines/obj/weapon.dm
  code/game/objects/items/weapons/circuitboards/machinery/power.dm
  code/game/objects/structures/loot_piles.dm
  code/modules/power/apc.dm
  code/modules/power/batteryrack.dm
  code/modules/power/cable.dm
  code/modules/power/cell.dm
  code/modules/power/debug_items.dm
  code/modules/power/fractal_reactor.dm
  code/modules/power/power.dm
  code/modules/power/powernet.dm
  code/modules/power/smes.dm
  code/modules/power/smes_construction.dm
  code/modules/power/terminal.dm
  html/changelogs/atlantiscze-power.yml
  icons/obj/cellrack.dmi
  maps/example/example-2.dmm
  nano/templates/psu.tmpl
  polaris.dme
Labels: Feature Tweak, Refactor

#7057 Allows robots to search loot piles
  code/game/objects/structures/loot_piles.dm
  html/changelogs/atlantiscze-dumpsterdive.yml
Labels: Feature Tweak

#7060 Ling Fixes + Various other fixes
  code/game/gamemodes/changeling/changeling_powers.dm
  code/game/gamemodes/changeling/powers/augmented_eyesight.dm
  code/game/gamemodes/changeling/powers/endoarmor.dm
  code/game/gamemodes/changeling/powers/fake_death.dm
  code/game/gamemodes/changeling/powers/respec.dm
  code/game/gamemodes/changeling/powers/revive.dm
  code/game/objects/items/weapons/swords_axes_etc.dm
  code/modules/mob/_modifiers/changeling.dm
  code/modules/mob/_modifiers/modifiers.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/life.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  polaris.dme
Labels: Bugfix

#7065 Speech Bubble Adjustments
  code/modules/mob/living/carbon/human/say.dm
Labels: Feature Tweak

#7072 Fix Broken Gun Examining
  code/modules/projectiles/broken.dm
Labels: Bugfix

#7075 Fixes weed related runtimes
  code/__defines/is_helpers.dm
  code/game/objects/effects/alien/aliens.dm
Labels: Bugfix

#7076 Fixes some Xenobio bugs
  code/modules/ai/aI_holder_subtypes/slime_xenobio_ai.dm
  code/modules/ai/ai_holder.dm
Labels: Bugfix

#7077 Kururaks now (theoretically) are not as agonizing to fight.
  code/modules/mob/living/simple_mob/subtypes/animal/sif/kururak.dm
Labels: Bugfix, Results To Be Reviewed

#7081 Add radial menus for mech occupants
  code/game/mecha/mecha.dm
  icons/mob/radial.dmi
Labels: Feature

#7055 Updates machines to use default_apply_parts()
  code/ATMOSPHERICS/components/unary/cold_sink.dm
  code/ATMOSPHERICS/components/unary/heat_source.dm
  code/game/dna/dna_modifier.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/adv_med.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/biogenerator.dm
  code/game/machinery/bioprinter.dm
  code/game/machinery/cell_charger.dm
  code/game/machinery/cloning.dm
  code/game/machinery/exonet_node.dm
  code/game/machinery/jukebox.dm
  code/game/machinery/machinery.dm
  code/game/machinery/mass_driver.dm
  code/game/machinery/pda_multicaster.dm
  code/game/machinery/recharger.dm
  code/game/machinery/rechargestation.dm
  code/game/machinery/telecomms/broadcaster.dm
  code/game/machinery/telecomms/telecomunications.dm
  code/game/machinery/teleporter.dm
  code/game/machinery/virtual_reality/vr_console.dm
  code/game/machinery/washing_machine.dm
  code/game/mecha/mech_bay.dm
  code/game/mecha/mech_fabricator.dm
  code/game/mecha/mech_prosthetics.dm
  code/modules/detectivework/microscope/dnascanner.dm
  code/modules/food/kitchen/microwave.dm
  code/modules/mining/drilling/drill.dm
  code/modules/paperwork/papershredder.dm
  code/modules/paperwork/photocopier.dm
  code/modules/power/batteryrack.dm
  code/modules/power/grid_checker.dm
  code/modules/power/pacman2.dm
  code/modules/power/port_gen.dm
  code/modules/power/smes_construction.dm
  code/modules/reagents/Chemistry-Machinery.dm
  code/modules/recycling/conveyor2.dm
  code/modules/research/circuitprinter.dm
  code/modules/research/destructive_analyzer.dm
  code/modules/research/protolathe.dm
  code/modules/research/server.dm
  code/modules/xenobio2/machinery/core_extractor.dm
  code/modules/xenobio2/machinery/gene_manipulators.dm
  code/modules/xenobio2/machinery/injector.dm
  code/modules/xenobio2/machinery/slime_replicator.dm
Labels: Refactor

#7086 Tweak bluespace backpack radio
  code/game/machinery/telecomms/broadcaster.dm
  code/game/objects/items/devices/radio/radiopack.dm
Labels: Bugfix

#7088 Fix SMES and debug power item examine messages
  code/modules/power/debug_items.dm
  code/modules/power/smes.dm
Labels: Oversight

#7089 Fix an overcharged smes from breaking charging on other smes.
  code/modules/power/smes.dm
Labels: Bugfix

#7091 [PORT] Use can_atmos_pass to reduce proc-calls in c_airblock()
  code/ZAS/Atom.dm
  code/__defines/ZAS.dm
  code/__defines/atmos.dm
  code/game/machinery/doors/blast_door.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/effects/zone_divider.dm
  code/game/objects/structures/window.dm
  code/modules/mob/living/living_movement.dm
  code/modules/power/turbine.dm
Labels: Optimization, Refactor

#7092 Fix out-of-order role candidate options
  code/__defines/gamemode.dm
  code/modules/client/preference_setup/antagonism/02_candidacy.dm
Labels: Higgs Bugson, Oversight

#7093 Fix condiment container infinite range
  code/modules/food/food/condiment.dm
Labels: Oversight

#7094 Fix protein shaker name
  code/modules/food/drinkingglass/shaker.dm
Labels: Bugfix

#7096 Fiftyspawners try to place themselves in crates if possible
  code/game/objects/items/stacks/fifty_spawner.dm
Labels: Feature Tweak

#7097 Prevent ghosts/others from messing with hydrotrays
  code/modules/hydroponics/trays/tray.dm
Labels: Oversight

#7100 Don't show borgs alarms not local to them
  code/modules/mob/living/silicon/silicon.dm
Labels: Feature Tweak

#7101 Fixes Promethean Language
  code/__defines/species_languages.dm
Labels: Oversight

#7064 Adds preference to control multilingual behaviour
  code/__defines/preferences.dm
  code/game/atoms.dm
  code/modules/client/client defines.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_toggle_procs.dm
  code/modules/mob/say.dm
  html/changelogs/atermonera_multilingual_pref.yml
Labels: Bugfix, Feature Tweak

#7059 Supermatter delamination tweaks
  code/modules/power/singularity/act.dm
  code/modules/power/supermatter/supermatter.dm
  html/changelogs/atlantiscze-sm.yml
Labels: Feature, Refactor

#7099 Rewrite airlock electronics
  code/game/machinery/doors/airlock_electronics.dm
Labels: Feature Tweak

#7110 adds logging variable to enable shuttle log spam
  code/modules/shuttles/shuttle.dm
  code/modules/shuttles/shuttle_autodock.dm
  code/modules/shuttles/shuttle_console.dm
  code/modules/shuttles/shuttle_emergency.dm
  code/modules/shuttles/shuttles_web.dm
  code/modules/shuttles/web_datums.dm
Labels: Feature Tweak, Quality of Life

#7108 Fixes #7079
  maps/submaps/surface_submaps/wilderness/DecoupledEngine.dmm
Labels: Bugfix, Point of Interest

#7111 Fixes #7017
  code/game/machinery/computer/shutoff_monitor.dm
Labels: Bugfix

#7112 Fixes #6887
  maps/southern_cross/southern_cross-1.dmm
Labels: Map Change / Issue, Oversight

#7113 mechs trigger mines. They're not very effective...
  code/game/objects/effects/mines.dm
Labels: Bugfix

#7132 Prevents simplemob spawning on random turfs, pending a better system.
  code/game/turfs/simulated/outdoors/grass.dm
Labels: Oversight, Priority: CRITICAL, Revert, Staff Request

#7061 FloorTiles now properly show damage.
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/simulated/floor_icon.dm
Labels: Bugfix

#7085 Quick fix for communicators
  code/game/machinery/telecomms/telecomunications.dm
Labels: Bugfix

#7102 Ian shirt for Teshari attempt 2
  icons/mob/species/seromi/suit.dmi
Labels: Sprite Change

#7087 Port SSnightshift from Paradise
  code/__defines/lighting.dm
  code/__defines/subsystems.dm
  code/_helpers/time.dm
  code/controllers/autotransfer.dm
  code/controllers/configuration.dm
  code/controllers/subsystems/game_master.dm
  code/controllers/subsystems/nightshift.dm
  code/controllers/subsystems/planets.dm
  code/game/gamemodes/game_mode_latespawn.dm
  code/game/machinery/exonet_node.dm
  code/game/machinery/newscaster.dm
  code/game/world.dm
  code/modules/events/event_container.dm
  code/modules/integrated_electronics/subtypes/time.dm
  code/modules/planet/time.dm
  code/modules/power/apc.dm
  code/modules/power/lighting.dm
  code/modules/security levels/security levels.dm
  config/example/config.txt
  maps/~map_system/maps.dm
  nano/templates/apc.tmpl
  polaris.dme
Labels: Feature

#7103 Fix for Resetting a Character Slot
  code/modules/client/preferences_savefile.dm
Labels: Bugfix

#7104 Refactor some job joining things related to robofriends
  code/__defines/misc.dm
  code/controllers/subsystems/ticker.dm
  code/game/antagonist/antagonist.dm
  code/game/antagonist/antagonist_helpers.dm
  code/game/antagonist/station/changeling.dm
  code/game/antagonist/station/cultist.dm
  code/game/antagonist/station/loyalist.dm
  code/game/antagonist/station/renegade.dm
  code/game/antagonist/station/revolutionary.dm
  code/game/antagonist/station/stowaway.dm
  code/game/antagonist/station/thug.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/silicon.dm
  code/game/jobs/job_controller.dm
  code/modules/client/preferences_spawnpoints.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/mob/transform_procs.dm
Labels: Refactor

#7105 Redo teleporter control in nanoui
  code/_onclick/observer.dm
  code/game/machinery/teleporter.dm
  code/game/objects/items/weapons/teleportation.dm
  nano/templates/teleport_control.tmpl
Labels: Feature

#7106 Make multikey warning less rude
  code/modules/mob/login.dm
Labels: Feature Tweak

#7107 Prevent holopad chat from going to lobby
  code/modules/mob/new_player/new_player.dm
Labels: Oversight

#7109 Fix very curious orbit offset issue (513?)
  code/datums/orbit.dm
Labels: Bugfix

#7098 Update R&D Console, Autolathes
  code/game/machinery/autolathe.dm
  code/modules/research/rdconsole.dm
Labels: Feature Tweak, Quality of Life

#7118 Check power on machine build
  code/game/machinery/machinery.dm
Labels: Oversight

#7123 Ports Aurora record laptop sprites
  code/game/machinery/computer/atmos_control.dm
  icons/obj/computer.dmi
Labels: Sprite Change

#7124 Fancier Mixer Sprites
  icons/obj/chemical.dmi
Labels: Sprite Change

#7125 Ports Vore Telecomms Sprites
  code/game/machinery/pda_multicaster.dm
  code/game/machinery/telecomms/broadcaster.dm
  code/modules/modular_computers/NTNet/NTNet_relay.dm
  icons/obj/stationobjs.dmi
Labels: Sprite Change

#7128 [PORT] Military Jackets
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/clothing/suits/miscellaneous.dm
  icons/mob/suit_1.dmi
  icons/obj/clothing/suits_1.dmi
Labels: Feature

#7129 Fix weird stray commas
  code/game/mecha/mecha.dm
Labels: Higgs Bugson, Oversight

#7130 Add bluespace flare to research designs
  code/modules/research/designs/misc.dm
Labels: Feature

#7135 Port Hover Inventory and Body Indicators
  code/_onclick/hud/human.dm
  code/_onclick/hud/screen_objects.dm
  code/game/objects/items/weapons/storage/internal.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/gloves/arm_guards.dm
  code/modules/clothing/gloves/gauntlets.dm
  code/modules/clothing/masks/monitor.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/clothing/suits/armor.dm
Labels: Feature

#7149 Fix an exploit
  code/modules/reagents/Chemistry-Machinery.dm
Labels: Bugfix, Priority: CRITICAL

#7137 CLAMP Backwards Compatibility Fix
  code/modules/power/smes.dm
Labels: BYOND Issue, Bugfix

#7039 Tesh suits port
  icons/mob/species/seromi/head.dmi
  icons/mob/species/seromi/suit.dmi
Labels: Sprite Change

#7080 Add UAVs
  code/_helpers/game.dm
  code/game/machinery/doors/door.dm
  code/game/objects/items/uav.dm
  code/game/objects/objs.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/life.dm
  code/modules/mob/mob_movement.dm
  code/modules/modular_computers/computers/modular_computer/core.dm
  code/modules/modular_computers/file_system/program.dm
  code/modules/modular_computers/file_system/programs/generic/uav.dm
  code/modules/modular_computers/hardware/network_card.dm
  code/modules/nano/modules/nano_module.dm
  code/modules/research/mechfab_designs.dm
  icons/obj/uav.dmi
  nano/templates/mod_uav.tmpl
  polaris.dme
Labels: Feature

#7052 Refactor Move() Code
  code/datums/helper_datums/teleport.dm
  code/game/atoms_movable.dm
  code/game/gamemodes/meteor/meteors.dm
  code/game/machinery/CableLayer.dm
  code/game/machinery/computer/camera.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/multi_tile.dm
  code/game/machinery/floorlayer.dm
  code/game/machinery/pipe/construction.dm
  code/game/machinery/pipe/pipelayer.dm
  code/game/mecha/mecha.dm
  code/game/objects/buckling.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/effects/explosion_particles.dm
  code/game/objects/items/shooting_range.dm
  code/game/objects/items/weapons/weaponry.dm
  code/game/objects/structures/door_assembly.dm
  code/game/objects/structures/janicart.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
  code/game/objects/structures/target_stake.dm
  code/game/objects/structures/window.dm
  code/modules/assembly/holder.dm
  code/modules/assembly/infrared.dm
  code/modules/assembly/proximity.dm
  code/modules/lighting/lighting_atom.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/freelook/ai/update_triggers.dm
  code/modules/mob/freelook/mask/update_triggers.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/silicon/robot/robot_movement.dm
  code/modules/mob/living/simple_mob/subtypes/animal/farm animals/goat.dm
  code/modules/mob/living/simple_mob/subtypes/animal/space/worm.dm
  code/modules/mob/mob_movement.dm
  code/modules/multiz/zshadow.dm
  code/modules/overmap/events/overmap_event.dm
  code/modules/power/singularity/particle_accelerator/particle_accelerator.dm
  code/modules/projectiles/projectile.dm
  code/modules/vehicles/quad.dm
  code/modules/vehicles/train.dm
  code/modules/xenoarcheaology/artifacts/artifact.dm
Labels: Refactor

#7082 Refactor move/click code and cooldowns
  code/__defines/is_helpers.dm
  code/_helpers/time.dm
  code/_onclick/ai.dm
  code/_onclick/click.dm
  code/_onclick/cyborg.dm
  code/_onclick/hud/action.dm
  code/_onclick/hud/screen_objects.dm
  code/_onclick/observer.dm
  code/_onclick/rig.dm
  code/datums/riding.dm
  code/defines/obj.dm
  code/game/atoms_movable.dm
  code/game/objects/buckling.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/weaponry.dm
  code/game/objects/structures/door_assembly.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/target_stake.dm
  code/game/turfs/turf.dm
  code/modules/admin/verbs/smite.dm
  code/modules/ai/interfaces.dm
  code/modules/client/client defines.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/inventory.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_movement.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_movement.dm
  code/modules/mob/living/simple_mob/simple_mob.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_grab.dm
  code/modules/mob/mob_movement.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/multiz/structures.dm
  code/modules/projectiles/targeting/targeting_triggers.dm
  code/modules/vehicles/vehicle.dm
Labels: Quality of Life, Refactor

#7114 Fixes #649
  code/modules/admin/admin_tools.dm
  code/modules/admin/verbs/randomverbs.dm
Labels: Bugfix, Higgs Bugson

#7121 Door shock() always has a cooldown
  code/game/machinery/doors/airlock.dm
Labels: Bugfix

#7134 Random item spawners qdel properly on init without using sleep
  code/game/objects/random/_random.dm
Labels: Oversight

#7148 cleans up advanced_who output
  code/game/verbs/advanced_who.dm
  code/modules/vchat/css/ss13styles.css
  code/stylesheet.dm
Labels: Feature Tweak

#7161 changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Layne - Promethean Language.yml
  html/changelogs/atermonera_multilingual_pref.yml
  html/changelogs/atlantiscze-dumpsterdive.yml
  html/changelogs/atlantiscze-hardsuit.yml
  html/changelogs/atlantiscze-power.yml
  html/changelogs/atlantiscze-sm.yml
  html/changelogs/mechoid-newhorizon.yml
Labels: Changelog Update

#7162 Fixes Runtime in ,: bad arg name 'disable_warning'
  code/game/objects/items.dm
  code/game/objects/items/weapons/storage/internal.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/gloves/arm_guards.dm
  code/modules/clothing/gloves/gauntlets.dm
  code/modules/clothing/shoes/leg_guards.dm
  code/modules/clothing/suits/armor.dm
Labels: Bugfix

#7163 Event managers are hot pink
  code/game/verbs/ooc.dm
Labels: Bugfix

#7090 Don't give POI SMES more charge than possible
  code/modules/power/smes_construction.dm
Labels: Oversight

#7115 Add some ctrl/alt vehicle helper clicks
  code/modules/vehicles/bike.dm
  code/modules/vehicles/cargo_train.dm
Labels: Feature Tweak

#7116 When looking at machines, don't allow mesons/material/etc
  code/game/machinery/machinery.dm
  code/modules/overmap/ships/computers/ship.dm
Labels: Feature Tweak

#7120 Fixes player control not disabling mob AI
  code/modules/ai/ai_holder.dm
Labels: Bugfix

#7122 Make buildmode AI control reset home turfs when move orders given
  code/modules/admin/verbs/buildmode.dm
Labels: Feature Tweak, Mob AI Issue

#7139 Even More GPS Variety
  code/game/objects/items/devices/gps.dm
  icons/obj/gps.dmi
Labels: Sprite Change

#7144 Allows fax machine toner replacement
  code/modules/paperwork/faxmachine.dm
Labels: Bugfix

#7145 Fix missing dash breaking numbers in URL ends
  code/modules/vchat/js/vchat.js
Labels: Higgs Bugson, Oversight

#7147 Give Mining Drones a proper fire delay.
  code/modules/mob/living/simple_mob/subtypes/mechanical/drones/mining_drone.dm
Labels: Oversight

#7150 [QOL] More Readable CMC
  nano/css/shared.css
  nano/templates/crew_monitor.tmpl
Labels: Quality of Life

#7151 Port tg/other hunger icons, and give synths their own
  code/modules/mob/living/carbon/human/life.dm
  icons/mob/screen/holo.dmi
  icons/mob/screen/midnight.dmi
  icons/mob/screen/minimalist.dmi
  icons/mob/screen/old-noborder.dmi
  icons/mob/screen/old.dmi
  icons/mob/screen/orange.dmi
  icons/mob/screen/white.dmi
Labels: Sprite Change

#7154 Fix missing icons for cigars/pipes/cigarettes for Taj/Unathi
  icons/mob/species/tajaran/mask.dmi
  icons/mob/species/unathi/mask.dmi
Labels: Bugfix, Sprite Change

#7156 Fix sofa icon layering
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
Labels: Bugfix

#7165 Fixes AI Eye Examining
  code/modules/mob/freelook/eye.dm
Labels: Bugfix

#7166 [Map/Bugfix/Southern Cross] Fix #7140
  maps/southern_cross/southern_cross-1.dmm
Labels: Map Change / Issue

#7174 Add a few more move tweaks
  code/_onclick/rig.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_movement.dm
  code/modules/mob/living/simple_mob/simple_mob.dm
Labels: Oversight

#7146 Small overhaul of floor icon generation
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor_icon.dm
  code/game/turfs/simulated/lava.dm
  code/game/turfs/simulated/outdoors/outdoors.dm
  code/game/turfs/simulated/water.dm
  icons/turf/outdoors_edge.dmi
Labels: Refactor

#7176 Custom RIGs function properly.
  code/game/objects/items/paintkit.dm
  icons/mob/custom_items_mob.dmi
  icons/mob/custom_items_rig_boots.dmi
  icons/mob/custom_items_rig_gloves.dmi
  icons/mob/custom_items_rig_helmet.dmi
  icons/mob/custom_items_rig_suit.dmi
  icons/obj/custom_items_obj.dmi
Labels: Bugfix, Priority: Medium

#7083 Port Bay's Catwalks
  code/game/objects/structures.dm
  code/game/objects/structures/catwalk.dm
  code/modules/multiz/movement.dm
  code/modules/tables/tables.dm
  icons/turf/catwalks.dmi
Labels: Feature, Ported from Baycode

#7095 Add cooldown to pen clicks
  code/modules/paperwork/pen.dm
Labels: Bikeshed, Feature Tweak

#7133 Upstream Port of Footstep Sounds for multiple tiles.
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/flooring/flooring_premade.dm
  code/game/turfs/simulated/lava.dm
  code/game/turfs/simulated/outdoors/dirt.dm
  code/game/turfs/simulated/outdoors/grass.dm
  code/game/turfs/simulated/outdoors/outdoors.dm
  code/game/turfs/simulated/water.dm
  code/game/turfs/unsimulated/beach.dm
  code/modules/mining/mine_turfs.dm
  icons/turf/outdoors.dmi
  sound/effects/footstep/HeavySand1.ogg
  sound/effects/footstep/HeavySand2.ogg
  sound/effects/footstep/HeavySand3.ogg
  sound/effects/footstep/HeavySand4.ogg
  sound/effects/footstep/LightDirt2.ogg
  sound/effects/footstep/LightDirt4.ogg
  sound/effects/footstep/LightStone1.ogg
  sound/effects/footstep/LightStone2.ogg
  sound/effects/footstep/LightStone3.ogg
  sound/effects/footstep/LightStone4.ogg
  sound/effects/footstep/MedDirt1.ogg
  sound/effects/footstep/MedDirt2.ogg
  sound/effects/footstep/MedDirt3.ogg
  sound/effects/footstep/MedDirt4.ogg
  sound/effects/footstep/bubbles3.ogg
  sound/effects/footstep/bubbles4.ogg
  sound/effects/footstep/bubbles5.ogg
  sound/effects/footstep/mud1.ogg
  sound/effects/footstep/mud2.ogg
  sound/effects/footstep/mud3.ogg
  sound/effects/footstep/mud4.ogg
Labels: Feature

#7195 Fixes runtime in antagonist_helpers.dm, line 15
  code/game/antagonist/antagonist_helpers.dm
Labels: Bugfix, Priority: High, Results To Be Reviewed, Staff Request

#7193 Edit Appearance and Change Appearance update icon sex
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/change_appearance.dm
  code/modules/mob/living/carbon/human/appearance.dm
  code/modules/organs/organ_icon.dm
  polaris.dme
Labels: Bugfix

#7196 Fixes runtime in ravenous_macrophage.dm, line 26: Cannot read null.mind
  code/modules/blob2/overmind/types/ravenous_macrophage.dm
Labels: Oversight

#7206 Allows you to toggle off Byond/Discord/URLs in OOC
  code/controllers/configuration.dm
  code/game/verbs/ooc.dm
  config/example/config.txt
Labels: Feature

#7153 Photocopier improvements and NanoUI fixes!
  code/modules/paperwork/photocopier.dm
  nano/templates/photocopier.tmpl
Labels: Refactor

#7155 Optimize what starts in SSobj
  code/datums/observation/power_change.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/devices/geiger.dm
  code/game/objects/items/devices/radio/intercom.dm
  code/game/objects/items/devices/suit_cooling.dm
  code/game/objects/items/weapons/tanks/jetpack.dm
  code/game/objects/items/weapons/tanks/tank_types.dm
  code/game/objects/items/weapons/tanks/tanks.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/power/lighting.dm
  polaris.dme
Labels: Optimization, Refactor

#7171 Add inventory item tooltips
  code/__defines/is_helpers.dm
  code/game/objects/items.dm
  code/modules/client/preference_setup/global/setting_datums.dm
  code/modules/client/preferences_toggle_procs.dm
Labels: Feature

#7172 Hybrid tools buffs.
  code/game/objects/items/weapons/tools/screwdriver.dm
  code/game/objects/items/weapons/tools/weldingtool.dm
  code/game/objects/items/weapons/tools/wirecutters.dm
  code/game/objects/items/weapons/tools/wrench.dm
Labels: Feature Tweak, Unwanted Feature Removal

#7175 Fix bad arg
  code/modules/mob/living/damage_procs.dm
Labels: Oversight

#7177 Port over AI Opening Doors from Paradise
  code/game/machinery/camera/tracking.dm
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Quality of Life

#7178 Fixes mousedrop shenanigans
  code/game/machinery/OpTable.dm
  code/game/machinery/oxygen_pump.dm
Labels: Bugfix

#7179 Make blood generation less garbage
  code/game/objects/items.dm
Labels: Optimization

#7182 Add serial comma
  code/_helpers/_lists.dm
Labels: Feature Tweak

#7184 adds some coats for teshari + fancy clothes
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
  code/modules/clothing/suits/aliens/seromi.dm
  code/modules/clothing/under/xenos/seromi.dm
  icons/mob/species/seromi/suit.dmi
  icons/obj/clothing/species/seromi/suits.dmi
  icons/obj/clothing/species/seromi/uniform.dmi
Labels: Feature, Sprite Change

#7186 Update old robot parts sprites
  icons/obj/robot_component.dmi
Labels: Sprite Change

#7187 Add grey railing
  code/game/objects/structures/railing.dm
  icons/obj/railing.dmi
Labels: Feature

#7188 New modular component sprites
  icons/obj/modular_components.dmi
Labels: Sprite Change

#7191 These can't be material stacks if they don't have a material
  code/game/machinery/washing_machine.dm
  code/game/objects/items/stacks/sheets/leather.dm
Labels: Oversight

#7224 Fixes runtime in AI generation
  code/modules/mob/transform_procs.dm
Labels: Oversight, Priority: High

#7226 Fixes runtime in ticker.dm, 411: Cannot read null.mobtype
  code/controllers/subsystems/ticker.dm
Labels: Oversight, Priority: High

#7127 Eris Research/Machine Sprite Port
  code/game/machinery/autolathe.dm
  code/game/mecha/mech_prosthetics.dm
  code/modules/research/protolathe.dm
  icons/obj/machines/research.dmi
  icons/obj/robotics.dmi
  icons/obj/stationobjs.dmi
  icons/obj/surgery.dmi
Labels: Sprite Change

#7152 [Project] Vintage Voidsuits
  code/game/machinery/suit_storage_unit.dm
  code/modules/clothing/spacesuits/void/event.dm
  icons/mob/head.dmi
  icons/mob/spacesuit.dmi
  icons/mob/species/skrell/helmet.dmi
  icons/mob/species/skrell/suit.dmi
  icons/mob/species/tajaran/helmet.dmi
  icons/mob/species/tajaran/suit.dmi
  icons/mob/species/unathi/helmet.dmi
  icons/mob/species/unathi/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/spacesuits.dmi
  icons/obj/clothing/species/skrell/hats.dmi
  icons/obj/clothing/species/skrell/suits.dmi
  icons/obj/clothing/species/tajaran/hats.dmi
  icons/obj/clothing/species/tajaran/suits.dmi
  icons/obj/clothing/species/unathi/hats.dmi
  icons/obj/clothing/species/unathi/suits.dmi
  polaris.dme
Labels: Sprite Change

#7185 New implanter and camera sprites
  icons/obj/items.dmi
Labels: Sprite Change

#7190 New janicart sprites/features
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/objs.dm
  code/game/objects/structures/janicart.dm
  html/changelogs/arokha-janicart.yml
  icons/obj/janitor.dmi
  nano/templates/janitorcart.tmpl
Labels: Feature Tweak, Sprite Change

#7235 Fixes runtime in ticker.dm, 424: Cannot read null.mob_type
  code/controllers/subsystems/ticker.dm
Labels: Oversight

#7189 New ore chunk sprites, ore box sprite
  icons/obj/mining.dmi
Labels: Sprite Change

#7209 Remove stat() sleeping
  code/modules/client/client procs.dm
Labels: Optimization

#7194 Stops hiding italicised messages from observers
  code/modules/mob/hear_say.dm
Labels: Feature Tweak

#7214 Adds vchat export chatlog verb
  code/modules/client/client procs.dm
  code/modules/vchat/js/vchat.js
  code/modules/vchat/vchat_client.dm
  html/changelogs/atermonera - vchat_exportlog.yml
Labels: Feature, Needs Review

#7223 Grab movement sped up
  code/modules/mob/mob.dm
  code/modules/mob/mob_movement.dm
Labels: Bugfix

#7230 Ports manifest duplication fix from Virgo
  code/controllers/subsystems/ticker.dm
Labels: Bugfix

#7220 Fix rollerbed movement with buckled mobs
  code/game/objects/buckling.dm
  code/modules/mob/living/living.dm
Labels: Bugfix

#7232 Fixes particle accelerator construction.
  code/modules/power/singularity/particle_accelerator/particle_control.dm
  code/modules/power/singularity/particle_accelerator/particle_emitter.dm
Labels: Bugfix

#7236 Fixes runtime in item_attack.dm, line 81
  code/modules/admin/admin_attack_log.dm
Labels: Bugfix

#7239 The Great Rotation (And water cooler fix)
  code/game/machinery/vending.dm
  code/modules/reagents/reagent_dispenser.dm
  icons/obj/vending.dmi
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-4.dmm
  maps/southern_cross/southern_cross-6.dmm
  maps/southern_cross/southern_cross-7.dmm
Labels: Bugfix, Map Change / Issue

#7204 Performance improvements
  code/__defines/flags.dm
  code/_helpers/game.dm
  code/_onclick/hud/skybox.dm
  code/controllers/subsystems/open_space.dm
  code/datums/observation/turf_enterexit.dm
  code/defines/obj.dm
  code/game/area/Space Station 13 areas.dm
  code/game/atoms.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/camera/motion.dm
  code/game/machinery/camera/presets.dm
  code/game/machinery/flasher.dm
  code/game/objects/effects/alien/aliens.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/transfer_valve.dm
  code/game/objects/items/weapons/tanks/tanks.dm
  code/game/turfs/space/space.dm
  code/game/turfs/turf.dm
  code/modules/assembly/holder.dm
  code/modules/assembly/proximity.dm
  code/modules/hydroponics/spreading/spreading.dm
  code/modules/hydroponics/spreading/spreading_response.dm
  code/modules/integrated_electronics/core/assemblies.dm
  code/modules/integrated_electronics/core/assemblies/clothing.dm
  code/modules/integrated_electronics/subtypes/output.dm
  code/modules/mob/living/carbon/human/species/xenomorphs/alien_facehugger.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_movement.dm
  code/modules/multiz/turf.dm
  code/modules/power/singularity/containment_field.dm
  code/modules/shieldgen/directional_shield.dm
  polaris.dme
Labels: Optimization, Refactor

#7242 Show sent PDA messages to sender
  code/game/objects/items/devices/PDA/PDA.dm
Labels: Feature Tweak

#7218 Traps don't get weird with removed limbs
  code/game/objects/items/weapons/traps.dm
Labels: Oversight

#7225 Increase the amounts of SNACKS and cigarettes in vending machines.
  code/game/machinery/vending.dm
Labels: Feature Tweak

#7215 Streamline (Facial) Hair & Marking Character Customization, Port color_square to Clean Prefcode
  code/modules/client/preference_setup/general/03_body.dm
  code/modules/client/preference_setup/global/01_ui.dm
  code/modules/client/preference_setup/preference_setup.dm
  code/modules/mob/new_player/preferences_setup.dm
  html/changelogs/KasparoVv - PR - 7215.yml
Labels: Feature

#7164 Ported /tg/ style screen alerts, replacing the hunger icon with them
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/alert.dm
  code/_onclick/hud/alien_larva.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/robot.dm
  code/datums/mind.dm
  code/game/area/areas.dm
  code/game/gamemodes/changeling/powers/escape_restraints.dm
  code/game/gamemodes/changeling/powers/revive.dm
  code/game/gamemodes/technomancer/spells/resurrect.dm
  code/game/machinery/computer/arcade.dm
  code/game/machinery/computer/cloning.dm
  code/game/mecha/mecha.dm
  code/game/objects/buckling.dm
  code/game/objects/items/devices/defib.dm
  code/game/objects/items/weapons/handcuffs.dm
  code/game/objects/items/weapons/implants/implantfreedom.dm
  code/game/objects/items/weapons/tools/wirecutters.dm
  code/game/objects/objs.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/holder.dm
  code/modules/mob/living/bot/secbot.dm
  code/modules/mob/living/carbon/alien/life.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_resist.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/resist.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/silicon/laws.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_mob/life.dm
  code/modules/mob/living/simple_mob/simple_hud.dm
  code/modules/mob/living/simple_mob/simple_mob.dm
  code/modules/mob/login.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/organs/organ_external.dm
  code/modules/surgery/implant.dm
  icons/mob/screen_alert.dmi
  polaris.dme
Labels: Feature Tweak, Sprite Change

#7210 [PORT] Static Machinery Power
  code/__defines/machinery.dm
  code/controllers/subsystems/machines.dm
  code/game/area/areas.dm
  code/game/machinery/machinery.dm
  code/game/machinery/machinery_power.dm
  code/game/machinery/rechargestation.dm
  code/game/mecha/equipment/tools/energy_relay.dm
  code/game/objects/structures/electricchair.dm
  code/modules/integrated_electronics/passive/power.dm
  code/modules/modular_computers/computers/modular_computer/power.dm
  code/modules/overmap/ships/computers/computer_shims.dm
  code/modules/overmap/ships/engines/gas_thruster.dm
  code/modules/power/apc.dm
  code/modules/power/power.dm
  code/modules/reagents/distilling/distilling.dm
  polaris.dme
Labels: Refactor

#7219 Fix sinks washing things at a distance
  code/game/objects/structures/watercloset.dm
Labels: Oversight

#7227 Add safety to GPSes to avoid runtimes
  code/game/objects/items/devices/gps.dm
Labels: Oversight

#7231 Warn VPN connectors better
  code/modules/client/client procs.dm
Labels: Feature Tweak

#7240 Fix doublewhispering
  code/modules/mob/living/say.dm
Labels: Oversight

#7243 Blob Infinite Loop Fix
  code/modules/blob2/core_chunk.dm
Labels: Bugfix, Priority: High

#7246 [PORT] Overmap Ship Pixel Movement
  code/modules/overmap/sectors.dm
  code/modules/overmap/ships/ship.dm
  code/modules/overmap/turfs.dm
Labels: Feature

#7248 Fix medical stack exploit
  code/game/objects/items/stacks/medical.dm
Labels: Bugfix

#7247 Port various auto-decorating floors from Eris
  code/__defines/_planes+layers.dm
  code/__defines/turfs.dm
  code/_helpers/turfs.dm
  code/game/objects/structures/window.dm
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/flooring/flooring_decals.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor_attackby.dm
  code/game/turfs/simulated/floor_icon.dm
  code/game/turfs/simulated/floor_types_eris.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/turf/flooring/eris/grass.dmi
  icons/turf/flooring/eris/hull.dmi
  icons/turf/flooring/eris/plating.dmi
  icons/turf/flooring/eris/tiles.dmi
  icons/turf/flooring/eris/tiles_dark.dmi
  icons/turf/flooring/eris/tiles_maint.dmi
  icons/turf/flooring/eris/tiles_steel.dmi
  icons/turf/flooring/eris/tiles_white.dmi
  icons/turf/flooring/eris/tilestack.dmi
  icons/turf/flooring/grass.dmi
  icons/turf/outdoors.dmi
  icons/turf/outdoors_edge.dmi
  polaris.dme
Labels: Feature

#7251 Fix solgov icons
  code/modules/clothing/suits/solgov.dm
Labels: Bugfix
