Repository PolarisSS13/Polaris, pull requests merged in 2020-12, with the labels that each got.

#7749 Stowaway Cryopod is now invisible, and incorporeal.
  code/game/objects/structures/ghost_pods/human.dm
Labels: Feature Tweak, Staff Request

#7756 Matter Matters
  code/game/machinery/autolathe.dm
  code/game/objects/items/stacks/stack.dm
  code/modules/materials/material_recipes.dm
  code/modules/research/designs.dm
Labels: Feature

#7757 Porting Food Additions
  code/modules/food/food/snacks.dm
  code/modules/food/recipes_grill.dm
  code/modules/food/recipes_microwave.dm
  code/modules/food/recipes_oven.dm
  icons/obj/food.dmi
Labels: Feature

#7760 Adds & Upgrades a Bunch of Teshari Clothing
  code/modules/client/preference_setup/loadout/loadout_eyes.dm
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/suits/aliens/seromi.dm
  code/modules/clothing/under/xenos/seromi.dm
  html/changelogs/KasparoVy - PR - 7760.yml
  icons/mob/eyes.dmi
  icons/mob/species/seromi/deptcloak.dmi
  icons/mob/species/seromi/deptjacket.dmi
  icons/mob/species/seromi/eyes.dmi
  icons/mob/species/seromi/gloves.dmi
  icons/mob/species/seromi/teshari_cloak.dmi
  icons/mob/species/seromi/teshari_hood.dmi
  icons/mob/species/seromi/teshari_uniform.dmi
  icons/mob/species/seromi/ties.dmi
  icons/obj/clothing/glasses.dmi
Labels: Feature, Sprite Change

#7762 Plainleather & Tobacco
  code/game/objects/items/stacks/sheets/leather.dm
  code/game/objects/structures/watercloset.dm
  code/modules/hydroponics/seed_packets.dm
  code/modules/hydroponics/seedtypes/eggplant.dm
  code/modules/hydroponics/seedtypes/mushrooms.dm
  code/modules/hydroponics/seedtypes/tobacco.dm
  code/modules/materials/materials.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
  icons/obj/hydroponics_products.dmi
  polaris.dme
Labels: Feature, Feature Tweak

#7765 Adds Point Defense turrets.
  code/datums/supplypacks/engineering.dm
  code/game/gamemodes/meteor/meteors.dm
  code/game/machinery/portable_turret.dm
  code/game/machinery/turret_control.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets.dm
  icons/obj/gun2.dmi
  icons/obj/turrets.dmi
Labels: Feature

#7771 Creates framework for species to experience traumatic shock at different rates
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/shock.dm
  html/changelogs/Runa Dacino - trauma mod.yml
Labels: Feature

#7773 Fixes unreachable landmarks breaking spacetravel
  code/modules/overmap/spacetravel.dm
Labels: Oversight

#7774 Prevents infinite money
  code/modules/economy/cash_register.dm
Labels: Bugfix

#7775 Facial-hair nanites are no longer only vomiting toner.
  code/modules/mob/new_player/sprite_accessories.dm
Labels: Bugfix

#7777 Modular honks
  code/game/objects/items/weapons/clown_items.dm
Labels: Feature Tweak

#7369 Department and Round Goals
  code/datums/roundstats/_defines_local.dm
  code/datums/roundstats/departmentgoal.dm
  code/datums/roundstats/roundstats.dm
  code/game/machinery/lightswitch.dm
  code/game/machinery/vending.dm
  code/game/mecha/mecha.dm
  code/modules/food/food/drinks.dm
  code/modules/hydroponics/grown.dm
  code/modules/hydroponics/trays/tray.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/organs/organ_external.dm
  code/modules/recycling/disposal.dm
  code/modules/turbolift/turbolift.dm
  polaris.dme
Labels: Feature

#7783 Reworks stairs to be sensible
  code/game/atoms_movable.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/living_movement.dm
  code/modules/multiz/ladders.dm
  code/modules/multiz/movement.dm
  code/modules/multiz/stairs.dm
  code/modules/multiz/turf.dm
  html/changelogs/atermonera_stairsv2.yml
  icons/obj/structures.dmi
  icons/obj/structures/multiz.dmi
  icons/obj/structures/stairs_64x64.dmi
  maps/example/example-1.dmm
  maps/example/example-2.dmm
  maps/southern_cross/southern_cross-1.dmm
  maps/submaps/_helpers.dm
  polaris.dme
Labels: Feature, Map Change / Issue, Prepare to Die, Project, Refactor

#7788 Fires nanites responsible for incorrect facial hair coloring. Hires human barber from the Bowl to dye everyone's beards
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/organs/organ_icon.dm
Labels: Oversight, Staff Request

#7791 Removes testing logs that were left in on stairs
  code/modules/multiz/stairs.dm
Labels: Oversight

#7778 A Thing About Digging Sand and Mineral Processor Speed
  code/__defines/mobs.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/modules/mining/machine_processing.dm
  code/modules/mining/machine_stacking.dm
  code/modules/mining/machine_unloading.dm
  code/modules/mining/mine_items.dm
  code/modules/mining/mine_turfs.dm
  code/modules/recycling/conveyor2.dm
Labels: Feature Tweak

#7785 borg chargers work for hardsuit wearers
  code/game/machinery/rechargestation.dm
Labels: Feature

#7794 Puts smelly pine tree over stinky event listeners
  code/datums/observation/~cleanup.dm
Labels: Staff Request, Unwanted Feature Removal

#7789 Changes formatting for RESPAWN_MESSAGE configuration to be more visible
  code/controllers/configuration.dm
  html/changelogs/Runa Dacino - configuration formatting.yml
Labels: Feature Tweak

#7795 Fixes indoor-use snow not having footprints
  code/game/turfs/flooring/flooring_premade.dm
Labels: Bugfix

#7799 Experimental: adds workflow to autoupdate changelog
  .github/workflows/autochangelog.yml
  html/changelogs/KasparoVy - PR - 7760.yml
  html/changelogs/Mechoid - Encumbrance.yml
  html/changelogs/Meghan Rossi - the_teslagen.yml
  html/changelogs/Runa Dacino -  Exosuit gripper tweak.yml
  html/changelogs/Runa Dacino - trauma mod.yml
  html/changelogs/SubberTheFabulous-PR-7642.yml
  html/changelogs/Woodrat - Vote.yml
  html/changelogs/mechoid - butchery.yml
  html/changelogs/mechoid - hydroupkeep.yml
  tools/GenerateChangelog/ss13_autochangelog.py
Labels: Feature, Priority: High, Quality of Life

#7804 Autochangelog Fix
  tools/GenerateChangelog/ss13_autochangelog.py
Labels: Bugfix, Priority: High

#7805 Updates autochangelog authentication
  .github/workflows/autochangelog.yml
Labels: Bugfix, Priority: High

#7806 Autochangelog fix 3
  .github/workflows/autochangelog.yml
Labels: Bugfix, Priority: High

#7796 Adds (Follow) link to emotes for ghosts
  code/modules/mob/emote.dm
Labels: Feature

#7807 Autochangelog fix 4
  .github/workflows/autochangelog.yml
Labels: Bugfix

#7808 Autochangelog fix 5
  .github/workflows/autochangelog.yml
Labels: Bugfix

#7809 Autochangelog fix 6
  .github/workflows/autochangelog.yml
  tools/GenerateChangelog/ss13_autochangelog.py
Labels: Bugfix

#7800 Fixes discarding cards onto walls
  code/modules/games/cards.dm
Labels: Bugfix

#7790 Grammar
  code/datums/roundstats/roundstats.dm
Labels: Oversight

#7792 Directional Signs Update
  code/game/objects/structures/signs.dm
  icons/obj/decals.dmi
  icons/obj/decals_directions.dmi
Labels: Feature Tweak

#7812 Update decals.dmi
  icons/turf/flooring/decals.dmi
Labels: Sprite Change

#7780 Adds a Whip.
  code/game/objects/items/weapons/material/misc.dm
  code/game/objects/items/weapons/melee/misc.dm
  code/modules/materials/material_recipes.dm
  icons/obj/weapons.dmi
Labels: Feature, Needs Retesting
