Repository PolarisSS13/Polaris, pull requests merged in 2020-07, with the labels that each got.

#7313 ice cream
  code/modules/client/preference_setup/general/03_body.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/gradient.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/mob/hair_gradients.dmi
  polaris.dme
Labels: Feature

#7318 Fixes oversight closet decl name
  maps/southern_cross/structures/closets/research.dm
  polaris.dme
Labels: Oversight, Priority: High

#7307 Makes mob/obj/turf spawn windows pop up in proper size
  code/modules/admin/create_mob.dm
  code/modules/admin/create_object.dm
  code/modules/admin/create_turf.dm
Labels: Quality of Life

#7314 Eyepatch no Longer Covers Other Eye with Strap
  html/changelogs/kasparovy-pr-7314.yml
  icons/mob/eyes.dmi
Labels: Sprite Change

#7300 Streamlined Voidsuits Upgrade
  code/datums/supplypacks/voidsuits.dm
  code/modules/clothing/spacesuits/void/station.dm
  icons/mob/species/seromi/head.dmi
  icons/mob/species/seromi/suit.dmi
  icons/mob/species/skrell/helmet.dmi
  icons/mob/species/skrell/suit.dmi
  icons/mob/species/tajaran/helmet.dmi
  icons/mob/species/tajaran/suit.dmi
  icons/mob/species/unathi/helmet.dmi
  icons/mob/species/unathi/suit.dmi
Labels: Feature Tweak, Sprite Change

#6799 New book sprites + inhands
  code/game/gamemodes/cult/ritual.dm
  code/game/objects/items/weapons/manuals.dm
  code/game/objects/items/weapons/scrolls.dm
  code/game/objects/items/weapons/storage/bible.dm
  code/modules/library/lib_items.dm
  code/modules/library/lib_machines.dm
  code/modules/lore_codex/codex.dm
  code/modules/xenoarcheaology/manuals.dm
  html/changelogs/cerebulon - booksprites.yml
  icons/mob/items/lefthand_books.dmi
  icons/mob/items/righthand_books.dmi
  icons/obj/custom_books.dmi
  icons/obj/library.dmi
Labels: Sprite Change

#7325 Fix runtime in projectile.dm, 664.
  code/modules/projectiles/projectile.dm
Labels: Bugfix, Priority: CRITICAL

#7326 Arrivals Shuttle Message Fix
  code/__defines/misc.dm
  code/defines/procs/announce.dm
  code/game/machinery/computer/camera.dm
  code/game/machinery/cryopod.dm
  code/game/machinery/telecomms/telecomunications.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/modular_computers/file_system/programs/generic/camera.dm
  code/modules/modular_computers/file_system/programs/generic/uav.dm
  code/modules/modular_computers/file_system/programs/medical/suit_sensors.dm
  code/modules/modular_computers/hardware/network_card.dm
  maps/southern_cross/overmap/sectors.dm
  maps/southern_cross/southern_cross_defines.dm
Labels: Bugfix

#7328 Move the vending machines into a separate file.
  code/game/machinery/vending.dm
  code/game/machinery/vending_machines.dm
  polaris.dme
Labels: Refactor

#7335 Attempts to fix blurry icon scaling
  code/game/atoms_movable.dm
  interface/skin.dmf
Labels: Results To Be Reviewed, Sprite Change

#7336 Mice Go Fast Again + Rat Sprites
  code/modules/mob/living/simple_mob/subtypes/animal/passive/mouse.dm
  icons/mob/animal.dmi
Labels: Feature, Feature Tweak

#7338 Fix Pink Slime Extract Description
  code/modules/xenobio/items/extracts.dm
Labels: Oversight

#7339 Fix Janicart PDA bug from Aro's Rewrite of Janicarts.
  code/game/objects/items/devices/PDA/cart.dm
Labels: Bugfix

#7353 [SEMI-URGENT] Fixes hanging/crashing server when using the Export-Chatlog verb in OOC
  code/modules/vchat/vchat_client.dm
Labels: Oversight, Priority: High

#7359 Clothes! (And rats)
  code/modules/client/preference_setup/loadout/loadout_mask.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/items/lefthand_holder.dmi
  icons/mob/items/righthand_holder.dmi
  icons/mob/mask.dmi
  icons/mob/uniform_1.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/uniforms_1.dmi
Labels: Sprite Change

#7337 Persistent Trash/Dirt/Graffiti/Notices
  code/__defines/misc.dm
  code/__defines/subsystems.dm
  code/_macros.dm
  code/controllers/configuration.dm
  code/controllers/subsystems/persistence.dm
  code/datums/supplypacks/supply.dm
  code/game/area/Space Station 13 areas.dm
  code/game/area/asteroid_areas.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/effects/decals/Cleanable/robots.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/items/devices/chameleonproj.dm
  code/game/objects/items/trash.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/material/ashtray.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/game/objects/items/weapons/tape.dm
  code/game/objects/random/_random.dm
  code/game/objects/random/misc.dm
  code/game/objects/structures/noticeboard.dm
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/initialization/maintenance.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor_attackby.dm
  code/game/turfs/simulated/wall_attacks.dm
  code/game/turfs/simulated/walls.dm
  code/game/turfs/turf.dm
  code/game/world.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verb_lists.dm
  code/modules/admin/banjob.dm
  code/modules/admin/persistence.dm
  code/modules/admin/topic.dm
  code/modules/materials/material_recipes.dm
  code/modules/mob/living/silicon/robot/drone/drone_items.dm
  code/modules/mob/living/silicon/robot/robot_items.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/mecha/phazon.dmglass.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/paper_sticky.dm
  code/modules/persistence/datum/datum_filth.dm
  code/modules/persistence/datum/datum_graffiti.dm
  code/modules/persistence/datum/datum_paper.dm
  code/modules/persistence/datum/datum_paper_sticky.dm
  code/modules/persistence/datum/datum_trash.dm
  code/modules/persistence/datum/persistence_datum.dm
  code/modules/persistence/filth.dm
  code/modules/persistence/graffiti.dm
  code/modules/persistence/noticeboard.dm
  code/modules/xenoarcheaology/misc.dm
  html/changelogs/cerebulon - persistence.yml
  icons/effects/writing.dmi
  icons/obj/stickynotes.dmi
  maps/southern_cross/southern_cross-6.dmm
  maps/southern_cross/southern_cross_areas.dm
  maps/submaps/surface_submaps/mountains/deadBeacon.dmm
  maps/submaps/surface_submaps/mountains/quarantineshuttle.dmm
  maps/submaps/surface_submaps/wilderness/wilderness_areas.dm
  polaris.dme
Labels: Feature

#7375 Fix scrubbers
  code/modules/mob/living/bot/medbot.dm
  code/modules/ventcrawl/ventcrawl.dm
Labels: Bugfix, Priority: CRITICAL

#7345 custom_sprites.dm small improvement and better commenting.
  code/modules/mob/living/silicon/robot/custom_sprites.dm
Labels: Refactor

#7350 Relatively small changes to how damage affects mechs.
  code/game/mecha/mecha.dm
Labels: Feature Tweak

#7352 Increase mob default reload time from 1 second to 4 seconds.
  code/modules/mob/living/simple_mob/combat.dm
  code/modules/mob/living/simple_mob/simple_mob.dm
Labels: Feature Tweak

#7344 Aurora Cooking Port
  code/_helpers/sorts/comparators.dm
  code/_helpers/type2type.dm
  code/datums/recipe.dm
  code/datums/supplypacks/hospitality.dm
  code/game/gamemodes/cult/cultify/obj.dm
  code/game/machinery/biogenerator.dm
  code/game/machinery/frame.dm
  code/game/machinery/vending_machines.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/items/trash.dm
  code/game/objects/items/weapons/circuitboards/frame.dm
  code/game/objects/items/weapons/circuitboards/machinery/kitchen_appliances.dm
  code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
  code/modules/food/food/condiment.dm
  code/modules/food/food/snacks.dm
  code/modules/food/food/snacks/meat.dm
  code/modules/food/food/thecake.dm
  code/modules/food/kitchen/cooking_machines/_appliance.dm
  code/modules/food/kitchen/cooking_machines/_cooker.dm
  code/modules/food/kitchen/cooking_machines/_cooker_output.dm
  code/modules/food/kitchen/cooking_machines/_mixer.dm
  code/modules/food/kitchen/cooking_machines/candy.dm
  code/modules/food/kitchen/cooking_machines/cereal.dm
  code/modules/food/kitchen/cooking_machines/container.dm
  code/modules/food/kitchen/cooking_machines/fryer.dm
  code/modules/food/kitchen/cooking_machines/grill.dm
  code/modules/food/kitchen/cooking_machines/oven.dm
  code/modules/food/kitchen/microwave.dm
  code/modules/food/recipe.dm
  code/modules/food/recipe_dump.dm
  code/modules/food/recipes_fryer.dm
  code/modules/food/recipes_grill.dm
  code/modules/food/recipes_microwave.dm
  code/modules/food/recipes_oven.dm
  code/modules/mob/living/silicon/robot/drone/drone_items.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_dispenser.dm
  code/modules/research/designs/circuits/circuits.dm
  html/changelogs/rykka-stormheart-pr-7344.yml
  icons/obj/cooking_machines.dmi
  icons/obj/food.dmi
  icons/obj/food_syn.dmi
  icons/obj/objects.dmi
  icons/obj/trash.dmi
  maps/northern_star/polaris-1.dmm
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-6.dmm
  maps/submaps/surface_submaps/plains/Diner.dmm
  maps/submaps/surface_submaps/wilderness/Manor1.dmm
  nano/README.md
  polaris.dme
  sound/machines/fryer/deep_fryer_1.ogg
  sound/machines/fryer/deep_fryer_2.ogg
  sound/machines/fryer/deep_fryer_emerge.ogg
  sound/machines/fryer/deep_fryer_immerse.ogg
  sound/machines/hatch_open.ogg
Labels: Feature, Refactor

#7354 Implements Status Indicators
  code/__defines/_planes+layers.dm
  code/__defines/mobs.dm
  code/game/atoms_movable.dm
  code/game/gamemodes/technomancer/spells/audible_deception.dm
  code/game/machinery/cryo.dm
  code/game/machinery/jukebox.dm
  code/game/mecha/equipment/weapons/honk.dm
  code/game/objects/items/devices/megaphone.dm
  code/modules/admin/admin.dm
  code/modules/client/preference_setup/global/setting_datums.dm
  code/modules/client/preferences_toggle_procs.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/mob/living/bot/bot.dm
  code/modules/mob/living/carbon/alien/life.dm
  code/modules/mob/living/carbon/brain/login.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/login.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_mob/subtypes/animal/space/alien.dm
  code/modules/mob/living/simple_mob/subtypes/animal/space/carp.dm
  code/modules/mob/living/simple_mob/subtypes/occult/constructs/juggernaut.dm
  code/modules/mob/living/status_indicators.dm
  code/modules/mob/login.dm
  code/modules/mob/mob_planes.dm
  code/modules/organs/pain.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
  code/modules/virus2/effect.dm
  code/modules/xenoarcheaology/finds/special.dm
  code/modules/xenoarcheaology/tools/suspension_generator.dm
  icons/mob/status_indicators.dmi
  polaris.dme
Labels: Feature

#7358 Makes using BYOND Filters easier.
  code/_helpers/visual_filters.dm
  code/modules/mob/_modifiers/modifiers.dm
  code/modules/mob/_modifiers/modifiers_misc.dm
  polaris.dme
Labels: Refactor

#7363 Fixes table/bench icon connections.
  code/modules/tables/tables.dm
Labels: Bugfix

#7367 Fixes the diagonal density melee exploit
  code/game/gamemodes/changeling/changeling_powers.dm
Labels: Bugfix

#7364 Rag Coding Fix
  code/modules/detectivework/tools/rag.dm
Labels: Bugfix

#7385 Clothes, clothes, clothes!
  code/modules/client/preference_setup/loadout/loadout_accessories.dm
  code/modules/client/preference_setup/loadout/loadout_head.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/under/accessories/clothing.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/ties.dmi
  icons/mob/uniform_1.dmi
  icons/obj/clothing/ties.dmi
  icons/obj/clothing/uniforms_1.dmi
Labels: Sprite Change
