Repository PolarisSS13/Polaris, pull requests merged in 2020-04, with the labels that each got.

#6932 Add missing bluespace flare sprite
  icons/obj/device.dmi
Labels: Oversight, Sprite Change

#6930 Change VChat sqllite error message handler
  code/modules/vchat/vchat_db.dm
Labels: Bugfix, Higgs Bugson

#6929 Add shield remote button
  code/game/machinery/door_control.dm
  code/modules/shieldgen/shield_gen.dm
Labels: Feature

#6928 Fix 2 runtimes
  code/modules/hydroponics/seed.dm
  code/modules/mob/mob.dm
Labels: Bugfix

#6926 Clean up some subsystem things
  code/controllers/autotransfer.dm
  code/controllers/subsystems/processing/chemistry.dm
  code/controllers/subsystems/processing/fastprocess.dm
  code/controllers/subsystems/processing/obj.dm
  code/controllers/subsystems/processing/processing.dm
  code/controllers/subsystems/processing/projectiles.dm
  code/controllers/subsystems/processing/turfs.dm
  code/game/turfs/simulated/lava.dm
Labels: Refactor

#6925 Changes webbing to Initialize
  code/modules/clothing/under/accessories/storage.dm
  code/modules/clothing/under/xenos/vox.dm
Labels: Refactor

#6924 Sniper Rifle QOL
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/projectile/sniper.dm
  html/changelogs/novacat - sniperqol.yml
Labels: Quality of Life

#6922 Fix matches and SSobj/SSprocessing
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/storage/boxes.dm
Labels: Refactor

#6912 [PORT] Speed up map load significantly
  code/__defines/machinery.dm
  code/_helpers/_lists.dm
  code/_helpers/global_lists.dm
  code/controllers/subsystems/air.dm
  code/controllers/subsystems/atoms.dm
  code/controllers/subsystems/mapping.dm
  code/controllers/subsystems/skybox.dm
  code/controllers/subsystems/xenoarch.dm
  code/game/area/areas.dm
  code/game/atoms.dm
  code/game/gamemodes/cult/hell_universe.dm
  code/game/gamemodes/endgame/supermatter_cascade/blob.dm
  code/game/gamemodes/endgame/supermatter_cascade/universe.dm
  code/game/gamemodes/events/wormholes.dm
  code/game/machinery/air_alarm.dm
  code/game/machinery/fire_alarm.dm
  code/game/turfs/simulated.dm
  code/game/turfs/simulated/dungeon/wall.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor_types.dm
  code/game/turfs/simulated/outdoors/outdoors.dm
  code/game/turfs/simulated/wall_types.dm
  code/game/turfs/simulated/walls.dm
  code/game/turfs/space/space.dm
  code/game/turfs/turf.dm
  code/game/turfs/unsimulated/beach.dm
  code/game/turfs/unsimulated/planetary.dm
  code/modules/admin/verbs/adminjump.dm
  code/modules/admin/verbs/atmosdebug.dm
  code/modules/admin/verbs/grief_fixers.dm
  code/modules/holodeck/HolodeckObjects.dm
  code/modules/lighting/lighting_turf.dm
  code/modules/mob/freelook/update_triggers.dm
  code/modules/overmap/_defines.dm
  code/modules/random_map/automata/diona.dm
  code/modules/turbolift/turbolift_turfs.dm
  maps/~map_system/maps.dm
  polaris.dme
Labels: Optimization, Refactor

#6859 Port Bay computer icons
  code/game/machinery/computer/RCON_Console.dm
  code/game/machinery/computer/aifixer.dm
  code/game/machinery/computer/computer.dm
  code/game/machinery/computer/shutoff_monitor.dm
  code/modules/power/sensors/sensor_monitoring.dm
  icons/obj/computer.dmi
  icons/obj/modular_console.dmi
  icons/obj/modular_laptop.dmi
  icons/obj/modular_tablet.dmi
Labels: Sprite Change

#6857 Port computer and 'machine' frame icons from Bay
  icons/obj/stock_parts.dmi
Labels: Sprite Change

#6904 Clean up various things
  code/ATMOSPHERICS/components/binary_devices/pipeturbine.dm
  code/_helpers/global_lists.dm
  code/_helpers/unsorted.dm
  code/game/dna/dna_modifier.dm
  code/game/gamemodes/cult/cult_structures.dm
  code/game/gamemodes/technomancer/spells/chroma.dm
  code/game/gamemodes/technomancer/spells/reflect.dm
  code/game/gamemodes/technomancer/spells/spawner/destablize.dm
  code/game/gamemodes/technomancer/spells/spawner/pulsar.dm
  code/game/machinery/atmoalter/canister.dm
  code/game/machinery/atmoalter/portable_atmospherics.dm
  code/game/machinery/camera/presets.dm
  code/game/machinery/computer/message.dm
  code/game/machinery/computer/pod.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/lightswitch.dm
  code/game/machinery/newscaster.dm
  code/game/machinery/vending.dm
  code/game/objects/effects/chem/foam.dm
  code/game/objects/effects/chem/water.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/effects/map_effects/beam_point.dm
  code/game/objects/effects/misc.dm
  code/game/objects/effects/portals.dm
  code/game/objects/items/devices/communicator/communicator.dm
  code/game/objects/items/devices/uplink.dm
  code/game/objects/items/stacks/fifty_spawner.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/game/objects/structures/ghost_pods/ghost_pods.dm
  code/game/objects/structures/props/beam_prism.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/modules/assembly/signaler.dm
  code/modules/economy/EFTPOS.dm
  code/modules/food/food/snacks.dm
  code/modules/food/kitchen/gibber.dm
  code/modules/holomap/station_holomap.dm
  code/modules/hydroponics/grown.dm
  code/modules/integrated_electronics/core/tools.dm
  code/modules/mining/machine_unloading.dm
  code/modules/mining/mint.dm
  code/modules/mining/resonator.dm
  code/modules/mob/freelook/ai/eye.dm
  code/modules/mob/living/bot/medbot.dm
  code/modules/mob/living/carbon/metroid/items.dm
  code/modules/power/generator.dm
  code/modules/power/generator_type2.dm
  code/modules/power/gravitygenerator.dm
  code/modules/power/smes.dm
  code/modules/random_map/drop/droppod_doors.dm
  code/modules/recycling/disposal.dm
  code/modules/xenoarcheaology/tools/artifact_harvester.dm
Labels: Optimization, Refactor

#6927 Adjust turret target finding process
  code/_helpers/mobs.dm
  code/game/machinery/portable_turret.dm
Labels: Optimization, Refactor

#6907 Ports SSmobs from Virgo
  code/controllers/Processes/mob.dm
  code/controllers/subsystems/mobs.dm
  polaris.dme
Labels: Refactor

#6917 Telecube tweaks
  code/modules/artifice/telecube.dm
Labels: Refactor

#6944 fixes telebaton hand sprite
  code/game/objects/items/weapons/swords_axes_etc.dm
Labels: Oversight

#6945 Adds confirmations message to cancel vote
  code/controllers/subsystems/vote.dm
Labels: Feature Tweak

#6946 cataloguers fit in belt slot
  code/modules/catalogue/cataloguer.dm
Labels: Feature Tweak

#6947 Fixes supply shuttle display timer
  code/game/machinery/supply_display.dm
  code/modules/shuttles/shuttle_supply.dm
Labels: Bugfix

#6948 Fixes #6905
  maps/southern_cross/southern_cross-1.dmm
Labels: Map Change / Issue, Oversight

#6941 Fix some parse errors
  code/_helpers/_lists.dm
  code/game/mecha/combat/fighter.dm
  code/game/mecha/mecha.dm
  code/game/turfs/simulated/water.dm
Labels: Oversight

#6938 Mining equipment vendor use new vendor sprite
  code/modules/mining/ore_redemption_machine/equipment_vendor.dm
Labels: Sprite Change

#6936 [PORT] Sundry Bugfixes XI
  code/game/objects/effects/chem/chemsmoke.dm
  code/game/objects/items/weapons/tanks/tanks.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/hydroponics/seed.dm
  code/modules/reagents/reagent_containers.dm
Labels: Bugfix

#6920 QoL: Small Medical Things
  code/datums/repositories/crew.dm
  code/game/area/areas.dm
  code/game/machinery/Sleeper.dm
  code/game/objects/items/devices/gps.dm
  code/modules/reagents/Chemistry-Machinery.dm
  code/modules/reagents/dispenser/dispenser2.dm
  code/modules/reagents/reagent_containers/glass.dm
  html/changelogs/neerti-medical_qol_1.yml
  maps/submaps/surface_submaps/wilderness/wilderness_areas.dm
Labels: Quality of Life

#6851 BUREAUCRACY TIME
  code/modules/paperwork/paper.dm
  code/modules/paperwork/stamps.dm
  icons/obj/bureaucracy.dmi
Labels: Sprite Change

#6923 QoL: Stasis and Defibs
  code/controllers/configuration.dm
  code/game/machinery/Sleeper.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/items/devices/defib.dm
  code/modules/mob/living/carbon/brain/MMI.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/organs/internal/brain.dm
  html/changelogs/neerti-qol_medical_2.yml
Labels: Feature Tweak

#6951 Account DB console icon fix
  code/modules/economy/Accounts_DB.dm
  icons/obj/computer.dmi
Labels: Bugfix

#6916 [PORT] Overmap Events (and updates)
  code/__defines/color.dm
  code/__defines/overmap.dm
  code/_helpers/turfs.dm
  code/controllers/subsystems/events.dm
  code/controllers/subsystems/skybox.dm
  code/game/gamemodes/events/dust.dm
  code/game/gamemodes/meteor/meteors.dm
  code/game/turfs/space/space.dm
  code/game/turfs/turf.dm
  code/modules/events/carp_migration.dm
  code/modules/events/dust.dm
  code/modules/events/electrical_storm.dm
  code/modules/events/event.dm
  code/modules/events/ion_storm.dm
  code/modules/events/meteors.dm
  code/modules/mob/new_player/skill.dm
  code/modules/overmap/events/event_handler.dm
  code/modules/overmap/events/generation.dm
  code/modules/overmap/events/overmap_event.dm
  code/modules/overmap/sectors.dm
  code/modules/overmap/ships/ship.dm
  code/modules/overmap/turfs.dm
  polaris.dme
Labels: Feature

#6918 Adds new voidsuit sprite
  icons/mob/head.dmi
  icons/mob/spacesuit.dmi
  icons/mob/species/skrell/helmet.dmi
  icons/mob/species/skrell/suit.dmi
  icons/mob/species/tajaran/helmet.dmi
  icons/mob/species/tajaran/suit.dmi
  icons/mob/species/unathi/helmet.dmi
  icons/mob/species/unathi/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/spacesuits.dmi
  icons/obj/clothing/species/skrell/hats.dmi
  icons/obj/clothing/species/skrell/suits.dmi
  icons/obj/clothing/species/tajaran/hats.dmi
  icons/obj/clothing/species/tajaran/suits.dmi
  icons/obj/clothing/species/unathi/hats.dmi
  icons/obj/clothing/species/unathi/suits.dmi
Labels: Sprite Change

#6935 Remove emergencyShuttle as a process controller
  code/controllers/Processes/emergencyShuttle.dm
  code/controllers/emergency_shuttle_controller.dm
  polaris.dme
Labels: Refactor

#6958 Looking glass holodeck
  code/__defines/_planes+layers.dm
  code/game/objects/effects/mines.dm
  code/modules/looking_glass/lg_area.dm
  code/modules/looking_glass/lg_console.dm
  code/modules/looking_glass/lg_imageholder.dm
  code/modules/looking_glass/lg_turfs.dm
  icons/turf/flooring/lg_origin.dmi
  nano/templates/lookingglass.tmpl
  polaris.dme
Labels: Feature, Map Change / Issue

#6950 Improves space edge-of-map behavior and add mapping tools
  code/__defines/_planes+layers.dm
  code/__defines/misc.dm
  code/controllers/subsystems/skybox.dm
  code/game/atoms_movable.dm
  code/game/turfs/space/space.dm
  code/modules/overmap/sectors.dm
  code/modules/overmap/spacetravel.dm
  icons/turf/space.dmi
  maps/submaps/_helpers.dm
  polaris.dme
Labels: Feature, Map Change / Issue

#6959 Syndicate Uplink redesign (Inspired by ParadiseSS13/Paradise#1844)
  code/game/objects/items/devices/uplink.dm
  nano/templates/uplink.tmpl
Labels: Feature

#6939 Update assemblies to modern coding standards
  code/_helpers/unsorted.dm
  code/game/objects/items/devices/transfer_valve.dm
  code/modules/assembly/assembly.dm
  code/modules/assembly/helpers.dm
  code/modules/assembly/holder.dm
  code/modules/assembly/igniter.dm
  code/modules/assembly/infrared.dm
  code/modules/assembly/mousetrap.dm
  code/modules/assembly/proximity.dm
  code/modules/assembly/shock_kit.dm
  code/modules/assembly/signaler.dm
  code/modules/assembly/timer.dm
  code/modules/assembly/voice.dm
Labels: Refactor

#6955 Increases SSjobs init priority so it's accessible earlier
  code/__defines/subsystems.dm
Labels: Quality of Life

#6965 changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/atermonera_headphone_fix.yml
  html/changelogs/neerti-medical_qol_1.yml
  html/changelogs/novacat - sniperqol.yml
Labels: Changelog Update

#6968 Splits circuit clothes IC interaction to ctrl-shift-click
  code/modules/integrated_electronics/core/assemblies.dm
  code/modules/integrated_electronics/core/assemblies/clothing.dm
  html/changelogs/atermonera_circuitpants_holstered.yml
Labels: Bugfix

#6969 Adds preference to output description_info with examine text
  code/__defines/preferences.dm
  code/game/atoms.dm
  code/modules/client/client defines.dm
  code/modules/client/preferences_toggle_procs.dm
  html/changelogs/atermonera_examine_pref.yml
  polaris.dme
Labels: Quality of Life

#6973 Ingested ethylredox removes ingested alcohol
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
Labels: Bugfix

#6976 Employment records use comments like medical records
  code/game/machinery/computer/skills.dm
  html/changelogs/atermonera_employment_comments.yml
Labels: Bugfix

#6988 Adheres to byond's ridiculous list indexing convention in carp_migration.dm, line 44
  code/modules/events/carp_migration.dm
Labels: Oversight, Priority: CRITICAL

#6970 Fix 2 bugs
  code/controllers/subsystems/skybox.dm
  code/game/objects/effects/map_effects/map_effects.dm
  maps/~map_system/maps.dm
Labels: Bugfix

#6974 Unfucks arrival shuttle latejoins when shuttle is docked
  code/game/objects/effects/landmarks.dm
Labels: Bugfix

#6981 Port followup misc fixes
  code/controllers/subsystems/xenoarch.dm
  code/game/turfs/space/space.dm
  code/modules/maps/tg/reader.dm
Labels: Bugfix

#6982 Fix VV on lists
  code/__defines/typeids.dm
  code/__defines/vv.dm
  code/modules/admin/view_variables/debug_variables.dm
  code/modules/admin/view_variables/modify_variables.dm
  code/modules/admin/view_variables/topic.dm
  code/modules/admin/view_variables/topic_list.dm
  code/modules/admin/view_variables/view_variables.dm
  polaris.dme
Labels: Bugfix

#6983 Fixes deadringer decloaking
  code/modules/artifice/deadringer.dm
Labels: Bugfix

#6937 Adds airlock setup helpers
  code/game/machinery/embedded_controller/mapping_helpers.dm
  icons/misc/map_helpers.dmi
  polaris.dme
Labels: Feature, Map Change / Issue

#6966 Refactor away area/New()
  code/ATMOSPHERICS/components/unary/vent_pump.dm
  code/ATMOSPHERICS/components/unary/vent_scrubber.dm
  code/_helpers/unsorted.dm
  code/controllers/emergency_shuttle_controller.dm
  code/game/area/areas.dm
  code/game/gamemodes/cult/hell_universe.dm
  code/game/gamemodes/endgame/supermatter_cascade/universe.dm
  code/game/gamemodes/events.dm
  code/game/machinery/air_alarm.dm
  code/game/machinery/turret_control.dm
  code/global.dm
  code/modules/admin/secrets/random_events/gravity.dm
  code/modules/admin/verbs/debug.dm
  code/modules/events/gravity.dm
  code/modules/events/prison_break.dm
  code/modules/gamemaster/event2/events/everyone/gravity.dm
  code/modules/gamemaster/event2/events/security/prison_break.dm
  code/modules/lighting/lighting_setup.dm
  code/modules/maps/tg/reader.dm
  code/unit_tests/map_tests.dm
Labels: Optimization, Refactor

#6980 Adds pref to toggle vchat without 60s wait for linux users
  code/modules/client/preference_setup/global/setting_datums.dm
  code/modules/client/preferences_toggle_procs.dm
  code/modules/vchat/vchat_client.dm
  html/changelogs/ateromnera_vchat_pref.yml
Labels: Feature, Priority: Medium, Quality of Life

#6878 A Tale of Blobs and Man
  code/__defines/species_languages.dm
  code/_onclick/click.dm
  code/_onclick/hud/human.dm
  code/game/objects/effects/chem/chemsmoke.dm
  code/game/objects/effects/effect_system.dm
  code/modules/ai/ai_holder.dm
  code/modules/ai/ai_holder_targeting.dm
  code/modules/ai/interfaces.dm
  code/modules/blob2/_defines.dm
  code/modules/blob2/blobs/base_blob.dm
  code/modules/blob2/blobs/core.dm
  code/modules/blob2/blobs/factory.dm
  code/modules/blob2/blobs/node.dm
  code/modules/blob2/core_chunk.dm
  code/modules/blob2/overmind/types.dm
  code/modules/blob2/overmind/types/blazing_oil.dm
  code/modules/blob2/overmind/types/classic.dm
  code/modules/blob2/overmind/types/cryogenic_goo.dm
  code/modules/blob2/overmind/types/ectoplasmic_horror.dm
  code/modules/blob2/overmind/types/electromagnetic_web.dm
  code/modules/blob2/overmind/types/energized_jelly.dm
  code/modules/blob2/overmind/types/explosive_lattice.dm
  code/modules/blob2/overmind/types/fabrication_swarm.dm
  code/modules/blob2/overmind/types/fulminant_organism.dm
  code/modules/blob2/overmind/types/fungal_bloom.dm
  code/modules/blob2/overmind/types/grey_goo.dm
  code/modules/blob2/overmind/types/pressurized_slime.dm
  code/modules/blob2/overmind/types/radioactive_ooze.dm
  code/modules/blob2/overmind/types/ravenous_macrophage.dm
  code/modules/blob2/overmind/types/reactive_spines.dm
  code/modules/blob2/overmind/types/roiling_mold.dm
  code/modules/blob2/overmind/types/shifting_fragments.dm
  code/modules/blob2/overmind/types/synchronous_mesh.dm
  code/modules/blob2/overmind/types/volatile_alluvium.dm
  code/modules/mob/_modifiers/modifiers.dm
  code/modules/mob/_modifiers/modifiers_misc.dm
  code/modules/mob/living/carbon/human/ai_controlled/ai_controlled.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_mob/defense.dm
  code/modules/mob/living/simple_mob/subtypes/blob/blob.dm
  code/modules/mob/living/simple_mob/subtypes/blob/spore.dm
  code/modules/projectiles/projectile/arc.dm
  code/modules/projectiles/projectile/blob.dm
  icons/mob/blob.dmi
  polaris.dme
Labels: Feature

#6967 Add 2 new pipe types
  code/ATMOSPHERICS/_atmospherics_helpers.dm
  code/ATMOSPHERICS/atmospherics.dm
  code/ATMOSPHERICS/components/binary_devices/pump.dm
  code/ATMOSPHERICS/components/portables_connector.dm
  code/ATMOSPHERICS/components/unary/vent_pump.dm
  code/ATMOSPHERICS/pipes/cap.dm
  code/ATMOSPHERICS/pipes/manifold.dm
  code/ATMOSPHERICS/pipes/manifold4w.dm
  code/ATMOSPHERICS/pipes/simple.dm
  code/ATMOSPHERICS/pipes/tank.dm
  code/ATMOSPHERICS/pipes/universal.dm
  code/__defines/construction.dm
  code/game/machinery/pipe/construction.dm
  code/game/machinery/pipe/pipe_dispenser.dm
  code/game/machinery/pipe/pipe_recipes.dm
  code/modules/multiz/pipes.dm
  icons/atmos/connector.dmi
  icons/atmos/manifold.dmi
  icons/atmos/pipe_underlays.dmi
  icons/atmos/pipes.dmi
  icons/atmos/pump.dmi
  icons/atmos/vent_pump.dmi
  icons/obj/pipes.dmi
  icons/obj/structures.dmi
Labels: Feature

#6986 Fix manifold and manifold4w underlay rendering.
  code/ATMOSPHERICS/pipes/manifold.dm
  code/ATMOSPHERICS/pipes/manifold4w.dm
  code/ATMOSPHERICS/pipes/vent.dm
  icons/obj/pipe-item.dmi
Labels: Oversight, Refactor

#6987 [PORT] Fix offline vent pumps and scrubbers on loaded maps.
  code/controllers/subsystem.dm
  code/modules/maps/tg/map_template.dm
Labels: Bugfix, Refactor

#6989 Random blast door fix
  code/game/machinery/doors/blast_door.dm
Labels: Refactor

#6971 Suit Cyclers: Faster, Smarter, Better
  code/game/machinery/suit_storage_unit.dm
Labels: Refactor

#6985 Security Voidsuit Overhaul Redux
  code/datums/supplypacks/voidsuits.dm
  code/modules/clothing/spacesuits/void/station.dm
  icons/mob/species/seromi/head.dmi
  icons/mob/species/seromi/suit.dmi
  icons/mob/species/skrell/helmet.dmi
  icons/mob/species/skrell/suit.dmi
  icons/mob/species/tajaran/helmet.dmi
  icons/mob/species/tajaran/suit.dmi
  icons/mob/species/unathi/helmet.dmi
  icons/mob/species/unathi/suit.dmi
  icons/obj/clothing/species/seromi/hats.dmi
  icons/obj/clothing/species/seromi/suits.dmi
  icons/obj/clothing/species/skrell/hats.dmi
  icons/obj/clothing/species/skrell/suits.dmi
  icons/obj/clothing/species/tajaran/hats.dmi
  icons/obj/clothing/species/tajaran/suits.dmi
  icons/obj/clothing/species/unathi/hats.dmi
  icons/obj/clothing/species/unathi/suits.dmi
Labels: Feature Tweak, Sprite Change

#6991 Allow 'offmap spawn' jobs to be isolated from station employees
  code/datums/datacore.dm
  code/defines/obj.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job_controller.dm
  code/game/world.dm
  code/modules/client/preferences_spawnpoints.dm
  code/modules/economy/Accounts.dm
  code/modules/economy/Accounts_DB.dm
  code/modules/mob/new_player/new_player.dm
Labels: Refactor

#6993 [PORT] Make glass firedoors constructable/deconstructable.
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/doors/firedoor_assembly.dm
  html/changelogs/Leshana-vplk-glass-firedoors.yml
Labels: Feature Tweak

#6996 [PORT] Refactor the Open Space controller into MC Subsystem
  code/__defines/subsystems.dm
  code/controllers/subsystems/open_space.dm
  code/modules/multiz/open_space_controller.dm
  code/modules/multiz/turf.dm
  polaris.dme
Labels: Bugfix, Refactor

#6999 Update Human HUD Generation to Fix Internals Graphical Bug
  code/_onclick/hud/human.dm
Labels: Bugfix

#6997 Replaces toy waterflower with spraybottle waterflower
  code/game/machinery/computer/arcade.dm
  code/game/machinery/vending.dm
  code/game/objects/items/toys.dm
  code/game/objects/random/mapping.dm
  code/game/objects/random/misc.dm
  code/modules/client/preference_setup/loadout/loadout_general.dm
  code/modules/mining/abandonedcrates.dm
Labels: Bugfix, Refactor

#6998 Adds empty filter classes to send messages to particular vchat filters.
  code/_helpers/logging.dm
  code/modules/admin/DB ban/functions.dm
  code/modules/admin/NewBan.dm
  code/modules/admin/ToRban.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_investigate.dm
  code/modules/admin/admin_memo.dm
  code/modules/admin/admin_verb_lists.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/callproc/callproc.dm
  code/modules/admin/holder2.dm
  code/modules/admin/map_capture.dm
  code/modules/admin/permissionverbs/permissionedit.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/BrokenInhands.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminjump.dm
  code/modules/admin/verbs/atmosdebug.dm
  code/modules/admin/verbs/buildmode.dm
  code/modules/admin/verbs/custom_event.dm
  code/modules/admin/verbs/debug.dm
  code/modules/vchat/js/vchat.js
  html/changelogs/atermonera_vchat_filters1.yml
  polaris.dme
Labels: Bugfix, Needs Review, Refactor, VChat Filter Issue

#7007 Fix Sundry Runtime Errors XII
  code/game/atoms_movable.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/turfs/simulated/floor_attackby.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/mob/new_player/preferences_setup.dm
  code/modules/xenoarcheaology/finds/find_spawning.dm
Labels: Bugfix

#7009 Fixes supermatter monitoring EPR indicator showing Undefined
  code/modules/modular_computers/file_system/programs/engineering/supermatter_monitor.dm
  code/modules/power/supermatter/supermatter.dm
Labels: Oversight

#7015 Airlock Description Error
  code/game/machinery/doors/door.dm
  html/changelogs/Shadow_Airlocks.yml
Labels: Oversight

#7023 Roiling Mold Blob Fix/Tweak
  code/modules/blob2/overmind/types/roiling_mold.dm
  code/modules/projectiles/projectile/arc.dm
Labels: Bugfix

#7012 Fixes HE pipes not leaking when breached
  code/ATMOSPHERICS/pipes/he_pipes.dm
Labels: Oversight

#7037 Fix HTML Injection bug in saycode
  code/modules/mob/say.dm
Labels: Oversight, Priority: CRITICAL

#7021 Fixes Large Escape Pod #2
  maps/southern_cross/southern_cross-7.dmm
  maps/southern_cross/southern_cross_shuttles.dm
Labels: Bugfix, Map Change / Issue, Oversight, Priority: High

#7022 changelog
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Leshana-vplk-glass-firedoors.yml
  html/changelogs/atermonera_circuitpants_holstered.yml
  html/changelogs/atermonera_employment_comments.yml
  html/changelogs/atermonera_examine_pref.yml
  html/changelogs/atermonera_vchat_filters1.yml
  html/changelogs/ateromnera_vchat_pref.yml
  html/changelogs/neerti-qol_medical_2.yml
Labels: Changelog Update

#6992 Dual-wield Penalties and Urist Onmob Sprites
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/sniper.dm
  html/changelogs/novacat-dualwielding.yml
  icons/mob/back.dmi
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
Labels: Feature Tweak, Sprite Change

#7014 Adds Colorable Apron & Tesh Labcoat
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
  code/modules/clothing/suits/aliens/seromi.dm
  code/modules/clothing/suits/jobs.dm
  icons/mob/species/seromi/suit.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Feature, Sprite Change

#7025 Removes stray unused variable that triggered a compile warning
  code/modules/mob/new_player/new_player.dm
Labels: Oversight

#7026 More machinery power update_var() proc usage
  code/ATMOSPHERICS/components/trinary_devices/filter.dm
  code/game/gamemodes/malfunction/malf_hardware.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/bioprinter.dm
  code/game/machinery/camera/presets.dm
  code/game/machinery/computer/camera.dm
  code/game/machinery/exonet_node.dm
  code/game/machinery/floor_light.dm
  code/game/machinery/machinery.dm
  code/game/machinery/magnet.dm
  code/game/machinery/pda_multicaster.dm
  code/game/machinery/supplybeacon.dm
  code/game/objects/structures/holoplant.dm
  code/modules/holodeck/HolodeckControl.dm
  code/modules/overmap/ships/computers/computer_shims.dm
  code/modules/power/fusion/core/_core.dm
  code/modules/power/fusion/gyrotron/gyrotron.dm
  code/modules/power/fusion/gyrotron/gyrotron_control.dm
  code/modules/power/lighting.dm
  code/modules/power/singularity/particle_accelerator/particle_control.dm
  code/modules/research/server.dm
  code/modules/shieldgen/emergency_shield.dm
Labels: Project, Refactor

#7031 Fixes Phazon and Janus being unable to phase
  code/game/mecha/combat/phazon.dm
Labels: Bugfix

#7032 Excludes AI shells from event probability calculations
  code/modules/metric/department.dm
Labels: Oversight

#7035 [PORT] Ship/Shuttle Console Construction
  code/controllers/subsystems/shuttles.dm
  code/game/objects/items/weapons/circuitboards/computer/computer.dm
  code/game/objects/items/weapons/circuitboards/computer/shuttle.dm
  code/modules/overmap/ships/computers/engine_control.dm
  code/modules/overmap/ships/computers/helm.dm
  code/modules/overmap/ships/computers/sensors.dm
  code/modules/overmap/ships/computers/ship.dm
  code/modules/overmap/ships/computers/shuttle.dm
  code/modules/shuttles/shuttle.dm
  code/modules/shuttles/shuttle_console.dm
  code/modules/shuttles/shuttle_console_multi.dm
  html/changelogs/Leshana-vplk-shuttle-construction.yml
  polaris.dme
Labels: Feature

#7036 Fixes Intellicore grabbing AI multiple times
  code/game/objects/items/devices/aicard.dm
Labels: Oversight

#7018 Space spaced through open space looks like space
  code/modules/multiz/turf.dm
Labels: Bugfix, Priority: Medium

#7006 Ports some power.dmi sprites from Bay
  code/ATMOSPHERICS/components/binary_devices/circulator.dm
  code/modules/power/cable.dm
  code/modules/power/generator.dm
  icons/obj/pipes.dmi
  icons/obj/power.dmi
Labels: Sprite Change

#7024 Converts Shutoff valve monitoring into a MC program
  code/game/machinery/computer/shutoff_monitor.dm
  code/modules/modular_computers/computers/subtypes/preset_console.dm
  code/modules/modular_computers/file_system/programs/engineering/shutoff_monitor.dm
  html/changelogs/atlantiscze-valveprogram.yml
  nano/templates/shutoff_monitor.tmpl
  polaris.dme
Labels: Feature Tweak

#7033 Urist Gun sprites
  icons/obj/gun2.dmi
Labels: Sprite Change

#7016 Adds heterochromia, makes Teshari clothes recolorable (and footwraps)
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_races/markings.dmi
Labels: Feature

#7003 Allow fighters to traverse overmap ships predictably
  code/game/mecha/combat/fighter.dm
  code/modules/multi-tile/multi-tile.dm
Labels: Feature Tweak, Oversight

#7041 Slightly clean disposal pipe construction code.
  code/__defines/construction.dm
  code/game/machinery/pipe/pipe_dispenser.dm
  code/game/machinery/pipe/pipe_recipes.dm
  code/modules/recycling/disposal-construction.dm
Labels: Refactor

#7042 Add "icon sheet" asset type
  code/controllers/subsystems/assets.dm
  code/modules/client/asset_cache.dm
Labels: Optimization

#7045 Removes limits on eating, centralizes nutrition changing.
  code/__defines/mobs.dm
  code/game/gamemodes/changeling/powers/absorb.dm
  code/game/gamemodes/technomancer/spells/energy_siphon.dm
  code/game/machinery/computer/arcade.dm
  code/game/machinery/rechargestation.dm
  code/game/objects/items/crayons.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/food/food/snacks.dm
  code/modules/mob/_modifiers/modifiers_misc.dm
  code/modules/mob/_modifiers/unholy.dm
  code/modules/mob/living/carbon/alien/diona/life.dm
  code/modules/mob/living/carbon/alien/life.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/human_powers.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species/station/prometheans.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/simple_mob/subtypes/slime/xenobio/consumption.dm
  code/modules/mob/living/simple_mob/subtypes/slime/xenobio/xenobio.dm
  code/modules/mob/mob_defines.dm
  code/modules/organs/blood.dm
  code/modules/organs/subtypes/machine.dm
  code/modules/power/cells/power_cells.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Core.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
  code/modules/spells/spellbook.dm
  code/modules/virus2/effect.dm
  code/modules/xenoarcheaology/effects/heal.dm
  code/modules/xenoarcheaology/effects/hurt.dm
  html/changelogs/neerti_all_the_food.yml
Labels: Feature Tweak, Staff Request

#7046 Tweaks and fixes for the new new event system.
  code/game/area/areas.dm
  code/modules/gamemaster/event2/event.dm
  code/modules/gamemaster/event2/events/engineering/airlock_failure.dm
  code/modules/gamemaster/event2/events/engineering/brand_intelligence.dm
  code/modules/gamemaster/event2/events/engineering/spacevine.dm
  code/modules/gamemaster/event2/events/engineering/window_break.dm
  code/modules/gamemaster/event2/events/everyone/gravity.dm
  code/modules/gamemaster/event2/events/security/prison_break.dm
  code/modules/gamemaster/event2/events/synthetic/ion_storm.dm
  code/modules/power/generator.dm
  maps/southern_cross/southern_cross_events.dm
Labels: Bugfix, Feature Tweak
