Repository PolarisSS13/Polaris, pull requests merged in 2020-06, with the labels that each got.

#7136 Add AI Picture-in-Picture Mode!
  code/_onclick/ai.dm
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/ai.dm
  code/_onclick/hud/movable_screen_objects.dm
  code/_onclick/hud/picture_in_picture.dm
  code/_onclick/hud/screen_objects.dm
  code/game/machinery/camera/camera.dm
  code/modules/mob/freelook/ai/eye.dm
  code/modules/mob/freelook/chunk.dm
  code/modules/mob/freelook/eye.dm
  code/modules/mob/freelook/visualnet.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/mob/living/silicon/ai/login.dm
  code/modules/mob/living/silicon/ai/multicam.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/mob.dm
  code/modules/overmap/spacetravel.dm
  icons/misc/pic_in_pic.dmi
  icons/mob/screen_ai.dmi
  icons/turf/areas.dmi
  maps/southern_cross/southern_cross-6.dmm
  polaris.dme
Labels: Feature, Results To Be Reviewed

#7249 Species Vars Extension
  code/__defines/species_languages.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
Labels: Feature

#7256 Tweak railguns, add flechette pistol
  code/modules/projectiles/ammunition/magnetic.dm
  code/modules/projectiles/guns/magnetic/magnetic.dm
  code/modules/projectiles/guns/magnetic/magnetic_railgun.dm
  code/modules/projectiles/projectile/magnetic.dm
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
  icons/obj/ammo.dmi
  icons/obj/projectiles.dmi
  icons/obj/railgun.dmi
Labels: Refactor, Sprite Change

#7261 Another Lesser Rotation
  code/modules/reagents/dispenser/dispenser2.dm
  maps/southern_cross/southern_cross-1.dmm
Labels: Bugfix, Map Change / Issue

#7262 fixes hybrid crowbars
  code/game/objects/items/weapons/tools/crowbar.dm
Labels: Oversight

#7263 Remove bloodspray when pulling standing people
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
Labels: Bugfix

#7237 Fixes runtimes related to mmi_holder and defib_timer
  code/modules/organs/subtypes/machine.dm
  polaris.dme
Labels: Bugfix

#7241 Adds proc to replace default cells with high cap on machinery
  code/game/machinery/machinery.dm
  code/game/machinery/rechargestation.dm
  code/modules/mining/drilling/drill.dm
Labels: Bugfix

#7211 Talking, and other bugs
  code/modules/mob/language/language.dm
  code/modules/mob/living/carbon/brain/brain.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/say.dm
  code/modules/organs/organ.dm
  code/modules/organs/subtypes/machine.dm
Labels: Bugfix

#7264 Adds marble floor tiles and crafting recipe
  code/game/objects/items/stacks/tiles/fifty_spawner_tiles.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/flooring/flooring_premade.dm
  code/modules/materials/material_recipes.dm
  html/changelogs/billybangles-marbletile.yml
  icons/obj/stacks.dmi
  icons/turf/flooring/misc.dmi
Labels: Feature

#7265 Allow reagents to have specific metaglass icon files
  code/modules/food/drinkingglass/metaglass.dm
Labels: Refactor

#7266 Vintage Voidsuits Expansion
  code/game/machinery/suit_storage_unit.dm
  code/modules/clothing/spacesuits/void/event.dm
  icons/mob/head.dmi
  icons/mob/spacesuit.dmi
  icons/mob/species/skrell/helmet.dmi
  icons/mob/species/skrell/suit.dmi
  icons/mob/species/tajaran/helmet.dmi
  icons/mob/species/tajaran/suit.dmi
  icons/mob/species/unathi/helmet.dmi
  icons/mob/species/unathi/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/spacesuits.dmi
  icons/obj/clothing/species/skrell/hats.dmi
  icons/obj/clothing/species/skrell/suits.dmi
  icons/obj/clothing/species/tajaran/hats.dmi
  icons/obj/clothing/species/tajaran/suits.dmi
  icons/obj/clothing/species/unathi/hats.dmi
  icons/obj/clothing/species/unathi/suits.dmi
Labels: Feature

#7269 Add airless versions of some Eris floors, tweak layers
  code/__defines/_planes+layers.dm
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/flooring/flooring_decals.dm
  code/game/turfs/simulated/floor_types_eris.dm
Labels: Feature Tweak

#7270 Prevents lava from being blown up
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/simulated/lava.dm
Labels: Oversight

#7271 fixes small package examination
  code/modules/recycling/sortingmachinery.dm
Labels: Oversight

#7277 [PORT] Fix vchat loading history without errors
  code/controllers/subsystems/chat.dm
  code/modules/vchat/vchat_client.dm
  code/modules/vchat/vchat_db.dm
Labels: Bugfix, Quality of Life

#7257 Telecomms fixes
  code/game/machinery/telecomms/presets.dm
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-6.dmm
  maps/southern_cross/southern_cross_defines.dm
  maps/southern_cross/southern_cross_presets.dm
  polaris.dme
Labels: Bugfix

#7290 mining drill and recharger find their shiny new cells
  code/game/machinery/machinery.dm
  code/game/machinery/rechargestation.dm
  code/modules/mining/drilling/drill.dm
Labels: Oversight, Priority: High

#7275 Fix virology typo
  code/modules/virus2/effect.dm
Labels: Oversight

#7276 Make it so you can FINALLY export other things but platinum and phoron.
  code/controllers/subsystems/supply.dm
Labels: Feature

#7278 Remove Unused Image Assets
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/client/asset_cache.dm
  icons/pda_icons/pda_atmos.png
  icons/pda_icons/pda_back.png
  icons/pda_icons/pda_bell.png
  icons/pda_icons/pda_blank.png
  icons/pda_icons/pda_boom.png
  icons/pda_icons/pda_bucket.png
  icons/pda_icons/pda_chatroom.png
  icons/pda_icons/pda_crate.png
  icons/pda_icons/pda_cuffs.png
  icons/pda_icons/pda_eject.png
  icons/pda_icons/pda_exit.png
  icons/pda_icons/pda_flashlight.png
  icons/pda_icons/pda_honk.png
  icons/pda_icons/pda_locked.PNG
  icons/pda_icons/pda_mail.png
  icons/pda_icons/pda_medical.png
  icons/pda_icons/pda_menu.png
  icons/pda_icons/pda_mule.png
  icons/pda_icons/pda_notes.png
  icons/pda_icons/pda_power.png
  icons/pda_icons/pda_rdoor.png
  icons/pda_icons/pda_reagent.png
  icons/pda_icons/pda_refresh.png
  icons/pda_icons/pda_scanner.png
  icons/pda_icons/pda_signaler.png
  icons/pda_icons/pda_status.png
  icons/spideros_icons/sos_1.png
  icons/spideros_icons/sos_10.png
  icons/spideros_icons/sos_11.png
  icons/spideros_icons/sos_12.png
  icons/spideros_icons/sos_13.png
  icons/spideros_icons/sos_14.png
  icons/spideros_icons/sos_2.png
  icons/spideros_icons/sos_3.png
  icons/spideros_icons/sos_4.png
  icons/spideros_icons/sos_5.png
  icons/spideros_icons/sos_6.png
  icons/spideros_icons/sos_7.png
  icons/spideros_icons/sos_8.png
  icons/spideros_icons/sos_9.png
Labels: Unwanted Feature Removal

#7281 Fix Penetrating Bullet Double-Jeopardy
  code/modules/projectiles/projectile.dm
Labels: Bugfix, Priority: Medium

#7283 Generalizes supply points per material sheet to the material datum.
  code/controllers/subsystems/supply.dm
  code/modules/materials/materials.dm
Labels: Refactor

#7285 Fixes a crash exploit.
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
Labels: Oversight

#7286 Combo damage type repair.
  code/modules/mob/living/damage_procs.dm
Labels: Bugfix, Priority: High

#7287 Make gloves half as expensive.
  code/modules/client/preference_setup/loadout/loadout_gloves.dm
Labels: Feature Tweak

#7288 Fix bug with in-round constructed teleporters
  code/game/machinery/teleporter.dm
Labels: Oversight

#7289 Give rock turfs radiation blocking capabilities.
  code/modules/radiation/radiation.dm
Labels: Feature Tweak

#6954 Enables overmap on SC, adds Sif to SC skybox
  code/controllers/subsystems/skybox.dm
  code/modules/multiz/basic.dm
  code/modules/overmap/overmap_planet.dm
  code/modules/overmap/sectors.dm
  icons/skybox/planet.dmi
  maps/southern_cross/overmap/sectors.dm
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-3.dmm
  maps/southern_cross/southern_cross.dm
  maps/southern_cross/southern_cross_defines.dm
  polaris.dme
Labels: Feature Tweak, Lore, Sprite Change

#7279 Change eris plating paths
  code/game/turfs/simulated/floor_types_eris.dm
Labels: Refactor

#7295 Dirt Fix
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/simulated/outdoors/dirt.dm
Labels: Feature

#7296 Fixes heater examining
  code/ATMOSPHERICS/components/unary/heat_source.dm
Labels: Oversight

#7297 Wrist-bound PDAs!
  code/_helpers/global_lists.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/client/preference_setup/general/04_equipment.dm
  html/changelogs/greenjoe - wrist PDAs.yml
  icons/mob/pda_wrist.dmi
  icons/mob/species/seromi/pda_wrist.dmi
  icons/obj/pda_wrist.dmi
  polaris.dme
Labels: Feature

#7273 Observing improvements
  code/_helpers/unsorted.dm
  code/modules/mob/mob.dm
  code/modules/power/tesla/energy_ball.dm
Labels: Optimization, Refactor

#7298 Hoorah. More Typo Fixy
  code/modules/events/solar_storm.dm
  code/modules/gamemaster/event2/events/everyone/solar_storm.dm
Labels: Oversight

#7299 un-earrapifies instruments
  code/game/objects/structures/musician.dm
Labels: Quality of Life

#7305 automated shuttles can dock with sif
  maps/southern_cross/overmap/sectors.dm
Labels: Oversight, Priority: CRITICAL

#7301 Suit Cycler Tweaks/Improvements
  code/game/machinery/suit_storage_unit.dm
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/clothing/spacesuits/void/void.dm
Labels: Feature Tweak

#7308 Fix sector initialization overflow crash.
  code/controllers/subsystems/skybox.dm
  code/modules/multiz/basic.dm
  code/modules/overmap/sectors.dm
Labels: Bugfix, Priority: High

#7303 Adds chess pieces and chessboard holodeck program
  code/game/area/Space Station 13 areas.dm
  code/game/objects/items/toys.dm
  code/game/turfs/flooring/flooring_decals.dm
  code/modules/holodeck/HolodeckControl.dm
  code/modules/holodeck/HolodeckObjects.dm
  html/changelogs/billybangles-chessboard.yml
  icons/obj/chess.dmi
  icons/turf/flooring/decals.dmi
  maps/southern_cross/southern_cross-6.dmm
Labels: Feature

#7304 Offload Defibrillatability from NO_SCAN
  code/__defines/species_languages.dm
  code/game/objects/items/devices/defib.dm
  code/modules/client/preference_setup/general/03_body.dm
  code/modules/mob/living/carbon/human/species/outsider/event.dm
  code/modules/mob/living/carbon/human/species/outsider/shadow.dm
  code/modules/mob/living/carbon/human/species/outsider/skeleton.dm
  code/modules/mob/living/carbon/human/species/outsider/vox.dm
  code/modules/mob/living/carbon/human/species/station/golem.dm
  code/modules/mob/living/carbon/human/species/station/prometheans.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/carbon/human/species/xenomorphs/alien_species.dm
Labels: Feature Tweak

#7302 changelog update
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/KasparoVv - PR - 7215.yml
  html/changelogs/arokha-janicart.yml
  html/changelogs/atermonera - vchat_exportlog.yml
  html/changelogs/billybangles-marbletile.yml
  html/changelogs/greenjoe - wrist PDAs.yml
Labels: Changelog Update

#7311 Fix timing error that allowed processing to reference a nulled list.
  code/modules/projectiles/projectile.dm
Labels: Bugfix, Priority: CRITICAL
