Repository PolarisSS13/Polaris, pull requests merged in 2020-01, with the labels that each got.

#6589 Allows admin spawning fruit in multiples
  code/modules/admin/admin.dm
Labels: Feature Tweak

#6590 Fixes AI not being able to escape out of energy nets
  code/game/objects/items/weapons/weaponry.dm
Labels: Bugfix

#6504 Change Vent Pump/Scrubbers to Retro-like with actual fanblades
  icons/atmos/vent_pump.dmi
  icons/atmos/vent_scrubber.dmi
Labels: Sprite Change

#6593 GameMaster Tuning
  code/game/objects/structures/props/swarm.dm
  code/modules/gamemaster/actions/swarmboarder.dm
  code/modules/gamemaster/game_master.dm
  code/modules/mob/holder.dm
  code/modules/mob/living/silicon/robot/drone/swarm.dm
  code/modules/mob/living/silicon/robot/drone/swarm_abilities.dm
  code/modules/mob/living/silicon/robot/drone/swarm_items.dm
  code/modules/projectiles/guns/energy/stun.dm
Labels: Feature Tweak

#6594 last changelog of the decade
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Cerebulon - Coffee Shop.yml
  html/changelogs/TheFurryFeline - Bulbs_Recycling.yml
  html/changelogs/TheFurryFeline - Print_Da_Sprayers.yml
  html/changelogs/atermonera - rad_buff.yml
Labels: Changelog Update

#6592 Xenoflora expansion take2
  code/game/machinery/seed_extractor.dm
  code/game/objects/items/weapons/material/chainsaw.dm
  code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm
  code/modules/hydroponics/_hydro_setup.dm
  code/modules/hydroponics/seed.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/seed_packets.dm
  code/modules/hydroponics/seed_storage.dm
  code/modules/hydroponics/spreading/spreading_response.dm
  code/modules/hydroponics/trays/tray.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/dispenser/dispenser_presets.dm
  code/modules/reagents/distilling/Distilling-Recipes.dm
  icons/obj/closet.dmi
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-4.dmm
  maps/southern_cross/southern_cross-6.dmm
Labels: Feature

#6595 adds gnomes.
  code/datums/supplypacks/contraband.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/seed_packets.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  icons/obj/hydroponics_growing.dmi
  icons/obj/hydroponics_products.dmi
  icons/obj/seeds.dmi
Labels: Feature

#6602 Makes legcuffs printable in hacked autolathe
  code/datums/autolathe/general.dm
Labels: Feature

#6606 Fixes clamp being used with wrong syntax in places
  code/game/objects/items/weapons/tanks/tanks.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_grab_specials.dm
Labels: BYOND Issue, Bugfix

#6610 Adds Pyralis borg sprite
  code/modules/mob/living/silicon/robot/robot_modules/station.dm
  html/changelogs/schnayy-glitterfly_borg.yml
  icons/mob/robots.dmi
Labels: Feature

#6623 Fixes calculation of wall rad resistance
  code/modules/radiation/radiation.dm
Labels: Oversight

#6612 Ctrl+Click now removes pens from PDAs
  code/game/objects/items/devices/PDA/PDA.dm
Labels: Feature Tweak

#6613 Fixes Map-Edited cryo freezers
  maps/southern_cross/southern_cross-1.dmm
Labels: Map Change / Issue

#6614 Psychiatrists can now properly get the medical turtleneck via loadout
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
Labels: Oversight

#6615 Fixes ion proj not EMPing when hitting walls
  code/modules/projectiles/projectile/special.dm
Labels: Bugfix, Priority: Medium

#6616 Sign Language translator now properly works
  code/modules/integrated_electronics/subtypes/input.dm
Labels: Bugfix

#6618 Event manager logs now show correct station time
  code/controllers/subsystems/events.dm
Labels: Oversight

#6619 Can now (de)construct chem masters
  code/game/objects/items/weapons/circuitboards/other.dm
  code/modules/reagents/Chemistry-Machinery.dm
  code/modules/research/designs/circuits/circuits.dm
Labels: Feature Tweak

#6620 Pauses event processing while doing event actions
  code/controllers/subsystems/events.dm
  code/modules/events/event.dm
Labels: Refactor

#6622 Water resistance exists
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/prometheans.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Core.dm
Labels: Feature Tweak

#6632 Move Microwave recipes to their own subtype of the recipe datum.
  code/datums/recipe.dm
  code/modules/food/food/thecake.dm
  code/modules/food/kitchen/microwave.dm
  code/modules/food/recipe_dump.dm
  code/modules/food/recipes_microwave.dm
Labels: Refactor

#6636 Fix various syntactic problems
  SpacemanDMM.toml
  code/ZAS/Controller.dm
  code/datums/position_point_vector.dm
  code/game/machinery/newscaster.dm
  code/game/objects/items/devices/whistle.dm
  code/game/objects/items/weapons/material/misc.dm
  code/game/turfs/simulated/wall_attacks.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_secrets.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/spacesuits/rig/suits/light.dm
  code/modules/economy/cash_register.dm
  code/modules/economy/retail_scanner.dm
  code/modules/flufftext/TextFilters.dm
  code/modules/hydroponics/trays/tray.dm
  code/modules/library/lib_items.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/silicon/robot/subtypes/lost_drone.dm
  code/modules/multiz/movement.dm
  code/modules/paperwork/carbonpaper.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/paper_bundle.dm
  code/modules/power/apc.dm
  code/modules/power/singularity/collector.dm
  code/modules/research/rdconsole.dm
  code/modules/scripting/Parser/Expressions.dm
  code/modules/scripting/Parser/Keywords.dm
  code/modules/scripting/Parser/Parser.dm
  code/modules/scripting/Scanner/Scanner.dm
Labels: Higgs Bugson, Refactor

#6630 IP reputation checking
  code/controllers/configuration.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/panicbunker.dm
  code/modules/client/client defines.dm
  code/modules/client/client procs.dm
  config/example/config.txt
Labels: Feature

#6638 Drops the time between events possible duration.
  code/modules/gamemaster/game_master.dm
Labels: Staff Request

#6648 Fix Water Resistance.
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/prometheans.dm
Labels: Bugfix, Priority: CRITICAL

#6644 Drink sprite additions
  code/modules/food/drinkingglass/metaglass.dm
  icons/obj/drinks.dmi
Labels: Sprite Change

#6645 Adds book cart to library
  code/modules/library/lib_items.dm
  html/changelogs/schnayy-bookcart.yml
  icons/obj/library.dmi
  maps/southern_cross/southern_cross-1.dmm
Labels: Feature, Map Change / Issue

#6639 Preset (mapped-in) modular computers now have printers by default.
  code/modules/modular_computers/computers/subtypes/preset_console.dm
  html/changelogs/atermonera - preset_printers.yml
Labels: Feature Tweak

#6637 Augments Respect Beds, Robotic
  code/modules/organs/internal/augment.dm
Labels: Bugfix

#6649 Fixes Bagel Poppy Recipe
  code/modules/food/recipes_microwave.dm
Labels: Oversight

#6603 Add an audible alarm sound to SM Delamination
  code/modules/power/supermatter/supermatter.dm
  sound/ambience/matteralarm.ogg
Labels: Feature

#6650 Fixes constant stacking machine runtimes
  code/modules/mining/machine_stacking.dm
Labels: Bugfix

#6651 Ports Clothing Expansion Code from World Server
  code/__defines/mobs.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/clothing/under/pants.dm
  code/modules/clothing/under/shorts.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/mob/items/lefthand_suits.dmi
  icons/mob/items/lefthand_suits_1.dmi
  icons/mob/items/lefthand_uniforms.dmi
  icons/mob/items/lefthand_uniforms_1.dmi
  icons/mob/items/righthand_suits.dmi
  icons/mob/items/righthand_suits_1.dmi
  icons/mob/items/righthand_uniforms.dmi
  icons/mob/items/righthand_uniforms_1.dmi
  icons/mob/suit.dmi
  icons/mob/suit_1.dmi
  icons/mob/uniform.dmi
  icons/mob/uniform_1.dmi
  icons/mob/uniform_rolled_down_1.dmi
  icons/mob/uniform_sleeves_rolled_1.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/suits_1.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/clothing/uniforms_1.dmi
Labels: Refactor

#6652 Hacky Fix for Athletic Shorts showing Missing Icon
  code/modules/clothing/under/shorts.dm
Labels: Bugfix
