Repository PolarisSS13/Polaris, pull requests merged in 2020-11, with the labels that each got.

#7629 Fresh Meat, Leatherworking
  code/__defines/misc.dm
  code/game/machinery/washing_machine.dm
  code/game/objects/items/stacks/sheets/leather.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/structures/bonfire.dm
  code/modules/food/kitchen/gibber.dm
  code/modules/food/kitchen/smartfridge.dm
  code/modules/materials/material_recipes.dm
  code/modules/materials/material_sheets.dm
  code/modules/materials/materials.dm
  code/modules/mob/living/butchering.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_organs.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/organs.dm
  code/modules/mob/living/simple_mob/appearance.dm
  code/modules/mob/living/simple_mob/butchering.dm
  code/modules/mob/living/simple_mob/defense.dm
  code/modules/mob/living/simple_mob/harvesting.dm
  code/modules/mob/living/simple_mob/life.dm
  code/modules/mob/living/simple_mob/simple_mob.dm
  code/modules/mob/living/simple_mob/subtypes/animal/animal.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/_giant_spider.dm
  code/modules/organs/internal/augment.dm
  code/modules/organs/internal/brain.dm
  code/modules/organs/internal/liver.dm
  code/modules/organs/internal/robotic/robotic.dm
  code/modules/organs/organ.dm
  code/modules/organs/organ_external.dm
  code/modules/organs/organ_icon.dm
  code/modules/organs/subtypes/machine.dm
  code/modules/organs/subtypes/standard.dm
  html/changelogs/mechoid - butchery.yml
  icons/obj/butchery.dmi
  icons/obj/stacks.dmi
  polaris.dme
Labels: Feature, Feature Tweak

#7701 Adds the Frostbelle
  code/game/objects/structures/flora/flora.dm
  code/game/turfs/simulated/outdoors/grass.dm
  code/modules/food/food/snacks.dm
  code/modules/food/recipes_fryer.dm
  icons/obj/flora/sifflora.dmi
  icons/obj/food_ingredients.dmi
  icons/obj/food_syn.dmi
Labels: Feature

#7751 Ports some clothing from uristcode
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/species/seromi/head.dmi
  icons/mob/species/seromi/uniform.dmi
  icons/mob/uniform_1.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/clothing/uniforms_1.dmi
Labels: Feature, Sprite Change

#7671 Self-Surgery
  code/_helpers/unsorted.dm
  code/_onclick/item_attack.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_powers.dm
  code/modules/surgery/surgery.dm
Labels: Feature

#7759 Fix Simplemob+ Organs
  code/modules/mob/living/butchering.dm
  code/modules/mob/living/organs.dm
  code/modules/mob/living/simple_mob/simple_mob.dm
  code/modules/organs/organ.dm
Labels: Bugfix, Priority: High

#7745 Adds one (1) PoI
  maps/submaps/surface_submaps/plains/VRDen.dmm
  maps/submaps/surface_submaps/plains/plains.dm
  maps/submaps/surface_submaps/plains/plains_areas.dm
Labels: Point of Interest

#7767 Tweak Ventcrawl To Allow Allowed Items to be Worn
  code/modules/ventcrawl/ventcrawl.dm
Labels: Feature Tweak

#7739 Datum Component System (/tg/ port)
  code/__defines/dcs/flags.dm
  code/__defines/dcs/helpers.dm
  code/__defines/dcs/signals.dm
  code/__defines/vv.dm
  code/_helpers/sorts/comparators.dm
  code/_helpers/type2type.dm
  code/_helpers/unsorted.dm
  code/_onclick/item_attack.dm
  code/controllers/subsystems/dcs.dm
  code/controllers/subsystems/garbage.dm
  code/datums/components/README.md
  code/datums/components/_component.dm
  code/datums/datum.dm
  code/datums/datumvars.dm
  code/datums/elements/_element.dm
  code/datums/observation/moved.dm
  code/game/atoms.dm
  code/world.dm
  interface/skin.dmf
  polaris.dme
Labels: Feature

#7754 Fix toeless knee and thigh high jackboots
  icons/mob/feet.dmi
Labels: Bugfix, Sprite Change

#7755 Fixes pointing going under mobs.
  code/modules/mob/mob.dm
Labels: Layering Issue

#7761 Arm-Laser rebranding.
  code/modules/projectiles/guns/energy/laser.dm
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
Labels: Feature Tweak, Sprite Change

#7766 Teshari name generation fix
  code/modules/mob/language/station.dm
Labels: Oversight

#7768 Move away from Travis CI to GitHub Actions
  .github/workflows/ci.yml
  .travis.yml
  _build_dependencies.sh
  code/_away_mission_tests.dm
  code/_helpers/text.dm
  code/_map_tests.dm
  code/_unit_tests.dm
  code/controllers/subsystems/air.dm
  code/game/antagonist/station/rogue_ai.dm
  code/modules/research/prosfab_designs.dm
  maps/submaps/engine_submaps/southern_cross/_engine_submaps.dm
  maps/submaps/space_submaps/space.dm
  maps/submaps/surface_submaps/mountains/mountains.dm
  maps/submaps/surface_submaps/plains/plains.dm
  maps/submaps/surface_submaps/wilderness/wilderness.dm
  maps/~map_system/maps.dm
  tools/TagMatcher/tag-matcher.py
  tools/ci/build_tgui.sh
  tools/ci/compile_and_run.sh
  tools/ci/install_build_deps.sh
  tools/ci/install_byond.sh
  tools/ci/validate_files.sh
Labels: Needs Review, Priority: High, Refactor
