Repository PolarisSS13/Polaris, pull requests merged in 2021-10, with the labels that each got.

#8309 Fixes flamethrower fuel spread runtime
  code/game/objects/effects/decals/Cleanable/fuel.dm
Labels: Oversight

#8305 Donk-Soft!
  code/datums/outfits/costumes/halloween.dm
  code/datums/supplypacks/recreation.dm
  code/game/machinery/computer/arcade.dm
  code/game/objects/items/toys/toys.dm
  code/game/objects/items/weapons/gift_wrappaper.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/random/misc.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/economy/vending_machines.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/ammunition/rounds.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  code/modules/projectiles/guns/projectile/toy.dm
  code/modules/projectiles/projectile/bullets.dm
  icons/mob/belt.dmi
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/ammo.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/gun.dmi
  icons/obj/gun_toy.dmi
  icons/obj/projectiles.dmi
  icons/obj/vending.dmi
  polaris.dme
Labels: Feature

#8315 Rootspeak isn't a RESTRICTED language
  code/modules/mob/language/station.dm
Labels: Oversight

#8322 Cynosure ATC and Lobby Fluff
  code/modules/busy_space/air_traffic.dm
  code/modules/busy_space/organizations.dm
  code/modules/lore_codex/lore_data/important_locations.dm
  maps/cynosure/cynosure_defines.dm
Labels: Lore, Map: Cynosure

#8323 Mob throwing fix
  code/modules/mob/living/living.dm
Labels: Bugfix

#8316 Refactors reagent pump code
  code/game/machinery/reagents/pump.dm
  code/modules/reagents/machinery/pump.dm
  icons/obj/machines/reagent.dmi
  polaris.dme
Labels: Refactor, Optimization

#8325 Fixes temp sector initialization
  code/modules/overmap/spacetravel.dm
  maps/~map_system/maps.dm
Labels: Bugfix
