Repository PolarisSS13/Polaris, pull requests merged in 2021-02, with the labels that each got.

#7847 Event Managers can use TGUI interactions
  code/modules/tgui/states.dm
Labels: Bugfix

#7854 Fixes invisible clothes
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/obj/clothing/uniforms.dmi
  icons/obj/clothing/uniforms_1.dmi
Labels: Bugfix

#7855 Fossil replacements
  icons/obj/xenoarchaeology.dmi
Labels: Sprite Change

#7852 Fixes minor spelling issue
  maps/submaps/engine_submaps/engine.dm
Labels: Oversight

#7857 Makes slimes not reproduce in unlimited stacks
  code/modules/mob/living/simple_mob/subtypes/slime/xenobio/xenobio.dm
Labels: Bugfix, Priority: High

#7860 Planetside crew appears on manifest
  code/datums/datacore.dm
Labels: Bugfix

#7861 Ports World Server Hair & Gradients
  code/modules/mob/living/carbon/human/gradient.dm
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/hair_gradients.dmi
  icons/mob/human_face.dmi
  icons/mob/human_face_m.dmi
Labels: Sprite Change

#7862 Properly centers projectile/beam icons
  icons/obj/projectiles.dmi
  icons/obj/projectiles_impact.dmi
  icons/obj/projectiles_muzzle.dmi
  icons/obj/projectiles_tracer.dmi
Labels: Oversight, Sprite Change

#7867 Adds Decapod borg sprites
  code/modules/mob/living/silicon/robot/robot_modules/station.dm
  icons/mob/robots.dmi
Labels: Sprite Change

#7865 Allows custom-selection of posters
  code/datums/supplypacks/recreation.dm
  code/game/objects/effects/decals/contraband.dm
  code/game/objects/effects/decals/posters/bs12.dm
  code/game/objects/effects/decals/posters/polarisposters.dm
  code/game/objects/items/weapons/gift_wrappaper.dm
  code/game/objects/random/misc.dm
  code/game/objects/structures/loot_piles.dm
  icons/obj/contraband.dmi
Labels: Feature Tweak, Sprite Change

#7863 Makes event managers admins as far as TGUI is concerned
  code/modules/tgui/states/admin.dm
Labels: Bugfix, Staff Request

#7871 Medical Soft/Field Cap
  code/modules/client/preference_setup/loadout/loadout_head.dm
  code/modules/clothing/head/soft_caps.dm
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Sprite Change

#7869 Telecrystals are only stored on the mind
  code/datums/mind.dm
  code/datums/uplink/badassery.dm
  code/datums/uplink/telecrystals.dm
  code/datums/uplink/uplink_categories.dm
  code/datums/uplink/uplink_items.dm
  code/game/antagonist/antagonist_print.dm
  code/game/gamemodes/game_mode.dm
  code/game/objects/items/devices/uplink.dm
  code/game/objects/items/devices/uplink_random_lists.dm
  code/modules/pda/cart.dm
  code/modules/pda/messenger_plugins.dm
Labels: Bugfix, Priority: Medium, Refactor

#7844 Makes wrenches only anchor lockers if they're open
  code/game/objects/structures/crates_lockers/__closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
Labels: Feature Tweak

#7886 Fixes drinks having uncontrollable transfer amount
  code/modules/food/food/drinks.dm
Labels: Feature Tweak

#7874 Fixes Telecom Storage Access
  maps/southern_cross/southern_cross-1.dmm
Labels: Bugfix

#7894 Dance, Flip, Spin!
  code/modules/mob/living/carbon/human/emote.dm
  sound/voice/longwhistle.ogg
  sound/voice/longwhistle_robot.ogg
  sound/voice/shortwhistle.ogg
  sound/voice/shortwhistle_robot.ogg
  sound/voice/summon_whistle.ogg
  sound/voice/summon_whistle_robot.ogg
  sound/voice/wolfwhistle.ogg
  sound/voice/wolfwhistle_robot.ogg
Labels: Feature Tweak

#7898 Fixed 'Hardsuit Modules' tab verbs
  code/modules/clothing/spacesuits/rig/modules/modules.dm
Labels: Bugfix

#7853 QoL Door Closing
  code/game/turfs/turf.dm
Labels: Quality of Life

#7864 Diet/Allergy System Rework
  code/__defines/species_languages.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
Labels: Feature

#7887 Sinta'unathi language color change
  code/modules/vchat/css/ss13styles.css
  code/stylesheet.dm
Labels: Feature Tweak

#7897 Makes some juices not sugary
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
Labels: Feature Tweak

#7835 R-UST rises again.
  code/modules/power/fusion/core/_core.dm
  code/modules/power/fusion/core/core_control.dm
  code/modules/power/fusion/core/core_field.dm
  code/modules/power/fusion/fuel_assembly/fuel_assembly.dm
  code/modules/power/fusion/fuel_assembly/fuel_compressor.dm
  code/modules/power/fusion/fuel_assembly/fuel_control.dm
  code/modules/power/fusion/fuel_assembly/fuel_injector.dm
  code/modules/power/fusion/gyrotron/gyrotron.dm
  code/modules/power/fusion/gyrotron/gyrotron_control.dm
  code/modules/power/fusion/magpower.dm
  code/modules/tgui/modules/gyrotron_control.dm
  code/modules/tgui/modules/rustcore_monitor.dm
  code/modules/tgui/modules/rustfuel_control.dm
  code/modules/tgui/modules/shutoff_monitor.dm
  icons/obj/computer.dmi
  icons/obj/power.dmi
  polaris.dme
  tgui/packages/tgui/interfaces/GyrotronControl.js
  tgui/packages/tgui/interfaces/RustCoreMonitor.js
  tgui/packages/tgui/interfaces/RustFuelControl.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Bugfix, Experimental: Needs End Date, Feature Tweak, Project, Results To Be Reviewed

#7877 Fixes animal type simplemobs runtiming on deletion
  code/modules/mob/living/living.dm
Labels: Oversight

#7881 Adds area soundproofing.
  code/game/area/areas.dm
  code/game/sound.dm
Labels: Feature Tweak

#7884 Fixes decapitation runtime spam.
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Bugfix

#7889 Makes simplemob braingibs not create brainmobs
  code/modules/organs/internal/brain.dm
Labels: Bugfix

#7891 Porting Fixes
  code/game/objects/effects/effect_system.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/mining/ore.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/mecha/mecha.dm
Labels: Bugfix

#7896 PoI fix
  maps/submaps/surface_submaps/plains/VRDen.dmm
Labels: Oversight, Point of Interest

#7899 Couple of small fixes.
  code/modules/food/food/snacks.dm
  code/modules/hydroponics/seed.dm
Labels: Bugfix

#7900 Fixes VChat HTML export text colours.
  code/modules/vchat/css/ss13styles.css
Labels: Bugfix

#7902 Ports TGUI Security Stuff
  code/game/area/Space Station 13 areas.dm
  code/game/gamemodes/events.dm
  code/game/machinery/computer/prisoner.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/doors/brigdoors.dm
  code/modules/detectivework/microscope/dnascanner.dm
Labels: Feature

#7856 Lobby Improvements
  code/game/machinery/newscaster.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/client/client defines.dm
  code/modules/lore_codex/news_data/main.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/mob/new_player/news.dm
  code/modules/news/new_newspaper.dm
  code/modules/news/news_init.dm
  code/modules/news/newspaper.dm
  code/modules/news/newspaper_layout.dm
  maps/southern_cross/southern_cross_defines.dm
  maps/~map_system/maps.dm
  polaris.dme
Labels: Feature, Lore

#7903 Ports TGUI Inventory Screen
  code/modules/mob/living/carbon/alien/alien.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/inventory.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/mob.dm
Labels: Feature, Refactor

#7910 Fixes modular computer game sound volume
  code/modules/modular_computers/file_system/programs/generic/game.dm
Labels: Oversight

#7912 Fixes some medical access
  maps/southern_cross/southern_cross-1.dmm
Labels: Map Change / Issue, Oversight

#7923 Adds Respawn to allow ghosts to return to lobby so admins stop disabling respawn instead because SOMEONE, SOMEWHERE IS WRONG
  code/modules/mob/dead/observer/observer.dm
Labels: Bugfix, Priority: CRITICAL, Quality of Life, Staff Request

#7905 Added verbs/handling for removing and attaching your own robotic bodyparts.
  code/__defines/damage_organs.dm
  code/modules/mob/living/carbon/human/human_modular_limbs.dm
  code/modules/mob/living/carbon/human/human_powers.dm
  code/modules/mob/living/carbon/human/species/outsider/event.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/organs/organ_external.dm
  code/modules/organs/robolimbs.dm
  icons/mob/human_races/cyberlimbs/prosthesis/wooden.dmi
  polaris.dme
Labels: Feature

#7907 Fixes some fluff weirdness with Virgo-ported prosthetics
  code/modules/organs/robolimbs.dm
  code/modules/organs/robolimbs_custom.dm
Labels: Lore

#7915 Small TGUI fixes
  code/modules/tgui/modules/communications.dm
  tgui/packages/tgui/interfaces/AppearanceChanger.js
  tgui/packages/tgui/interfaces/CommunicationsConsole.js
  tgui/packages/tgui/public/tgui.bundle.js
  tgui/packages/tgui/public/tgui.html
Labels: Bugfix

#7916 Add mass edit functionality to ai_holder datums
  code/modules/ai/ai_holder.dm
Labels: Feature

#7917 Deletes the process scheduler.
  code/_helpers/time.dm
  code/controllers/ProcessScheduler/.gitignore
  code/controllers/ProcessScheduler/LICENSE-AGPL
  code/controllers/ProcessScheduler/LICENSE-CC-BY-NC
  code/controllers/ProcessScheduler/README.md
  code/controllers/ProcessScheduler/bower.json
  code/controllers/ProcessScheduler/core/process.dm
  code/controllers/ProcessScheduler/core/processScheduler.dm
  code/controllers/ProcessScheduler/package.json
  code/controllers/subsystems/ticker.dm
  code/game/world.dm
  code/modules/mob/mob.dm
  polaris.dme
Labels: Unwanted Feature Removal

#7920 Removes ping subsystem that was breaking chat
  code/__defines/subsystems.dm
  code/controllers/subsystems/ping.dm
  code/modules/client/client defines.dm
  code/modules/client/verbs/advanced_who.dm
  code/modules/client/verbs/ping.dm
  code/modules/client/verbs/who.dm
  code/modules/mob/mob.dm
  polaris.dme
Labels: Bugfix, Unwanted Feature Removal

#7919 Hybridizes Point Defense Turrets with Bay's System
  code/__defines/color.dm
  code/__defines/misc.dm
  code/_global_vars/lists/misc.dm
  code/datums/supplypacks/engineering.dm
  code/game/gamemodes/meteor/meteors.dm
  code/game/machinery/pointdefense.dm
  code/game/machinery/portable_turret.dm
  code/game/machinery/turret_control.dm
  code/game/objects/effects/temporary_visuals/projectiles/impact.dm
  code/game/objects/effects/temporary_visuals/projectiles/muzzle.dm
  code/game/objects/effects/temporary_visuals/projectiles/tracer.dm
  code/game/objects/items/weapons/circuitboards/machinery/ships.dm
  code/modules/client/preference_setup/preference_setup.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/research/designs/circuits/circuits.dm
  icons/obj/pointdefense.dmi
  icons/obj/projectiles_impact.dmi
  icons/obj/projectiles_muzzle.dmi
  icons/obj/projectiles_tracer.dmi
  nano/templates/pointdefense_control.tmpl
  polaris.dme
  sound/machines/apc_nopower.ogg
  sound/weapons/mandalorian.ogg
Labels: Feature Tweak, Optimization, Ported from Baycode, Unwanted Feature Removal

#7924 Adds some tacticooler undershirts
  code/datums/underwear/undershirts.dm
  icons/mob/human.dmi
Labels: Sprite Change

#7820 Adds the Restraining Bolt.
  code/_onclick/cyborg.dm
  code/datums/supplypacks/robotics.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/items/weapons/implants/implantcase.dm
  code/game/objects/items/weapons/implants/implanter.dm
  code/game/objects/items/weapons/implants/implantrestrainingbolt.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_movement.dm
  code/modules/organs/internal/augment.dm
  code/modules/organs/internal/augment/armmounted.dm
  polaris.dme
Labels: Feature

#7927 Removes transform from speech bubbles when speaker is scaled at less than 2x.
  code/game/atoms.dm
  code/modules/mob/living/carbon/brain/brain.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/voice/voice.dm
  code/modules/mob/typing_indicator.dm
  code/modules/multiz/zshadow.dm
Labels: Quality of Life

#7929 Snow no longer goes clang and shovels are more efficient
  code/game/turfs/simulated/outdoors/snow.dm
  code/modules/materials/material_sheets.dm
Labels: Feature Tweak, Sound Change
