Repository PolarisSS13/Polaris, pull requests merged in 2021-03, with the labels that each got.

#7931 Loot Trawler Update
  icons/obj/vending.dmi
Labels: Sprite Change

#7933 Fix parrot runtime
  code/modules/mob/living/simple_mob/subtypes/animal/pets/parrot.dm
Labels: Oversight

#7943 Stair tweaks
  code/game/atoms_movable.dm
  code/game/objects/buckling.dm
  code/modules/multiz/stairs.dm
  code/modules/multiz/turf.dm
  maps/example/example-2.dmm
  maps/southern_cross/southern_cross-1.dmm
Labels: Bugfix, Feature Tweak

#7928 Added a GPS compass.
  code/_helpers/unsorted.dm
  code/game/objects/items/devices/gps.dm
  code/modules/client/preference_setup/preference_setup.dm
  code/modules/compass/^compass.dm
  code/modules/compass/_compass.dm
  code/modules/compass/compass_holder.dm
  code/modules/compass/compass_waypoint.dm
  polaris.dme
Labels: Feature, Quality of Life

#7921 Adds a modular armour version of the explorer suit and adds sprites to specialist armour
  code/datums/supplypacks/security.dm
  code/game/objects/items/weapons/material/material_armor.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/accessories/armor.dm
  code/modules/materials/material_recipes.dm
  code/modules/materials/materials.dm
  icons/mob/modular_armor.dmi
  icons/obj/clothing/modular_armor.dmi
  maps/southern_cross/southern_cross-3.dmm
  maps/southern_cross/structures/closets/misc.dm
Labels: Feature

#7937 The Deep Scan Device
  code/modules/mining/drilling/scanner.dm
  icons/obj/device.dmi
Labels: Sprite Change

#7938 The Arcade Machine Update
  code/game/machinery/computer/arcade.dm
  icons/obj/computer.dmi
Labels: Sprite Change

#7941 Small cleanup from init PR.
  code/modules/nano/nanoui.dm
  code/modules/organs/internal/augment.dm
Labels: Oversight

#7940 Diet/Allergy Rework & Refactor Pt2
  code/__defines/species_languages.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
Labels: Feature Tweak

#7948 Fix stacking machine not stacking most materials
  code/modules/mining/machine_stacking.dm
Labels: Bugfix

#7953 Fixed/generalized loadout implants.
  code/_helpers/_global_objects.dm
  code/game/jobs/job_controller.dm
  code/game/objects/items/weapons/implants/implantdud.dm
  code/modules/client/preference_setup/loadout/gear_tweaks.dm
  code/modules/client/preference_setup/loadout/loadout_cyberware.dm
  code/modules/client/preference_setup/loadout/loadout_utility.dm
  polaris.dme
Labels: Bugfix, Refactor

#7849 Adds some new wheelchair types
  code/game/jobs/job_controller.dm
  code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
  code/game/objects/structures/stool_bed_chair_nest/wheelchair_item.dm
  code/modules/client/preference_setup/loadout/loadout_utility.dm
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
  icons/obj/furniture.dmi
  icons/obj/wheelchair.dmi
  polaris.dme
Labels: Sprite Change, Work In Progress

#7954 Chirp chirp
  code/modules/mob/living/carbon/human/emote.dm
Labels: Feature Tweak

#7936 Ports Tertiary Colors
  code/modules/client/preference_setup/general/03_body.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/new_player/sprite_accessories_ear.dm
  code/modules/mob/new_player/sprite_accessories_tail.dm
  code/modules/mob/new_player/sprite_accessories_wing.dm
Labels: Feature

#7949 E-cigarette improvements
  code/game/objects/items/weapons/ecigs.dm
Labels: Quality of Life

#7950 Allergens v2
  code/__defines/species_languages.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
Labels: Feature Tweak, Lore

#7951 Fix laptop vendors not selling tesla relays on tablets
  tgui/packages/tgui/interfaces/ComputerFabricator.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Bugfix

#7952 Allows removing omni filters/mixers at any pressure (same as non-omni)
  code/ATMOSPHERICS/components/omni_devices/omni_base.dm
Labels: Feature Tweak

#7955 Adds an advanced version of the mining drill scanner.
  code/game/objects/structures/loot_piles.dm
  code/modules/mining/drilling/scanner.dm
  code/modules/research/designs/mining_toys.dm
Labels: Feature

#7961 Re-adds flashing on heavy-duty cell chargers
  icons/obj/power.dmi
Labels: Oversight, Sprite Change

#7963 Tweaked implant loadout, refactored implant detection.
  code/game/machinery/adv_med.dm
  code/game/machinery/cloning.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/implants/implantlanguage.dm
  code/modules/client/preference_setup/loadout/gear_tweaks.dm
Labels: Feature Tweak

#7964 Taking cell out of a standing drill now attempts to put it in your hands.
  code/modules/mining/drilling/drill.dm
Labels: Feature Tweak

#7975 Don't even install gcc-multilib at all.
  .github/workflows/ci.yml
Labels: Bugfix, Priority: CRITICAL

#7935 Added think-tanks.
  code/__defines/mobs.dm
  code/datums/ai_law_sets.dm
  code/datums/datacore.dm
  code/game/atoms_movable.dm
  code/game/machinery/rechargestation.dm
  code/game/mecha/mech_bay.dm
  code/game/mecha/mecha.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/floor_painter.dm
  code/game/objects/items/weapons/id cards/station_ids.dm
  code/game/objects/objs.dm
  code/game/world.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/robot/component.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules/event.dm
  code/modules/mob/living/silicon/robot/robot_modules/station.dm
  code/modules/mob/living/silicon/robot/robot_modules/syndicate.dm
  code/modules/mob/living/silicon/robot/subtypes/thinktank/_thinktank.dm
  code/modules/mob/living/silicon/robot/subtypes/thinktank/thinktank_icon.dm
  code/modules/mob/living/silicon/robot/subtypes/thinktank/thinktank_interactions.dm
  code/modules/mob/living/silicon/robot/subtypes/thinktank/thinktank_module.dm
  code/modules/mob/living/silicon/robot/subtypes/thinktank/thinktank_storage.dm
  code/modules/mob/living/silicon/robot/subtypes/thinktank/thinktank_subtypes.dm
  code/modules/paperwork/handlabeler.dm
  code/modules/power/cells/power_cells.dm
  code/modules/projectiles/guns/energy/phase.dm
  code/modules/research/prosfab_designs.dm
  icons/effects/thinktank_labels.dmi
  icons/mob/robots_thinktank.dmi
  icons/mob/screen1_robot.dmi
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-3.dmm
  maps/southern_cross/southern_cross.dm
  maps/southern_cross/southern_cross_overrides.dm
  polaris.dme
Labels: Feature

#7956 Ported Poppy the possum.
  code/modules/mob/holder.dm
  code/modules/mob/living/simple_mob/subtypes/animal/passive/possum.dm
  code/modules/mob/living/simple_mob/subtypes/animal/pets/cat.dm
  icons/mob/animal.dmi
  icons/mob/head.dmi
  icons/mob/items/lefthand_holder.dmi
  icons/mob/items/righthand_holder.dmi
  maps/southern_cross/southern_cross-1.dmm
  polaris.dme
Labels: Feature

#7967 Makes drag-drop bodyjacking not break aghost bonds
  code/modules/admin/admin.dm
Labels: Quality of Life

#7968 Clicking on turfs while dragging something no longer closes the door
  code/game/turfs/turf.dm
Labels: Bugfix

#7971 Syncs icon/obj with Virgo
  icons/obj/device.dmi
  icons/obj/pointdefense.dmi
  icons/obj/reagentfillings.dmi
  icons/obj/surgery.dmi
  icons/obj/turbolift.dmi
  icons/obj/vending.dmi
Labels: Sprite Change

#7974 Added Doctress' Jager drink.
  code/datums/supplypacks/hospitality.dm
  code/game/machinery/vending_machines.dm
  code/game/objects/random/misc.dm
  code/modules/economy/price_list.dm
  code/modules/food/food/drinks/bottle.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  icons/obj/drinks.dmi
Labels: Feature

#7976 Fixes Global and Fixes Eyes
  code/__defines/sound.dm
  code/_helpers/global_lists.dm
  code/game/jobs/job_controller.dm
  code/game/objects/structures/crates_lockers/__closets.dm
  code/modules/organs/organ_icon.dm
  code/modules/organs/subtypes/standard.dm
Labels: Bugfix

#7978 Technomancer log adjustments
  code/game/gamemodes/technomancer/spells/apportation.dm
  code/game/gamemodes/technomancer/spells/blink.dm
  code/game/gamemodes/technomancer/spells/condensation.dm
  code/game/gamemodes/technomancer/spells/control.dm
  code/game/gamemodes/technomancer/spells/energy_siphon.dm
  code/game/gamemodes/technomancer/spells/flame_tongue.dm
  code/game/gamemodes/technomancer/spells/insert/insert.dm
  code/game/gamemodes/technomancer/spells/projectile/projectile.dm
  code/game/gamemodes/technomancer/spells/reflect.dm
  code/game/gamemodes/technomancer/spells/warp_strike.dm
Labels: Feature Tweak, Quality of Life

#7979 Ghosts now use their body appearance initially.
  code/modules/mob/dead/observer/observer.dm
Labels: Bugfix

#7981 Minor cleanup.
  code/__defines/mobs.dm
  code/modules/food/food/snacks.dm
  code/modules/mob/living/simple_mob/subtypes/animal/passive/mouse.dm
  code/modules/tgui/states/default.dm
Labels: Refactor

#7983 Fixes pilots not getting a harness if they use a loadout uniform
  code/datums/outfits/outfit.dm
  maps/southern_cross/items/clothing/sc_under.dm
  maps/southern_cross/job/outfits.dm
Labels: Bugfix

#7985 adds ticket redemption
  code/game/machinery/computer/arcade.dm
Labels: Feature Tweak

#7959 Examining dark click catcher doesn't show turfs
  code/_onclick/click.dm
Labels: Bugfix

#7977 Updates some ancient comments
  code/modules/mob/inventory.dm
Labels: Oversight

#7980 GPS presentation/update tweaks/fixes.
  code/game/objects/items.dm
  code/game/objects/items/devices/gps.dm
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Feature Tweak

#7925 Makes custom cigarettes even more custom-ier
  code/game/machinery/vending_machines.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/storage/fancy.dm
  icons/obj/cigarettes.dmi
Labels: Feature

#7988 Tachikoma tweaks.
  code/game/objects/items/weapons/material/knives.dm
  code/modules/mob/living/silicon/robot/component.dm
  code/modules/mob/living/silicon/robot/subtypes/thinktank/_thinktank.dm
  code/modules/mob/living/silicon/robot/subtypes/thinktank/thinktank_interactions.dm
  code/modules/mob/living/silicon/robot/subtypes/thinktank/thinktank_module.dm
  code/modules/mob/living/silicon/robot/subtypes/thinktank/thinktank_storage.dm
Labels: Feature Tweak

#7973 News Update + Communicator Lag Fix
  code/game/objects/items/devices/communicator/helper.dm
  code/modules/lore_codex/news_data/main.dm
Labels: Bugfix, Lore

#7815 New ID Card Design
  code/datums/outfits/jobs/cargo.dm
  code/datums/outfits/jobs/civilian.dm
  code/datums/outfits/jobs/engineering.dm
  code/datums/outfits/jobs/medical.dm
  code/datums/outfits/jobs/security.dm
  code/game/jobs/job/civilian.dm
  code/game/machinery/computer/guestpass.dm
  code/game/objects/items/weapons/id cards/cards.dm
  code/game/objects/items/weapons/id cards/id_stacks.dm
  code/game/objects/items/weapons/id cards/id_stacks_cit.dm
  code/game/objects/items/weapons/id cards/id_stacks_deptname.dm
  code/game/objects/items/weapons/id cards/station_ids.dm
  code/game/objects/items/weapons/id cards/syndicate_ids.dm
  code/modules/clothing/under/accessories/permits.dm
  icons/obj/card_cit.dmi
  icons/obj/card_new.dmi
  maps/southern_cross/job/outfits.dm
  polaris.dme
Labels: Sprite Change

#7990 Allows Teshari to glide in some multiz fall conditions.
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/seromi.dm
  code/modules/mob/living/living.dm
  code/modules/multiz/movement.dm
Labels: Feature

#7992 Fixes despawn cryopods gib-killing the occupant
  code/game/machinery/cryopod.dm
Labels: Oversight

#7993 Removed inactive platforms from the end of round laws output, gives them pilot access.
  code/controllers/subsystems/ticker.dm
  code/modules/mob/living/silicon/robot/subtypes/thinktank/_thinktank.dm
  maps/southern_cross/southern_cross_overrides.dm
Labels: Feature Tweak

#7998 Deletes unused var.
  code/modules/organs/subtypes/standard.dm
Labels: Oversight, Priority: High, Quality of Life

#7982 Adds random wilderness encounter event.
  maps/southern_cross/events/wildlife_encounter.dm
  maps/southern_cross/southern_cross.dm
Labels: Feature

#8008 Patches new ID card code
  code/game/objects/items/weapons/id cards/cards.dm
  code/game/objects/items/weapons/id cards/id_stacks.dm
  code/game/objects/items/weapons/id cards/id_stacks_cit.dm
  code/game/objects/items/weapons/id cards/id_stacks_deptname.dm
Labels: Oversight, Priority: CRITICAL

#7960 Fixes replica syndi suit worn sprite
  code/modules/clothing/suits/miscellaneous.dm
Labels: Bugfix

#7989 Fixes roofing tiles not working in multiz areas
  code/modules/multiz/turf.dm
Labels: Bugfix

#8007 Fixes mapped R-UST connections, removes debug logs
  code/modules/power/fusion/core/core_control.dm
  code/modules/power/fusion/fuel_assembly/fuel_control.dm
  code/modules/power/fusion/gyrotron/gyrotron.dm
  code/modules/power/fusion/gyrotron/gyrotron_control.dm
  code/modules/tgui/modules/gyrotron_control.dm
  code/modules/tgui/modules/rustcore_monitor.dm
  code/modules/tgui/modules/rustfuel_control.dm
Labels: Bugfix, Oversight, Priority: High

#8011 Ported updated decls repository from Neb.
  code/__defines/misc.dm
  code/controllers/subsystems/atoms.dm
  code/datums/repositories/decls.dm
  code/game/world.dm
  code/modules/hydroponics/grown_inedible.dm
  code/modules/hydroponics/seed_controller.dm
  code/unit_tests/integrated_circuits/prefabs.dm
Labels: Refactor

#7994 Fixes manifest datacore failing to find job datums for alt titles
  code/datums/datacore.dm
Labels: Bugfix

#7997 Fixes naked ghosts
  code/modules/mob/dead/observer/observer.dm
Labels: Oversight

#8004 Technomancer Bugfixes
  code/game/gamemodes/technomancer/instability.dm
  code/game/gamemodes/technomancer/spells/illusion.dm
  code/modules/mob/living/simple_mob/subtypes/illusion/illusion.dm
Labels: Bugfix

#7965 Tanning Tweaks
  code/game/machinery/washing_machine.dm
  code/game/objects/items/stacks/sheets/leather.dm
  code/modules/food/kitchen/smartfridge.dm
  code/modules/materials/material_recipes.dm
  code/modules/reagents/Chemistry-Holder.dm
  icons/obj/kitchen.dmi
Labels: Bugfix, Feature, Feature Tweak, Quality of Life, Sprite Change

#8000 Fixes runtime in chunk.dm: line 91, I think?
  code/modules/mob/freelook/chunk.dm
Labels: Bugfix, Higgs Bugson

#8001 Fixes runtime in prison_break.dm, line 214
  code/modules/gamemaster/event2/events/security/prison_break.dm
Labels: Oversight

#8003 Tesla engine waste handling has atmos vent/scrubber
  maps/submaps/engine_submaps/southern_cross/engine_tesla.dmm
Labels: Bugfix, Map Change / Issue

#8012 Tesh gliding tweaks.
  code/game/objects/structures/cliff.dm
  code/modules/mob/living/carbon/human/species/station/teshari.dm
Labels: Bugfix, Feature Tweak

#8014 rutile is an alloying material
  code/modules/mining/ore_datum.dm
Labels: Oversight

#8016 Minor ID sprite tweaks
  html/changelogs/woodrat - idtweaks.yml
  icons/obj/card_new.dmi
Labels: Sprite Change

#8017 Updates respawn_character some more
  code/modules/admin/verbs/randomverbs.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/update_icons.dm
Labels: Bugfix

#8021 Partially reverts https://github.com/PolarisSS13/Polaris/pull/7713
  code/modules/overmap/spacetravel.dm
Labels: Bugfix, Optimization
