Repository PolarisSS13/Polaris, pull requests merged in 2021-11, with the labels that each got.

#8341 ChangeTurf improvements.
  code/game/gamemodes/endgame/supermatter_cascade/blob.dm
  code/game/turfs/simulated/floor_types.dm
  code/game/turfs/simulated/walls.dm
  code/game/turfs/turf.dm
  code/game/turfs/turf_changing.dm
  code/game/turfs/unsimulated/planetary.dm
  code/modules/admin/view_variables/admin_delete.dm
  code/modules/artifice/deadringer.dm
  code/modules/mob/freelook/update_triggers.dm
  code/modules/turbolift/turbolift.dm
  code/modules/xenobio2/mob/xeno.dm
  code/modules/xenobio2/mob/xeno_product.dm
Labels: Bugfix

#8338 Fixes emote targetting.
  code/modules/emotes/emote_define.dm
Labels: Bugfix

#8218 Adds random map generation to Sif. [IDB IGNORE] [MDB IGNORE]
  code/controllers/subsystems/mapping.dm
  code/game/turfs/simulated/outdoors/grass.dm
  code/game/turfs/simulated/outdoors/grass_random.dm
  maps/southern_cross/datums/random_map.dm
  maps/southern_cross/southern_cross-3.dmm
  maps/southern_cross/southern_cross-8.dmm
  maps/southern_cross/southern_cross.dm
  maps/southern_cross/southern_cross_defines.dm
  maps/submaps/surface_submaps/mountains/CrashedMedShuttle1.dmm
  polaris.dme
Labels: Map Change / Issue, Map: Southern Cross, Test Merge: Short-term

#8345 Fixes simplemobs with 0 init nutrition runtiming
  code/modules/mob/living/simple_mob/life.dm
Labels: Bugfix

#8344 Fixes rocket launcher
  code/modules/projectiles/projectile/explosive.dm
Labels: Bugfix

#8343 Fixes runtime with ducks and turrets
  code/modules/mob/living/simple_mob/subtypes/animal/sif/duck.dm
Labels: Bugfix

#8340 Various tweaks on and around exploration.
  code/game/objects/items/weapons/melee/misc.dm
  code/game/objects/structures/flora/flora.dm
  code/game/turfs/simulated/outdoors/outdoors.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/masks/hailer.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/accessories/holster.dm
  code/modules/hydroponics/grown_sif.dm
  code/modules/hydroponics/seedtypes/flowers.dm
  code/modules/hydroponics/seedtypes/grapes.dm
  code/modules/hydroponics/trays/tray_soil.dm
  code/modules/planet/sif.dm
Labels: Bugfix

#8354 Initialize engine_loader landmark immediately
  code/modules/shieldgen/directional_shield.dm
  maps/submaps/engine_submaps/engine.dm
Labels: Priority: CRITICAL, Bugfix

#8355 Fixes overflow bug that can delete sheets from smartfridge
  code/datums/vending/stored_item.dm
  code/modules/food/kitchen/smartfridge/engineering.dm
Labels: Bugfix
