Repository PolarisSS13/Polaris, pull requests merged in 2021-09, with the labels that each got.

#8230 Separates Swimsuit and Athletic Lockers, Adds Wetsuits
  code/game/objects/structures/crates_lockers/closets/fitness.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprite Change, Requires Author Response

#8245 New dirt and paved sidewalk sprites
  code/game/turfs/simulated/outdoors/dirt.dm
  code/game/turfs/simulated/outdoors/sidewalk.dm
  icons/turf/outdoors.dmi
  icons/turf/outdoors_edge.dmi
  polaris.dme
Labels: Sprite Change, Requires Author Response

#8267 Removes an empty file. No clue what's the deal with this.
  code/game/objects/items/weapons/power_cells.dm
Labels: Oversight

#8184 Refactors crafting to support requirement alternatives
  code/datums/components/crafting/crafting.dm
  code/datums/components/crafting/crafting_external.dm
  code/datums/components/crafting/recipes.dm
Labels: Refactor, Bugfix

#8274 Gives the baristas sugar in their dispenser
  code/modules/reagents/machinery/dispenser/dispenser_presets.dm
Labels: Feature

#8271 Give all coins a material amount, so you can recycle them
  code/modules/economy/coins.dm
Labels: Feature Tweak

#8247 Throw Mode QoL Tweaks
  code/_onclick/click.dm
  code/modules/mob/living/carbon/give.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
Labels: Refactor, Quality of Life

#8264 Sec Helmet sprite patch
  icons/mob/species/vox/head.dmi
Labels: Sprite Change

#8266 Converts pretty much all of the mech fab and pros_fab designs to mat defines instead of the other...String thing?
  code/modules/research/mechfab_designs.dm
  code/modules/research/prosfab_designs.dm
Labels: Refactor

#8263 Adds new borg sprites
  code/modules/mob/living/silicon/robot/robot_modules/station.dm
  icons/mob/robots.dmi
Labels: Sprite Change

#8273 Adjusts vatborn ages
  code/modules/mob/living/carbon/human/species/station/human_subspecies.dm
Labels: Lore

#8272 Expands the ring selection
  code/__defines/materials.dm
  code/modules/client/preference_setup/loadout/loadout_gloves.dm
  code/modules/clothing/rings/material.dm
Labels: Feature

#8281 Misc runtime fixes
  code/game/objects/random/guns_and_ammo.dm
  code/modules/food/food/snacks.dm
  code/modules/mob/living/living.dm
  code/modules/xenoarcheaology/effects/vampire.dm
  maps/submaps/surface_submaps/wilderness/borglab.dmm
Labels: Bugfix

#8287 Fixes Colony Director's Armour
  code/modules/clothing/spacesuits/miscellaneous.dm
Labels: Bugfix

#8289 :siffet:
  code/modules/clothing/head/hood.dm
  code/modules/clothing/suits/hooded.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprite Change

#8286 Map test 6 fixes
  maps/cynosure/cynosure-1.dmm
  maps/cynosure/cynosure-2.dmm
  maps/cynosure/cynosure-3.dmm
  maps/cynosure/cynosure-4.dmm
  maps/cynosure/cynosure-6.dmm
  maps/cynosure/cynosure-7.dmm
  maps/cynosure/cynosure.dm
  maps/cynosure/cynosure_shuttles.dm
  maps/cynosure/shuttles/ert.dm
  maps/cynosure/shuttles/heist.dm
  maps/cynosure/shuttles/merc.dm
  maps/cynosure/shuttles/ninja.dm
  maps/cynosure/submaps/9x8/HotTub.dmm
Labels: Map Change / Issue, Project, Map: Cynosure

#8229 Disables the gateway as a departure point, adds a checkpoint and departure gate to the plains.
  code/game/machinery/cryopod.dm
  code/game/objects/effects/landmarks.dm
  code/global.dm
  code/modules/awaymissions/gateway.dm
  code/modules/client/preferences_spawnpoints.dm
  maps/southern_cross/southern_cross-3.dmm
  maps/southern_cross/southern_cross_areas.dm
  maps/southern_cross/southern_cross_defines.dm
Labels: Feature, Map Change / Issue, Lore

#8293 Adds multitools to roboticist/engi toolbelts
  code/datums/outfits/jobs/engineering.dm
  code/datums/outfits/jobs/science.dm
  code/game/objects/items/weapons/storage/belt.dm
Labels: Feature Tweak

#8292 Fixes stray bugs
  code/game/objects/items/weapons/id cards/station_ids.dm
  code/modules/food/kitchen/cooking_machines/container.dm
  code/modules/mining/machinery/machine_processing.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/mob.dm
Labels: Bugfix

#8291 Fixes changeling transform bug
  code/game/gamemodes/changeling/changeling_powers.dm
  code/game/gamemodes/changeling/powers/extract_dna_sting.dm
Labels: Bugfix

#8296 fixes crafting reqs not storing parts in the result
  code/datums/components/crafting/crafting.dm
Labels: Oversight, Bugfix

#8269 Mecha Bugfixes
  code/game/mecha/mecha.dm
Labels: Bugfix

#8300 Fixes VChat Export
  code/modules/mob/hear_say.dm
Labels: Bugfix

#8253 By-species age restrictions
  code/game/jobs/job/captain.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/jobs/job_controller.dm
  code/modules/client/preference_setup/occupation/occupation.dm
  code/modules/mob/living/carbon/human/species/station/prometheans.dm
  code/modules/mob/new_player/new_player.dm
  maps/southern_cross/southern_cross_jobs.dm
Labels: Feature, Lore

#8297 Adds sanity check to overmap temp Z level can_die()
  code/modules/overmap/spacetravel.dm
Labels: Oversight, Bugfix, Higgs Bugson

#8304 Removes suicide verb function
  code/game/verbs/suicide.dm
Labels: Staff Request

#7914 Universal Anomalies
  code/__defines/dcs/signals.dm
  code/_onclick/item_attack.dm
  code/_onclick/other_mobs.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/modules/reagents/reagents/_reagents.dm
  code/modules/reagents/reagents/core.dm
  code/modules/reagents/reagents/dispenser.dm
  code/modules/reagents/reagents/food_drinks.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/reagents/modifiers.dm
  code/modules/reagents/reagents/other.dm
  code/modules/reagents/reagents/toxins.dm
  code/modules/xenoarcheaology/anomaly_container.dm
  code/modules/xenoarcheaology/artifacts/artifact.dm
  code/modules/xenoarcheaology/artifacts/predefined/_predefined.dm
  code/modules/xenoarcheaology/artifacts/predefined/hungry_statue.dm
  code/modules/xenoarcheaology/boulder.dm
  code/modules/xenoarcheaology/effect.dm
  code/modules/xenoarcheaology/effect_master.dm
  code/modules/xenoarcheaology/effects/animate_anomaly.dm
  code/modules/xenoarcheaology/effects/badfeeling.dm
  code/modules/xenoarcheaology/effects/berserk.dm
  code/modules/xenoarcheaology/effects/cannibal.dm
  code/modules/xenoarcheaology/effects/cellcharge.dm
  code/modules/xenoarcheaology/effects/celldrain.dm
  code/modules/xenoarcheaology/effects/cold.dm
  code/modules/xenoarcheaology/effects/dnaswitch.dm
  code/modules/xenoarcheaology/effects/electric_field.dm
  code/modules/xenoarcheaology/effects/emp.dm
  code/modules/xenoarcheaology/effects/feysight.dm
  code/modules/xenoarcheaology/effects/forcefield.dm
  code/modules/xenoarcheaology/effects/gaia.dm
  code/modules/xenoarcheaology/effects/gasco2.dm
  code/modules/xenoarcheaology/effects/gasnitro.dm
  code/modules/xenoarcheaology/effects/gasoxy.dm
  code/modules/xenoarcheaology/effects/gasphoron.dm
  code/modules/xenoarcheaology/effects/gassleeping.dm
  code/modules/xenoarcheaology/effects/goodfeeling.dm
  code/modules/xenoarcheaology/effects/gravitational_waves.dm
  code/modules/xenoarcheaology/effects/heal.dm
  code/modules/xenoarcheaology/effects/heat.dm
  code/modules/xenoarcheaology/effects/hurt.dm
  code/modules/xenoarcheaology/effects/poltergeist.dm
  code/modules/xenoarcheaology/effects/radiate.dm
  code/modules/xenoarcheaology/effects/resurrect.dm
  code/modules/xenoarcheaology/effects/roboheal.dm
  code/modules/xenoarcheaology/effects/robohurt.dm
  code/modules/xenoarcheaology/effects/sleepy.dm
  code/modules/xenoarcheaology/effects/stun.dm
  code/modules/xenoarcheaology/effects/teleport.dm
  code/modules/xenoarcheaology/effects/vampire.dm
  code/modules/xenoarcheaology/finds/find_spawning.dm
  code/modules/xenoarcheaology/tools/artifact_analyser.dm
  code/modules/xenoarcheaology/tools/artifact_harvester.dm
  icons/effects/effects.dmi
  polaris.dme
Labels: Refactor, Staff Request, Prepare to Die

#8299 Backports Bay/Neb random map optimizations.
  code/modules/random_map/_random_map_setup.dm
  code/modules/random_map/automata/automata.dm
  code/modules/random_map/automata/caves.dm
  code/modules/random_map/noise/noise.dm
Labels: Refactor, Optimization, Ported from Nebula

#8308 Fixes runtime in mech equipment deletion
  code/game/mecha/equipment/mecha_equipment.dm
Labels: Bugfix
