Repository PolarisSS13/Polaris, pull requests merged in 2021-06, with the labels that each got.

#8080 Adds admin verb to hopefully fix database connection failures
  code/modules/admin/admin_verb_lists.dm
  code/modules/admin/verbs/dbcon_fix.dm
  polaris.dme
Labels: Bugfix, Higgs Bugson, Test Merge: Long-term

#8086 Adds more winter coats + moves existing winter coats to the same file
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/clothing/head/hood.dm
  code/modules/clothing/suits/hooded.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  maps/southern_cross/icons/mob/sc_suit.dmi
  maps/southern_cross/icons/obj/sc_suit.dmi
  maps/southern_cross/items/clothing/sc_suit.dm
Labels: Feature

#8099 Tweaks to emote system to avoid memory overhead and make runtime validation easier.
  code/modules/client/preference_setup/general/03_body.dm
  code/modules/emotes/definitions/_mob.dm
  code/modules/emotes/definitions/_species.dm
  code/modules/emotes/definitions/exertion.dm
  code/modules/emotes/definitions/human.dm
  code/modules/emotes/definitions/slimes.dm
  code/modules/emotes/definitions/synthetics.dm
  code/modules/emotes/definitions/visible.dm
  code/modules/emotes/definitions/visible_animated.dm
  code/modules/emotes/emote_define.dm
  code/modules/emotes/emote_mob.dm
  code/modules/mob/living/carbon/alien/diona/diona.dm
  code/modules/mob/living/carbon/alien/emote.dm
  code/modules/mob/living/carbon/brain/emote.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/silicon/emote.dm
  code/modules/mob/living/silicon/robot/emote.dm
  code/modules/mob/living/simple_mob/subtypes/animal/pets/cat.dm
  code/modules/mob/living/simple_mob/subtypes/slime/slime.dm
  code/modules/mob/mob.dm
  code/modules/organs/subtypes/standard.dm
Labels: Refactor

#8104 Adds new rocks + resprites mining outcrops
  code/game/objects/structures/props/rocks.dm
  icons/obj/flora/rocks.dmi
  icons/obj/outcrop.dmi
  polaris.dme
Labels: Feature Tweak, Sprite Change

#8111 Add Secret ZLevels
  code/game/objects/effects/landmarks.dm
  code/modules/mob/dead/observer/observer.dm
  maps/~map_system/maps.dm
Labels: Feature

#8115 Random mob spawners can accept faction input now
  code/game/objects/random/mob.dm
Labels: Feature Tweak

#8117 Adds new UI for secure stuff
  code/game/objects/items/weapons/storage/secure.dm
  tgui/packages/tgui/interfaces/SecureSafe.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Feature

#8118 Fixes infinite loop following cooking error
  code/modules/food/recipe.dm
Labels: Oversight

#8119 Adds unit test for invalid recipes
  code/unit_tests/recipe_tests.dm
  polaris.dme
Labels: Refactor

#8120 Add CI annotations to compile errors/warnings.
  tools/ci/compile_and_run.sh
Labels: CI Issue, Refactor

#8097 Portable mapping devices
  code/__defines/_planes+layers.dm
  code/__defines/holomap.dm
  code/__defines/map.dm
  code/_helpers/global_lists.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/minihud.dm
  code/_onclick/hud/minihud_mapper.dm
  code/_onclick/hud/minihud_rigmech.dm
  code/_onclick/hud/screen_objects.dm
  code/modules/holomap/generate_holomap.dm
  code/modules/holomap/mapper.dm
  code/modules/holomap/station_holomap.dm
  icons/effects/64x64.dmi
  icons/effects/effects.dmi
  icons/effects/gpshud.dmi
  icons/holomap_markers.dmi
  icons/obj/device.dmi
  maps/~map_system/maps.dm
  polaris.dme
Labels: Feature

#8116 Fixes some unseen combat ai jank
  code/modules/ai/ai_holder_combat_unseen.dm
Labels: Mob AI Issue, Oversight

#8121 Runechat
  code/__defines/_planes+layers.dm
  code/_helpers/time.dm
  code/datums/chat_message.dm
  code/datums/components/_component.dm
  code/game/atoms.dm
  code/game/machinery/air_alarm.dm
  code/game/machinery/cloning.dm
  code/game/machinery/computer/arcade.dm
  code/game/objects/effects/map_effects/portal.dm
  code/game/objects/items/devices/communicator/phone.dm
  code/game/objects/items/devices/defib.dm
  code/game/objects/items/devices/megaphone.dm
  code/game/objects/items/devices/taperecorder.dm
  code/game/objects/items/devices/text_to_speech.dm
  code/game/objects/items/devices/whistle.dm
  code/game/objects/items/uav.dm
  code/game/world.dm
  code/modules/admin/admin_verbs.dm
  code/modules/client/client defines.dm
  code/modules/client/preference_setup/global/setting_datums.dm
  code/modules/emotes/emote_define.dm
  code/modules/emotes/emote_mob.dm
  code/modules/integrated_electronics/subtypes/output.dm
  code/modules/mob/hear_say.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/say.dm
  code/modules/mob/mob.dm
  code/modules/multiz/ladders.dm
  code/modules/multiz/movement.dm
  code/modules/overmap/ships/engines/gas_thruster.dm
  code/modules/paperwork/photocopier.dm
  code/modules/projectiles/guns/magnetic/bore.dm
  code/modules/projectiles/guns/magnetic/magnetic.dm
  code/modules/research/message_server.dm
  code/modules/shuttles/shuttles_web.dm
  code/modules/turbolift/turbolift.dm
  code/modules/turbolift/turbolift_door.dm
  code/modules/ventcrawl/ventcrawl_atmospherics.dm
  interface/skin.dmf
  polaris.dme
Labels: Feature

#8122 Make req_[one_]access lazy
  code/__defines/_lists.dm
  code/controllers/subsystems/supply.dm
  code/game/gamemodes/sandbox/h_sandbox.dm
  code/game/jobs/access.dm
  code/game/machinery/deployable.dm
  code/game/machinery/door_control.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/windowdoor.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/spacesuits/rig/rig_attackby.dm
  code/modules/customitems/item_spawning.dm
  code/modules/hydroponics/seed_storage.dm
Labels: Optimization, Refactor

#8124 Adds a graffiti spawner for PoI and general map-making.
  code/game/objects/effects/spawners/graffiti.dm
  icons/effects/map_effects.dmi
  polaris.dme
Labels: Quality of Life

#8125 ripleys autoscoop ore in an aoe
  code/game/mecha/working/ripley.dm
Labels: Quality of Life

#8126 Added unit test to ensure emote key uniqueness.
  code/modules/emotes/definitions/audible.dm
  code/modules/emotes/definitions/slimes.dm
  code/modules/emotes/definitions/visible.dm
  code/modules/emotes/emote_mob.dm
  code/unit_tests/decl_tests.dm
  polaris.dme
Labels: Refactor

#8129 leg holsters in cargo crate
  code/datums/supplypacks/security.dm
Labels: Oversight

#8131 Ports Paradise pod doors
  code/game/machinery/doors/blast_door.dm
  icons/obj/doors/1x2blast_hor.dmi
  icons/obj/doors/1x2blast_vert.dmi
  icons/obj/doors/1x3blast_hor.dmi
  icons/obj/doors/1x3blast_vert.dmi
  icons/obj/doors/1x4blast_hor.dmi
  icons/obj/doors/1x4blast_vert.dmi
Labels: Sprite Change

#8132 Fix random holoplant bug
  code/game/objects/structures/holoplant.dm
Labels: Bugfix

#8133 clamps decon_mod between 0 and 1
  code/modules/research/destructive_analyzer.dm
Labels: Oversight

#8135 Makes the chaos cake cheaper.
  code/modules/food/food/thecake.dm
  icons/obj/food.dmi
Labels: Feature Tweak

#8136 Improve subsystem robustness
  code/controllers/failsafe.dm
  code/controllers/master.dm
  code/controllers/subsystems/air.dm
  code/controllers/subsystems/lighting.dm
Labels: Feature Tweak, Refactor

#8143 Code fixes + refactors who/staffwho
  code/game/jobs/job_controller.dm
  code/game/machinery/adv_med.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/weapons/chewables.dm
  code/modules/client/ui_style.dm
  code/modules/client/verbs/who.dm
Labels: Refactor

#8146 Removes Global Iterators
  code/datums/helper_datums/global_iterator.dm
  code/game/mecha/combat/gorilla.dm
  code/game/mecha/combat/gygax.dm
  code/game/mecha/combat/marauder.dm
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/mecha/equipment/tools/armor_melee.dm
  code/game/mecha/equipment/tools/armor_ranged.dm
  code/game/mecha/equipment/tools/cable_layer.dm
  code/game/mecha/equipment/tools/catapult.dm
  code/game/mecha/equipment/tools/clamp.dm
  code/game/mecha/equipment/tools/cloak.dm
  code/game/mecha/equipment/tools/drill.dm
  code/game/mecha/equipment/tools/energy_relay.dm
  code/game/mecha/equipment/tools/extinguisher.dm
  code/game/mecha/equipment/tools/generator.dm
  code/game/mecha/equipment/tools/hardpoint_actuator.dm
  code/game/mecha/equipment/tools/inflatables.dm
  code/game/mecha/equipment/tools/jetpack.dm
  code/game/mecha/equipment/tools/repair_droid.dm
  code/game/mecha/equipment/tools/shield.dm
  code/game/mecha/equipment/tools/shield_omni.dm
  code/game/mecha/equipment/tools/sleeper.dm
  code/game/mecha/equipment/tools/syringe_gun.dm
  code/game/mecha/equipment/tools/teleporter.dm
  code/game/mecha/equipment/tools/wormhole.dm
  code/game/mecha/equipment/weapons/weapons.dm
  code/game/mecha/mecha.dm
  code/game/vehicles/vehicle.dm
  code/modules/shieldgen/directional_shield.dm
  polaris.dme
Labels: Optimization, Refactor

#8137 Adds blank icon state to lefthand_holder.dmi
  icons/mob/items/lefthand_holder.dmi
Labels: Oversight, Sprite Change

#8138 fixes coughs screaming in the chat
  code/modules/emotes/definitions/audible_scream.dm
Labels: Oversight

#8140 Refactors utensils to use weakrefs
  code/game/objects/items/weapons/material/kitchen.dm
  code/modules/food/food/snacks.dm
  html/changelogs/MDP-utensilsrefactor.yml
Labels: Bugfix

#8141 Improves select_recipe.
  code/_helpers/sorts/comparators.dm
  code/modules/food/recipe.dm
  html/changelogs/MDP-recipecleanup.yml
Labels: Optimization, Refactor

#8149 Fixes unlocked air alarm uis
  code/game/machinery/air_alarm.dm
Labels: Bugfix, Priority: Medium

#8128 Refactors posters to use decls
  code/_helpers/global_lists.dm
  code/datums/repositories/decls.dm
  code/datums/supplypacks/recreation.dm
  code/datums/supplypacks/security.dm
  code/game/objects/effects/decals/contraband.dm
  code/game/objects/effects/decals/posters/bs12.dm
  code/game/objects/effects/decals/posters/polarisposters.dm
  code/game/objects/effects/decals/posters/posters.dm
  code/game/objects/effects/decals/posters/tgposters.dm
  code/game/objects/items/weapons/gift_wrappaper.dm
  code/game/objects/random/misc.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/loot_piles.dm
  code/global_init.dm
  maps/northern_star/polaris-2.dmm
  maps/southern_cross/southern_cross-6.dmm
  maps/submaps/surface_submaps/mountains/quarantineshuttle.dmm
  maps/submaps/surface_submaps/wilderness/Drugden.dmm
  polaris.dme
Labels: Refactor, Staff Request

#8139 Configure some VV bitfields and fix editor
  code/_global_vars/bitfields.dm
  code/datums/browser.dm
Labels: Feature Tweak

#8144 Indescribable! - A Food Flavor Fixing Pass
  code/modules/food/food/snacks.dm
  html/changelogs/MDP-indescribable.yml
Labels: Higgs Bugson, Refactor

#8145 Make item/attackby call ..(), multitool tool quality fix
  code/_onclick/item_attack.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/multitool.dm
Labels: Oversight, Refactor

#8148 Fixes synthetic var not getting cleared between loaded chars
  code/modules/client/preference_setup/general/03_body.dm
Labels: Bugfix

#8151 Removes unused var in select_recipe
  code/modules/food/recipe.dm
Labels: Oversight

#8152 waste doesnt exist
  code/modules/assembly/igniter.dm
  code/modules/assembly/infrared.dm
  code/modules/assembly/mousetrap.dm
  code/modules/assembly/proximity.dm
  code/modules/assembly/signaler.dm
  code/modules/assembly/timer.dm
  code/modules/assembly/voice.dm
  code/modules/power/antimatter/shielding.dm
Labels: Unwanted Feature Removal

#8154 Closet appearance decls correctly use the repository
  code/_helpers/global_lists.dm
  code/datums/repositories/decls.dm
  code/game/objects/structures/crates_lockers/__closets.dm
  code/global_init.dm
Labels: Oversight, Refactor

#8155 Adds optional area-based definition for outdoors-ness
  code/__defines/turfs.dm
  code/controllers/subsystems/planets.dm
  code/game/objects/effects/step_triggers.dm
  code/game/turfs/simulated/floor_attackby.dm
  code/game/turfs/simulated/lava.dm
  code/game/turfs/simulated/outdoors/outdoors.dm
  code/game/turfs/simulated/outdoors/sky.dm
  code/game/turfs/simulated/wall_attacks.dm
  code/game/turfs/simulated/water.dm
  code/modules/admin/verbs/lightning_strike.dm
  code/modules/flufftext/look_up.dm
  code/modules/mining/fulton.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/planet/sif.dm
  code/modules/planet/weather.dm
  maps/southern_cross/southern_cross_areas.dm
  maps/southern_cross/turfs/outdoors.dm
Labels: Feature, Map Change / Issue

#8157 Medicine Tweaks
  code/datums/uplink/medical.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/game/objects/items/weapons/storage/quickdraw.dm
  code/game/objects/random/unidentified/medicine.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/unidentified_hypospray.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/reagents/other.dm
Labels: Feature Tweak

#8158 Halves Item Slowdown Effects
  code/game/gamemodes/changeling/powers/armor.dm
  code/game/gamemodes/cult/cult_items.dm
  code/game/gamemodes/technomancer/core_obj.dm
  code/game/gamemodes/technomancer/devices/tesla_armor.dm
  code/game/objects/items/uav.dm
  code/game/objects/items/weapons/material/material_armor.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/items/weapons/tools/screwdriver.dm
  code/game/objects/items/weapons/tools/weldingtool.dm
  code/game/objects/items/weapons/tools/wirecutters.dm
  code/game/objects/items/weapons/tools/wrench.dm
  code/modules/artifice/telecube.dm
  code/modules/clothing/shoes/leg_guards.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/spacesuits/rig/modules/specific/sprinter.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/spacesuits/rig/suits/alien.dm
  code/modules/clothing/spacesuits/rig/suits/combat.dm
  code/modules/clothing/spacesuits/rig/suits/merc.dm
  code/modules/clothing/spacesuits/rig/suits/robotics.dm
  code/modules/clothing/spacesuits/rig/suits/station.dm
  code/modules/clothing/spacesuits/spacesuits.dm
  code/modules/clothing/spacesuits/syndi.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/accessories/armor.dm
  code/modules/clothing/under/accessories/temperature/poncho.dm
  code/modules/fishing/fishing_net.dm
Labels: Feature Tweak

#8159 Typo Fixy
  code/modules/reagents/reagents/food_drinks.dm
Labels: Oversight
