Repository PolarisSS13/Polaris, pull requests merged in 2021-08, with the labels that each got.

#8192 Fixes the Smart Fridge Error
  icons/obj/vending.dmi
Labels: Oversight, Priority: Medium

#8186 Cell Rack Update
  code/modules/power/batteryrack.dm
  icons/obj/cellrack.dmi
Labels: Sprite Change

#8188 New Rack and Wardrobe
  code/game/objects/structures/under_wardrobe.dm
  icons/obj/closets/undies_wardrobe.dmi
  icons/obj/objects.dmi
Labels: Sprite Change

#8189 Taser Update
  icons/obj/gun.dmi
Labels: Sprite Change

#8190 New Jukebox
  code/game/machinery/jukebox.dm
  icons/obj/jukebox.dmi
Labels: Sprite Change

#8178 Stun Revolver Update
  code/game/antagonist/outsider/raider.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/random/guns_and_ammo.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/research/designs/weapons.dm
  icons/obj/gun.dmi
Labels: Feature Tweak, Sprite Change

#8182 New Shotguns/Rifles
  code/modules/projectiles/guns/projectile/boltaction.dm
  code/modules/projectiles/guns/projectile/semiauto.dm
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
  icons/obj/gun.dmi
Labels: Cannot Merge, Sprite Change

#8226 Fixes infinite naming loop
  code/modules/surgery/robotics.dm
Labels: Bugfix

#8222 General wilderness updates.
  code/game/objects/items.dm
  code/game/objects/items/weapons/material/misc.dm
  code/game/objects/structures/flora/flora.dm
  code/game/objects/structures/flora/trees.dm
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/simulated/outdoors/dirt.dm
  code/game/turfs/simulated/outdoors/grass.dm
  code/game/turfs/simulated/outdoors/outdoors.dm
  code/game/turfs/simulated/outdoors/outdoors_attackby.dm
  code/modules/food/food/snacks.dm
  code/modules/hydroponics/grown.dm
  code/modules/hydroponics/grown_predefined.dm
  code/modules/hydroponics/grown_sif.dm
  code/modules/hydroponics/seed_packets.dm
  code/modules/hydroponics/seedtypes/apples.dm
  code/modules/hydroponics/trays/tray_soil.dm
  code/modules/materials/materials/organic/wood.dm
  code/modules/materials/sheets/organic/tanning/hide.dm
  code/modules/mining/mine_items.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/living/simple_mob/subtypes/animal/passive/fish.dm
  code/modules/random_map/random_map.dm
  code/modules/reagents/reactions/instant/instant.dm
  code/modules/reagents/reagents/food_drinks.dm
  code/modules/reagents/reagents/other.dm
  code/modules/reagents/reagents/toxins.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/flora/mushrooms.dmi
  icons/obj/items.dmi
  icons/obj/weapons.dmi
  icons/turf/flooring/asteroid.dmi
  polaris.dme
Labels: Feature

#8254 Fixes radio headset sound toggle not working
  code/game/objects/items/devices/radio/headset.dm
Labels: Bugfix

#8238 Updated Robot Component Sprites
  code/modules/mob/living/silicon/robot/component.dm
  icons/obj/robot_component.dmi
Labels: Sprite Change

#8231 New Labcoat Sprites
  code/datums/outfits/jobs/science.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/clothing/suits/labcoat.dm
  icons/mob/suit_1.dmi
  icons/obj/clothing/suits_1.dmi
Labels: Sprite Change

#8195 Misc. Skyrat Sprites Port
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/modules/power/singularity/containment_field.dm
  code/modules/tables/rack.dm
  icons/obj/machines/field_generator.dmi
  icons/obj/objects.dmi
  icons/obj/pipes/disposal.dmi
  icons/obj/sofas.dmi
  icons/obj/vending.dmi
Labels: Sprite Change
