Repository PolarisSS13/Polaris, pull requests merged in 2021-05, with the labels that each got.

#8056 weather sounds adjustments
  code/datums/looping_sounds/weather_sounds.dm
  code/modules/planet/sif.dm
Labels: Quality of Life

#8057 Body style selection and sanitizing refactor.
  code/modules/client/preference_setup/general/03_body.dm
  code/modules/mob/new_player/sprite_accessories.dm
  code/modules/mob/new_player/sprite_accessories_ear.dm
  code/modules/mob/new_player/sprite_accessories_tail.dm
  code/modules/mob/new_player/sprite_accessories_taur.dm
Labels: Refactor

#8058 Swaps emote(me) out for custom_emote().
  code/modules/genetics/side_effects.dm
  code/modules/mob/living/carbon/human/MedicalSideEffects.dm
  code/modules/mob/living/carbon/human/chem_side_effects.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_organs.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/organs/internal/appendix.dm
  code/modules/organs/internal/lungs.dm
  code/modules/spells/spell_code.dm
Labels: Oversight

#8059 Fixes centering on corgis and cats and their stuff.
  icons/mob/animal.dmi
  icons/mob/corgi_back.dmi
  icons/mob/corgi_head.dmi
Labels: Sprite Change

#8060 Personal Crafting & Dependencies
  code/__defines/_lists.dm
  code/__defines/crafting.dm
  code/__defines/dcs/signals.dm
  code/__defines/tools.dm
  code/_global_vars/lists/misc.dm
  code/_helpers/_lists.dm
  code/_helpers/global_lists.dm
  code/_helpers/sorts/comparators.dm
  code/_helpers/string_lists.dm
  code/_onclick/click.dm
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/screen_objects.dm
  code/datums/components/crafting/crafting.dm
  code/datums/components/crafting/crafting_external.dm
  code/datums/components/crafting/recipes.dm
  code/datums/components/crafting/tool_quality.dm
  code/datums/mind.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/multitool.dm
  code/game/objects/items/weapons/handcuffs.dm
  code/game/objects/items/weapons/improvised_components.dm
  code/game/objects/items/weapons/tools/crowbar.dm
  code/game/objects/items/weapons/tools/screwdriver.dm
  code/game/objects/items/weapons/tools/weldingtool.dm
  code/game/objects/items/weapons/tools/wirecutters.dm
  code/game/objects/items/weapons/tools/wrench.dm
  code/game/objects/random/misc.dm
  code/game/objects/structures/loot_piles.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/login.dm
  code/modules/power/cable.dm
  code/modules/projectiles/broken.dm
  code/modules/projectiles/guns/modular_guns.dm
  code/modules/reagents/holder/holder.dm
  code/modules/reagents/reagents/_reagents.dm
  icons/mob/screen/midnight.dmi
  polaris.dme
  tgui/packages/tgui/interfaces/PersonalCrafting.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Project, Quality of Life, Refactor

#8064 Fixes Virgo #10254.
  code/modules/client/preference_setup/general/02_language.dm
Labels: Oversight

#8046 Adds verb to VV global variables
  code/controllers/globals.dm
  code/datums/datumvars.dm
  code/modules/admin/admin_verb_lists.dm
  code/modules/admin/view_variables/helpers.dm
  code/modules/admin/view_variables/helpers_deprecated.dm
  code/modules/admin/view_variables/view_variables.dm
  code/modules/admin/view_variables/view_variables_global.dm
  polaris.dme
Labels: Feature, Quality of Life

#8069 The Personal Computer Unit
  code/game/machinery/computer/atmos_control.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/skills.dm
  code/game/objects/items/weapons/circuitboards/computer/computer.dm
  icons/obj/computer.dmi
Labels: Sprite Change

#8062 B to Resist!
  interface/interface.dm
  interface/skin.dmf
Labels: Feature, Quality of Life

#8065 Standardizes Boxes
  code/__defines/inventory_sizes.dm
Labels: Feature Tweak

#8071 Ports Nebula's Discord Webhook Integration
  code/__defines/color.dm
  code/__defines/misc.dm
  code/__defines/subsystems.dm
  code/__defines/webhooks.dm
  code/_helpers/_lists.dm
  code/_helpers/text.dm
  code/_helpers/type2type.dm
  code/controllers/configuration.dm
  code/controllers/subsystems/ticker.dm
  code/controllers/subsystems/webhooks.dm
  code/game/gamemodes/game_mode.dm
  code/game/world.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verb_lists.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/custom_event.dm
  code/modules/paperwork/faxmachine.dm
  code/modules/webhooks/_webhook.dm
  code/modules/webhooks/webhook_ahelp2discord.dm
  code/modules/webhooks/webhook_custom_event.dm
  code/modules/webhooks/webhook_fax2discord.dm
  code/modules/webhooks/webhook_roundend.dm
  code/modules/webhooks/webhook_roundprep.dm
  code/modules/webhooks/webhook_roundstart.dm
  config/example/webhooks.json
  polaris.dme
Labels: Feature

#8072 Allow more than one ore processor
  code/_helpers/global_lists.dm
  code/modules/mining/machinery/machine_processing.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mining/mineral_effect.dm
  code/modules/mining/ore_datum.dm
Labels: Bugfix

#8077 Port current glob initialize from tg
  code/controllers/globals.dm
Labels: Bugfix

#8078 Refactors IsSynthetic
  code/modules/client/preference_setup/general/03_body.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/human_powers.dm
  code/modules/organs/subtypes/standard.dm
Labels: Bugfix, Priority: CRITICAL

#8079 Adds map name and in-round player count to Topic reply.
  code/game/world.dm
Labels: Feature Tweak

#8052 Simplemobs seek lost targets
  code/modules/ai/ai_holder_combat_unseen.dm
  code/modules/ai/ai_holder_movement.dm
  code/modules/ai/ai_holder_targeting.dm
Labels: Feature, Mob AI Issue, Prepare to Die, Test Merge: Long-term

#8081 Mecha Balance and Fighter Fixes
  code/game/mecha/combat/fighter.dm
  code/game/mecha/mecha.dm
  code/modules/research/mechfab_designs.dm
Labels: Feature Tweak, Unwanted Feature Removal

#8082 More Spawner Tweaks
  code/game/objects/random/mapping.dm
  code/game/objects/random/misc.dm
  icons/obj/stacks.dmi
Labels: Feature, Sprite Change

#8084 [Bugfix] Stop SSD Snoring
  code/modules/mob/living/carbon/human/life.dm
Labels: Oversight

#8083 Food 4 thought
  code/game/objects/items/trash.dm
  code/game/objects/items/weapons/chewables.dm
  code/game/objects/random/misc.dm
  code/game/objects/structures/loot_piles.dm
  code/modules/economy/price_list.dm
  code/modules/economy/vending_machines.dm
  code/modules/food/food/lunch.dm
  code/modules/food/food/snacks.dm
  icons/mob/mask.dmi
  icons/mob/species/teshari/masks.dmi
  icons/obj/food.dmi
  icons/obj/food_canned.dmi
  icons/obj/food_snacks.dmi
  icons/obj/trash.dmi
  icons/obj/vending.dmi
  maps/submaps/surface_submaps/mountains/quarantineshuttle.dmm
  polaris.dme
  sound/effects/desktop.ini
  sound/effects/packagedfoodopen.ogg
  sound/effects/tincanopen.ogg
Labels: Feature, Sound Change, Sprite Change

#8087 SSpersistence tweaks
  code/__defines/map.dm
  code/controllers/subsystems/persistence.dm
  code/modules/food/kitchen/smartfridge/engineering.dm
  code/modules/food/kitchen/smartfridge/hydroponics.dm
  code/modules/food/kitchen/smartfridge/smartfridge.dm
  code/modules/persistence/datum/persistence_datum.dm
  code/modules/persistence/effects/filth.dm
  code/modules/persistence/effects/graffiti.dm
  code/modules/persistence/effects/paper.dm
  code/modules/persistence/effects/paper_sticky.dm
  code/modules/persistence/storage/smartfridge.dm
  code/modules/persistence/storage/storage.dm
  maps/~map_system/maps.dm
  polaris.dme
Labels: Feature Tweak, Refactor

#8089 [Bugfix] Maybe Fix Cleanbots
  code/modules/mob/living/bot/cleanbot.dm
  code/modules/mob/living/bot/edCLNbot.dm
Labels: Bugfix, Higgs Bugson

#8090 Help beam_components qdel properly
  code/game/objects/effects/temporary_visuals/projectiles/tracer.dm
Labels: Oversight

#8091 Replaces Gunpod Sprite
  ATTRIBUTIONS.md
  icons/mecha/fighters64x64.dmi
Labels: Sprite Change

#8093 Wall Locker Adjustments
  code/game/objects/structures/crates_lockers/closets/walllocker.dm
Labels: Bugfix, Unwanted Feature Removal

#8094 phoron bore stock parts now affect range, along with other bits
  code/modules/projectiles/guns/magnetic/bore.dm
  code/modules/projectiles/projectile/magnetic.dm
Labels: Bugfix, Feature Tweak

#8095 Wall-mounted Geiger Counters
  code/datums/autolathe/engineering.dm
  code/game/machinery/frame.dm
  code/game/objects/items/devices/geiger.dm
  code/game/objects/items/weapons/circuitboards/frame.dm
  code/modules/economy/vending_machines.dm
  icons/obj/device.dmi
  icons/obj/stock_parts.dmi
Labels: Feature

#8074 Removes tin for ore generation
  code/modules/mining/drilling/drill.dm
  code/modules/mining/mine_turfs.dm
Labels: Staff Request, Unwanted Feature Removal

#8075 Reverts recipe changes from Industrial Expansion
  code/game/objects/items/devices/communicator/communicator.dm
  code/game/objects/items/devices/laserpointer.dm
  code/game/objects/items/devices/multitool.dm
  code/game/objects/items/devices/radio/electropack.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/weapons/circuitboards/circuitboard.dm
  code/game/objects/items/weapons/circuitboards/frame.dm
  code/game/objects/items/weapons/circuitboards/mecha.dm
  code/modules/assembly/igniter.dm
  code/modules/assembly/infrared.dm
  code/modules/assembly/proximity.dm
  code/modules/assembly/signaler.dm
  code/modules/assembly/timer.dm
  code/modules/assembly/voice.dm
  code/modules/projectiles/ammunition/rounds.dm
  code/modules/research/designs/HUDs.dm
  code/modules/research/designs/ai_holders.dm
  code/modules/research/designs/bag_of_holding.dm
  code/modules/research/designs/bio_devices.dm
  code/modules/research/designs/circuits/ai_modules.dm
  code/modules/research/designs/circuits/circuits.dm
  code/modules/research/designs/circuits/disks.dm
  code/modules/research/designs/engineering.dm
  code/modules/research/designs/implants.dm
  code/modules/research/designs/locator_devices.dm
  code/modules/research/designs/medical.dm
  code/modules/research/designs/mining_toys.dm
  code/modules/research/designs/misc.dm
  code/modules/research/designs/modular_computer.dm
  code/modules/research/designs/pdas.dm
  code/modules/research/designs/power_cells.dm
  code/modules/research/designs/stock_parts.dm
  code/modules/research/designs/weapons.dm
  code/modules/research/designs/xenoarch_toys.dm
  code/modules/research/designs/xenobio_toys.dm
  code/modules/research/mechfab_designs.dm
Labels: Staff Request, Unwanted Feature Removal

#8098 Makes roundstart webhook not metagame.
  code/modules/webhooks/webhook_roundstart.dm
Labels: Oversight

#8101 Fixes Resist Button
  code/__defines/mobs.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
Labels: Bugfix

#8102 Initialize all vending products on server start & fix multiple food icons
  code/game/objects/random/misc.dm
  code/modules/admin/topic.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/economy/price_list.dm
  code/modules/food/food/snacks.dm
  code/modules/food/recipes_oven.dm
  icons/obj/food_syn.dmi
Labels: Bugfix

#8105 Add icon state for turned off keyboard for PCU
  icons/obj/computer.dmi
Labels: Oversight

#8106 Voidsuit Balance Overhaul
  code/datums/supplypacks/voidsuits.dm
  code/game/machinery/suit_storage_unit.dm
  code/modules/clothing/spacesuits/void/event.dm
  code/modules/clothing/spacesuits/void/merc.dm
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/clothing/spacesuits/void/void.dm
  code/modules/clothing/spacesuits/void/wizard.dm
Labels: Feature, Prepare to Die

#8107 Autoinjectors are Autoinjectors
  code/modules/identification/identification.dm
Labels: Oversight

#8108 Make figurines small instead of normal sized
  code/game/objects/items/toys/toys.dm
Labels: Feature Tweak

#8109 Misc Bits
  code/game/objects/structures/handrail.dm
  icons/obj/handrail.dmi
  icons/obj/statue.dmi
  polaris.dme
Labels: Feature, Map: Cynosure, Project

#8110 Makes deepspace levels slightly more robust
  code/modules/overmap/sectors.dm
  code/modules/overmap/spacetravel.dm
  maps/~map_system/maps.dm
Labels: Bugfix, Higgs Bugson

#8112 Various small fixes
  code/game/objects/items/stacks/marker_beacons.dm
  code/game/turfs/simulated/outdoors/snow.dm
  code/game/turfs/simulated/wall_icon.dm
  code/game/turfs/simulated/wall_types.dm
  code/modules/ai/ai_holder_combat_unseen.dm
  code/modules/ai/ai_holder_targeting.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/nurse.dm
  code/modules/persistence/graffiti.dm
  icons/turf/wall_masks.dmi
  icons/turf/wall_masks32x64.dmi
  icons/turf/wall_masks64x32.dmi
Labels: Bugfix, Feature Tweak, Mob AI Issue, Sprite Change

#8114 Fix language sani on relogins
  code/modules/client/client procs.dm
Labels: Oversight
