Repository PolarisSS13/Polaris, pull requests merged in 2021-07, with the labels that each got.

#8164 Fix compiler warning from unused var.
  code/datums/browser.dm
Labels: Oversight

#8161 Fixes inverted logic in staffwho
  code/modules/client/verbs/who.dm
Labels: Oversight

#8165 Fixes utensils, adds variable scoop size
  code/game/objects/items/weapons/material/kitchen.dm
  code/modules/food/food/snacks.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  html/changelogs/MDP-utensilfix.yml
Labels: Bugfix

#8166 Cold cavern tileset.
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/flooring/flooring_premade.dm
  code/game/turfs/simulated/outdoors/snow.dm
  code/modules/mining/mine_turfs.dm
  icons/turf/flooring/asteroid.dmi
  icons/turf/outdoors.dmi
  icons/turf/outdoors_edge.dmi
  icons/turf/walls.dmi
Labels: Feature

#8171 Fixes Indoor Rain
  code/controllers/subsystems/planets.dm
  code/game/objects/effects/step_triggers.dm
  code/game/turfs/simulated/floor_attackby.dm
  code/game/turfs/simulated/outdoors/outdoors.dm
  code/game/turfs/simulated/wall_attacks.dm
  code/modules/admin/verbs/lightning_strike.dm
  code/modules/flufftext/look_up.dm
  code/modules/mining/fulton.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/planet/sif.dm
  code/modules/planet/weather.dm
Labels: Bugfix

#8172 Sign Oh Sure
  code/game/objects/structures/signs.dm
  code/game/turfs/flooring/flooring_decals.dm
  icons/obj/decals.dmi
  icons/obj/decals_directions.dmi
  icons/obj/decals_levels.dmi
  icons/turf/flooring/decals.dmi
  maps/southern_cross/southern_cross-6.dmm
  maps/submaps/surface_submaps/wilderness/DecoupledEngine.dmm
Labels: Feature Tweak, Map Change / Issue, Map: Cynosure, Map: Point of Interest

#8173 Misc Vore-TG Port Ports
  code/__defines/color.dm
  code/game/objects/effects/decals/posters/bs12.dm
  code/game/objects/effects/decals/posters/polarisposters.dm
  code/game/objects/items/toys/mech_toys.dm
  code/game/objects/items/toys/toys.dm
  code/game/objects/items/uav.dm
  code/game/objects/items/weapons/material/kitchen.dm
  code/game/objects/items/weapons/material/knives.dm
  code/game/objects/items/weapons/storage/misc.dm
  code/game/objects/random/misc.dm
  code/game/objects/structures/barsign.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/stool_bed_chair_nest/stools.dm
  code/game/objects/structures/watercloset.dm
  code/modules/economy/vending_machines.dm
  code/modules/food/food/lunch.dm
  code/modules/food/food/snacks.dm
  code/modules/food/recipes_fryer.dm
  code/modules/materials/sheets/organic/wood.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/tables/presets.dm
  icons/mob/pai.dmi
  icons/obj/barsigns.dmi
  icons/obj/bureaucracy.dmi
  icons/obj/contraband.dmi
  icons/obj/device.dmi
  icons/obj/food.dmi
  icons/obj/food_donuts.dmi
  icons/obj/food_ingredients.dmi
  icons/obj/forensics.dmi
  icons/obj/furniture.dmi
  icons/obj/holoplants.dmi
  icons/obj/kitchen.dmi
  icons/obj/lighting.dmi
  icons/obj/singularity.dmi
  icons/obj/sofas.dmi
  icons/obj/toy.dmi
  icons/obj/watercloset.dmi
Labels: Feature Tweak, Needs Review, Sprite Change

#8179 Fixes double chat bug
  code/modules/multiz/zshadow.dm
Labels: Bugfix, Oversight

#8180 Chemsprayer Update
  code/modules/reagents/reagent_containers/spray.dm
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
  icons/obj/gun.dmi
Labels: Sprite Change

#8183 Fixes blank ID sprite for HoP/Secretary
  code/datums/outfits/jobs/command.dm
Labels: Oversight

#8176 Binoculars and Spyglass
  code/game/gamemodes/technomancer/equipment.dm
  code/game/objects/items/devices/binoculars.dm
  icons/obj/device.dmi
Labels: Feature Tweak

#8185 2021 Drink Revamp
  code/modules/economy/vending_machines.dm
  code/modules/food/food/cans.dm
  code/modules/food/food/drinks/bottle.dm
  code/modules/reagents/machinery/dispenser/cartridge_presets.dm
  code/modules/reagents/machinery/dispenser/dispenser2_energy.dm
  code/modules/reagents/machinery/dispenser/dispenser_presets.dm
  code/modules/reagents/machinery/dispenser/supply.dm
  code/modules/reagents/reactions/instant/drinks.dm
  code/modules/reagents/reagents/food_drinks.dm
  icons/obj/drinks.dmi
  icons/obj/vending.dmi
Labels: Feature, Sprite Change

#8174 Custom poster fix
  code/game/objects/effects/decals/posters/posters.dm
Labels: Oversight
