Repository PolarisSS13/Polaris, pull requests merged in 2022-05, with the labels that each got.

#8593 SSOverlays cuts queue from start to count, not count to end
  code/controllers/subsystems/overlays.dm
Labels: Oversight, Priority: High, Bugfix

#8599 Toner has a sprite again
  code/modules/paperwork/photocopier.dm
Labels: Oversight

#8598 Fixes zone_sel always having torso overlay
  code/_onclick/hud/screen_objects.dm
Labels: Priority: Low, Bugfix

#8600 Readds ability overlays
  code/_onclick/hud/ability_screen_objects.dm
Labels: Oversight

#8588 Adds Sjorgen Inertial Shotgun (by H-H)
  code/datums/supplypacks/munitions.dm
  code/datums/uplink/visible_weapons.dm
  code/game/objects/random/guns_and_ammo.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  icons/obj/gun.dmi
Labels: Feature

#8609 SAR as alt title
  maps/cynosure/cynosure_jobs.dm
  maps/cynosure/loadout/loadout_suit.dm
  maps/cynosure/structures/closets/misc.dm
Labels: Feature Tweak

#8607 Expands Loadout Contraband
  code/modules/client/preference_setup/loadout/loadout_contraband.dm
  code/modules/client/preference_setup/loadout/loadout_cyberware.dm
  code/modules/client/preference_setup/loadout/loadout_mask.dm
  code/modules/reagents/reagent_containers/spray.dm
  icons/obj/weapons.dmi
Labels: Feature Tweak

#8620 un-recommends editorconfig for vscode
  .vscode/extensions.json
Labels: Repo

#8623 Adds Nutmeg to Seed Storage
  code/modules/hydroponics/seed_storage.dm
Labels: Feature Tweak

#8624 fix reactor pool heating up cooling pipes
  code/ATMOSPHERICS/datum_pipeline.dm
Labels: Priority: High, Bugfix

#8625 Removes dnaswitch artifact effect
  code/modules/xenoarcheaology/effects/dnaswitch.dm
  polaris.dme
Labels: Revert

#8627 db flex tape
  code/_global_vars/sensitive.dm
  code/controllers/configuration.dm
  code/controllers/subsystems/misc_slow.dm
  code/game/world.dm
  code/global.dm
  code/modules/admin/view_variables/view_variables_global.dm
  config/example/forumdbconfig.txt
  polaris.dme
Labels: Bugfix, Quality of Life

#8629 Chest -> Torso Targeting Fixes
  code/_helpers/mobs.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/food/kitchen/cooking_machines/fryer.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/mob_helpers.dm
  code/modules/spells/targeted/projectile/projectile.dm
Labels: Bugfix

#8633 Bartending enhancements
  code/datums/supplypacks/hospitality.dm
  code/modules/economy/vending_machines.dm
  code/modules/reagents/machinery/dispenser/cartridge_presets.dm
  code/modules/reagents/machinery/dispenser/dispenser_presets.dm
  code/modules/reagents/reactions/instant/drinks.dm
  code/modules/reagents/reagent_containers/glass.dm
  icons/obj/chemical.dmi
  icons/obj/reagentfillings.dmi
Labels: Feature, Bugfix, Sprites

#8634 Nerfs Hyperzine
  code/game/machinery/doors/airlock.dm
  code/modules/reagents/reagents/drugs.dm
  code/modules/reagents/reagents/medicine.dm
Labels: Feature Tweak

#8636 clothing port May 2022
  code/_helpers/global_lists.dm
  code/datums/outfits/outfit.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/modules/client/preference_setup/loadout/loadout_accessories.dm
  code/modules/client/preference_setup/loadout/loadout_ears.dm
  code/modules/client/preference_setup/loadout/loadout_mask.dm
  code/modules/clothing/ears/ears.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/under/accessories/accessory.dm
  icons/mob/back.dmi
  icons/mob/ears.dmi
  icons/mob/hands.dmi
  icons/mob/items/lefthand_storage.dmi
  icons/mob/items/righthand_storage.dmi
  icons/mob/mask.dmi
  icons/mob/species/tajaran/mask.dmi
  icons/mob/species/teshari/back.dmi
  icons/mob/species/teshari/ears.dmi
  icons/mob/species/teshari/gloves.dmi
  icons/mob/species/teshari/masks.dmi
  icons/mob/species/teshari/ties.dmi
  icons/mob/species/teshari/uniform.dmi
  icons/mob/species/unathi/mask.dmi
  icons/mob/ties.dmi
  icons/obj/clothing/backpack.dmi
  icons/obj/clothing/ears.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/ties.dmi
  maps/cynosure/structures/closets/misc.dm
Labels: Feature

#8637 New blender sound but done right hopefully
  sound/machines/blender.ogg
Labels: Sounds

#8635 Vents Auto-scrub Phoron Again
  code/ATMOSPHERICS/components/unary/vent_scrubber.dm
Labels: Quality of Life

#8622 Fixes directional overlays on padded comfy and rounded chairs
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/modules/materials/materials/metals/steel.dm
Labels: Bugfix
