Repository PolarisSS13/Polaris, pull requests merged in 2022-11, with the labels that each got.

#8815 Fix runtimes with uplink random item selections
  code/datums/uplink/badassery.dm
  code/datums/uplink/uplink_items.dm
Labels: Bugfix

#8808 Notifies player of additional lore/mechanical info on examined objects
  code/game/atoms.dm
Labels: Feature

#8810 fix up a bunch of macro cruft
  code/__defines/misc.dm
  code/__defines/qdel.dm
  code/_helpers/game.dm
  code/_macros.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/minihud.dm
  code/_onclick/hud/screen_objects.dm
  code/controllers/globals.dm
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/controllers/subsystems/chat.dm
  code/controllers/subsystems/timer.dm
  code/datums/ghost_query.dm
  code/datums/looping_sounds/_looping_sound.dm
  code/game/machinery/teleporter.dm
  code/game/objects/effects/mines.dm
  code/game/objects/effects/temporary_visuals/projectiles/tracer.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/devices/suit_cooling.dm
  code/game/objects/items/uav.dm
  code/game/objects/items/weapons/RPD.dm
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/game/objects/structures/crates_lockers/__closets.dm
  code/game/world.dm
  code/modules/admin/view_variables/mass_edit_variables.dm
  code/modules/admin/view_variables/modify_variables.dm
  code/modules/admin/view_variables/topic_list.dm
  code/modules/antagonist/antagonist_create.dm
  code/modules/assembly/infrared.dm
  code/modules/asset_cache/asset_cache_item.dm
  code/modules/client/client procs.dm
  code/modules/client/preference_setup/loadout/loadout.dm
  code/modules/client/preference_setup/occupation/occupation.dm
  code/modules/gamemaster/event2/events/command/raise_funds.dm
  code/modules/holomap/mapper.dm
  code/modules/integrated_electronics/subtypes/output.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/silicon/laws.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/mecha/mecha.dm
  code/modules/mob/mob_planes.dm
  code/modules/modular_computers/file_system/news_article.dm
  code/modules/modular_computers/hardware/battery_module.dm
  code/modules/persistence/datum/persistence_datum.dm
  code/modules/projectiles/guns/launcher/bows.dm
  code/modules/shieldgen/shield_gen.dm
  code/modules/vchat/vchat_client.dm
  code/modules/vchat/vchat_db.dm
Labels: Refactor, Bugfix, Repo

#8809 adds a client verb to force stop playing audio
  code/game/sound.dm
Labels: Quality of Life

#8811 add atom/Topic & atom/CreateAtomTopic + examine
  code/__defines/misc.dm
  code/game/atoms.dm
Labels: Feature, Bugfix

#8788 Nerfs mech armor
  code/game/mecha/components/armor.dm
  code/game/mecha/mecha.dm
Labels: Contentious, Feature Tweak

#8817 Naming Food & Blood Cakes
  code/modules/food/food.dm
  code/modules/food/kitchen/cooking_machines/_appliance.dm
Labels: Feature, Bugfix

#8750 Adding vox reagents, removing Vox Delight.
  code/datums/outfits/vox.dm
  code/modules/food/food/drinks.dm
  code/modules/food/food/lunch.dm
  code/modules/reagents/reactions/_reactions.dm
  code/modules/reagents/reactions/instant/drinks.dm
  code/modules/reagents/reactions/instant/vox.dm
  code/modules/reagents/reagents/core.dm
  code/modules/reagents/reagents/food_drinks.dm
  code/modules/reagents/reagents/vox.dm
  icons/obj/drinks.dmi
  polaris.dme
Labels: Feature, Feature Tweak, Sprites

#8826 AlienObjects tm are once again alien objects
  code/game/objects/structures/props/alien_props.dm
Labels: Bugfix

#8812 added the skeleton for envelopes
  code/game/objects/items.dm
  code/modules/paperwork/folders.dm
  code/modules/paperwork/stamps.dm
  icons/obj/bureaucracy.dmi
Labels: Feature, Sprites

#8827 storage item late-naming
  code/game/objects/items/weapons/storage/internal.dm
  code/game/objects/items/weapons/storage/misc.dm
  code/game/objects/items/weapons/storage/storage.dm
  maps/cynosure/cynosure-3.dmm
  maps/northern_star/polaris-1.dmm
  maps/southern_cross/southern_cross-1.dmm
Labels: Refactor, Bugfix

#8838 submaps should init but may hide issues
  code/controllers/subsystems/atoms.dm
Labels: Priority: High, Bugfix

#8839 correct uplink item cost behavior
  code/datums/uplink/badassery.dm
  code/datums/uplink/telecrystals.dm
  code/datums/uplink/uplink_items.dm
  code/game/objects/items/devices/uplink.dm
  code/game/objects/items/devices/uplink_random_lists.dm
Labels: Priority: Medium, Bugfix

#8845 temp downgrade to ubuntu 20 for libssl1.1 in tests
  .github/workflows/autochangelog.yml
  .github/workflows/ci.yml
  .github/workflows/enforce_lables.yml
Labels: Priority: High, Bugfix

#8846 Adds more generic clothing paintkit.
  code/game/objects/items/paintkit.dm
Labels: Feature Tweak

#8832 drakes can break down trees and dig up stumps
  code/game/objects/structures/flora/trees.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka/grafadreka_interaction.dm
Labels: Feature Tweak
