Repository PolarisSS13/Polaris, pull requests merged in 2022-10, with the labels that each got.

#8704 Adds a morgue access corridor
  maps/cynosure/cynosure-1.dmm
Labels: Map: Cynosure

#8709 moved sdmm defines to as early as possible in env
  code/__spaceman_dmm.dm
  polaris.dme
Labels: Repo

#8711 Post-Timeskip News Update
  code/modules/lore_codex/news_data/main.dm
Labels: Lore

#8719 Admin Build Mode Agony Removal
  code/modules/admin/verbs/buildmode.dm
Labels: Quality of Life

#8722 Adds SSTyping
  code/__defines/appearance.dm
  code/controllers/subsystems/typing.dm
  code/modules/client/preference_setup/global/setting_datums.dm
  code/modules/mob/living/carbon/brain/brain.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/say.dm
  code/modules/mob/typing_indicator.dm
  code/modules/multiz/zshadow.dm
  polaris.dme
Labels: Feature

#8714 Consolidates Loadout Lists
  code/modules/client/preference_setup/loadout/loadout_accessories.dm
  code/modules/client/preference_setup/loadout/loadout_cyberware.dm
  code/modules/client/preference_setup/loadout/loadout_eyes.dm
  code/modules/client/preference_setup/loadout/loadout_gloves.dm
  code/modules/client/preference_setup/loadout/loadout_head.dm
  code/modules/client/preference_setup/loadout/loadout_mask.dm
  code/modules/client/preference_setup/loadout/loadout_shoes.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/solgov.dm
  maps/cynosure/loadout/loadout_accessories.dm
  maps/cynosure/loadout/loadout_suit.dm
Labels: Quality of Life

#8705 An Abundance of Hats
  code/game/machinery/suit_storage_unit.dm
  code/game/objects/random/misc.dm
  code/game/objects/random/spacesuits.dm
  code/modules/awaymissions/corpse.dm
  code/modules/client/preference_setup/loadout/loadout_head.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/head/solgov.dm
  code/modules/clothing/spacesuits/alien.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/spacesuits/void/event.dm
  code/modules/clothing/spacesuits/void/merc.dm
  code/modules/clothing/spacesuits/void/misc.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/head.dmi
  icons/mob/spacesuit.dmi
  icons/mob/species/tajaran/helmet.dmi
  icons/mob/species/tajaran/suit.dmi
  icons/mob/species/teshari/head.dmi
  icons/mob/species/unathi/helmet.dmi
  icons/mob/species/unathi/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/spacesuits.dmi
  icons/obj/clothing/species/tajaran/hats.dmi
  icons/obj/clothing/species/unathi/hats.dmi
  icons/obj/clothing/species/unathi/suits.dmi
  maps/cynosure/cynosure-4.dmm
  maps/submaps/surface_submaps/mountains/Mineshaft1.dmm
  maps/submaps/surface_submaps/mountains/excavation1.dmm
  maps/submaps/surface_submaps/mountains/prepper1.dmm
  maps/submaps/surface_submaps/mountains/vault5.dmm
  maps/submaps/surface_submaps/plains/Mechpt.dmm
  maps/submaps/surface_submaps/wilderness/Blackshuttledown.dmm
  maps/submaps/surface_submaps/wilderness/Blueshuttledown.dmm
  maps/submaps/surface_submaps/wilderness/MCamp1.dmm
  maps/submaps/surface_submaps/wilderness/MHR.dmm
  polaris.dme
Labels: Feature Tweak, Sprites

#8735 Spkrtn/fix/8703 8733
  code/modules/hydroponics/seed.dm
  code/modules/mob/living/bot/bot.dm
  code/modules/mob/living/bot/mulebot.dm
Labels: Bugfix

#8726 Rub A Dub Dub
  code/defines/obj/weapon.dm
  code/game/objects/random/misc.dm
  icons/obj/soap.dmi
Labels: Feature Tweak, Sprites

#8721 A -ton of Flags
  code/game/objects/structures/signs.dm
  icons/obj/flags.dmi
Labels: Feature Tweak, Sprites

#8717 Aurora shield generator port
  icons/obj/machines/shielding.dmi
Labels: Sprites

#8718 Shuttle Refit
  code/game/machinery/doors/airlock.dm
  code/game/turfs/flooring/flooring_decals.dm
  code/game/turfs/flooring/flooring_premade.dm
  code/game/turfs/simulated/wall_types.dm
  icons/obj/doors/Doorextwhite.dmi
  icons/turf/flooring/decals.dmi
  icons/turf/flooring/tiles.dmi
  icons/turf/wall_masks_tgmc.dmi
  icons/turf/wall_masks_tgmc_win.dmi
  maps/cynosure/cynosure-2.dmm
  maps/cynosure/cynosure-3.dmm
  maps/cynosure/cynosure-6.dmm
  maps/submaps/surface_submaps/mountains/quarantineshuttle.dmm
Labels: Feature Tweak, Sprites

#8713 Morgan Trading prosthetic expansion
  code/modules/organs/robolimbs.dm
  icons/mob/human_races/cyberlimbs/prosthesis/wooden_sif.dmi
  icons/mob/human_races/cyberlimbs/prosthesis/wooden_sif_teshari.dmi
  icons/mob/human_races/cyberlimbs/prosthesis/wooden_teshari.dmi
Labels: Feature Tweak, Sprites

#8729 Fixed showers not appearing to turn off
  code/game/objects/structures/watercloset.dm
Labels: Bugfix

#8730 Fixes Teshari Directionals
  code/modules/clothing/under/xenos/teshari.dm
  icons/mob/species/teshari/deptjacket.dmi
  icons/mob/species/teshari/teshari_uniform.dmi
Labels: Bugfix, Sprites

#8732 Adds and updates some underwear and undershirt options
  code/datums/underwear/bottom.dm
  code/datums/underwear/top.dm
  code/datums/underwear/undershirts.dm
  icons/mob/human.dmi
Labels: Feature Tweak, Sprites

#8728 Fixes blue blazer being double-listed in xenowear and requiring whitelist
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
Labels: Bugfix

#8716 Ports Aurora mining vendor as base for exploration vendor
  icons/obj/machines/mining_machines.dmi
Labels: Sprites

#8706 A Jillion Jumpsuits
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/under/color.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/items/lefthand_uniforms.dmi
  icons/mob/items/righthand_uniforms.dmi
  icons/mob/uniform.dmi
  icons/mob/uniform_1.dmi
  icons/mob/uniform_rolled_down.dmi
  icons/mob/uniform_sleeves_rolled.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/clothing/uniforms_1.dmi
Labels: Feature Tweak, Sprites

#8199 Ports Diagonal Movement
  code/__defines/_compile_options.dm
  code/__defines/flags.dm
  code/__defines/input.dm
  code/__defines/subsystems.dm
  code/_helpers/type2type.dm
  code/controllers/subsystems/input.dm
  code/game/atoms_movable.dm
  code/global.dm
  code/modules/client/client defines.dm
  code/modules/keybindings/bindings_atom.dm
  code/modules/keybindings/bindings_movekeys.dm
  code/modules/keybindings/readme.md
  code/modules/keybindings/setup.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_movement.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_movement.dm
  code/modules/multiz/movement.dm
  interface/skin.dmf
  polaris.dme
Labels: Feature, Contentious, Test Merge

#8739 Firefighting Gear
  code/datums/outfits/costumes/halloween.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/game/objects/structures/crates_lockers/closets/walllocker.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/clothing/suits/utility.dm
  code/modules/reagents/machinery/dispenser/reagent_tank.dm
  icons/mob/head.dmi
  icons/mob/species/tajaran/helmet.dmi
  icons/mob/species/unathi/helmet.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  maps/northern_star/polaris-1.dmm
  maps/southern_cross/southern_cross-1.dmm
  maps/submaps/surface_submaps/mountains/deadspy.dmm
Labels: Feature Tweak, Sprites

#8741 Adjustments to recent sprites
  code/modules/hydroponics/trays/tray_tools.dm
  icons/obj/structures.dmi
  icons/obj/tools.dmi
Labels: Bugfix, Sprites

#8742 Replaces shuttle windows with dummy objects for aesthetic reasons
  code/game/shuttle_engines.dm
  maps/cynosure/cynosure-6.dmm
Labels: Bugfix

#8745 Complete gun sprite overhaul + additions
  code/datums/uplink/ammunition.dm
  code/datums/uplink/visible_weapons.dm
  code/game/objects/random/guns_and_ammo.dm
  code/modules/fishing/fishing.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/nuclear.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/boltaction.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/guns/projectile/revolver.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/xenobio/items/weapons.dm
  icons/mob/back.dmi
  icons/mob/belt_mirror.dmi
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
  icons/obj/energygun.dmi
  icons/obj/gun.dmi
  icons/obj/gun2.dmi
  maps/submaps/surface_submaps/mountains/vault5.dmm
Labels: Feature Tweak, Sprites

#8737 fix || in type2parent switch, gentle refactor
  code/_helpers/type2type.dm
Labels: Bugfix

#8748 Makes ghosting apply proper rest
  code/modules/mob/dead/observer/observer.dm
Labels: Bugfix

#8720 Ian: The Next Generation
  code/modules/mob/living/simple_mob/subtypes/animal/pets/cat.dm
  code/modules/mob/living/simple_mob/subtypes/animal/pets/dog.dm
  icons/mob/animal.dmi
  icons/mob/head.dmi
  icons/mob/items/lefthand_holder.dmi
  icons/mob/items/righthand_holder.dmi
Labels: Feature Tweak, Sprites

#8740 Adds Parkas
  code/modules/clothing/head/hood.dm
  code/modules/clothing/suits/hooded.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
  maps/cynosure/cynosure-2.dmm
Labels: Feature Tweak, Sprites

#8710 Vox pressure immunity is now a toggle.
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species/outsider/vox.dm
  code/modules/mob/living/carbon/human/species/species_getters.dm
  code/modules/mob/living/carbon/human/species/station/prometheans.dm
Labels: Feature, Refactor, Feature Tweak

#8753 fixes for a number of logged errors
  code/_helpers/logging.dm
  code/controllers/subsystems/antag.dm
  code/controllers/subsystems/garbage.dm
  code/datums/weakref.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/items/contraband.dm
  code/modules/client/preference_setup/general/03_body.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/unit_tests/subsystem_tests.dm
Labels: Bugfix

#8752 speculative fix for obj/random's not being deleted
  code/game/objects/random/_random.dm
Labels: Bugfix

#8715 Replaces Skrell sprites
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
  icons/mob/human_face_alt.dmi
  icons/mob/human_face_m.dmi
  icons/mob/human_races/r_def_skrell.dmi
  icons/mob/human_races/r_skrell.dmi
  icons/obj/surgery.dmi
Labels: Sprites

#8756 Update partial pressures for planetary turfs upon weather change.
  code/game/turfs/unsimulated/planetary.dm
Labels: Bugfix

#8754 hairs n tails
  code/modules/mob/new_player/sprite_accessories.dm
  code/modules/mob/new_player/sprite_accessories_tail.dm
  icons/effects/species_tails.dmi
  icons/mob/human_face.dmi
  icons/mob/human_face_m.dmi
  polaris.dme
Labels: Sprites

#8770 Gives Checkpoint Outpost A Roof
  maps/cynosure/cynosure-2.dmm
  maps/cynosure/cynosure-3.dmm
Labels: Feature Tweak

#8772 Fixes a bug with deleted disposal outlets
  code/modules/recycling/disposal.dm
Labels: Bugfix

#8766 remove duplicate turf/CanPass + tweaks
  code/ZAS/Atom.dm
  code/game/turfs/turf.dm
Labels: Bugfix

#8774 Cargonia Buff
  code/modules/persistence/storage/smartfridge.dm
  maps/cynosure/cynosure-2.dmm
  maps/cynosure/cynosure-3.dmm
Labels: Feature Tweak

#8767 Adds Sivian Creole Language
  code/__defines/species_languages.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/mob/language/generic.dm
  code/modules/mob/language/monkey.dm
  code/modules/mob/language/station.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/robot_modules/station.dm
  code/modules/mob/living/silicon/robot/robot_modules/syndicate.dm
  code/modules/mob/transform_procs.dm
  code/modules/vchat/css/ss13styles.css
  code/stylesheet.dm
Labels: Feature, Feature Tweak

#8777 Fixes janitor drone north-facing icon state
  icons/mob/robots.dmi
Labels: Bugfix

#8725 Implements a path-based, player-specific whitelisting system
  code/__defines/vv.dm
  code/_helpers/files.dm
  code/game/jobs/whitelist.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verb_lists.dm
  code/modules/admin/banjob.dm
  code/modules/admin/topic.dm
  code/modules/admin/view_variables/view_variables_global.dm
  code/modules/client/preference_setup/general/03_body.dm
  code/modules/whitelist/admin_ops.dm
  code/modules/whitelist/legacy.dm
  code/modules/whitelist/phony_paths.dm
  code/modules/whitelist/whitelist.dm
  polaris.dme
Labels: Refactor

#8781 Fixes issue with language whitelists
  code/modules/whitelist/whitelist.dm
Labels: Oversight, Bugfix

#8779 no vchat failed alert if we don't want vchat
  code/modules/vchat/vchat_client.dm
Labels: Quality of Life

#8778 Mutual Intelligibility Lore Pass
  code/modules/mob/language/generic.dm
  code/modules/mob/language/language.dm
  code/modules/mob/language/station.dm
Labels: Lore

#8792 Ports Aurora hijab sprite
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Sprites

#8784 Nudges sif's resting temperature
  code/game/turfs/unsimulated/planetary.dm
  maps/cynosure/turfs/outdoors.dm
Labels: Bugfix

#8755 Sleek Communicator
  code/game/objects/items/devices/communicator/communicator.dm
  code/modules/client/preference_setup/loadout/loadout_utility.dm
  icons/obj/device.dmi
Labels: Feature Tweak, Sprites

#8780 Basic Uniform Polish: Civilian
  code/datums/outfits/jobs/civilian.dm
  code/datums/supplypacks/costumes.dm
  code/game/jobs/job/civilian.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/spacesuits/spacesuits.dm
  code/modules/clothing/spacesuits/syndi.dm
  code/modules/clothing/spacesuits/void/void.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/head.dmi
  icons/mob/spacesuit.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/mob/uniform_1.dmi
  icons/mob/uniform_rolled_down.dmi
  icons/mob/uniform_sleeves_rolled.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/spacesuits.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/clothing/uniforms_1.dmi
  maps/cynosure/job/outfits.dm
Labels: Sprites

#8789 Enforcing no sleep during mob/Life(), tick checking AStar().
  code/defines/procs/AStar.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/blob2/blobs/base_blob.dm
  code/modules/blob2/overmind/powers.dm
  code/modules/emotes/emote_mob.dm
  code/modules/mob/living/bot/bot.dm
  code/modules/mob/living/simple_mob/life.dm
  code/modules/mob/living/simple_mob/subtypes/animal/pets/dog.dm
  code/modules/mob/mob.dm
Labels: Bugfix

#8785 size traits don't have slowdowns
  code/modules/mob/_modifiers/traits.dm
Labels: Feature Tweak

#8790 unuses DS2NEARESTTICK, fixes a diagonal snafu
  code/modules/mob/living/living_movement.dm
  code/modules/mob/mob_movement.dm
Labels: Bugfix, Quality of Life

#8791 match server byond version for CI
  _build_dependencies.sh
Labels: Repo

#8796 Balloon Expansion (Inflation?)
  code/datums/uplink/badassery.dm
  code/game/objects/items/latexballoon.dm
  code/game/objects/items/toys/toys.dm
  code/game/objects/items/weapons/tanks/tanks.dm
  code/game/objects/random/mapping.dm
  code/game/objects/random/misc.dm
  code/modules/client/preference_setup/loadout/gear_tweaks.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/mining/abandonedcrates.dm
  code/modules/random_map/drop/drop_types.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/lefthand_gloves.dmi
  icons/mob/items/righthand.dmi
  icons/mob/items/righthand_gloves.dmi
  icons/obj/toy.dmi
  icons/obj/weapons.dmi
  maps/northern_star/polaris-1.dmm
  maps/southern_cross/southern_cross-1.dmm
  polaris.dme
Labels: Feature, Sprites

#8797 Halloween Costumes
  code/datums/outfits/costumes/halloween.dm
  code/datums/outfits/horror_killers.dm
  code/datums/outfits/jobs/misc.dm
  code/datums/outfits/misc.dm
  code/datums/outfits/pirates.dm
  code/datums/supplypacks/costumes.dm
  code/datums/supplypacks/misc.dm
  code/game/jobs/job/silicon.dm
  code/game/machinery/computer/arcade.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/random/mapping.dm
  code/game/objects/structures/crates_lockers/closets/gimmick.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/antagonist/outsider/raider.dm
  code/modules/awaymissions/corpse.dm
  code/modules/client/preference_setup/loadout/loadout_head.dm
  code/modules/client/preference_setup/loadout/loadout_mask.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/chameleon.dm
  code/modules/clothing/head/collectable.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/costume.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/food/kitchen/cooking_machines/container.dm
  code/modules/food/recipes_grill.dm
  code/modules/materials/materials/organic/cloth.dm
  code/modules/materials/materials/organic/leather.dm
  code/modules/materials/materials/plastic.dm
  code/modules/mining/abandonedcrates.dm
  code/modules/mob/dead/corpse.dm
  code/modules/spells/spellbook.dm
  code/modules/spells/targeted/equip/horsemask.dm
  icons/mob/head.dmi
  icons/mob/items/lefthand_suits.dmi
  icons/mob/items/righthand_suits.dmi
  icons/mob/mask.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  maps/cynosure/cynosure-6.dmm
  maps/cynosure/submaps/16x11/OldDorms.dmm
  maps/northern_star/polaris-1.dmm
  maps/northern_star/polaris-2.dmm
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-6.dmm
  maps/submaps/surface_submaps/plains/house1.dmm
  maps/submaps/surface_submaps/plains/house1_arealess.dmm
  maps/submaps/surface_submaps/plains/methlab.dmm
  maps/submaps/surface_submaps/plains/priderock.dmm
  maps/submaps/surface_submaps/wilderness/chasm.dmm
  polaris.dme
Labels: Feature

#8799 Adds flasks to the forensic belt allowed items
  code/defines/procs/AStar.dm
  code/game/objects/items/weapons/storage/belt.dm
Labels: Feature

#8775 On-mob item examination
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Feature

#8776 Snowmobiles and Quadhancements V2
  code/datums/looping_sounds/machinery_sounds.dm
  code/datums/riding.dm
  code/modules/research/mechfab_designs.dm
  code/modules/vehicles/cargo_train.dm
  code/modules/vehicles/construction.dm
  code/modules/vehicles/quad.dm
  code/modules/vehicles/snowmobile.dm
  code/modules/vehicles/train.dm
  code/modules/vehicles/vehicle.dm
  icons/obj/vehicles.dmi
  maps/cynosure/cynosure-2.dmm
  polaris.dme
  sound/machines/vehicle/engine_end.ogg
  sound/machines/vehicle/engine_mid.ogg
  sound/machines/vehicle/engine_start.ogg
  sound/machines/vehicle/ignition.ogg
Labels: Feature

#8801 Added Slow Mover traits
  code/modules/client/preference_setup/traits/trait_defines.dm
  code/modules/mob/_modifiers/traits.dm
Labels: Feature Tweak
