Repository PolarisSS13/Polaris, pull requests merged in 2022-12, with the labels that each got.

#8849 rejuvenate strips ghost vision from mobs
  code/modules/mob/living/living.dm
Labels: Bugfix

#8835 The dead can't rename food.
  code/modules/food/food.dm
Labels: Oversight, Bugfix

#8840 fixed assorted ore bag/box bugs and perf issues
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/items/weapons/storage/bags/ore.dm
  code/modules/mining/ore_box.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/drones/mining_drone.dm
  polaris.dme
Labels: Refactor, Bugfix, Feature Tweak, Quality of Life

#8844 markings expansion
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_races/markings.dmi
Labels: Feature Tweak, Sprites

#8861 Unfuck skrell headtail gradients
  icons/mob/human_face_m.dmi
Labels: Bugfix, Sprites

#8862 small lil pair of bugfixes
  code/modules/emotes/emote_mob.dm
  tgui/packages/tgui/interfaces/BodyScanner.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Bugfix
