Repository PolarisSS13/Polaris, pull requests merged in 2022-01, with the labels that each got.

#8365 Fixes Cynosure Shuttle Issue
  code/modules/multiz/turf.dm
Labels: Priority: High, Bugfix

#8366 Small shuttle fixes
  maps/cynosure/cynosure-2.dmm
  maps/cynosure/cynosure-3.dmm
  maps/cynosure/cynosure_shuttles.dm
Labels: Map Change / Issue, Map: Cynosure

#8371 Fixes literally everything dismantling walls
  code/game/turfs/simulated/wall_attacks.dm
Labels: Oversight, Priority: CRITICAL, Bugfix

#8370 Mech and Locker Sounds
  code/game/mecha/equipment/weapons/ballistic/automatic.dm
  code/game/mecha/equipment/weapons/ballistic/mortar.dm
  code/game/mecha/equipment/weapons/ballistic/shotgun.dm
  code/game/mecha/mecha.dm
  code/game/objects/items/poi_items.dm
  code/game/objects/structures/crates_lockers/__closets.dm
  code/game/objects/structures/crates_lockers/closets/coffin.dm
  code/game/objects/structures/crates_lockers/closets/secure/bar.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/personal.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/hivebot/ranged_damage.dm
  code/modules/projectiles/projectile/arc.dm
  code/modules/projectiles/projectile/energy.dm
  sound/machines/closet/closet_close.ogg
  sound/machines/closet/closet_open.ogg
  sound/machines/closet/closet_wood_close.ogg
  sound/machines/closet/closet_wood_open.ogg
  sound/machines/closet/crate_close.ogg
  sound/machines/closet/crate_open.ogg
  sound/mecha/mech_enter.ogg
  sound/mecha/mech_exit.ogg
  sound/weapons/Gunshot_phase.ogg
  sound/weapons/mech_autocannon.ogg
  sound/weapons/mech_mortar.ogg
  sound/weapons/mech_shotgun.ogg
Labels: Sound Change

#8367 Adds config-enabled whitelist for sprite accessories
  code/_helpers/global_lists.dm
  code/controllers/configuration.dm
  code/game/jobs/whitelist.dm
  code/modules/client/preference_setup/general/03_body.dm
  code/modules/mob/new_player/sprite_accessories.dm
  code/modules/mob/new_player/sprite_accessories_ear.dm
  code/modules/mob/new_player/sprite_accessories_tail.dm
  code/modules/mob/new_player/sprite_accessories_taur.dm
  code/modules/mob/new_player/sprite_accessories_wing.dm
  config/example/config.txt
  config/example/genemodwhitelist.txt
Labels: Feature, Lore, Project, Map: Cynosure

#8372 A KNIFE!
  code/game/objects/items/weapons/material/knives.dm
  code/game/objects/items/weapons/material/misc.dm
Labels: Oversight

#8373 Adds sanity checks to ssai ai_holders
  code/modules/ai/ai_holder.dm
Labels: Bugfix

#8376 Genemod whitelist fix
  code/modules/mob/new_player/sprite_accessories_taur.dm
Labels: Oversight

#8380 Readd sc dmm 1
  maps/southern_cross/southern_cross-1.dmm
Labels: Oversight

#8378 Fixes assorted mining toolspeed uses
  code/game/objects/structures/simple_doors.dm
  code/game/turfs/simulated/wall_attacks.dm
  code/modules/mining/mine_items.dm
  code/modules/mining/mine_turfs.dm
  code/modules/xenoarcheaology/boulder.dm
  code/modules/xenoarcheaology/tools/tools_pickaxe.dm
Labels: Bugfix

#8382 Cynosure map fixes round 8
  code/_helpers/turfs.dm
  maps/cynosure/cynosure-2.dmm
  maps/cynosure/cynosure-3.dmm
  maps/cynosure/cynosure-6.dmm
  maps/cynosure/cynosure-7.dmm
  maps/cynosure/cynosure.dm
  maps/cynosure/cynosure_defines.dm
  maps/cynosure/cynosure_shuttles.dm
  maps/cynosure/datums/random_map.dm
  maps/cynosure/submaps/16x11/OldDorms.dmm
  maps/cynosure/submaps/7x7/FightClub.dmm
  maps/cynosure/submaps/8x9/MouseHouse.dmm
  maps/cynosure/submaps/8x9/ReptileRoom.dmm
Labels: Project, Map: Cynosure

#8381 Properly filters the genemod whitelisting
  code/modules/mob/new_player/sprite_accessories_ear.dm
  code/modules/mob/new_player/sprite_accessories_extra.dm
  code/modules/mob/new_player/sprite_accessories_tail.dm
  code/modules/mob/new_player/sprite_accessories_taur.dm
  icons/mob/human_races/sprite_accessories/ears.dmi
  icons/mob/human_races/sprite_accessories/tails.dmi
  icons/mob/human_races/sprite_accessories/taurs.dmi
Labels: Feature Tweak, Lore, Map: Cynosure

#8383 Adds antag subsystem to handle antag datum init
  code/__defines/subsystems.dm
  code/controllers/master_controller.dm
  code/controllers/subsystems/antag.dm
  code/controllers/subsystems/vote.dm
  code/controllers/verbs.dm
  code/datums/mind.dm
  code/game/antagonist/_antagonist_setup.dm
  code/game/gamemodes/calamity/calamity.dm
  code/game/gamemodes/game_mode.dm
  code/game/objects/items/antag_spawners.dm
  code/game/objects/items/devices/uplink_random_lists.dm
  code/game/objects/structures/ghost_pods/human.dm
  code/modules/admin/DB ban/functions.dm
  code/modules/admin/admin.dm
  code/modules/admin/player_panel.dm
  code/modules/admin/topic.dm
  code/modules/antagonist/alien/borer.dm
  code/modules/antagonist/alien/xenomorph.dm
  code/modules/antagonist/antagonist.dm
  code/modules/antagonist/antagonist_add.dm
  code/modules/antagonist/antagonist_create.dm
  code/modules/antagonist/antagonist_equip.dm
  code/modules/antagonist/antagonist_factions.dm
  code/modules/antagonist/antagonist_helpers.dm
  code/modules/antagonist/antagonist_objectives.dm
  code/modules/antagonist/antagonist_panel.dm
  code/modules/antagonist/antagonist_place.dm
  code/modules/antagonist/antagonist_print.dm
  code/modules/antagonist/antagonist_update.dm
  code/modules/antagonist/mutiny/loyalist.dm
  code/modules/antagonist/mutiny/mutineer.dm
  code/modules/antagonist/outsider/commando.dm
  code/modules/antagonist/outsider/deathsquad.dm
  code/modules/antagonist/outsider/ert.dm
  code/modules/antagonist/outsider/mercenary.dm
  code/modules/antagonist/outsider/ninja.dm
  code/modules/antagonist/outsider/raider.dm
  code/modules/antagonist/outsider/technomancer.dm
  code/modules/antagonist/outsider/trader.dm
  code/modules/antagonist/outsider/wizard.dm
  code/modules/antagonist/station/changeling.dm
  code/modules/antagonist/station/cultist.dm
  code/modules/antagonist/station/highlander.dm
  code/modules/antagonist/station/infiltrator.dm
  code/modules/antagonist/station/loyalist.dm
  code/modules/antagonist/station/renegade.dm
  code/modules/antagonist/station/revolutionary.dm
  code/modules/antagonist/station/rogue_ai.dm
  code/modules/antagonist/station/stowaway.dm
  code/modules/antagonist/station/thug.dm
  code/modules/antagonist/station/traitor.dm
  code/modules/client/preferences.dm
  code/modules/events/random_antagonist.dm
  code/modules/gamemaster/event2/events/everyone/random_antag.dm
  code/modules/random_map/drop/droppod.dm
  polaris.dme
Labels: Bugfix

#8385 Adds caseless BB rounds for common gun types
  code/modules/projectiles/ammunition/rounds.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullets.dm
Labels: Feature, Staff Request
