Repository PolarisSS13/Polaris, pull requests merged in 2022-08, with the labels that each got.

#8666 Xenoarchaeology sprites n sounds
  code/modules/food/kitchen/microwave.dm
  code/modules/research/designs/mining_toys.dm
  code/modules/xenoarcheaology/tools/suspension_generator.dm
  code/modules/xenoarcheaology/tools/tools.dm
  code/modules/xenoarcheaology/tools/tools_pickaxe.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/storage.dmi
  icons/obj/xenoarchaeology.dmi
  sound/machines/boop1.ogg
  sound/machines/boop2.ogg
  sound/machines/quiet_beep.ogg
  sound/machines/triple_beep.ogg
Labels: Sprites

#8670 Archery Tweaks
  code/datums/components/crafting/recipes.dm
  code/datums/components/crafting/recipes/archery.dm
  code/game/objects/items/weapons/material/misc.dm
  code/game/objects/items/weapons/material/thrown.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/modules/materials/sheets/_sheets.dm
  code/modules/projectiles/guns/launcher/bows.dm
  code/modules/projectiles/guns/launcher/crossbow.dm
  icons/obj/weapons.dmi
  polaris.dme
Labels: Feature Tweak

#8673 Antag Uplink Medical Adjustments
  code/datums/uplink/medical.dm
Labels: Feature Tweak

#8675 Removes eject from the mecha radial.
  code/game/mecha/mecha.dm
Labels: Feature Tweak

#8672 Cellcharge artifact effect iterates over shorter lists
  code/modules/xenoarcheaology/effects/cellcharge.dm
Labels: Bugfix

#8676 Added GPS to crashed pod spawns, commented out spider pod.
  maps/cynosure/cynosure_jobs.dm
Labels: Feature

#8677 Fixed ghost pod event not spawning ghost pods
  code/modules/gamemaster/event2/events/ghost_pod_spawner.dm
  code/modules/gamemaster/event2/events/security/stowaway.dm
  code/modules/gamemaster/event2/events/security/swarm_boarder.dm
  maps/cynosure/cynosure_defines.dm
  maps/~map_system/maps.dm
Labels: Bugfix

#8678 Uplink Armor Point Adjustments
  code/datums/uplink/armor.dm
Labels: Feature Tweak

#8679 Adding foraging, burrowing and scavenging interactions for animals + added drakes
  code/game/gamemodes/technomancer/spells/control.dm
  code/game/objects/items.dm
  code/game/objects/random/mob.dm
  code/game/objects/structures/animal_den.dm
  code/game/objects/structures/flora/flora.dm
  code/game/objects/structures/flora/trees.dm
  code/game/turfs/simulated/outdoors/outdoors.dm
  code/modules/ai/interfaces.dm
  code/modules/emotes/definitions/_mob.dm
  code/modules/emotes/definitions/audible.dm
  code/modules/emotes/emote_define.dm
  code/modules/food/food/snacks.dm
  code/modules/mob/language/monkey.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species/species_attack.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_mob/combat.dm
  code/modules/mob/living/simple_mob/defense.dm
  code/modules/mob/living/simple_mob/harvesting.dm
  code/modules/mob/living/simple_mob/on_click.dm
  code/modules/mob/living/simple_mob/simple_mob.dm
  code/modules/mob/living/simple_mob/subtypes/animal/animal.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/webslinger.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka_ai.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/kururak.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/siffet.dm
  code/modules/organs/organ.dm
  code/modules/projectiles/projectile/bullets.dm
  icons/mob/64x32.dmi
  icons/obj/structures/den.dmi
  maps/southern_cross/events/wildlife_encounter.dm
  maps/submaps/surface_submaps/wilderness/grafadreka_den.dmm
  maps/submaps/surface_submaps/wilderness/wilderness.dm
  maps/submaps/surface_submaps/wilderness/wilderness_areas.dm
  polaris.dme
  sound/effects/drakehowl_close.ogg
  sound/effects/drakehowl_far.ogg
Labels: Feature

#8686 Adjustments to Uplink Tools cost
  code/datums/uplink/tools.dm
Labels: Feature Tweak

#8684 Removes irrelevant gluttony regen code segment.
  code/modules/mob/_modifiers/unholy.dm
Labels: Bugfix

#8683 Allows public login to public fax machine
  maps/cynosure/cynosure-2.dmm
Labels: Bugfix

#8681 Drake tweaks/enhancements.
  code/__defines/mobs.dm
  code/game/machinery/doors/door.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/effects/spiders.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/structures/animal_den.dm
  code/game/objects/structures/flora/flora.dm
  code/game/turfs/flooring/flooring_premade.dm
  code/game/turfs/simulated.dm
  code/game/turfs/simulated/outdoors/snow.dm
  code/modules/ai/ai_holder_communication.dm
  code/modules/food/food/snacks.dm
  code/modules/hydroponics/grown_sif.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_mob/defense.dm
  code/modules/mob/living/simple_mob/harvesting.dm
  code/modules/mob/living/simple_mob/simple_mob.dm
  code/modules/mob/living/simple_mob/subtypes/animal/animal.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka_ai.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/kururak.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/sif.dm
  code/modules/organs/organ.dm
  code/modules/xenoarcheaology/effects/cellcharge.dm
  icons/turf/outdoors.dmi
Labels: Feature, Bugfix, Feature Tweak

#8626 Adds singularity artifact effect
  code/modules/xenoarcheaology/effects/gravitational_waves.dm
Labels: Feature

#8688 More drake stuff.
  code/__defines/misc.dm
  code/controllers/subsystems/ticker.dm
  code/datums/datacore.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job_controller.dm
  code/game/objects/items/weapons/storage/internal.dm
  code/game/objects/random/mob.dm
  code/game/objects/structures/animal_den.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/clothing/suits/storage.dm
  code/modules/mob/living/simple_mob/subtypes/animal/animal.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka_ai.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/sif.dm
  code/modules/tgui/modules/appearance_changer.dm
  icons/mob/64x32.dmi
  icons/mob/drake_adult.dmi
  icons/mob/drake_baby.dmi
  maps/cynosure/cynosure_jobs.dm
  maps/cynosure/job/outfits.dm
  maps/southern_cross/events/wildlife_encounter.dm
  maps/submaps/surface_submaps/wilderness/grafadreka_den.dmm
Labels: Feature, Feature Tweak, Sprites

#8694 A couple ghost fixes
  code/modules/mob/dead/observer/observer.dm
Labels: Bugfix
