Repository PolarisSS13/Polaris, pull requests merged in 2022-04, with the labels that each got.

#8477 Fixes missing colouration of station holomap
  code/modules/holomap/holomap_datum.dm
  code/modules/holomap/station_holomap.dm
  icons/effects/64x64.dmi
  maps/cynosure/cynosure_areas.dm
Labels: Bugfix, Quality of Life

#8465 Corrects spelling of a Zaddat shroud
  code/modules/clothing/spacesuits/void/zaddat.dm
Labels: Spellcheck

#8470 Some admin log "usr" fixes
  code/controllers/subsystems/webhooks.dm
  code/datums/mind.dm
  code/game/gamemodes/changeling/powers/electric_lockpick.dm
  code/game/gamemodes/cult/construct_spells.dm
  code/game/gamemodes/cult/ritual.dm
  code/game/gamemodes/cult/runes.dm
  code/game/gamemodes/technomancer/spells/resurrect.dm
  code/game/gamemodes/technomancer/spells/spawner/spawner.dm
  code/game/gamemodes/technomancer/spells/summon/summon.dm
  code/game/objects/items/devices/defib.dm
  code/game/objects/items/weapons/AI_modules.dm
  code/game/objects/items/weapons/id cards/cards.dm
  code/game/objects/structures/ghost_pods/human.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_attack_log.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/change_appearance.dm
  code/modules/admin/verbs/debug.dm
  code/modules/assembly/signaler.dm
  code/modules/events/event_manager.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/silicon/pai/admin.dm
  code/modules/projectiles/targeting/targeting_overlay.dm
  code/modules/shuttles/shuttle_emergency.dm
  code/modules/tgui/modules/law_manager.dm
Labels: Bugfix

#8457 More Map Mods March
  maps/cynosure/cynosure-1.dmm
  maps/cynosure/cynosure-2.dmm
  maps/cynosure/cynosure-3.dmm
Labels: Bugfix, Quality of Life, Map: Cynosure

#8480 Gives mech autocannon projectiles their own entry with unique sprite and lighting
  code/game/mecha/equipment/weapons/ballistic/automatic.dm
  code/modules/projectiles/projectile/bullets.dm
  icons/obj/projectiles.dmi
Labels: Feature Tweak, Quality of Life, Sprites, Sounds

#8441 Adds Hairnets
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/modules/client/preference_setup/loadout/loadout_head.dm
  code/modules/clothing/head/jobs.dm
  icons/mob/head.dmi
  icons/mob/items/lefthand_hats.dmi
  icons/mob/items/righthand_hats.dmi
  icons/mob/species/tajaran/helmet.dmi
  icons/obj/clothing/hats.dmi
Labels: Feature Tweak, Sprites

#8429 Breathing Sounds While in Space
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species/species.dm
  sound/effects/mob_effects/suit_breathe_in.ogg
  sound/effects/mob_effects/suit_breathe_out.ogg
Labels: Feature, Sounds

#8501 Reversion to puddle
  code/game/objects/effects/chem/puddle.dm
  code/game/objects/items/weapons/tools/weldingtool.dm
  code/game/objects/structures/watercloset.dm
  code/modules/assembly/igniter.dm
  code/modules/materials/materials/plastic.dm
  code/modules/power/tesla/tesla_act.dm
  code/modules/reagents/holder/holder.dm
  code/modules/reagents/machinery/dispenser/reagent_tank.dm
  code/modules/reagents/machinery/pump.dm
  code/modules/reagents/reactions/distilling/distilling.dm
  code/modules/reagents/reactions/instant/instant.dm
  code/modules/reagents/reagents/_reagents.dm
  code/modules/reagents/reagents/core.dm
  code/modules/reagents/reagents/other.dm
  code/modules/reagents/reagents/toxins.dm
  code/modules/reagents/structures/geyser.dm
  icons/effects/chempuddle.dmi
  icons/obj/machines/reagent.dmi
  polaris.dme
Labels: Priority: High, Bugfix

#8422 Planetary Meteors
  code/__defines/map.dm
  code/__defines/xenoarcheaology.dm
  code/game/gamemodes/meteor/meteors.dm
  code/modules/blob2/blobs/core.dm
  code/modules/blob2/overmind/types/barnacle.dm
  code/modules/events/meteors.dm
  code/modules/mining/mine_turfs.dm
  code/modules/projectiles/projectile/pellets.dm
  code/modules/random_map/meteor/meteor.dm
  code/modules/xenoarcheaology/finds/find_spawning.dm
  code/modules/xenoarcheaology/finds/finds_defines.dm
  icons/obj/meteor.dmi
  icons/turf/flooring/asteroid.dmi
  icons/turf/flooring/decals.dmi
  icons/turf/walls.dmi
  maps/cynosure/cynosure_defines.dm
  maps/~map_system/maps.dm
  polaris.dme
Labels: Feature, Needs Announcement

#8431 Allergen CE Conversion
  code/__defines/chemistry.dm
  code/__defines/species_languages.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/reagents/reagents/_reagents.dm
  code/modules/reagents/reagents/dispenser.dm
  code/modules/reagents/reagents/medicine.dm
Labels: Refactor, Feature Tweak

#8476 default client fps is 40 instead of match-server
  code/modules/client/preferences.dm
Labels: Quality of Life

#8481 adds client helpers, fixes an oversight from 8451
  code/_helpers/client.dm
  code/datums/browser.dm
  code/modules/admin/topic.dm
  code/modules/paperwork/paper.dm
  polaris.dme
Labels: Bugfix

#8486 cleans up atom/movable/Destroy + adds walk(src, 0)
  code/datums/orbit.dm
  code/game/atoms_movable.dm
  code/game/gamemodes/events/clang.dm
  code/game/gamemodes/events/dust.dm
  code/game/objects/buckling.dm
  code/game/objects/effects/chem/chemsmoke.dm
  code/game/objects/effects/spiders.dm
  code/game/objects/items/weapons/grenades/flashbang.dm
  code/modules/lighting/lighting_atom.dm
Labels: Bugfix

#8488 cynosure pilots get explorer headsets
  maps/cynosure/items/encryptionkey_cyno.dm
  maps/cynosure/items/headset_cyno.dm
  maps/cynosure/job/outfits.dm
  maps/cynosure/structures/closets/misc.dm
Labels: Bugfix, Quality of Life, Map: Cynosure

#8492 adds material armor crafting recipes
  code/datums/components/crafting/crafting.dm
  code/datums/components/crafting/recipes.dm
  code/game/objects/items/weapons/material/material_armor.dm
Labels: Feature Tweak

#8497 subsystem pass 1
  code/controllers/subsystem.dm
  code/controllers/subsystems/ai.dm
  code/controllers/subsystems/aifast.dm
  code/controllers/subsystems/air.dm
  code/controllers/subsystems/airflow.dm
  code/controllers/subsystems/alarm.dm
  code/controllers/subsystems/character_setup.dm
  code/controllers/subsystems/chat.dm
  code/controllers/subsystems/chemistry.dm
  code/controllers/subsystems/dcs.dm
  code/controllers/subsystems/events.dm
  code/controllers/subsystems/events2.dm
  code/controllers/subsystems/game_master.dm
  code/controllers/subsystems/garbage.dm
  code/controllers/subsystems/inactivity.dm
  code/controllers/subsystems/lighting.dm
  code/controllers/subsystems/machines.dm
  code/controllers/subsystems/mobs.dm
  code/controllers/subsystems/nanoui.dm
  code/controllers/subsystems/nightshift.dm
  code/controllers/subsystems/open_space.dm
  code/controllers/subsystems/orbits.dm
  code/controllers/subsystems/overlays.dm
  code/controllers/subsystems/planets.dm
  code/controllers/subsystems/processing/fastprocess.dm
  code/controllers/subsystems/processing/obj.dm
  code/controllers/subsystems/processing/processing.dm
  code/controllers/subsystems/processing/projectiles.dm
  code/controllers/subsystems/processing/turfs.dm
  code/controllers/subsystems/radiation.dm
  code/controllers/subsystems/shuttles.dm
  code/controllers/subsystems/sun.dm
  code/controllers/subsystems/supply.dm
  code/controllers/subsystems/tgui.dm
  code/controllers/subsystems/ticker.dm
  code/controllers/subsystems/time_track.dm
  code/controllers/subsystems/timer.dm
  code/controllers/subsystems/vote.dm
  code/modules/tgui/tgui_window.dm
Labels: Refactor

#8508 Removes highlander
  code/modules/admin/secrets/fun_secrets/only_one.dm
  code/modules/antagonist/station/highlander.dm
  polaris.dme
Labels: Bugfix

#8507 Colors hud alerts according to their master object's color.
  code/_onclick/hud/alert.dm
Labels: Bugfix

#8509 Another round of map tweaks/fixes
  maps/cynosure/cynosure-1.dmm
  maps/cynosure/cynosure-2.dmm
  maps/cynosure/cynosure-3.dmm
  maps/cynosure/cynosure-4.dmm
  maps/cynosure/cynosure-6.dmm
Labels: Map Change / Issue, Bugfix, Quality of Life, Map: Cynosure

#8463 Ports Vaurca autohiss from Aurora to Zaddat
  code/modules/mob/living/autohiss.dm
Labels: Feature Tweak, Spellcheck

#8494 Fixes runtime with turrets and viscerators
  code/modules/mob/living/simple_mob/subtypes/mechanical/viscerator.dm
Labels: Bugfix

#8506 Removes ERT Rangers items from loadout
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/under/miscellaneous.dm
Labels: Bugfix

#8514 replace the crazy global vars decl, hide vchatdb
  code/controllers/globals.dm
  code/modules/admin/view_variables/view_variables_global.dm
Labels: Refactor

#8505 Spiderlings die if they have 0 health
  code/game/objects/effects/spiders.dm
Labels: Bugfix

#8516 Station's Message Monitor Functions Again
  code/game/machinery/computer/message.dm
Labels: Bugfix

#8504 C4 still explodes if the turf its placed upon changes
  code/datums/wires/explosive.dm
  code/game/objects/items/weapons/explosives.dm
  code/modules/power/cells/esoteric_cells.dm
Labels: Bugfix

#8510 human/get_visible_gender applies user perspective
  code/__defines/mobs.dm
  code/game/atoms.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Bugfix, Quality of Life

#8513 TGMC Ammo HUD Port
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/screen_objects.dm
  code/game/objects/items/weapons/grenades/explosive.dm
  code/game/objects/items/weapons/grenades/grenade.dm
  code/game/objects/items/weapons/grenades/smokebomb.dm
  code/modules/power/cell.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/energy.dm
  code/modules/projectiles/projectile/explosive.dm
  code/modules/projectiles/projectile/magnetic.dm
  code/modules/projectiles/projectile/special.dm
  icons/mob/screen_ammo.dmi
Labels: Feature, Port, Sprites

#8517 improved fire loop behavior of SSai & SSaifast
  code/__defines/ai.dm
  code/controllers/subsystems/ai.dm
  code/controllers/subsystems/aifast.dm
  code/modules/ai/ai_holder.dm
  polaris.dme
Labels: Refactor

#8519 Fixes 6 year old bug with icon filepaths being override in update_icon
  code/modules/mining/mine_turfs.dm
Labels: Bugfix

#8533 Removes Teshari
  code/game/jobs/job/captain.dm
Labels: Bugfix

#8532 Clothing fixes + Pocky fix
  code/game/objects/items/weapons/chewables.dm
  code/modules/client/preference_setup/loadout/loadout_gloves.dm
  code/modules/clothing/gloves/color.dm
  code/modules/clothing/suits/solgov.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/reagents/reagents/food_drinks.dm
  icons/mob/hands.dmi
  icons/obj/clothing/masks.dmi
Labels: Bugfix, Sprites

#8525 Replaces basically every bag and briefcase sprite, some new bag types.
  code/_helpers/global_lists.dm
  code/datums/outfits/jobs/civilian.dm
  code/datums/outfits/jobs/medical.dm
  code/datums/outfits/jobs/science.dm
  code/datums/outfits/jobs/security.dm
  code/datums/outfits/outfit.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/storage/briefcase.dm
  code/modules/antagonist/outsider/mercenary.dm
  code/modules/antagonist/outsider/wizard.dm
  code/modules/client/preference_setup/general/04_equipment.dm
  code/modules/mob/new_player/preferences_setup.dm
  icons/mob/back.dmi
  icons/mob/items/lefthand_storage.dmi
  icons/mob/items/righthand_storage.dmi
  icons/obj/clothing/backpack.dmi
  icons/obj/device.dmi
  icons/obj/storage.dmi
Labels: Feature Tweak, Sprites

#8522 More Nicer Chairs
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/modules/materials/materials/metals/steel.dm
  code/modules/materials/materials/organic/leather.dm
  icons/obj/furniture.dmi
Labels: Feature Tweak, Sprites

#8520 New holobadges, holsters, and sprites
  code/modules/client/preference_setup/loadout/loadout_accessories.dm
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/clothing/under/accessories/badges.dm
  code/modules/clothing/under/accessories/holster.dm
  icons/mob/ties.dmi
  icons/obj/clothing/ties.dmi
Labels: Feature Tweak, Sprites

#8523 More general bureaucracy sprites/additions
  code/modules/paperwork/pen.dm
  code/modules/paperwork/photocopier.dm
  code/modules/paperwork/stamps.dm
  icons/obj/bureaucracy.dmi
  icons/obj/library.dmi
  icons/obj/papershredder.dmi
Labels: Feature Tweak, Sprites

#8524 Adds Preference for Graffiti Engraving
  code/game/turfs/simulated/floor_attackby.dm
  code/game/turfs/simulated/wall_attacks.dm
  code/modules/client/preference_setup/global/setting_datums.dm
  code/modules/client/preferences_toggle_procs.dm
Labels: Feature Tweak, Quality of Life

#8527 Big Pharma's Blessing: Snorting Mechanics
  code/__defines/chemistry.dm
  code/game/gamemodes/newobjective.dm
  code/game/objects/items/contraband.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/random/unidentified/medicine.dm
  code/modules/food/food/snacks.dm
  code/modules/food/food/thecake.dm
  code/modules/hydroponics/grown.dm
  code/modules/hydroponics/seedtypes/ambrosia.dm
  code/modules/hydroponics/seedtypes/mushrooms.dm
  code/modules/library/hardcode_library/fiction/PortedBooks.dm
  code/modules/mob/living/carbon/human/MedicalSideEffects.dm
  code/modules/mob/living/carbon/human/chem_side_effects.dm
  code/modules/reagents/reactions/instant/instant.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/reagents/reagent_containers/unidentified_hypospray.dm
  code/modules/reagents/reagents/drugs.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/reagents/toxins.dm
  code/modules/virus2/effect.dm
  code/modules/xenobio2/_xeno_setup.dm
  icons/obj/chemical.dmi
  polaris.dme
  sound/effects/chop.ogg
  sound/effects/snort.ogg
Labels: Feature, Feature Tweak, Sprites, Sounds

#8502 Historic weapon expansion
  code/__defines/crafting.dm
  code/datums/components/crafting/recipes.dm
  code/game/objects/items/weapons/material/swords.dm
  code/game/objects/items/weapons/material/twohanded.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/modules/projectiles/guns/launcher/bows.dm
  icons/mob/back.dmi
  icons/mob/belt.dmi
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/lefthand_material.dmi
  icons/mob/items/righthand_guns.dmi
  icons/mob/items/righthand_material.dmi
  icons/mob/species/teshari/back.dmi
  icons/obj/storage.dmi
  icons/obj/weapons.dmi
  polaris.dme
Labels: Input: Staff, Feature Tweak, Sprites

#8521 Skathari buff & AI bugfix
  code/game/objects/effects/overlays.dm
  code/modules/ai/ai_holder_combat_unseen.dm
  code/modules/ai/ai_holder_subtypes/xeno_alien_ai.dm
  code/modules/ai/ai_holder_targeting.dm
  code/modules/mob/living/simple_mob/subtypes/animal/space/alien.dm
  polaris.dme
Labels: Feature, Bugfix, Feature Tweak

#8550 Historic Weapons Expansion
  code/__defines/crafting.dm
  code/datums/components/crafting/recipes.dm
  code/game/objects/items/weapons/material/swords.dm
  code/game/objects/items/weapons/material/twohanded.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/modules/projectiles/guns/launcher/bows.dm
  icons/mob/back.dmi
  icons/mob/belt.dmi
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/lefthand_material.dmi
  icons/mob/items/righthand_guns.dmi
  icons/mob/items/righthand_material.dmi
  icons/mob/species/teshari/back.dmi
  icons/obj/storage.dmi
  icons/obj/weapons.dmi
  polaris.dme
Labels: Feature, Sprites

#8552 Adds BB Magazines
  code/datums/uplink/ammunition.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/ammunition/rounds.dm
Labels: Feature

#8551 Prevents merging PRs that have some DNM labels.
  .github/workflows/enforce_lables.yml
Labels: Bugfix

#8409 HE pipe turf interaction
  code/ATMOSPHERICS/datum_pipeline.dm
  code/ATMOSPHERICS/pipes/he_pipes.dm
  code/game/turfs/simulated.dm
  code/game/turfs/simulated/water.dm
Labels: Feature Tweak

#8562 Poncho Custom Item compatibility
  code/game/objects/items/paintkit.dm
  code/modules/clothing/under/accessories/clothing.dm
Labels: Feature Tweak

#8559 Patches runtime when update_icon() is called without a user on hats
  code/modules/clothing/clothing.dm
Labels: Bugfix

#8557 New Rollerbeds... Again!
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/rollerbed.dmi
Labels: Feature Tweak, Sprites

#8563 Readds SA_ANIMAL vulnerability to phase projectiles
  code/modules/projectiles/projectile/energy.dm
Labels: Oversight, Bugfix

#8570 Fixes ALL random tech components having a chance of being anomalous
  code/game/objects/random/anomalous.dm
Labels: Priority: High, Bugfix

#8547 fix pickweight, add pickweight_index
  code/_helpers/_lists.dm
Labels: Bugfix

#8542 avoid the most common ci runtime by preventing ai running freely during unit tests
  code/controllers/subsystems/ai.dm
  code/controllers/subsystems/aifast.dm
Labels: Bugfix, Quality of Life, Mob AI Issue

#8518 improved fire loop behavior of SSalarm
  code/__defines/MC.dm
  code/controllers/controller.dm
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/controllers/subsystems/air.dm
  code/controllers/subsystems/alarm.dm
  code/controllers/subsystems/antag.dm
  code/controllers/subsystems/assets.dm
  code/controllers/subsystems/atoms.dm
  code/controllers/subsystems/character_setup.dm
  code/controllers/subsystems/chat.dm
  code/controllers/subsystems/chemistry.dm
  code/controllers/subsystems/circuits.dm
  code/controllers/subsystems/events.dm
  code/controllers/subsystems/game_master.dm
  code/controllers/subsystems/garbage.dm
  code/controllers/subsystems/holomaps.dm
  code/controllers/subsystems/job.dm
  code/controllers/subsystems/lighting.dm
  code/controllers/subsystems/machines.dm
  code/controllers/subsystems/mapping.dm
  code/controllers/subsystems/nightshift.dm
  code/controllers/subsystems/open_space.dm
  code/controllers/subsystems/overlays.dm
  code/controllers/subsystems/persistence.dm
  code/controllers/subsystems/planets.dm
  code/controllers/subsystems/shuttles.dm
  code/controllers/subsystems/skybox.dm
  code/controllers/subsystems/supply.dm
  code/controllers/subsystems/tgui.dm
  code/controllers/subsystems/ticker.dm
  code/controllers/subsystems/timer.dm
  code/controllers/subsystems/webhooks.dm
  code/controllers/subsystems/xenoarch.dm
  code/game/area/areas.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/camera/motion.dm
  code/game/machinery/computer/atmos_alert.dm
  code/game/machinery/fire_alarm.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/silicon/subystems.dm
  code/modules/power/apc.dm
  code/modules/tgui/modules/alarm.dm
Labels: Refactor

#8567 Replaces/Expands Upon Xenoarch Sprites
  code/modules/xenoarcheaology/boulder.dm
  code/modules/xenoarcheaology/finds/find_spawning.dm
  code/modules/xenoarcheaology/tools/artifact_analyser.dm
  code/modules/xenoarcheaology/tools/artifact_scanner.dm
  code/modules/xenoarcheaology/tools/tools.dm
  icons/obj/device.dmi
  icons/obj/mining.dmi
  icons/obj/xenoarchaeology.dmi
Labels: Sprites

#8569 Puts the elevator back on the example map
  maps/example/example-1.dmm
Labels: Oversight, Map Change / Issue

#8573 Fixes security duffle sprite
  icons/obj/clothing/backpack.dmi
Labels: Sprites

#8572 Adjusts frequency of anomalies and weights effect rarity
  code/game/objects/random/_random.dm
  code/modules/shieldgen/energy_field.dm
  code/modules/xenoarcheaology/artifacts/predefined/hungry_statue.dm
  code/modules/xenoarcheaology/effect_master.dm
  code/modules/xenoarcheaology/effects/animate_anomaly.dm
  code/modules/xenoarcheaology/effects/badfeeling.dm
  code/modules/xenoarcheaology/effects/berserk.dm
  code/modules/xenoarcheaology/effects/cannibal.dm
  code/modules/xenoarcheaology/effects/cellcharge.dm
  code/modules/xenoarcheaology/effects/celldrain.dm
  code/modules/xenoarcheaology/effects/cold.dm
  code/modules/xenoarcheaology/effects/dnaswitch.dm
  code/modules/xenoarcheaology/effects/electric_field.dm
  code/modules/xenoarcheaology/effects/emp.dm
  code/modules/xenoarcheaology/effects/feysight.dm
  code/modules/xenoarcheaology/effects/forcefield.dm
  code/modules/xenoarcheaology/effects/gaia.dm
  code/modules/xenoarcheaology/effects/gasco2.dm
  code/modules/xenoarcheaology/effects/gasnitro.dm
  code/modules/xenoarcheaology/effects/gasoxy.dm
  code/modules/xenoarcheaology/effects/gasphoron.dm
  code/modules/xenoarcheaology/effects/gassleeping.dm
  code/modules/xenoarcheaology/effects/goodfeeling.dm
  code/modules/xenoarcheaology/effects/gravitational_waves.dm
  code/modules/xenoarcheaology/effects/heal.dm
  code/modules/xenoarcheaology/effects/heat.dm
  code/modules/xenoarcheaology/effects/hurt.dm
  code/modules/xenoarcheaology/effects/poltergeist.dm
  code/modules/xenoarcheaology/effects/radiate.dm
  code/modules/xenoarcheaology/effects/resurrect.dm
  code/modules/xenoarcheaology/effects/roboheal.dm
  code/modules/xenoarcheaology/effects/robohurt.dm
  code/modules/xenoarcheaology/effects/sleepy.dm
  code/modules/xenoarcheaology/effects/stun.dm
  code/modules/xenoarcheaology/effects/teleport.dm
  code/modules/xenoarcheaology/effects/vampire.dm
Labels: Feature Tweak, Quality of Life

#8576 Slightly tweaked the mech enter and exit sounds to make them a little punchier
  sound/mecha/mech_enter.ogg
  sound/mecha/mech_exit.ogg
Labels: Sounds

#8577 Vehicle Runtime Fix
  code/modules/vehicles/cargo_train.dm
  code/modules/vehicles/vehicle.dm
Labels: Bugfix

#8579 Changeling Menu Now Shows Cost
  code/datums/managed_browsers/changelingevolution.dm
Labels: Oversight

#8580 Fixes doubled name when deathgasping
  code/modules/emotes/definitions/human.dm
Labels: Oversight

#8581 Befure
  code/modules/xenoarcheaology/effects/poltergeist.dm
Labels: Spellcheck

#8575 Drug Expansion
  code/game/objects/items/contraband.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/modules/client/preference_setup/loadout/loadout_contraband.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/hydroponics/seed_packets.dm
  code/modules/hydroponics/seedtypes/nutmeg.dm
  code/modules/lore_codex/legal_code_data/corporate_regulations.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/living_defines.dm
  code/modules/reagents/machinery/chem_master.dm
  code/modules/reagents/reactions/instant/drinks.dm
  code/modules/reagents/reactions/instant/instant.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/reagents/reagents/drugs.dm
  code/modules/reagents/reagents/medicine.dm
  icons/obj/hydroponics_products.dmi
  icons/obj/seeds.dmi
  polaris.dme
  sound/hallucinations/serithi/creepy1.ogg
  sound/hallucinations/serithi/creepy2.ogg
  sound/hallucinations/serithi/creepy3.ogg
Labels: Refactor, Feature Tweak

#8582 Atmospheric Retention Fields Port
  code/game/area/areas.dm
  code/game/machinery/atm_ret_field.dm
  code/game/machinery/frame.dm
  code/game/objects/items/weapons/circuitboards/frame.dm
  code/modules/research/designs/circuits/circuits.dm
  icons/obj/atm_fieldgen.dmi
  icons/obj/stock_parts.dmi
  maps/example/example-1.dmm
  polaris.dme
Labels: Feature, Port

#8591 Fixes AI subsystems being NOFIRE
  code/controllers/subsystems/ai.dm
  code/controllers/subsystems/aifast.dm
Labels: Oversight, Priority: High, Bugfix

#8590 fix overlay odds
  code/controllers/subsystems/overlays.dm
  code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
  code/modules/hydroponics/trays/tray_update_icons.dm
Labels: Priority: Medium, Bugfix
