Repository PolarisSS13/Polaris, pull requests merged in 2022-02, with the labels that each got.

#8364 Fixes inactive vr pods trapping occupant
  code/game/machinery/virtual_reality/vr_console.dm
Labels: Bugfix

#8379 """Halves""" chem bag slowdown
  code/game/objects/items/weapons/storage/bags.dm
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: Bugfix, Unwanted Feature Removal, Requires Staff Input

#8389 Fixes powertool sprites, fixes unfastening atmospheric devices
  code/ATMOSPHERICS/atmospherics.dm
  code/ATMOSPHERICS/components/binary_devices/passive_gate.dm
  code/ATMOSPHERICS/components/binary_devices/pump.dm
  code/ATMOSPHERICS/components/omni_devices/omni_base.dm
  code/ATMOSPHERICS/components/portables_connector.dm
  code/ATMOSPHERICS/components/trinary_devices/trinary_base.dm
  code/ATMOSPHERICS/components/tvalve.dm
  code/ATMOSPHERICS/components/unary/heat_exchanger.dm
  code/ATMOSPHERICS/components/unary/outlet_injector.dm
  code/ATMOSPHERICS/components/unary/vent_pump.dm
  code/ATMOSPHERICS/components/unary/vent_scrubber.dm
  code/ATMOSPHERICS/components/valve.dm
  code/_helpers/unsorted.dm
  code/modules/surgery/robotics.dm
  code/modules/tools/tools/crowbar.dm
  code/modules/tools/tools/screwdriver.dm
Labels: Oversight, Bugfix

#8390 Fixes runtime on server start: SSAtoms doesn't exist yet
  code/__defines/subsystems.dm
  code/_helpers/unsorted.dm
Labels: Bugfix

#8200 Cybernetic Augments and Sick Tats
  code/_helpers/global_lists.dm
  code/game/dna/dna2.dm
  code/game/objects/items/weapons/implants/implantlanguage.dm
  code/modules/client/preference_setup/loadout/loadout_cyberware.dm
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_races/markings.dmi
Labels: Sprite Change, Requires Author Response, Map: Cynosure

#8268 Reagent Geysers, Pump Fixing, Puddles.
  code/game/objects/effects/chem/puddle.dm
  code/modules/assembly/igniter.dm
  code/modules/materials/materials/plastic.dm
  code/modules/power/tesla/tesla_act.dm
  code/modules/reagents/holder/holder.dm
  code/modules/reagents/machinery/dispenser/reagent_tank.dm
  code/modules/reagents/machinery/pump.dm
  code/modules/reagents/reactions/distilling/distilling.dm
  code/modules/reagents/reactions/instant/instant.dm
  code/modules/reagents/reagents/_reagents.dm
  code/modules/reagents/reagents/core.dm
  code/modules/reagents/reagents/other.dm
  code/modules/reagents/reagents/toxins.dm
  code/modules/reagents/structures/geyser.dm
  code/modules/tools/tools/weldingtool.dm
  icons/effects/chempuddle.dmi
  icons/obj/machines/reagent.dmi
  polaris.dme
Labels: Feature, Lore, Prepare to Die

#8391 Fixes ABS reports getting sanitized by initialize()
  code/game/machinery/adv_med.dm
  code/modules/paperwork/paper.dm
Labels: Oversight

#8392 Reenables placing things by throwing at adjacent turfs on help intent
  code/modules/mob/living/living.dm
Labels: Bugfix, Quality of Life

#8393 Fixes material bats not returning init hints
  code/game/objects/items/weapons/material/bats.dm
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/food/food/cans.dm
Labels: Oversight

#8394 Ports Virgo's character setup display.
  code/modules/client/preference_setup/general/03_body.dm
  code/modules/client/preference_setup/preference_setup.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/mob/new_player/preferences_setup.dm
  interface/skin.dmf
Labels: Feature, Quality of Life

#8395 Re-adds Cynosure map and ATC fluff
  code/_helpers/time.dm
  code/global.dm
  code/modules/busy_space/air_traffic.dm
  code/modules/busy_space/organizations.dm
  code/modules/lore_codex/lore_data/important_locations.dm
  maps/cynosure/cynosure_defines.dm
Labels: Oversight, Lore

#8396 Adds event region definitions to cynosure z levels
  maps/cynosure/cynosure_defines.dm
Labels: Oversight

#8399 Fixes tail layering over dresses/cloaks
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/new_player/preferences_setup.dm
Labels: Bugfix

#8400 Less Dreary Nightshift
  code/modules/power/lighting.dm
  maps/cynosure/cynosure-1.dmm
  maps/cynosure/cynosure-2.dmm
  maps/cynosure/cynosure-3.dmm
  maps/cynosure/cynosure-4.dmm
  maps/cynosure/cynosure-6.dmm
Labels: Quality of Life

#8402 Makes bees faster.
  icons/obj/beekeeping.dmi
Labels: Sprite Change

#8403 Adds NT logo to NT plate carrier tags
  code/modules/clothing/under/accessories/armor.dm
  icons/mob/modular_armor.dmi
Labels: Sprite Change

#8405 Fixes paper missing write links
  code/modules/paperwork/paper.dm
Labels: Oversight
