Repository PolarisSS13/Polaris, pull requests merged in 2022-07, with the labels that each got.

#8660 Adds some core behavior code, uses it to fix a small bug
  code/core/atom/Transform.dm
  code/core/datum/IsAbstract.dm
  code/core/image/Transform.dm
  code/core/matrix/Transform.dm
  code/modules/client/preference_setup/traits/trait_defines.dm
  code/modules/client/preference_setup/traits/traits.dm
  polaris.dme
Labels: Refactor

#8662 Properly fixes holodeck landmark deletion
  code/modules/holodeck/HolodeckControl.dm
Labels: Bugfix

#8663 Nerfs Fennec
  code/modules/emotes/definitions/audible.dm
  code/modules/emotes/definitions/visible.dm
  code/modules/mob/holder.dm
  code/modules/mob/living/simple_mob/subtypes/animal/pets/fennec.dm
  code/modules/mob/living/simple_mob/subtypes/animal/pets/karik.dm
  polaris.dme
Labels: Lore

#8665 Generator and inflatable-box sprites
  icons/obj/power.dmi
  icons/obj/storage.dmi
Labels: Sprites

#8668 Nerfs allergic reactions (Again)
  code/modules/reagents/reagents/_reagents.dm
Labels: Bugfix
