Repository PolarisSS13/Polaris, pull requests merged in 2022-09, with the labels that each got.

#8697 Organs transfer EMPs to their contents
  code/modules/organs/organ.dm
  code/modules/organs/organ_external.dm
Labels: Bugfix

#8698 Airlock assembly naming window starts with base_name
  code/game/objects/structures/door_assembly.dm
Labels: Bugfix

#8693 Even more drake stuff.
  code/game/objects/items/devices/scanners.dm
  code/game/objects/structures/animal_den.dm
  code/modules/ai/ai_holder_targeting.dm
  code/modules/emotes/definitions/audible_whistle.dm
  code/modules/emotes/emote_define.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_mob/defense.dm
  code/modules/mob/living/simple_mob/subtypes/animal/animal.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka_ai.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka_harness.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka_trained.dm
  code/modules/mob/mob.dm
  code/modules/reagents/holder/holder.dm
  code/modules/reagents/readme.md
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/reagents/reagents/_reagents.dm
  code/modules/reagents/reagents/food_drinks.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/reagents/toxins.dm
  maps/cynosure/cynosure-2.dmm
  maps/cynosure/cynosure-3.dmm
  maps/cynosure/cynosure-7.dmm
  maps/cynosure/cynosure_jobs.dm
  maps/northern_star/polaris-5.dmm
  maps/overmap/bearcat/bearcat.dmm
  maps/submaps/surface_submaps/plains/oldhotel.dmm
  polaris.dme
Labels: Feature, Refactor, Feature Tweak

#8685 cellcharge DoEffectAura sends a message per robot (and friends)
  code/modules/xenoarcheaology/effect.dm
  code/modules/xenoarcheaology/effects/animate_anomaly.dm
  code/modules/xenoarcheaology/effects/badfeeling.dm
  code/modules/xenoarcheaology/effects/berserk.dm
  code/modules/xenoarcheaology/effects/cannibal.dm
  code/modules/xenoarcheaology/effects/cellcharge.dm
  code/modules/xenoarcheaology/effects/celldrain.dm
  code/modules/xenoarcheaology/effects/cold.dm
  code/modules/xenoarcheaology/effects/electric_field.dm
  code/modules/xenoarcheaology/effects/emp.dm
  code/modules/xenoarcheaology/effects/feysight.dm
  code/modules/xenoarcheaology/effects/forcefield.dm
  code/modules/xenoarcheaology/effects/gaia.dm
  code/modules/xenoarcheaology/effects/gasco2.dm
  code/modules/xenoarcheaology/effects/gasnitro.dm
  code/modules/xenoarcheaology/effects/gasoxy.dm
  code/modules/xenoarcheaology/effects/gasphoron.dm
  code/modules/xenoarcheaology/effects/gassleeping.dm
  code/modules/xenoarcheaology/effects/goodfeeling.dm
  code/modules/xenoarcheaology/effects/gravitational_waves.dm
  code/modules/xenoarcheaology/effects/heal.dm
  code/modules/xenoarcheaology/effects/heat.dm
  code/modules/xenoarcheaology/effects/hurt.dm
  code/modules/xenoarcheaology/effects/poltergeist.dm
  code/modules/xenoarcheaology/effects/radiate.dm
  code/modules/xenoarcheaology/effects/resurrect.dm
  code/modules/xenoarcheaology/effects/roboheal.dm
  code/modules/xenoarcheaology/effects/robohurt.dm
  code/modules/xenoarcheaology/effects/sleepy.dm
  code/modules/xenoarcheaology/effects/stun.dm
  code/modules/xenoarcheaology/effects/teleport.dm
  code/modules/xenoarcheaology/effects/vampire.dm
Labels: Refactor, Bugfix

#8700 Sets area on plastic flaps outside of mining
  maps/cynosure/cynosure-1.dmm
Labels: Map Change / Issue, Map: Cynosure

#8695 Overhauls loadout naming and point costs
  code/modules/client/preference_setup/loadout/loadout_accessories.dm
  code/modules/client/preference_setup/loadout/loadout_eyes.dm
  code/modules/client/preference_setup/loadout/loadout_general.dm
  code/modules/client/preference_setup/loadout/loadout_gloves.dm
  code/modules/client/preference_setup/loadout/loadout_head.dm
  code/modules/client/preference_setup/loadout/loadout_mask.dm
  code/modules/client/preference_setup/loadout/loadout_shoes.dm
  code/modules/client/preference_setup/loadout/loadout_smoking.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/client/preference_setup/loadout/loadout_utility.dm
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
  maps/cynosure/loadout/loadout_suit.dm
  maps/southern_cross/loadout/loadout_suit.dm
Labels: Feature Tweak
