Repository PolarisSS13/Polaris, pull requests merged in 2023-06, with the labels that each got.

#9109 fixes bug in who verb ignoring admin info
  code/modules/client/verbs/who.dm
Labels: Oversight

#9110 All work completed by union labour.
  maps/cynosure/cynosure-2.dmm
Labels: Map: Cynosure

#9112 Corrects surgery surface logic.
  code/_helpers/unsorted.dm
Labels: Bugfix

#9111 Added sprite sheet setting for tesh hoods.
  code/modules/clothing/suits/aliens/teshari.dm
Labels: Bugfix

#9055 Rotatable stools
  code/game/objects/structures/stool_bed_chair_nest/stools.dm
Labels: Feature

#9034 Flavour Enhancement: Flavour
  code/modules/examine/descriptions/containers.dm
  code/modules/food/food/cans.dm
  code/modules/food/food/lunch.dm
  code/modules/food/food/snacks.dm
  code/modules/food/food/snacks/meat.dm
  code/modules/food/recipes_fryer.dm
  code/modules/food/recipes_grill.dm
  code/modules/food/recipes_microwave.dm
  code/modules/food/recipes_oven.dm
  code/modules/mob/living/carbon/taste.dm
  code/modules/reagents/reactions/instant/food.dm
  code/modules/reagents/reagents/food_drinks.dm
  icons/obj/food.dmi
Labels: Feature Tweak

#9118 Removes failure condition from brand intelligence.
  code/modules/gamemaster/event2/events/engineering/brand_intelligence.dm
Labels: Quality of Life

#9120 Fixes appliance typo(s)
  code/modules/food/kitchen/cooking_machines/_appliance.dm
Labels: Oversight
