Repository PolarisSS13/Polaris, pull requests merged in 2023-05, with the labels that each got.

#9044 Ports various downstream clothes
  code/game/objects/random/maintenance.dm
  code/game/objects/structures/loot_piles.dm
  code/modules/client/preference_setup/loadout/loadout_accessories.dm
  code/modules/client/preference_setup/loadout/loadout_contraband.dm
  code/modules/client/preference_setup/loadout/loadout_ears.dm
  code/modules/client/preference_setup/loadout/loadout_eyes.dm
  code/modules/client/preference_setup/loadout/loadout_general.dm
  code/modules/client/preference_setup/loadout/loadout_gloves.dm
  code/modules/client/preference_setup/loadout/loadout_head.dm
  code/modules/client/preference_setup/loadout/loadout_shoes.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/client/preference_setup/loadout/loadout_utility.dm
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
  code/modules/clothing/head/hood.dm
  code/modules/clothing/shoes/colour.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/hooded.dm
  code/modules/clothing/suits/storage.dm
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/clothing/under/accessories/clothing.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/clothing/under/shorts.dm
  icons/mob/feet.dmi
  icons/mob/hands.dmi
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/mob/suit_1.dmi
  icons/mob/ties.dmi
  icons/mob/uniform.dmi
  icons/mob/uniform_1.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/ties.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/clothing/uniforms_1.dmi
Labels: Sprites

#9046 fixes infinite morphium duplication exploit
  code/game/machinery/autolathe.dm
  code/game/machinery/machinery.dm
  code/game/mecha/mech_fabricator.dm
  code/game/mecha/mech_prosthetics.dm
  code/game/objects/items/stacks/tiles/fifty_spawner_tiles.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/modules/materials/fifty_spawner_mats.dm
  code/modules/materials/materials/organic/grass.dm
  code/modules/materials/sheets/organic/wood.dm
  code/modules/research/protolathe.dm
  code/modules/research/rdmachines.dm
Labels: Refactor, Bugfix

#9070 Language transfer on brain removal bugfix
  code/modules/organs/internal/brain.dm
Labels: Bugfix

#9082 Updates text sanitization
  code/_helpers/text.dm
  code/datums/uplink/announcements.dm
  code/game/machinery/requests_console.dm
  code/game/objects/items/devices/uplink.dm
  code/modules/client/preference_setup/antagonism/01_basic.dm
  code/modules/client/preference_setup/general/05_background.dm
  code/modules/emotes/emote_mob.dm
  code/modules/paperwork/handlabeler.dm
Labels: Refactor, Bugfix

#9097 kirani drinks
  code/modules/food/drinkingglass/metaglass.dm
  code/modules/reagents/reactions/instant/drinks.dm
  code/modules/reagents/reagents/food_drinks.dm
  icons/obj/drinks.dmi
Labels: Feature Tweak, Sprites

#9103 Fixes phoron generator runtime gigaspam
  code/game/mecha/equipment/tools/generator.dm
Labels: Bugfix

#9104 Added a cloak sprite sheet set for hooded Teshari cloaks.
  code/modules/clothing/suits/aliens/teshari.dm
Labels: Feature

#9108 Reverts apparently broken sprite_sheets checking on tesh cloaks.
  code/modules/clothing/suits/aliens/teshari.dm
Labels: Bugfix
