Repository PolarisSS13/Polaris, pull requests merged in 2023-03, with the labels that each got.

#8991 Removes gnomes. We are being un-gnomed.
  code/modules/hydroponics/_hydro_setup.dm
  code/modules/hydroponics/seed.dm
  code/modules/hydroponics/seed_packets.dm
  code/modules/hydroponics/seedtypes/gnomes.dm
  code/modules/reagents/reagents/food_drinks.dm
  polaris.dme
Labels: Priority: High, Bugfix, Quality of Life, Revert

#8941 Fix various anomaly bugs and oversights.
  code/modules/xenoarcheaology/effects/cellcharge.dm
  code/modules/xenoarcheaology/effects/celldrain.dm
  code/modules/xenoarcheaology/effects/robohurt.dm
  code/modules/xenoarcheaology/effects/sleepy.dm
  code/modules/xenoarcheaology/effects/sweating_reagents.dm
Labels: Bugfix

#8946 Upkeep on Mech & Cliff code.
  code/__defines/is_helpers.dm
  code/_helpers/atom_movables.dm
  code/_helpers/matrices.dm
  code/game/atoms_movable.dm
  code/game/mecha/combat/fighter.dm
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/mecha/equipment/tools/jetpack.dm
  code/game/mecha/equipment/tools/jumpjet.dm
  code/game/mecha/equipment/weapons/explosive/grenade.dm
  code/game/mecha/equipment/weapons/weapons.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_helpers.dm
  code/game/objects/items/mines/_mine.dm
  code/game/objects/items/mines/mine_assembly.dm
  code/game/objects/structures/cliff.dm
  code/game/objects/structures/flora/trees.dm
  code/modules/multiz/movement.dm
  code/modules/research/mechfab_designs.dm
  icons/mecha/mecha_equipment.dmi
  polaris.dme
Labels: Feature, Bugfix, Feature Tweak

#8953 Refluff space bats and space bears
  code/modules/mob/living/simple_mob/subtypes/animal/space/bats.dm
  code/modules/mob/living/simple_mob/subtypes/animal/space/bear.dm
Labels: Lore

#8955 AI can change their hologram color.
  code/game/machinery/hologram.dm
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Feature

#8958 Sounds for fabricators, mining machines, levers
  code/datums/looping_sounds/machinery_sounds.dm
  code/game/machinery/autolathe.dm
  code/game/mecha/mech_fabricator.dm
  code/game/mecha/mech_prosthetics.dm
  code/modules/food/kitchen/cooking_machines/_appliance.dm
  code/modules/food/kitchen/cooking_machines/_mixer.dm
  code/modules/mining/drilling/drill.dm
  code/modules/mining/machinery/machine_processing.dm
  code/modules/mining/machinery/machine_stacking.dm
  code/modules/recycling/conveyor2.dm
  sound/machines/clunk.ogg
  sound/machines/drill/drill_end.ogg
  sound/machines/drill/drill_mid.ogg
  sound/machines/drill/drill_start.ogg
  sound/machines/fabricator/fabricator1.ogg
  sound/machines/fabricator/fabricator2.ogg
  sound/machines/lever.ogg
Labels: Sounds

#8970 Prototype - floor-generalized snow layers, instead of snow turfs
  code/__defines/turfs.dm
  code/game/objects/effects/landmarks.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor_attackby.dm
  code/game/turfs/simulated/floor_icon.dm
  code/game/turfs/simulated/lava.dm
  code/game/turfs/simulated/outdoors/outdoors.dm
  code/game/turfs/simulated/outdoors/outdoors_attackby.dm
  code/game/turfs/simulated/outdoors/snow.dm
  code/game/turfs/simulated/water.dm
  code/game/turfs/turf.dm
  code/modules/examine/descriptions/turfs.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/simple_mob/simple_mob.dm
  code/modules/vehicles/quad.dm
  code/modules/vehicles/snowmobile.dm
  maps/cynosure/cynosure-2.dmm
  maps/cynosure/cynosure-7.dmm
  maps/cynosure/datums/random_map.dm
  maps/cynosure/turfs/outdoors.dm
  maps/southern_cross/datums/random_map.dm
  maps/southern_cross/southern_cross-3.dmm
  maps/southern_cross/turfs/outdoors.dm
  maps/submaps/surface_submaps/plains/RationCache.dmm
  maps/submaps/surface_submaps/plains/chemspill1.dmm
  maps/submaps/surface_submaps/plains/snow1.dmm
  maps/submaps/surface_submaps/plains/snow2.dmm
  maps/submaps/surface_submaps/plains/snow3.dmm
  maps/submaps/surface_submaps/plains/snow4.dmm
  maps/submaps/surface_submaps/plains/snow5.dmm
  maps/submaps/surface_submaps/wilderness/Shelter.dmm
  maps/submaps/surface_submaps/wilderness/Smol1.dmm
  maps/submaps/surface_submaps/wilderness/chemspill2.dmm
  maps/submaps/surface_submaps/wilderness/frostoasis.dmm
Labels: Refactor

#8975 fixes a runtime in huds deleting and the gun deletion on login issue
  code/_onclick/hud/hud.dm
Labels: Oversight

#8986 Generalizing sleeping updates and adding it to simple mobs.
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/nymph/life.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/simple_mob/healing.dm
  code/modules/mob/living/simple_mob/life.dm
Labels: Bugfix

#8951 [Requested] Serenity changed to proper medical exosuit.
  code/game/mecha/combat/combat.dm
  code/game/mecha/combat/gygax.dm
  code/game/mecha/equipment/tools/jumpjet.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_construction_paths.dm
  code/game/mecha/medical/medical.dm
  code/game/mecha/medical/odysseus.dm
  code/game/mecha/medical/serenity.dm
  code/game/objects/random/mechs.dm
  polaris.dme
Labels: Contentious, Feature Tweak

#8997 Projectiles properly set starting var.
  code/modules/projectiles/projectile.dm
Labels: Oversight

#8993 Converts move intents to /decl/move_intent
  code/__defines/movement.dm
  code/_onclick/hud/alien_larva.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/screen_objects.dm
  code/datums/move_intent.dm
  code/game/area/areas.dm
  code/game/gamemodes/changeling/powers/visible_camouflage.dm
  code/game/machinery/flasher.dm
  code/game/objects/items/toys/toys.dm
  code/game/objects/items/weapons/handcuffs.dm
  code/game/objects/items/weapons/traps.dm
  code/game/objects/structures/crates_lockers/closets/coffin.dm
  code/game/turfs/simulated.dm
  code/modules/assembly/mousetrap.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/living_movement.dm
  code/modules/mob/living/simple_mob/simple_hud.dm
  code/modules/mob/living/simple_mob/simple_mob.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_movement.dm
  code/modules/organs/internal/intestine.dm
  code/modules/organs/internal/kidneys.dm
  code/modules/projectiles/targeting/targeting_mob.dm
  polaris.dme
Labels: Refactor, Port

#8995 different voidsuits!
  maps/cynosure/cynosure-2.dmm
  maps/cynosure/cynosure-3.dmm
Labels: Map: Cynosure

#8904 Drake harnesses are removable.
  code/modules/mob/living/simple_mob/subtypes/animal/_animal_harness.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka/grafadreka.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka/grafadreka_harness.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka/grafadreka_misc.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka/grafadreka_trained.dm
  icons/mob/drake_harness.dmi
  maps/cynosure/cynosure_jobs.dm
Labels: Feature

#9040 Fixes move intent switching for living but non-carbon mobs
  code/_onclick/hud/screen_objects.dm
Labels: Oversight, Priority: Medium

#8967 Bugfixes
  code/datums/autolathe/general.dm
  code/datums/outfits/jobs/security.dm
  code/game/machinery/autolathe.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/devices/suit_cooling.dm
  code/game/objects/items/stacks/stack.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/voice/voice.dm
  code/modules/mob/new_player/sprite_accessories.dm
  html/changelogs/Bugfixes - Varlaisvea.yml
  icons/obj/stacks.dmi
  maps/cynosure/structures/closets/security.dm
Labels: Bugfix

#8976 Tweaks the positioning and icons of the eye slot and ear slots on the inventory UI
  code/_onclick/hud/_defines.dm
  code/modules/mob/living/carbon/human/species/species_hud.dm
  icons/mob/screen/holo.dmi
  icons/mob/screen/midnight.dmi
  icons/mob/screen/minimalist.dmi
  icons/mob/screen/old-noborder.dmi
  icons/mob/screen/old.dmi
  icons/mob/screen/orange.dmi
  icons/mob/screen/white.dmi
Labels: Contentious, Feature Tweak, Quality of Life

#8989 Making floor decls use the decl repository.
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor_attackby.dm
  code/game/turfs/simulated/water.dm
  code/game/world.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/living/bot/floorbot.dm
Labels: Refactor

#8992 R&D Design Updates
  code/modules/research/designs/HUDs.dm
  code/modules/research/designs/power_cells.dm
  code/modules/research/mechfab_designs.dm
Labels: Feature Tweak

#9038 Hotfix for moving pulled objects
  code/game/turfs/simulated/floor_attackby.dm
Labels: Oversight, Bugfix

#9005 Adds xenofauna lab
  code/game/area/Space Station 13 areas.dm
  code/game/jobs/access_datum.dm
  code/game/jobs/job/science.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/weapons/id cards/station_ids.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/modules/mob/living/simple_mob/defense.dm
  code/modules/mob/living/simple_mob/life.dm
  code/modules/mob/living/simple_mob/simple_mob.dm
  code/modules/projectiles/guns/energy/phase.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/energy.dm
  maps/cynosure/cynosure-1.dmm
  maps/cynosure/cynosure-2.dmm
  maps/cynosure/cynosure_jobs.dm
  maps/cynosure/cynosure_presets.dm
  maps/cynosure/structures/closets/misc.dm
  maps/southern_cross/southern_cross_presets.dm
  maps/~map_system/maps.dm
Labels: Feature, Map: Cynosure

#9002 the little construction pr
  code/__defines/materials.dm
  code/datums/autolathe/engineering.dm
  code/game/machinery/computer/arcade.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/frame.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/items/weapons/circuitboards/frame.dm
  code/game/objects/structures/lattice.dm
  code/game/objects/structures/window.dm
  code/modules/materials/materials/organic/grass.dm
  icons/obj/stock_parts.dmi
  icons/turf/flooring/carpet.dmi
  polaris.dme
Labels: Feature

#9011 Fixing positional custom emotes.
  code/_helpers/text.dm
  code/game/machinery/hologram.dm
  code/game/objects/effects/map_effects/portal.dm
  code/game/objects/items/devices/taperecorder.dm
  code/game/objects/items/uav.dm
  code/game/objects/objs.dm
  code/modules/blob2/overmind/overmind.dm
  code/modules/emotes/emote_mob.dm
  code/modules/fishing/fishing_rod.dm
  code/modules/food/food/snacks.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/bot/cleanbot.dm
  code/modules/mob/living/bot/edCLNbot.dm
  code/modules/mob/living/bot/floorbot.dm
  code/modules/mob/living/bot/medbot.dm
  code/modules/mob/living/bot/mulebot.dm
  code/modules/mob/living/bot/secbot.dm
  code/modules/mob/living/carbon/human/human_organs.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/silicon/say.dm
  code/modules/mob/living/simple_mob/on_click.dm
  code/modules/mob/mob.dm
  code/modules/power/cells/power_cells.dm
Labels: Refactor, Bugfix

#9012 Fix some coffee mugs not using the correct sprites
  code/modules/food/drinkingglass/mugs.dm
Labels: Oversight

#9013 Fixes Simplemob Movement Delay
  code/modules/mob/living/simple_mob/simple_mob.dm
Labels: Oversight

#9014 Prometheans self clean adjust.
  code/modules/mob/living/carbon/human/species/station/prometheans.dm
Labels: Feature Tweak

#9015 Phoron Bore Adjustment Take 2
  code/modules/projectiles/guns/magnetic/bore.dm
  code/modules/projectiles/projectile/magnetic.dm
Labels: Feature Tweak

#9016 Duffle and Bag of Holding Sprites
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/random/maintenance.dm
  code/game/objects/random/misc.dm
  code/game/objects/structures/loot_piles.dm
  code/modules/research/designs/bag_of_holding.dm
  icons/mob/back.dmi
  icons/mob/items/lefthand_storage.dmi
  icons/mob/items/righthand_storage.dmi
  icons/obj/clothing/backpack.dmi
Labels: Sprites

#9023 Vox prosthetic icons update.
  icons/mob/ascent.dmi
  icons/mob/human_races/cyberlimbs/vox/improvised.dmi
  icons/mob/human_races/cyberlimbs/vox/improvised.dmi.png
  icons/mob/human_races/cyberlimbs/vox/primalis.dmi
  icons/mob/human_races/cyberlimbs/vox/primalis.dmi.png
Labels: Sprites

#9042 Roofs the xenofauna lab.
  maps/cynosure/cynosure-3.dmm
Labels: Oversight, Map: Cynosure

#8947 reworks handling of transparent limbs
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/organs/organ_icon.dm
  code/modules/organs/subtypes/standard.dm
Labels: Quality of Life

#9049 Adding some debug logic to SSmobs to try and chase down the sleeping issue.
  code/controllers/subsystems/mobs.dm
Labels: Priority: High

#8994 big heckin chonker ultragigamega-ears!!!!
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/carbon/human/species/station/teshari.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
Labels: Feature Tweak

#9007 Adds MtG except in space
  code/datums/supplypacks/recreation.dm
  code/game/objects/random/misc.dm
  code/game/objects/random/recreation.dm
  code/modules/games/saintsandsins_cards.dm
  icons/obj/playing_cards.dmi
  polaris.dme
Labels: Feature, Sprites

#9018 Fixes a looping sound bug, adds additional options
  code/datums/looping_sounds/_looping_sound.dm
Labels: Bugfix, Quality of Life

#9022 new overmap icons
  code/modules/overmap/turfs.dm
  icons/obj/overmap.dmi
  icons/turf/space.dmi
  maps/cynosure/cynosure_shuttles.dm
  maps/cynosure/overmap/sectors.dm
Labels: Sprites

#9024 Transplant DMI of Scars, Augs, and Bandages
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_races/markings.dmi
  icons/mob/human_races/sprite_accessories/augments.dmi
  icons/mob/human_races/sprite_accessories/bandages.dmi
  icons/mob/human_races/sprite_accessories/scars.dmi
Labels: Sprites

#9025 Rocks Fall, Everyone Dies. AKA Adds Planetary Meteors (Again) (For Real)
  code/__defines/flags.dm
  code/game/gamemodes/meteor/meteors.dm
  code/game/objects/structures/flora/trees.dm
  code/modules/events/meteors.dm
  code/modules/gamemaster/event2/events/engineering/planet_meteor_defense.dm
  code/modules/shieldgen/shield_gen_external.dm
  polaris.dme
Labels: Feature

#9028 Finally allows RPD to be used.
  code/datums/supplypacks/atmospherics.dm
  code/game/objects/items/weapons/RPD.dm
  code/modules/mob/living/silicon/robot/robot_modules/station.dm
Labels: Feature

#9029 Sheet storage has different caps per type.
  code/game/objects/effects/decals/crayon.dm
  code/modules/food/kitchen/smartfridge/engineering.dm
  code/modules/persistence/storage/smartfridge.dm
  code/modules/persistence/storage/storage.dm
Labels: Feature Tweak

#9030 Fixes a small hiccup in cable coil examine text
  code/modules/power/cable.dm
Labels: Oversight

#9031 Fixes a raunchy typo
  code/game/objects/items/weapons/storage/mre.dm
Labels: Spellcheck

#9032 Static communicators
  code/game/objects/items/devices/communicator/UI.dm
  code/game/objects/items/devices/communicator/communicator.dm
  code/game/objects/items/devices/communicator/desktop.dm
  icons/obj/device.dmi
  maps/cynosure/cynosure-2.dmm
  maps/cynosure/cynosure-3.dmm
  polaris.dme
Labels: Feature

#9033 *bing
  code/modules/emotes/definitions/synthetics.dm
  code/modules/mob/living/silicon/emote.dm
  code/modules/mob/living/silicon/robot/emote.dm
Labels: Feature Tweak, Quality of Life

#9035 Arri Vals
  maps/cynosure/cynosure-6.dmm
Labels: Map: Cynosure

#9036 Removes the deprecated archive from the library computer
  code/modules/library/lib_machines.dm
Labels: Revert

#9039 Siege Hivebots Use Proper Projectile
  code/modules/mob/living/simple_mob/subtypes/mechanical/hivebot/ranged_damage.dm
Labels: Oversight

#9043 Add interact_message proc for more flexible visible messages between two parties
  code/game/objects/items/devices/flash.dm
  code/modules/mob/mob.dm
Labels: Quality of Life

#9045 Click catchers no longer display as Darkness
  code/_onclick/click.dm
Labels: Quality of Life

#9050 Move intent tweaks.
  code/__defines/movement.dm
  code/_onclick/hud/screen_objects.dm
  code/controllers/configuration.dm
  code/datums/move_intent.dm
  code/game/gamemodes/changeling/powers/visible_camouflage.dm
  code/game/objects/items/weapons/handcuffs.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/silicon/robot/robot_movement.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_mob/simple_mob.dm
  code/modules/mob/mob.dm
  code/modules/organs/internal/intestine.dm
  code/modules/organs/internal/kidneys.dm
  code/modules/projectiles/targeting/targeting_mob.dm
  config/example/game_options.txt
Labels: Refactor, Bugfix

#9051 Fixes mistake with drake update_icon.
  code/game/objects/structures/animal_den.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka/grafadreka.dm
Labels: Oversight

#9072 Readds missing default icon to inhand gen.
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Oversight

#8887 Another take at a new whitelist system
  code/modules/admin/banjob.dm
  code/modules/admin/topic.dm
  code/modules/client/preference_setup/general/03_body.dm
  code/modules/whitelist/admin.dm
  code/modules/whitelist/admin_ops.dm
  code/modules/whitelist/legacy.dm
  code/modules/whitelist/phony_paths.dm
  code/modules/whitelist/whitelist.dm
  polaris.dme
  tools/whitelistupdate5000.py
Labels: Refactor

#9076 Load whitelist on server start
  code/modules/whitelist/whitelist.dm
  tools/whitelistupdate5000.py
Labels: Oversight, Priority: High

#9077 And actually call the proc...
  code/game/world.dm
Labels: Oversight, Priority: High

#9078 Revert whitelist rev 3
  code/game/world.dm
  code/modules/admin/banjob.dm
  code/modules/admin/topic.dm
  code/modules/client/preference_setup/general/03_body.dm
  code/modules/whitelist/admin.dm
  code/modules/whitelist/admin_ops.dm
  code/modules/whitelist/legacy.dm
  code/modules/whitelist/phony_paths.dm
  code/modules/whitelist/whitelist.dm
  polaris.dme
  tools/whitelistupdate5000.py
Labels: Priority: High, Revert

#9017 Energy Gun maint, Electromag damage type.
  code/__defines/damage_organs.dm
  code/game/objects/effects/temporary_visuals/projectiles/impact.dm
  code/game/objects/effects/temporary_visuals/projectiles/muzzle.dm
  code/game/objects/effects/temporary_visuals/projectiles/tracer.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/hooklauncher.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/projectile/beams.dm
  icons/obj/gun.dmi
  icons/obj/gun2.dmi
  icons/obj/gun_energy.dmi
  icons/obj/projectiles.dmi
  icons/obj/projectiles_impact.dmi
  icons/obj/projectiles_muzzle.dmi
  icons/obj/projectiles_tracer.dmi
Labels: Feature

#8950 Fixing Tape Recorder Voices
  code/game/objects/items/devices/taperecorder.dm
Labels: Bugfix

#9021 Bioprinter refactor and nanoUI-ification
  code/__defines/misc.dm
  code/game/machinery/bioprinter.dm
  code/modules/reagents/reagent_containers/syringes.dm
  maps/cynosure/cynosure-2.dmm
  maps/southern_cross/southern_cross-1.dmm
  maps/submaps/surface_submaps/wilderness/Blackshuttledown.dmm
  maps/submaps/surface_submaps/wilderness/Blueshuttledown.dmm
  nano/templates/bioprinter.tmpl
Labels: Feature, Refactor

#9026 Adds Research Lab POI and some other stuff.
  code/game/objects/items/poi_items.dm
  code/game/objects/random/misc.dm
  code/modules/ai/ai_holder_fleeing.dm
  code/modules/ai/say_list.dm
  code/modules/mob/dead/corpse.dm
  code/modules/mob/living/simple_mob/subtypes/humanoid/android.dm
  code/modules/mob/living/simple_mob/subtypes/humanoid/mercs/mercs.dm
  icons/mob/animal.dmi
  maps/submaps/surface_submaps/wilderness/Research1.dmm
  maps/submaps/surface_submaps/wilderness/wilderness.dm
  maps/submaps/surface_submaps/wilderness/wilderness_areas.dm
  polaris.dme
Labels: Map: Point of Interest

#9054 Justice for AcmeCo
  code/game/objects/items/weapons/storage/fancy.dm
  code/modules/client/preference_setup/loadout/loadout_smoking.dm
Labels: Oversight

#9060 Updates eroneous tt_descs
  code/modules/mob/living/simple_mob/subtypes/animal/passive/penguin.dm
  code/modules/mob/living/simple_mob/subtypes/animal/passive/possum.dm
  code/modules/mob/living/simple_mob/subtypes/animal/space/alien.dm
Labels: Lore

#9061 Bump up fabricator volume slightly
  code/datums/looping_sounds/machinery_sounds.dm
Labels: Sounds

#9066 Lolliglock Nerf
  code/game/objects/items/trash.dm
Labels: Sounds

#9086 Assorted bugfixes ahead of the merc event
  code/game/objects/structures/props/prop.dm
  code/modules/clothing/chameleon.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/projectile/special.dm
  maps/cynosure/cynosure-6.dmm
Labels: Bugfix
