Repository PolarisSS13/Polaris, pull requests merged in 2023-04, with the labels that each got.

#9057 Carp Land
  code/modules/fishing/fishing.dm
  code/modules/mob/living/simple_mob/subtypes/animal/passive/fish.dm
  icons/mob/fish.dmi
Labels: Feature, Lore

#9058 ATC Fixes
  code/modules/busy_space/air_traffic.dm
  code/modules/busy_space/missions.dm
  code/modules/busy_space/organizations.dm
  code/modules/busy_space/systems.dm
Labels: Oversight

#9062 Tones down Hedberg-Hammarstrom uniforms just a smidge
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites

#9065 Desk toys allow alt-click to toggle
  code/game/objects/items/toys/toys.dm
Labels: Feature Tweak

#9067 Fix several hats and hoods shaving your face
  code/modules/clothing/chameleon.dm
  code/modules/clothing/head/collectable.dm
  code/modules/clothing/head/hood.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/xenoarcheaology/tools/equipment.dm
  maps/cynosure/cynosure-6.dmm
  maps/northern_star/polaris-2.dmm
  maps/southern_cross/southern_cross-6.dmm
Labels: Bugfix

#9074 Adding clothing offsets for Teshari.
  code/modules/mob/living/carbon/human/species/station/teshari.dm
  icons/mob/species/teshari/uniform.dmi
Labels: Sprites

#9083 fixes iaa holobadge
  code/modules/client/preference_setup/loadout/loadout_accessories.dm
Labels: Spellcheck

#9084 Stuff dview back into nullspace
  code/modules/lighting/lighting_source.dm
Labels: Oversight, Higgs Bugson

#9085 makes overlays less eyesearing (v2)
  code/_onclick/hud/hud.dm
Labels: Quality of Life

#9073 Fixes the RPD (again (hopefully for the last time (fingers crossed)))
  code/game/objects/items/weapons/RPD.dm
Labels: Bugfix

#9064 Slimes can eat loose food, decals, dirt, and so on
  code/game/atoms.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/effects/decals/Cleanable/misc.dm
  code/game/objects/effects/decals/Cleanable/robots.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/turfs/simulated.dm
  code/modules/ai/ai_holder_subtypes/slime_xenobio_ai.dm
  code/modules/food/food/snacks.dm
  code/modules/mob/living/simple_mob/subtypes/slime/xenobio/xenobio.dm
  code/modules/organs/organ.dm
Labels: Feature

#9095 Fixes Teshari cloaks being offset due to not using sprite sheets.
  code/modules/clothing/suits/aliens/teshari.dm
Labels: Bugfix

#9096 Axe player-facing references to 'biological gender'
  code/__defines/mobs.dm
  code/modules/client/preference_setup/general/01_basic.dm
  code/modules/lore_codex/lore_data/species.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
Labels: Quality of Life

#9092 Removes random yellow pixels from Ward-Takahashi monitor
  icons/mob/human_races/cyberlimbs/wardtakahashi/wardtakahashi_monitor.dmi
Labels: Sprites

#9088 Tank gauge overlays initialize correctly
  code/game/objects/items/weapons/tanks/tanks.dm
Labels: Oversight

#9068 Smol botany update
  code/game/machinery/biogenerator.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/modules/hydroponics/trays/tray.dm
  icons/obj/clothing/belts.dmi
  maps/cynosure/cynosure-2.dmm
Labels: Feature

#9091 Adds plastic clogs to loadout, ports sprite by Pawn
  code/modules/client/preference_setup/loadout/loadout_shoes.dm
  code/modules/clothing/shoes/miscellaneous.dm
  icons/mob/feet.dmi
  icons/obj/clothing/shoes.dmi
Labels: Feature

#9094 Fixes quick gather taking anchored items
  code/game/objects/items/weapons/storage/storage.dm
Labels: Bugfix

#9098 adds hub visibility toggling and config option
  code/controllers/configuration.dm
  code/game/world.dm
  code/hub.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verb_lists.dm
  code/modules/mob/mob.dm
  config/example/config.txt
Labels: Priority: High, Bugfix
