Repository PolarisSS13/Polaris, pull requests merged in 2023-10, with the labels that each got.

#9253 drake rejuvenate resets scarring and nutrition
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka/grafadreka.dm
Labels: Bugfix

#9267 Small shuttle additions
  code/game/turfs/flooring/flooring_decals.dm
  icons/turf/flooring/decals.dmi
  maps/cynosure/cynosure-6.dmm
Labels: Map: Cynosure

#9269 Comms blackout no longer disables communicators
  code/modules/gamemaster/event2/events/everyone/comms_blackout.dm
Labels: Feature Tweak

#9271 Zaddat can wear ties
  code/modules/clothing/spacesuits/spacesuits.dm
Labels: Feature Tweak

#9273 Unathi now have larynxes
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/organs/subtypes/unathi.dm
Labels: Bugfix

#9276 Ghost Blanket Costume
  code/modules/clothing/masks/miscellaneous.dm
  icons/mob/mask.dmi
  icons/mob/species/tajaran/mask.dmi
  icons/mob/species/teshari/masks.dmi
  icons/mob/species/unathi/mask.dmi
  icons/mob/species/vox/masks.dmi
  icons/obj/clothing/masks.dmi
Labels: Feature

#9270 POI - Chasm Remap
  maps/submaps/surface_submaps/wilderness/chasm.dmm
Labels: Map: Point of Interest

#9272 POI - Frostoasis Fixes
  maps/submaps/surface_submaps/wilderness/frostoasis.dmm
Labels: Map: Point of Interest
