Repository PolarisSS13/Polaris, pull requests merged in 2023-12, with the labels that each got.

#9286 chicken gliding
  code/modules/mob/living/simple_mob/subtypes/animal/farm animals/chicken.dm
Labels: Feature Tweak, Quality of Life

#9284 Adds a tattoo 'masquerade mask'.
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_races/markings.dmi
Labels: Feature Tweak

#9143 Blob Chunks 2
  code/modules/blob2/_defines.dm
  code/modules/blob2/blobs/core.dm
  code/modules/blob2/overmind/chunks.dm
  code/modules/blob2/overmind/types.dm
  code/modules/blob2/overmind/types/barnacle.dm
  code/modules/blob2/overmind/types/blazing_oil.dm
  code/modules/blob2/overmind/types/classic.dm
  code/modules/blob2/overmind/types/cryogenic_goo.dm
  code/modules/blob2/overmind/types/ectoplasmic_horror.dm
  code/modules/blob2/overmind/types/electromagnetic_web.dm
  code/modules/blob2/overmind/types/energized_jelly.dm
  code/modules/blob2/overmind/types/explosive_lattice.dm
  code/modules/blob2/overmind/types/fabrication_swarm.dm
  code/modules/blob2/overmind/types/fulminant_organism.dm
  code/modules/blob2/overmind/types/fungal_bloom.dm
  code/modules/blob2/overmind/types/grey_goo.dm
  code/modules/blob2/overmind/types/pressurized_slime.dm
  code/modules/blob2/overmind/types/radioactive_ooze.dm
  code/modules/blob2/overmind/types/ravenous_macrophage.dm
  code/modules/blob2/overmind/types/reactive_spines.dm
  code/modules/blob2/overmind/types/roiling_mold.dm
  code/modules/blob2/overmind/types/shifting_fragments.dm
  code/modules/blob2/overmind/types/synchronous_mesh.dm
  code/modules/blob2/overmind/types/volatile_alluvium.dm
  code/modules/reagents/reactions/instant/blob.dm
  code/modules/xenoarcheaology/effects/disarm.dm
  code/modules/xenoarcheaology/effects/gassleeping.dm
  code/modules/xenoarcheaology/effects/indiscriminate_spines.dm
  code/modules/xenoarcheaology/effects/lifemerger.dm
  polaris.dme
Labels: Feature

#9255 Graffiti centers on where you click.
  code/game/objects/effects/decals/crayon.dm
  code/game/objects/items/crayons.dm
  code/game/turfs/simulated/floor_attackby.dm
  code/game/turfs/simulated/wall_attacks.dm
  code/game/turfs/turf.dm
  code/modules/persistence/datum/persistence_datum.dm
  code/modules/persistence/effects/filth.dm
  code/modules/persistence/effects/graffiti.dm
  code/modules/persistence/effects/trash.dm
  icons/effects/writing.dmi
Labels: Feature Tweak

#9283 area blurbs
  code/game/area/Space Station 13 areas.dm
  code/game/area/areas.dm
  maps/cynosure/cynosure_areas.dm
  maps/submaps/surface_submaps/plains/plains_areas.dm
  maps/submaps/surface_submaps/wilderness/wilderness_areas.dm
Labels: Feature

#9287 Fixes head plugs missing/incorrect icons
  icons/mob/human_races/markings.dmi
  icons/mob/human_races/sprite_accessories/augments.dmi
Labels: Oversight

#9293 Scratches up the bar communicator take 2
  maps/cynosure/cynosure-2.dmm
Labels: Lore

#9295 Improves the dark mode color of some languages
  code/modules/vchat/css/ss13styles.css
  code/stylesheet.dm
Labels: Quality of Life

#9296 Drakes and kururak will now threaten before attacking.
  code/modules/ai/ai_holder_communication.dm
  code/modules/ai/ai_holder_debug.dm
  code/modules/ai/say_list.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka/grafadreka_ai.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka/grafadreka_misc.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/kururak.dm
Labels: Feature Tweak, Sounds

#9297 Corrects arg indices in artifact attacby callback.
  code/modules/xenoarcheaology/effect_master.dm
Labels: Oversight

#9285 Tweaks the Head of Security's locker and office layout
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/head/jobs.dm
  maps/cynosure/cynosure-2.dmm
  maps/cynosure/structures/closets/security.dm
Labels: Map: Cynosure

#9288 POI - CaveS Rebalance
  maps/submaps/surface_submaps/wilderness/CaveS.dmm
Labels: Map: Point of Interest
