Repository PolarisSS13/Polaris, pull requests merged in 2023-01, with the labels that each got.

#8851 Maintenance on Hydro code, specifically vines and bees.
  code/modules/hydroponics/beekeeping/beehive.dm
  code/modules/hydroponics/seed.dm
  code/modules/hydroponics/seed_gene_mut.dm
  code/modules/hydroponics/spreading/spreading.dm
  code/modules/hydroponics/spreading/spreading_growth.dm
  code/modules/projectiles/projectile/bullets.dm
  icons/mob/animal.dmi
  icons/obj/beekeeping.dmi
Labels: Feature Tweak, Sprites

#8867 fixes augment implants so you can't spam the fuck out of them
  code/modules/organs/internal/augment.dm
  code/modules/organs/internal/augment/armmounted.dm
  code/modules/organs/internal/augment/bio.dm
Labels: Bugfix

#8864 Alternative communicator and cane sprites
  code/game/objects/items/devices/communicator/communicator.dm
  code/game/objects/items/weapons/canes.dm
  code/modules/client/preference_setup/loadout/loadout_general.dm
  code/modules/client/preference_setup/loadout/loadout_utility.dm
  icons/mob/items/lefthand_melee.dmi
  icons/mob/items/righthand_melee.dmi
  icons/obj/device.dmi
  icons/obj/weapons.dmi
Labels: Feature

#8783 Moves blob chunk effects to artifact effects.
  code/modules/blob2/blobs/core.dm
  code/modules/blob2/core_chunk.dm
  code/modules/blob2/overmind/types.dm
  code/modules/blob2/overmind/types/barnacle.dm
  code/modules/blob2/overmind/types/blazing_oil.dm
  code/modules/blob2/overmind/types/classic.dm
  code/modules/blob2/overmind/types/cryogenic_goo.dm
  code/modules/blob2/overmind/types/ectoplasmic_horror.dm
  code/modules/blob2/overmind/types/electromagnetic_web.dm
  code/modules/blob2/overmind/types/energized_jelly.dm
  code/modules/blob2/overmind/types/explosive_lattice.dm
  code/modules/blob2/overmind/types/fabrication_swarm.dm
  code/modules/blob2/overmind/types/fulminant_organism.dm
  code/modules/blob2/overmind/types/fungal_bloom.dm
  code/modules/blob2/overmind/types/grey_goo.dm
  code/modules/blob2/overmind/types/pressurized_slime.dm
  code/modules/blob2/overmind/types/radioactive_ooze.dm
  code/modules/blob2/overmind/types/ravenous_macrophage.dm
  code/modules/blob2/overmind/types/reactive_spines.dm
  code/modules/blob2/overmind/types/roiling_mold.dm
  code/modules/blob2/overmind/types/shifting_fragments.dm
  code/modules/blob2/overmind/types/synchronous_mesh.dm
  code/modules/blob2/overmind/types/volatile_alluvium.dm
  code/modules/mob/living/simple_mob/subtypes/blob/blob.dm
  code/modules/xenoarcheaology/artifacts/autocloner.dm
  code/modules/xenoarcheaology/effect.dm
  code/modules/xenoarcheaology/effect_master.dm
  code/modules/xenoarcheaology/effects/animate_anomaly.dm
  code/modules/xenoarcheaology/effects/blast_shielding.dm
  code/modules/xenoarcheaology/effects/cold.dm
  code/modules/xenoarcheaology/effects/extinguisher.dm
  code/modules/xenoarcheaology/effects/faraday.dm
  code/modules/xenoarcheaology/effects/forcefield.dm
  code/modules/xenoarcheaology/effects/fortify.dm
  code/modules/xenoarcheaology/effects/indiscriminate_spines.dm
  code/modules/xenoarcheaology/effects/lifedrain.dm
  code/modules/xenoarcheaology/effects/lifesteal.dm
  code/modules/xenoarcheaology/effects/noxious.dm
  code/modules/xenoarcheaology/effects/sprinting.dm
  code/modules/xenoarcheaology/effects/sweating_reagents.dm
  code/modules/xenoarcheaology/effects/tesla.dm
  polaris.dme
Labels: Feature

#8868 Blobs do damage to mechs
  code/game/mecha/mecha.dm
Labels: Bugfix

#8870 Repairing light robotic damage messaging fix
  code/game/objects/items/weapons/tools/weldingtool.dm
  code/modules/organs/organ_external.dm
Labels: Quality of Life

#8886 Revert "cynosure christmas decorations + snowy exterior"
  code/game/turfs/simulated/outdoors/snow.dm
  code/modules/planet/sif.dm
  maps/cynosure/cynosure-2.dmm
  maps/cynosure/cynosure-3.dmm
  maps/cynosure/cynosure-6.dmm
  maps/cynosure/cynosure-7.dmm
  maps/cynosure/datums/random_map.dm
Labels: Map: Cynosure

#8891 News Update Oct-Jan 2022-2023
  code/modules/lore_codex/news_data/main.dm
Labels: Lore

#8894 Simple animal flavour text will now show instead of desc, if set.
  code/game/atoms.dm
  code/modules/mob/living/simple_mob/subtypes/animal/_animal_harness.dm
  code/modules/mob/living/simple_mob/subtypes/animal/animal.dm
Labels: Feature Tweak

#8895 Survivalist no longer announces arrivals or departures.
  code/game/jobs/job/job.dm
  code/game/jobs/job_controller.dm
  code/game/machinery/cryopod.dm
  code/modules/mob/new_player/new_player.dm
  maps/cynosure/cynosure_jobs.dm
Labels: Bugfix

#8896 Adds rodent spawners to maintenance
  code/game/objects/random/mob.dm
  icons/misc/random_spawners.dmi
  maps/cynosure/cynosure-1.dmm
  maps/cynosure/cynosure-2.dmm
  maps/cynosure/cynosure-3.dmm
Labels: Map: Cynosure

#8898 Lowers frostbelle point value, increases rarity.
  code/game/objects/structures/flora/flora.dm
  maps/cynosure/datums/random_map.dm
Labels: Feature Tweak

#8899 Fixes Electrical Fault and Containment Subroutine events
  code/modules/gamemaster/event2/events/engineering/wallrot.dm
  code/modules/gamemaster/event2/events/everyone/electrical_fault.dm
  maps/cynosure/cynosure_events.dm
Labels: Bugfix

#8900 Drake spit is no longer a hard stun against humans.
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka/grafadreka_misc.dm
Labels: Bugfix

#8825 Splitting drakes out into their own job, which replaces the joinable version.
  code/game/jobs/job/science.dm
  code/game/jobs/jobs.dm
  code/modules/client/preference_setup/general/02_language.dm
  code/modules/mob/living/simple_mob/subtypes/animal/_animal_harness.dm
  code/modules/mob/living/simple_mob/subtypes/animal/animal.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka/grafadreka.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka/grafadreka_harness.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka/grafadreka_hatchling.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka/grafadreka_misc.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka/grafadreka_trained.dm
  code/modules/reagents/reagent_containers/syringes.dm
  icons/mob/drake_adult.dmi
  icons/mob/drake_harness.dmi
  maps/cynosure/cynosure-2.dmm
  maps/cynosure/cynosure-7.dmm
  maps/cynosure/cynosure_jobs.dm
  maps/cynosure/datums/spawn.dm
  maps/submaps/surface_submaps/wilderness/grafadreka_den.dmm
Labels: Feature, Refactor, Feature Tweak

#8907 Tiny grammar tweaks
  code/game/objects/structures/morgue.dm
  code/modules/client/client procs.dm
  code/modules/projectiles/guns/projectile/revolver.dm
  maps/submaps/surface_submaps/wilderness/Blackshuttledown.dmm
  maps/submaps/surface_submaps/wilderness/Blueshuttledown.dmm
Labels: Bugfix

#8889 Removes flame and incendiary weapons
  code/modules/research/mechfab_designs.dm
Labels: Bugfix

#8890 New Tattoos by Drawsstuff
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_races/markings.dmi
Labels: Feature, Sprites

#8897 Fixes missing hidden doors on several basement PoIs
  maps/cynosure/submaps/10x9/Shop.dmm
  maps/cynosure/submaps/10x9/TreasureHoard.dmm
  maps/cynosure/submaps/10x9/Warehouse1.dmm
  maps/cynosure/submaps/10x9/Warehouse2.dmm
  maps/cynosure/submaps/10x9/Warehouse3.dmm
  maps/cynosure/submaps/16x11/LaserTag.dmm
  maps/cynosure/submaps/5x7/MedicalBreakRoom.dmm
  maps/cynosure/submaps/7x7/JanitorCloset.dmm
  maps/cynosure/submaps/7x7/PartyRoom.dmm
  maps/cynosure/submaps/8x5/GrowersDen.dmm
  maps/cynosure/submaps/8x5/SquattersDen.dmm
  maps/cynosure/submaps/8x9/RitualRoom.dmm
  maps/cynosure/submaps/9x10/Theater.dmm
Labels: Oversight, Map: Point of Interest
