Repository PolarisSS13/Polaris, pull requests merged in 2023-08, with the labels that each got.

#9192 Fix records being wiped when hitting 'cancel' on input
  code/modules/client/preference_setup/antagonism/01_basic.dm
  code/modules/client/preference_setup/general/05_background.dm
Labels: Oversight, Priority: Medium

#9180 Nymph phyxes
  code/__defines/is_helpers.dm
  code/_helpers/unsorted.dm
  code/_onclick/hud/action.dm
  code/_onclick/hud/diona_nymph.dm
  code/_onclick/other_mobs.dm
  code/datums/mind.dm
  code/game/gamemodes/events.dm
  code/game/gamemodes/objective.dm
  code/game/machinery/computer/cloning.dm
  code/game/machinery/portable_turret.dm
  code/game/objects/structures/kitchen_spike.dm
  code/game/turfs/simulated.dm
  code/modules/admin/player_panel.dm
  code/modules/admin/secrets/random_events/trigger_xenomorph_infestation.dm
  code/modules/admin/topic.dm
  code/modules/ai/ai_holder.dm
  code/modules/antagonist/alien/xenomorph.dm
  code/modules/food/food/snacks.dm
  code/modules/ghosttrap/trap.dm
  code/modules/mob/living/carbon/human/species/xenomorphs/alien_species.dm
  code/modules/mob/living/carbon/nymph/diona.dm
  code/modules/mob/living/carbon/nymph/life.dm
  code/modules/reagents/reagents/core.dm
  code/modules/ventcrawl/ventcrawl.dm
  polaris.dme
Labels: Oversight, Bugfix

#9170 Ports several Unathi and Skrell hair from Neb and Bay
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/hair_skrell.dmi
  icons/mob/hair_skrell_add.dmi
  icons/mob/hair_unathi.dmi
  icons/mob/hair_unathi_add.dmi
  icons/mob/human_face.dmi
  icons/mob/human_face_alt.dmi
  icons/mob/human_face_alt_add.dmi
  icons/mob/human_face_m.dmi
Labels: Feature

#9172 Weapon Rebalance Part I: Energy Weapons
  code/datums/supplypacks/munitions.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/nuclear.dm
  code/modules/projectiles/guns/energy/phase.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/xenobio/items/weapons.dm
Labels: Feature Tweak

#9171 Teshari drip update: tail edition.
  code/game/objects/items/weapons/storage/backpack.dm
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/clothing/under/accessories/xeno/teshari.dm
  icons/mob/items/lefthand_storage.dmi
  icons/mob/items/righthand_storage.dmi
  icons/mob/species/teshari/back.dmi
  icons/mob/species/teshari/ties.dmi
  icons/obj/clothing/backpack.dmi
  icons/obj/clothing/suits_1.dmi
  icons/obj/clothing/ties.dmi
  polaris.dme
  sound/misc/dingaling1.ogg
  sound/misc/dingaling2.ogg
  sound/misc/dingaling3.ogg
  sound/misc/dingaling4.ogg
Labels: Feature, Sprites

#9174 POI - Rest Stop correction + cost reduction
  maps/submaps/surface_submaps/plains/plains.dm
Labels: Bugfix, Map: Point of Interest

#9175 Gives unathi the big snake tail
  code/modules/mob/new_player/sprite_accessories_tail.dm
  icons/effects/species_tails.dmi
Labels: Lore

#9176 Vox are defibbable.
  code/modules/mob/living/carbon/human/species/outsider/vox.dm
Labels: Bugfix

#9177 Adds a volume channel for system sounds (roundstart, votes, etc)
  code/__defines/misc.dm
  code/controllers/subsystems/ticker.dm
  code/controllers/subsystems/vote.dm
Labels: Sounds

#9178 Removes all but one boot knife overlays, makes them universal
  code/modules/clothing/clothing.dm
  icons/obj/clothing/shoes.dmi
Labels: Sprites

#9181 Zaddat plush + minor plush fixes
  code/game/objects/items/toys/toys.dm
  icons/obj/toy.dmi
Labels: Feature

#9182 welders now update their icon upon refilling them.
  code/game/objects/items/weapons/tools/weldingtool.dm
Labels: Quality of Life

#9183 Porting some Neb/Bay gluttony changes.
  code/__defines/mobs.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species/outsider/vox.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/carbon/human/species/station/teshari.dm
  code/modules/mob/living/carbon/human/species/xenomorphs/alien_species.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/organs.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_grab.dm
  code/modules/mob/mob_grab_specials.dm
  code/modules/mob/mob_helpers.dm
  code/modules/organs/internal/heart.dm
  code/modules/organs/internal/stomach.dm
  code/modules/organs/subtypes/vox.dm
Labels: Feature

#9179 Adds Paramedic Winter Coat Hood
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Sprites

#9184 Vox hair tweaks.
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/hair_vox.dmi
  icons/mob/hair_vox_add.dmi
Labels: Sprites

#9185 A couple of loadout fixes (Mostly Cloaks)
  code/modules/client/preference_setup/loadout/loadout_general.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
Labels: Oversight

#9186 Minor food taste fixes
  code/modules/food/food/snacks.dm
Labels: Oversight

#9187 Yellow slimes won't try to shock non-mob food targets
  code/modules/mob/living/simple_mob/subtypes/slime/xenobio/subtypes.dm
Labels: Bugfix

#9188 Union Renovations Package #2
  maps/cynosure/cynosure-2.dmm
  maps/cynosure/cynosure-3.dmm
  maps/cynosure/cynosure_areas.dm
Labels: Map: Cynosure

#9190 Corrects a couple of mecha do_afters that relied on previous implementation.
  code/game/mecha/equipment/tools/passenger.dm
  code/game/mecha/mech_prosthetics.dm
  code/game/mecha/mecha.dm
Labels: Bugfix

#9195 Fixes oversight in nonhuman mob job proc.
  code/game/jobs/job/job.dm
Labels: Oversight

#9206 Removed a space from the Moghesian Sea Delight type definition
  code/modules/food/food/snacks.dm
Labels: Oversight

#9191 Refluffs spellbooks as dubious augment applicators
  code/modules/spells/spellbook.dm
  code/modules/spells/targeted/projectile/fireball.dm
  icons/obj/wizard.dmi
Labels: Feature Tweak

#9194 Non-antag vox nerfs.
  code/game/objects/items/weapons/material/shards.dm
  code/game/objects/items/weapons/traps.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/species/outsider/event.dm
  code/modules/mob/living/carbon/human/species/outsider/replicant.dm
  code/modules/mob/living/carbon/human/species/outsider/shadow.dm
  code/modules/mob/living/carbon/human/species/outsider/skeleton.dm
  code/modules/mob/living/carbon/human/species/outsider/vox.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/species_getters.dm
  code/modules/mob/living/carbon/human/species/station/golem.dm
  code/modules/mob/living/carbon/human/species/station/prometheans.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/carbon/human/species/xenomorphs/alien_species.dm
  code/modules/mob/living/simple_mob/subtypes/slime/xenobio/combat.dm
  code/modules/power/power.dm
Labels: Feature Tweak

#9201 news articles jan-aug 23
  code/modules/busy_space/organizations.dm
  code/modules/lore_codex/news_data/main.dm
Labels: Lore

#9202 Teshari agility toggle
  code/modules/mob/living/carbon/human/species/station/teshari.dm
  code/modules/mob/living/living_powers.dm
Labels: Feature

#9199 Various post-flying bots fixes.
  code/game/objects/items/robot/robot_frame.dm
  code/game/objects/structures/catwalk.dm
  code/modules/mob/animations.dm
  code/modules/mob/living/silicon/robot/robot_modules/station.dm
  code/modules/mob/living/silicon/robot/robot_remote_control.dm
  code/modules/mob/living/silicon/robot/subtypes/flying.dm
  icons/mob/robots/robots_flying.dmi
  maps/cynosure/cynosure-3.dmm
Labels: Bugfix, Feature Tweak

#9204 POI - Remaps the Xenohive
  maps/submaps/surface_submaps/wilderness/xenohive.dmm
Labels: Map Change / Issue, Feature Tweak, Map: Point of Interest

#9207 Adds stomach organ contents to Regurgitate verb.
  code/modules/mob/living/carbon/human/human_powers.dm
Labels: Bugfix, Feature Tweak

#9208 Fixing issues with human spacemove.
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/silicon/robot/subtypes/flying.dm
  code/modules/mob/mob_movement.dm
Labels: Bugfix

#9209 Removed ghosts from talking artifact listeners.
  code/modules/xenoarcheaology/finds/talking.dm
Labels: Feature Tweak, Quality of Life

#9210 battery hud alert names
  code/_onclick/hud/alert.dm
Labels: Feature Tweak

#9213 fixe left shoulder cloak
  icons/mob/ties.dmi
Labels: Bugfix, Sprites

#9214 Fix robobags icons, synthmorph->synthbody
  code/game/objects/items/robobag.dm
  code/game/objects/items/weapons/tanks/tank_types.dm
  code/modules/clothing/under/accessories/badges.dm
  code/modules/research/prosfab_designs.dm
  icons/obj/robobag.dmi
Labels: Bugfix, Feature Tweak

#9215 Tweaks the Head of Personnel's hat and locker contents
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/head/jobs.dm
Labels: Feature Tweak

#9216 update vscode recommends & settings
  .vscode/extensions.json
  .vscode/settings.json
Labels: Repo

#9217 update to suite-1.7.3 for CI
  _build_dependencies.sh
Labels: Repo

#9218 respawn timers are correctly applied to ghosting and observing
  code/modules/mob/mob.dm
Labels: Bugfix

#9219 corrected include order of robot_frame in main dme
  polaris.dme
Labels: Bugfix

#9205 Nerfs the Robot VTEC Module
  code/game/objects/items/robot/robot_upgrades.dm
Labels: Feature Tweak

#9196 teshari synthetic feather tails
  code/modules/mob/new_player/sprite_accessories_tail.dm
  icons/effects/species_tails.dmi
  icons/mob/human_races/sprite_accessories/tails.dmi
Labels: Feature Tweak, Sprites

#9212 Digging update.
  code/game/objects/structures/crates_lockers/closets/coffin.dm
  code/game/turfs/simulated/outdoors/outdoors.dm
  code/game/turfs/simulated/outdoors/outdoors_attackby.dm
Labels: Feature, Feature Tweak, Quality of Life

#9221 Fixes inconsistent hair highlight icons
  icons/mob/human_face.dmi
  icons/mob/human_face_alt.dmi
  icons/mob/human_face_alt_add.dmi
  icons/mob/human_face_or_alt.dmi
Labels: Quality of Life, Sprites

#9230 removes tesharii
  code/modules/food/drinkingglass/metaglass.dm
  code/modules/mob/living/carbon/human/species/station/teshari.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/reagents/reactions/instant/drinks.dm
  code/modules/reagents/reagents/food_drinks.dm
  icons/obj/drinks.dmi
Labels: Priority: High, Bugfix, Lore, Quality of Life, Sprites

#9227 POI - Xenohive fixes and changes
  maps/submaps/surface_submaps/wilderness/xenohive.dmm
Labels: Map: Point of Interest

#9107 Adding species-level flavours and refactoring how reagent flavour is handled.
  code/__defines/mobs.dm
  code/_helpers/_lists.dm
  code/game/gamemodes/technomancer/spells/condensation.dm
  code/modules/food/food/snacks.dm
  code/modules/food/food/snacks/meat.dm
  code/modules/food/food/thecake.dm
  code/modules/mob/living/carbon/taste.dm
  code/modules/projectiles/projectile/arc.dm
  code/modules/reagents/holder/holder.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
  code/modules/reagents/reagents/_reagents.dm
  code/modules/reagents/reagents/core.dm
  code/modules/reagents/reagents/dispenser.dm
  code/modules/reagents/reagents/food_drinks.dm
  code/modules/reagents/reagents/other.dm
  code/modules/reagents/reagents/toxins.dm
  code/modules/reagents/reagents/vox.dm
  code/modules/xenobio/items/slime_objects.dm
Labels: Lore, Quality of Life

#9232 Tweaking hologram colours.
  code/_helpers/icons.dm
  code/game/machinery/camera/tracking.dm
  code/game/objects/structures/holoplant.dm
  code/modules/integrated_electronics/subtypes/output.dm
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Bugfix, Feature Tweak, Quality of Life

#9231 Fixing issues with the gibber not processing humans.
  code/game/objects/effects/spawners/gibs.dm
  code/modules/food/kitchen/gibber.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/monkey.dm
Labels: Bugfix
