Repository PolarisSS13/Polaris, pull requests merged in 2023-09, with the labels that each got.

#9233 Unifying MMI creation on robot subtypes.
  code/game/objects/items/robot/robot_frame.dm
  code/modules/mob/living/silicon/robot/drone/drone.dm
  code/modules/mob/living/silicon/robot/drone/swarm.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_remote_control.dm
  code/modules/mob/living/silicon/robot/subtypes/gravekeeper.dm
  code/modules/mob/living/silicon/robot/subtypes/lost_drone.dm
  code/modules/mob/living/silicon/robot/subtypes/syndicate.dm
  code/modules/mob/living/silicon/robot/subtypes/thinktank/_thinktank.dm
  code/modules/mob/living/silicon/robot/syndicate.dm
  code/modules/mob/mob_helpers.dm
  code/modules/mob/transform_procs.dm
  code/modules/projectiles/projectile/change.dm
Labels: Refactor, Bugfix

#9220 fix automatic changelog generation
  .github/workflows/autochangelog.yml
Labels: Repo

#9225 aghost respawn confirmation
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/mob.dm
Labels: Quality of Life

#9235 Sleeping verb is now a toggle.
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living.dm
Labels: Quality of Life

#9236 Adding survivalist and drake options to jobban panel.
  code/modules/admin/topic.dm
Labels: Oversight

#9237 Condiment cubes now take colour from reagents.
  code/modules/reagents/machinery/chem_master.dm
  icons/obj/chemical.dmi
Labels: Feature Tweak, Quality of Life

#9238 Poker chips for playing with cards
  code/game/objects/items/toys/poker_chips.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/modules/materials/materials/plastic.dm
  icons/obj/items.dmi
  icons/obj/poker.dmi
  icons/obj/storage.dmi
  maps/cynosure/cynosure-2.dmm
  polaris.dme
Labels: Feature, Sprites

#9242 fix some misc hits on direct overlays access
  code/game/machinery/atm_ret_field.dm
  code/game/objects/items.dm
  code/modules/food/food/condiment.dm
  code/modules/food/kitchen/cooking_machines/container.dm
  code/modules/hydroponics/beekeeping/beehive.dm
  code/modules/mob/living/simple_mob/appearance.dm
  code/modules/mob/living/simple_mob/subtypes/blob/spore.dm
  code/modules/mob/living/simple_mob/subtypes/occult/constructs/_construct.dm
Labels: Bugfix

#9241 added build, launch, and build + launch configs
  .vscode/launch.json
  .vscode/tasks.json
Labels: Repo

#9243 Stops artifacts from turning the frogs gay
  code/modules/xenoarcheaology/effects/radiate.dm
Labels: Bugfix, Quality of Life

#9248 POI - Remap CaveS
  maps/submaps/surface_submaps/wilderness/CaveS.dmm
Labels: Map Change / Issue, Map: Point of Interest

#9247 nerfs nanopaste
  code/game/objects/items/stacks/nanopaste.dm
Labels: Feature Tweak

#9249 makes white cane use message use item's name
  code/game/objects/items/weapons/canes.dm
Labels: Feature Tweak

#9252 meatshake
  code/modules/food/drinkingglass/metaglass.dm
  code/modules/reagents/reactions/instant/drinks.dm
  code/modules/reagents/reagents/food_drinks.dm
  icons/obj/drinks.dmi
Labels: Feature Tweak, Sprites

#9251 Updates the ATC to recent lore changes and additions + adds new organizations
  code/modules/busy_space/organizations.dm
  code/modules/busy_space/systems.dm
Labels: Feature Tweak, Lore, Quality of Life

#9250 POI - Frost Oasis Remap
  maps/submaps/surface_submaps/wilderness/frostoasis.dmm
Labels: Map Change / Issue, Map: Point of Interest

#9254 Meatshake lore pass
  code/modules/reagents/reagents/food_drinks.dm
Labels: Priority: High, Bugfix, Feature Tweak, Lore, Quality of Life, Revert, Spellcheck
