Repository PolarisSS13/Polaris, pull requests merged in 2024-01, with the labels that each got.

#9309 device.dmi updates
  html/changelogs/Devices - listerla.yml
  icons/obj/device.dmi
Labels: Sprites

#9315 Adds nugget share packs.
  code/datums/supplypacks/hospitality.dm
  code/game/objects/items/weapons/storage/misc.dm
  code/game/objects/structures/loot_piles.dm
  code/modules/food/food/snacks.dm
  code/modules/food/recipes_microwave.dm
  code/modules/materials/materials/plastic.dm
  icons/obj/food_nuggets.dmi
  icons/obj/food_syn.dmi
Labels: Feature Tweak, Quality of Life

#9304 removed to_world uses from filth/CompileEntry
  code/modules/persistence/effects/filth.dm
Labels: Bugfix

#9312 Drakes now have a preview icon.
  code/game/jobs/job/civilian_chaplain.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/silicon.dm
  code/game/objects/items/weapons/id cards/station_ids.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka/grafadreka.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka/grafadreka_misc.dm
  code/modules/mob/new_player/preferences_setup.dm
  maps/cynosure/cynosure_jobs.dm
Labels: Feature, Quality of Life

#9264 Demolishing Mobs
  code/game/objects/structures/flora/trees.dm
  code/modules/ai/ai_holder_combat.dm
  code/modules/ai/ai_holder_subtypes/simple_mob_ai.dm
  code/modules/ai/ai_holder_targeting.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/living/bot/bot.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/phorogenic.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/thermic.dm
  code/modules/mob/living/simple_mob/subtypes/animal/space/worm.dm
Labels: Feature, Contentious

#9318 Backyard grilling and some Sivian cuisine.
  code/game/objects/structures/bonfire.dm
  code/modules/economy/price_list.dm
  code/modules/food/food/snacks.dm
  code/modules/food/food/snacks_sif.dm
  code/modules/food/recipes_microwave.dm
  code/modules/food/recipes_oven.dm
  code/modules/food/recipes_sif.dm
  code/modules/hydroponics/grown.dm
  code/modules/hydroponics/seed.dm
  code/modules/hydroponics/seedtypes/apples.dm
  code/modules/hydroponics/seedtypes/corn.dm
  code/modules/hydroponics/seedtypes/flowers.dm
  code/modules/hydroponics/seedtypes/grapes.dm
  code/modules/hydroponics/seedtypes/potato.dm
  code/modules/hydroponics/seedtypes/wabback.dm
  code/modules/mob/living/simple_mob/subtypes/animal/animal.dm
  code/modules/reagents/reactions/instant/food.dm
  code/modules/reagents/reagents/food_drinks.dm
  icons/obj/food.dmi
  icons/obj/food_sivian.dmi
  icons/obj/trash.dmi
  polaris.dme
Labels: Feature, Quality of Life, Sprites

#9322 PoI - Plains Animal Dens
  maps/submaps/surface_submaps/plains/animalruin_den.dmm
  maps/submaps/surface_submaps/plains/crescent_den.dmm
  maps/submaps/surface_submaps/plains/plains.dm
  maps/submaps/surface_submaps/plains/plains_areas.dm
  maps/submaps/surface_submaps/plains/plainsdrake_den.dmm
  maps/submaps/surface_submaps/plains/pondside_den.dmm
  maps/submaps/surface_submaps/plains/swampy_den.dmm
Labels: Map Change / Issue, Map: Point of Interest

#9324 Revised Sivian Fauna Lists
  code/game/objects/random/mob.dm
  maps/submaps/surface_submaps/plains/swampy_den.dmm
Labels: Feature Tweak

#9323 Adds colorable cowboy hats and minor clothing fixes
  code/modules/client/preference_setup/loadout/loadout_head.dm
  code/modules/clothing/head/misc.dm
  icons/mob/head.dmi
  icons/mob/species/unathi/mask.dmi
  icons/mob/ties.dmi
  icons/obj/clothing/hats.dmi
Labels: Feature Tweak, Sprites

#9325 POI - Tape House
  code/game/objects/effects/map_effects/sound_emitter.dm
  code/game/objects/items/poi_items.dm
  maps/submaps/surface_submaps/plains/TapeHouse.dmm
  maps/submaps/surface_submaps/plains/plains.dm
  maps/submaps/surface_submaps/plains/plains_areas.dm
Labels: Map Change / Issue, Map: Point of Interest, Sounds

#9305 drakes can dig through outcrops
  code/modules/mining/mine_outcrops.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka/grafadreka_interaction.dm
Labels: Feature Tweak

#9307 teshari meat looks like chicken
  code/modules/food/food/snacks/meat.dm
  code/modules/mob/living/carbon/human/species/station/teshari.dm
Labels: Quality of Life

#9308 drakes can eat soap
  code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka/grafadreka_interaction.dm
Labels: Feature Tweak, Quality of Life

#9310 harvesting cooldown correctly displays minutes
  code/modules/mob/living/simple_mob/harvesting.dm
Labels: Bugfix

#9316 only /item archeology finds try to set origin tech
  code/modules/xenoarcheaology/finds/find_spawning.dm
Labels: Bugfix
